Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-09, with the labels that each got.

#7503 adds toxins to omega
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Currently Testmerged, Feature, Map Edit

#7511 Updates IC issue message
  code/modules/admin/verbs/adminhelp.dm
Labels: Currently Testmerged, Tweak

#7512 Adds *insult
  modular_citadel/code/modules/mob/cit_emotes.dm
  strings/insult.json
Labels: Currently Testmerged, Feature

#7526 Makes Spare more Accessible for heads (V2 because I forgot to compile the first time haha yes)
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  tgstation.dme
Labels: Currently Testmerged, Map Edit

#7524 adds missing shutters to pubby
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Currently Testmerged, Map Edit

#7518 Fixes Cit_toggles by sanitizing it with less autism
  code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
Labels: Currently Testmerged, Fix

#7517 Forces Vore prefs to use rust_g
  modular_citadel/code/modules/vore/eating/vore_vr.dm
Labels: Currently Testmerged, Fix

#7497 Makes the syndicate suspicous toolbox not be called "suspicous anymore" but just black and red striped instead.
  code/game/objects/items/storage/toolbox.dm
Labels: Balance/Rebalance, Currently Testmerged

#7527 Fixes some missing magmag mag icons
  modular_citadel/icons/obj/guns/cit_guns.dmi
Labels: Currently Testmerged, Fix

#7516 Adds electro-stimulation integrated circuit part
  modular_citadel/code/modules/integrated_electronics/subtypes/manipulation.dm
  tgstation.dme
Labels: Currently Testmerged, Feature

#7531 clarifies drone rules when becoming a drone
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
Labels: Currently Testmerged

#7522 Nerfs the starting armory
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Currently Testmerged

#7533 Ports new fusion from /tg/station. Now with extra FUN*! *lethality, lightning, radioactive fallout, and explosions
  code/__DEFINES/flags.dm
  code/__DEFINES/reactions.dm
  code/__HELPERS/type2type.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/gas_types.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/projectiles/projectile/energy/nuclear_particle.dm
  icons/obj/projectiles.dmi
  tgstation.dme
Labels: Currently Testmerged, Sprites

#7508 Adds the Kitchen Gun (TM)
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/projectiles/ammunition/ballistic/smg.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/guns/projectile.dmi
Labels: Currently Testmerged, Feature, Sprites

#7424 Ports TG's Agent Stealth Box/Stealth Implanter (with small tweaks)
  code/datums/action.dm
  code/game/objects/items/implants/implant_stealth.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/actions/actions_items.dmi
  icons/mob/actions/backgrounds.dmi
  icons/obj/closet.dmi
  icons/obj/library.dmi
  sound/misc/box_deploy.ogg
  tgstation.dme
Labels: Currently Testmerged, Feature, Sound, Sprites

#7548 Fixes an <i> noticed in Musician.dm
  code/game/objects/structures/musician.dm
Labels: Currently Testmerged

#7504 Reduces the stamina buffer regen timer to 1 second
  modular_citadel/code/modules/mob/living/carbon/damage_procs.dm
Labels: Balance/Rebalance, Currently Testmerged

#7534 [s] nerfs smuggler satchels cus wtf
  code/game/objects/items/storage/backpack.dm
Labels: Currently Testmerged

#7542 adds prescription nvgs
  code/modules/clothing/glasses/_glasses.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Currently Testmerged

#7547 fixes admin buildmode being unable to erase the heat of fusion reactions
  code/modules/procedural_mapping/mapGeneratorModules/helpers.dm
Labels: Currently Testmerged

#7577 Makes it plausible to use a list for geargroupid
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/loadout.dm
Labels: Feature

#7562 tgstation/tgstation#39172 - illegal paper-tech fix
  code/modules/uplink/uplink_items.dm
Labels: Currently Testmerged, Fix

#7576 Removes armor form Fed Officer Cap
  modular_citadel/code/modules/clothing/under/trek_under.dm
Labels: Removal

#7582 Fixes tennis ball equip slots
  modular_citadel/code/game/objects/items/balls.dm
Labels: Fix

#7583 Adds option to hide individual genitals without clothes
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/arousal/organs/vagina.dm
Labels: Currently Testmerged, Feature

#7592 Digitigrade Shoes
  code/modules/clothing/shoes/_shoes.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/surgery/bodyparts/helpers.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  modular_citadel/icons/mob/digishoes.dmi
Labels: Currently Testmerged, Sprites

#7599 Digitigrade Uniforms from Oracle
  code/__DEFINES/inventory.dm
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/vg_glasses.dm
  code/modules/clothing/head/cit_hats.dm
  code/modules/clothing/head/vg_hats.dm
  code/modules/clothing/masks/vg_masks.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/clothing/shoes/vg_shoes.dm
  code/modules/clothing/suits/vg_suits.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/vg_under.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/surgery/bodyparts/helpers.dm
  modular_citadel/code/game/objects/items/devices/radio/shockcollar.dm
  modular_citadel/code/modules/clothing/under/polychromic_clothes.dm
  modular_citadel/code/modules/clothing/under/trek_under.dm
  modular_citadel/code/modules/clothing/under/turtlenecks.dm
  modular_citadel/code/modules/clothing/under/under.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
  modular_citadel/icons/mob/uniform_digi.dmi
  modular_citadel/icons/polyclothes/item/uniform.dmi
  modular_citadel/icons/polyclothes/mob/uniform.dmi
Labels: Currently Testmerged, Sprites
