Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-11, with the labels that each got.

#7671 Makes human tails and human ears save again
  code/modules/mob/living/carbon/human/species_types/humans.dm
Labels: Fix

#7696 Mirror of tg's new gas sprites
  code/__DEFINES/atmospherics.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/gas_types.dm
  code/modules/flufftext/Hallucination.dm
  config/admins.txt
  icons/effects/atmospherics.dmi
  icons/effects/tile_effects.dmi
Labels: Config Update, Sprites

#7699 Fixes stamina not properly affecting non-organic limbs
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#7700 Probably fixes rogue icon overrides
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Fix

#7703 fixes job exp requirements by unmodularizing job list defines
  code/modules/jobs/jobs.dm
  modular_citadel/code/modules/jobs/jobs.dm
  tgstation.dme
Labels: Fix

#7690 [Ready] Makes PDA notes have basic ship terms that relate to the NSEW form PFBSQ
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Needs Review

#7608 okay, let's watch the population drop - adds a config option that makes all stamina buffer actions free (TG-style gameplay)
  code/_onclick/hud/human.dm
  code/controllers/configuration/entries/game_options.dm
  code/modules/mob/living/carbon/human/human.dm
  config/game_options.txt
  modular_citadel/code/modules/mob/living/carbon/damage_procs.dm
Labels: Config Update, Feature

#7694 Adds Voice of God commands to orgasm and dab
  code/modules/surgery/organs/vocal_cords.dm
Labels: Feature

#7688 makes it impossible to resist/move out of grabs while resting (though disarming your way out of the grab still works)
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
Labels: Balance/Rebalance

#7729 Makes teleporters viable - Buffs launchpads across the board (18 max launchpad range to 60 max launchpad range)
  code/game/machinery/launch_pad.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#7727 Makes the eyeblur effect scale depending on how much eyeblur you have
  code/__DEFINES/misc.dm
  code/modules/mob/living/life.dm
  code/modules/mob/status_procs.dm
Labels: Feature

#7723 Brings back nonlethal 38 bullets in a semi-nerfed state, keeps the current lethal variant in as a brand new sec autolathe printable ammo box
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Feature

#7726 Makes it plausible to join as ghost roles from the latejoin menu
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/awaymissions/corpse.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/ruins/lavaland_ruin_code.dm
  modular_citadel/code/modules/awaymissions/citadel_ghostrole_spawners.dm
Labels: Feature

#7730 Reduces the revolution win condition check grace period to 10 minutes
  code/game/gamemodes/revolution/revolution.dm
Labels: Tweak

#7731 Adds the ability to choose plural and neuter genders (labelled "non-binary" and "object", respectively)
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Tweak

#7719 Reduces shadow species light threshold leniency to accommodate for cit's lighting changes
  code/__DEFINES/mobs.dm
Labels: Balance/Rebalance, i ded

#7712 Adds an emag exclusive syndicate emergency shuttle.
  _maps/shuttles/emergency_syndicate.dmm
  code/datums/shuttles.dm
  code/game/machinery/porta_turret/portable_turret.dm
  config/unbuyableshuttles.txt
Labels: Config Update, Feature, Map Edit

#7714 Lone Ops but they are an actual threat (hopefully)
  code/game/gamemodes/nuclear/nuclear.dm
  code/modules/antagonists/nukeop/nukeop.dm
Labels: Balance/Rebalance

#7717 Pubby Engineering has been redesigned with a SM engine.
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit, Removal

#7733 Update chat_commands.dm
  modular_citadel/code/modules/admin/chat_commands.dm
Labels: Feature

#7732 Cult deconversion now properly removes the blood halo
  code/modules/antagonists/cult/cult.dm
Labels: Priority: High, Removal

#7721 Oldstation but it doesn't lag the server.
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
Labels: Balance/Rebalance, Feature, Map Edit, Tweak

#7710 [Grammar] [Ready] Makes Space Queens men pirate gear have better item descriptions
  code/modules/clothing/spacesuits/miscellaneous.dm
Labels: Needs Review

#7645 [Ready] Re-balance Tech Web nodes and points
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance

#7678 [Ready] Nerfs reactive armor a bit.
  code/modules/clothing/suits/reactive_armour.dm
Labels: Needs Review, Unresolved Reviews

#7697 [Ready]Roboticist Headset in there vendor for a coin
  code/modules/vending/wardrobes.dm
Labels: Needs Review

#7739 [PRIORITY] Pubby Station Air Injector Hotfix
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#7736 Fixes spawners with defined job descriptions causing the mob spawners list to fill up with null entries (makes spawner menu work again and properly removes ghost roles from latejoin menu when filled)
  code/modules/awaymissions/corpse.dm
Labels: Fix, Removal

#7738 Using help intent on someone that's in hard stamcrit will now make them heal 15 staminaloss
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Balance/Rebalance

#7737 Makes the voting system actually track who voted for what - makes it possible to change your vote and shows you what you voted for
  code/controllers/subsystem/vote.dm
Labels: Feature

#7735 Moves airlock lights to the above lighting layer. They now actually glow in the dark
  code/game/machinery/doors/airlock.dm
Labels: Tweak

#7734 Fancy lighting wave 2 - nonbinary colored lighting now applies to gun/helmet flashlights, borgs, bots, welders, and more
  code/game/machinery/camera/camera.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/projectiles/gun.dm
Labels: Tweak

#7728 Buffs ebows by making them deal 50 drowsiness
  code/modules/projectiles/projectile/energy/ebow.dm
Labels: Balance/Rebalance

#7743 Disables TG's biased preference-based map voting system in favor of an actual end-of-round map voting system
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/modules/client/preferences.dm
  config/config.txt
Labels: Config Update, Feature

#7741 Makes auto fit viewport enabled by default for new players
  code/modules/client/preferences.dm
Labels: Tweak

#7742 Y'all n'wahs aint even smoke - adds skooma
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
Labels: Feature

#7684 [Ready]Silly Tips
  strings/sillytips.txt
Labels: Needs Review

#7698 [Ready] More riot gear, cap pen and more!
  code/modules/cargo/packs.dm
Labels: Needs Review

#7637 [READY] More Slime core deconstruction, now with Cross bread slime cores! (Best Grammar! 100% ready for merging PDM!!)
  code/controllers/subsystem/research.dm
Labels: Do Not Merge, Needs Review

#7750 Fixes the "genitals use skintone" option not appearing in the character appearance menu
  code/modules/client/preferences.dm
Labels: Fix

#7751 clicking your stamina bar will now show your staminaloss and info regarding your stamina buffer
  modular_citadel/code/_onclick/hud/stamina.dm
Labels: Feature

#7748 buffs lavaland's cacti just a smidge by increasing the amount of vitfro they have by 1.5x (4 > 6)
  code/modules/mining/lavaland/ash_flora.dm
Labels: Balance/Rebalance

#7752 ports tgstation/tgstation#40260 (fixes stealth implants)
  code/datums/action.dm
Labels: Fix

#7764 Adds Corgi Suit for a donator
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Donor Fluff

#7756 readds the kitchen gun sprite (fixes the kitchen gun being invisible)
  icons/obj/guns/projectile.dmi
Labels: Fix, Sprites

#7754 actually fixes ghost role spawners leaving null entries in mob_spawners
  code/modules/awaymissions/corpse.dm
Labels: Fix

#7769 Adds a peep emote.
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/sound/voice/peep.ogg
Labels: Donor Fluff, Exploit, FUCK, Feature, Not A Bug, Priority: CRITICAL

#7770 Buffs Gloves of the North Star by making them restore 2/3 of the stamina used when punching
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Balance/Rebalance

#7772 Small QOL changes for a big station.
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Map Edit, Tweak

#7771 Makes rev deconversion in-line with the rest of the conversion antag deconversions (revs are no longer told that they remember the name of the one who flashed them on deconvert)
  code/modules/antagonists/revolution/revolution.dm
Labels: Balance/Rebalance
