Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-04, with the labels that each got.

#6025 Increase age gap
  modular_citadel/code/modules/jobs/job_types/captain.dm
  modular_citadel/code/modules/jobs/job_types/engineering.dm
  modular_citadel/code/modules/jobs/job_types/medical.dm
  modular_citadel/code/modules/jobs/job_types/science.dm
  modular_citadel/code/modules/jobs/job_types/security.dm
  tgstation.dme
Labels: Enhancement, Tweak/Balance

#6272 Readds handholding
  code/modules/mob/living/living.dm
Labels: Balance/Rebalance, Code Improvement, Drama Overload, Exploit, FUCK, Fix, Github, Kneejerk Revert, Priority: CRITICAL, Priority: High, Test Merge Candidate

#6247 Adjust permissions for Admin Observers
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/adminpm.dm
Labels: FUCK, Fix, Priority: CRITICAL

#6296 Adds "Man up" verb for admins.
  code/modules/admin/admin_verbs.dm
  modular_citadel/code/modules/admin/admin.dm
  modular_citadel/sound/misc/manup.ogg
Labels: Administration, Feature

#6449 Rebalances pump-action energy shotguns
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
Labels: Balance/Rebalance

#6519 Fixes shitcode in slime code
  modular_citadel/code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Exploit, Fix
