Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-07, with the labels that each got.

#7266 stops admins from "accidentally" ending the round by elder god
  code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
  code/modules/antagonists/clockcult/clock_structures/ratvar_the_clockwork_justicar.dm
Labels: Currently Testmerged

#7083 nerfs techwebs passive generation, pushes back full max time by 15 minutes
  code/controllers/subsystem/research.dm
Labels: Currently Testmerged

#7029 Adds devilwings donor item for kitsun
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
  modular_citadel/icons/mob/clothing/devilwings64x64.dmi
Labels: Currently Testmerged, Donor Fluff, Sprites

#7152 removes extra circuit config
  config/game_options.txt
Labels: Config Update, Removal

#7347 Removes the rest spam from spam- I mean, dance machine
  code/game/machinery/dance_machine.dm
Labels: Removal

#7358 Fixes democracy
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Fix

#7193 Cyborgs now drop their encryption keys on detonation/deconstruction
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Currently Testmerged

#7344 fixes lewd handcuffs
  modular_citadel/code/game/objects/items/handcuffs.dm
  modular_citadel/code/game/objects/items/holy_weapons.dm
  modular_citadel/icons/obj/items_and_weapons.dmi
  modular_citadel/icons/obj/weapons.dmi
Labels: Currently Testmerged

#7357 readds the cryo and lewdstuff on the map
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Currently Testmerged, Map Edit

#7345 adds plushnar and plushvar on chapvendors
  modular_citadel/code/game/machinery/vending.dm
Labels: Currently Testmerged

#7356 Hopefully this will add in the missing WT-550 Toxin Ammo for sec
  code/modules/projectiles/projectile/bullets/smg.dm
  modular_citadel/code/modules/projectiles/ammunition/ballistic/smg/smg.dm
  modular_citadel/code/modules/projectiles/boxes_magazines/external/smg/smg.dm
  modular_citadel/code/modules/projectiles/bullets/bullets/smg.dm
  modular_citadel/code/modules/research/designs/weapon_designs/weapon_designs.dm
  modular_citadel/code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Currently Testmerged

#7354 Removes armor form Non-head only Trek suits
  modular_citadel/code/modules/clothing/under/trek_under.dm
Labels: Currently Testmerged, Removal

#7023 Telebatons/policebatons buffed to be a viable stun weapon (but not as good as stunbatons/prods), secways nerfed to non-sprint movespeed with sprint buffer (but this time they're actually responsive instead of being laggy and the buffer is weaker)
  modular_citadel/code/datums/status_effects/debuffs.dm
  modular_citadel/game/objects/items/melee/misc.dm
  modular_citadel/modules/mob/living/status_procs.dm
  modular_citadel/modules/vehicles/secway.dm
  tgstation.dme
Labels: Currently Testmerged

#7363 New pAI holochassis options, display images
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/software.dm
  modular_citadel/icons/mob/pai.dmi
  modular_citadel/icons/obj/aicards.dmi
Labels: Currently Testmerged, Feature

#7364 flightsuit speed rebalancing
  code/modules/mob/living/carbon/human/species.dm
Labels: Currently Testmerged

#7377 flashes are no longer invisible
  code/modules/assembly/flash.dm
Labels: Priority: High

#7366 [requires testmerge]upstream mirror - projectile pathing/hitscan lighting refactor
  code/controllers/subsystem/processing/projectiles.dm
  code/game/objects/effects/temporary_visuals/projectiles/projectile_effects.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/projectiles/projectile.dm
Labels: Currently Testmerged, Refactor

#7365 Makes Revs have a min pop needed
  modular_citadel/code/game/gamemodes/revolution/revolution.dm
Labels: Currently Testmerged

#7369 Fixes doppler arrays detecting explosions it shouldn't detect
  code/game/machinery/doppler_array.dm
Labels: Currently Testmerged

#7370 gives AI smartfridge interaction why not we already caved and let them fuck wtih vending machines
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Labels: Currently Testmerged

#7374 hardcaps stamina to 200 again
  modular_citadel/code/modules/mob/living/carbon/damage_procs.dm
Labels: Currently Testmerged

#7381 Minor grammar fix + crow pAI rest fix
  modular_citadel/code/game/objects/structures/tables_racks.dm
  modular_citadel/icons/mob/pai.dmi
Labels: Fix

#7373 Nerfs gas tank ruptures by reducing the pressure from ^4 to ^3
  code/game/objects/items/tanks/tanks.dm
Labels: Balance/Rebalance, Currently Testmerged

#7383 Licenses memes
  icons/emoji.dmi
Labels: Sprites

#7367 Jukebox rework + environment/reverb controls for sounds played via playsound_local
  code/__DEFINES/sound.dm
  code/controllers/subsystem/jukeboxes.dm
  code/game/machinery/dance_machine.dm
  code/game/sound.dm
  tgstation.dme
Labels: Code Improvement, Config Update, Currently Testmerged, Feature

#7147 Buffs the syndicate mask, makes it cost TC.
  modular_citadel/code/modules/clothing/glasses/phantomthief.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/other_reagents.dm
  modular_citadel/code/modules/uplink/uplink_items.dm
  modular_citadel/sound/misc/adrenalinject.ogg
Labels: Currently Testmerged, Tweak

#7378 It's a feature now - makes it plausible to use custom say verbs in place of emotes (allows proper non-buggy emotes over radio)
  code/game/say.dm
  modular_citadel/code/modules/mob/mob.dm
Labels: Currently Testmerged, Tweak

#7361 Fixes items spawning on top of rather than inside closets
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Currently Testmerged, Fix

#7372 Adds citadel snowflake features as UE blocks
  code/__DEFINES/DNA.dm
  code/__DEFINES/citadel_defines.dm
  code/datums/dna.dm
Labels: Currently Testmerged, Feature

#7359 Reduces the default space ruin z-level count to 1
  code/datums/map_config.dm
Labels: Currently Testmerged, Tweak

#7389 dhonk: not a conflict edition
  icons/emoji.dmi
Labels: Sprites

#7398 Donator - Lucky Jack Boots
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff, Sprites

#7382 nerfs telebatons some more because i accidently buffed them to be more op than infinite cell stunbatons
  modular_citadel/game/objects/items/melee/misc.dm
Labels: Currently Testmerged

#7406 Fix/Changes for Donator item
  icons/obj/custom.dmi
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff, Sprites

#7408 Removes the W
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Removal

#7410 fixes the reason I and a lot of you lock up for more than half a minute when trying to join the server
  code/modules/client/asset_cache.dm
Labels: FUCK, Priority: CRITICAL, Priority: High

#7387 wormhole guns now pass through mobs without doing anything but gain hitscan
  code/game/objects/effects/portals.dm
  code/game/objects/effects/temporary_visuals/projectiles/impact.dm
  code/game/objects/effects/temporary_visuals/projectiles/muzzle.dm
  code/game/objects/effects/temporary_visuals/projectiles/projectile_effects.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/special/wormhole.dm
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/obj/projectiles_tracer.dmi
Labels: Currently Testmerged, Sprites

#7385 removes flightsuits until pixel movement is out and i can redesign them
  code/modules/research/techweb/all_nodes.dm
Labels: Currently Testmerged, Removal

#7413 Icon fix
  icons/mob/custom_w.dmi
Labels: Currently Testmerged, Sprites
