Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-05, with the labels that each got.

#6860 fixes flash icons
  code/modules/assembly/flash.dm
Labels: Fix

#6782 Small hub entry tweaks
  code/game/world.dm
Labels: Tweak

#6761 Tones down particle defender stamina damage
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
Labels: Balance/Rebalance

#6748 Emag QoL and addition of emag recharge devices
  modular_citadel/code/game/objects/ids.dm
  modular_citadel/code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Tweak/Balance

#6908 Removes VR SLEEPER entry from Biotech Node
  code/modules/research/techweb/all_nodes.dm
Labels: Removal

#6092 Combat rework adjustments (Making use of 512's new filter feature, small balance tweaks, and more)
  code/__DEFINES/citadel_defines.dm
  modular_citadel/code/datums/components/phantomthief.dm
  modular_citadel/code/game/objects/items/melee/transforming.dm
  modular_citadel/code/modules/clothing/glasses/phantomthief.dm
  modular_citadel/code/modules/mob/living/carbon/carbon.dm
  modular_citadel/code/modules/mob/living/living.dm
  modular_citadel/code/modules/uplink/uplink_items.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature, Tweak

#6952 Re-enables lavaland lighting
  modular_citadel/hopefully_temporary_patches.dm
Labels: Tweak
