Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-12, with the labels that each got.

#7778 lets try fixing the fucking stamcrit bug - removes redundant update_stamina() calls and moves update_stamina() calls outside of if clauses
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/damage_procs.dm
Labels: Fix, Removal

#7776 Replaces all missing texture turf on Omega Station with sandy plating as was intended.
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit

#7765 Cult buffs (Makes most cult whispers not be shouted and makes stun spell guarantee stamcrit at the cost of a higher cost and reduced charges)
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/antagonists/cult/runes.dm
  modular_citadel/code/modules/antagonists/cult/blood_magic.dm
  tgstation.dme
Labels: Balance/Rebalance

#7779 Buffs and nerfs night vision trait - makes the night vision trait expand your darksight to 7 tiles but increases the night vision trait's lighting plane alpha from 245 to 250
  code/__DEFINES/lighting.dm
  code/modules/surgery/organs/eyes.dm
Labels: Balance/Rebalance

#7783 Added a new carpet
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/modules/cargo/packs.dm
  icons/obj/tiles.dmi
  icons/turf/floors/carpet_red.dmi
Labels: Feature, Sprites

#7782 Buffs bone spears by increasing their reach to 2 whole tiles
  code/game/objects/items/twohanded.dm
Labels: Balance/Rebalance

#7780 Adds a new PKA to the mining Vendor
  code/modules/mining/machine_vending.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
Labels: Sprites

#7791 Nerfs wavedashing
  code/game/turfs/open.dm
Labels: Fix

#7799 Added Another new carpet, and two tables, a new cargo crate, and two new medals.
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/table_frames.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/under/accessories.dm
  icons/obj/clothing/accessories.dmi
  icons/obj/smooth_structures/fancy_table_blackred.dmi
  icons/obj/smooth_structures/fancy_table_monochrome.dmi
  icons/obj/structures.dmi
  icons/obj/tiles.dmi
  icons/turf/floors/carpet_blackred.dmi
  icons/turf/floors/carpet_monochrome.dmi
Labels: Sprites

#7794 Buffs NanoMed Wall units!
  code/modules/vending/medical_wall.dm
Labels: PRB: Reset

#7857 Adds two donation items
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff

#7862 Adds fans to each white ship hopefully at all doors leading to space! - Requested by Seras/Others
  _maps/shuttles/whiteship_box.dmm
  _maps/shuttles/whiteship_delta.dmm
  _maps/shuttles/whiteship_meta.dmm
  _maps/shuttles/whiteship_pubby.dmm
Labels: Map Edit

#7865 Makes stamcrit completely unaffected by health
  modular_citadel/code/modules/mob/living/living.dm
Labels: Balance/Rebalance

#7863 [Ready] Adds in a scatter shot Bulldog drum!
  code/modules/projectiles/boxes_magazines/external/shotgun.dm
  code/modules/uplink/uplink_items.dm
Labels: Needs Review
