Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-10, with the labels that each got.

#7605 Fixes vore prefs, missing species features
  code/__DEFINES/rust_g.config.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/simple_animal/simple_animal_vr.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  modular_citadel/code/modules/vore/eating/belly_obj_vr.dm
  modular_citadel/code/modules/vore/eating/living_vr.dm
  modular_citadel/code/modules/vore/eating/vore_vr.dm
  rust_g.dll
  tgstation.dme
Labels: Currently Testmerged, Fix

#7530 updates the title screen config readme to account for the 7:5 lobby
  config/title_screens/README.txt
Labels: Config Update

#7611 Alternative Miner Suits
  code/__DEFINES/flags.dm
  code/_globalvars/bitfields.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#7612 Mirrors tgstation/tgstation#40662 (100mb memory freed up roundstart, hell ya)
  code/__DEFINES/components.dm
  code/__DEFINES/flags.dm
  code/__HELPERS/radiation.dm
  code/_globalvars/bitfields.dm
  code/datums/components/mirage_border.dm
  code/datums/components/rad_insulation.dm
  code/datums/radiation_wave.dm
  code/game/atoms.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/holosign.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/signs/_signs.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed.dm
  code/game/turfs/simulated/wall/reinf_walls.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/power/singularity/collector.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/recycling/disposal/holder.dm
  code/modules/recycling/disposal/outlet.dm
  code/modules/recycling/disposal/pipe.dm
Labels: Code Improvement

#7598 makes footsteps sound less like ass by shoving cit's original values into the new system
  code/datums/components/footstep.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Tweak

#7604 Fixes jukeboxes not exiting the active jukebox list when destroyed
  code/game/machinery/dance_machine.dm
Labels: Currently Testmerged, Fix

#7596 Mostly fixes stamina by making knockdown() apply its staminaloss to the chest, giving adjuststaminaloss() new args, disabling limb-specific stamina regen for the chest, and disabling head stamina
  code/game/objects/items/stunbaton.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/head.dm
  modular_citadel/code/modules/mob/living/carbon/damage_procs.dm
Labels: Currently Testmerged, Fix, Tweak

#7550 super turbo lavaland 2 tournament edition (Buffs a bunch of lavaland mobs by increasing their speed)
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
Labels: Balance/Rebalance, Currently Testmerged

#7552 combine with mob buff PR - buffs kinetic crushers
  code/modules/mining/equipment/kinetic_crusher.dm
Labels: Currently Testmerged, Relies on another PR

#7626 Blue air alarms
  code/modules/atmospherics/machinery/airalarm.dm
  icons/obj/monitors.dmi
Labels: Sprites, Tweak

#7631 Adds *dab. Yep. The future is here.
  modular_citadel/code/modules/mob/cit_emotes.dm
Labels: Feature, MEME PR

#7627 APC have Damage Resistance, Health, and armor buffs
  code/modules/power/apc.dm
Labels: Balance/Rebalance

#7632 Digitigrade suits
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/vg_suits.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/surgery/bodyparts/helpers.dm
  modular_citadel/code/modules/clothing/spacesuits/cydonian_armor.dm
  modular_citadel/code/modules/clothing/suits/suits.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
  modular_citadel/icons/mob/suit_digi.dmi
Labels: Feature, Sprites

#7633 Fixes Guilmon features
  modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
Labels: Fix

#7630 The cooler nuke op base (featuring more air)
  _maps/map_files/generic/CentCom.dmm
Labels: Fix, Map Edit, Tweak

#7625 Medihound Tweaks and Sound Preference improvements
  code/__DEFINES/citadel_defines.dm
  code/game/objects/items/devices/dogborg_sleeper.dm
  modular_citadel/code/modules/vore/eating/belly_obj_vr.dm
  modular_citadel/code/modules/vore/eating/bellymodes_vr.dm
Labels: Balance/Rebalance, Fix, Refactor

#7647 Adds permanent sprites for the SEVA suit
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/machine_vending.dm
  icons/mob/head.dmi
  icons/mob/mask.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#7650 (HOPEFULLY) Fixes autostand making item dropping wait for stand attempts to finish
  code/modules/mob/living/living.dm
Labels: Fix

#7648 Soft sync some fixes
  Dockerfile
  code/__DEFINES/mobs.dm
  code/__DEFINES/tgs.dm
  code/_compile_options.dm
  code/datums/mood_events/needs_events.dm
  code/datums/position_point_vector.dm
  code/game/data_huds.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/harvester.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/clothing/suits/utility.dm
  code/modules/events/pirates.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  dependencies.sh
  strings/phobia.json
  tools/mapmerge2/dmm.py
Labels: Tools

#7652 Resprites all regular crates to 3/4ths ones
  code/game/objects/structures/crates_lockers/crates.dm
  icons/obj/crates.dmi
Labels: Feature, Sprites

#7640 Adds minor protection to emag clicks
  code/game/objects/items/cards_ids.dm
  modular_citadel/code/game/objects/ids.dm
Labels: Balance/Rebalance

#7660 Makes the O2 crate sprites consistent
  icons/obj/crates.dmi
Labels: Fix, Sprites

#7657 Rewords a misleading tip of the round
  strings/tips.txt
Labels: Removal

#7639 [READY] Tauric full body suits
  code/__DEFINES/inventory.dm
  code/__DEFINES/misc.dm
  code/modules/client/preferences.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/under/_under.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
  modular_citadel/icons/mob/taur_canine.dmi
  modular_citadel/icons/mob/taur_hooved.dmi
  modular_citadel/icons/mob/taur_naga.dmi
Labels: Needs Review

#7624 Tweaks/rebalances disarms and disarm pushes
  code/modules/mob/living/carbon/human/species.dm
  modular_citadel/code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance, Tweak

#7663 fixes mapmerge2
  tools/mapmerge2/dmm.py
Labels: Tools

#7664 fixes AOOC printing to players in the lobby
  code/modules/client/verbs/aooc.dm
Labels: Fix

#7662 [READY](?) Gives Warden/Hos/Det donuts healing powers with working code
  code/modules/food_and_drinks/food/snacks_pastry.dm
Labels: Needs Review

#7465 Makes portal guns spawn without firing pins
  code/modules/projectiles/guns/energy/special.dm
Labels: Balance/Rebalance

#7451 Makes game setup failure send messages to admin IRC and ingame admin chat
  code/controllers/subsystem/ticker.dm
Labels: Administration

#7666 Adds Cryo Sleepers to Permabrig
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#7667 You're killing me, Smalls
  code/game/objects/items/devices/dogborg_sleeper.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/client/preferences.dm
  code/modules/mining/equipment/explorer_gear.dm
  modular_citadel/code/game/objects/items/robot/robot_upgrades.dm
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
  modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_citadel/icons/mob/suit_digi.dmi
  modular_citadel/icons/mob/taur_canine.dmi
  modular_citadel/icons/mob/taur_naga.dmi
Labels: Fix

#7669 Exosuit sprites have arrived. "Now with more gasmask."
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/machine_vending.dm
  icons/mob/head.dmi
  icons/mob/mask.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#7677 Makes all ion references to "humans" reference to "crew" instead.
  code/game/objects/items/AI_modules.dm
  code/modules/events/ion_storm.dm
  code/modules/research/designs/AI_module_designs.dm
  strings/ion_laws.json
Labels: Tweak

#7675 Adds loader engineering cyborg sprite.
  modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature

#7680 Removes vampires from being able to ventcrawl with items while in bat form, makes the bat named after the original mob
  code/modules/mob/living/carbon/human/species_types/vampire.dm
Labels: Balance/Rebalance, Drama Overload

#7656 [READY] Cargo packet update and modification
  code/modules/cargo/packs.dm
Labels: Needs Review

#7683 You're too exhausted to be lifted up - makes it much harder to force stamcritted spacemen to stand
  code/game/objects/items/robot/robot_items.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Fix

#7689 Makes staminaloss taken while in hard stamcrit decrease the amount of staminaloss you'll take until you're out of stamcrit, and adds scrambling while in stamcrit
  code/game/turfs/open.dm
  code/modules/mob/living/carbon/life.dm
  modular_citadel/code/modules/mob/living/carbon/damage_procs.dm
  modular_citadel/code/modules/mob/living/living.dm
Labels: Feature

#7681 Fixes disarm pushing being able to deal staminaloss to resting targets
  modular_citadel/code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#7686 Makes the rev gamemode simply not check for win conditions until the 20 minute mark
  code/game/gamemodes/revolution/revolution.dm
Labels: Tweak
