Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-02, with the labels that each got.

#5408 Fixes and Reimplements Magnetic Weapons
  code/citadel/cit_guns.dm
  icons/obj/guns/cit_guns.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites, Tweak

#5440 Ports prayer beads from Paradise
  modular_citadel/code/game/objects/items/holy_weapons.dm
  modular_citadel/icons/obj/weapons.dmi
  tgstation.dme
Labels: Feature

#5485 Cryopods from Oracle Station
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/citadel/cit_areas.dm
  code/citadel/icons/areas.dmi
  code/game/gamemodes/objective.dm
  code/game/machinery/announcement_system.dm
  code/modules/mob/dead/observer/observer.dm
  icons/obj/Cryogenic2.dmi
  modular_citadel/code/controllers/subsystem/job.dm
  modular_citadel/code/game/machinery/cryopod.dm
  modular_citadel/code/modules/client/client_defines.dm
  tgstation.dme
Labels: Feature, Map Edit, Sprites

#5490 Adds stunsword modification kits to the security vendor
  modular_citadel/code/game/machinery/vending.dm
  tgstation.dme
Labels: Feature

#5521 I mean, I guess?
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit

#5525 [Ready!] The Slimening - Reworking slimepeople to be less like humans without unbalanced advantages.
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  config/game_options.txt
  icons/mob/actions/actions_slime.dmi
  icons/mob/human_parts_greyscale.dmi
  modular_citadel/code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  tgstation.dme
Labels: Config Update, Feature, Sprites

#5515 Flightsuit Armor adjustments
  code/modules/clothing/spacesuits/flightsuit.dm
  modular_citadel/code/modules/clothing/spacesuits/flightsuit.dm
  tgstation.dme
Labels: Balance/Rebalance

#5452 Adds in special fluff items for TechnicalMagi
  code/citadel/custom_loadout/custom_items.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Donor Fluff

#5534 [Ready to merge] Au-toy-lathe
  code/__DEFINES/construction.dm
  code/__DEFINES/machines.dm
  code/citadel/cit_guns.dm
  code/datums/components/material_container.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/toys.dm
  modular_citadel/code/datums/wires/autoylathe.dm
  modular_citadel/code/game/machinery/toylathe.dm
  modular_citadel/code/game/objects/items/circuitboards/machine_circuitboards.dm
  modular_citadel/code/modules/research/designs/autoylathe_designs.dm
  modular_citadel/code/modules/research/designs/machine_designs.dm
  modular_citadel/code/modules/research/techweb/_techweb.dm
  modular_citadel/code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Feature

#5432 QM is now a Head of Staff, everyone rejoice!
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/jobs/jobs.dm
  modular_citadel/code/game/gamemodes/revolution/revolution.dm
  modular_citadel/code/game/machinery/computer/card.dm
  modular_citadel/code/game/objects/items/devices/radio/encryptionkey.dm
  modular_citadel/code/game/objects/items/devices/radio/headset.dm
  modular_citadel/code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  modular_citadel/code/modules/jobs/job_types/captain.dm
  modular_citadel/code/modules/jobs/job_types/cargo_service.dm
  modular_citadel/code/modules/jobs/jobs.dm
  strings/sillytips.txt
  tgstation.dme
Labels: Feature, Revert/Removal, Tweak

#5484 Emag limits
  modular_citadel/code/game/objects/ids.dm
Labels: Balance/Rebalance, Tweak/Balance

#5560 Fixes some sprite issues
  code/modules/mob/dead/new_player/sprite_accessories_Citadel.dm
  icons/mob/mam_body_markings.dmi
  icons/mob/mam_bodyparts.dmi
Labels: Sprites

#5576 Makes lighting a little fancier
  modular_citadel/code/game/objects/items/devices/flashlight.dm
  modular_citadel/code/modules/power/lighting.dm
  tgstation.dme
Labels: Tweak

#5478 Gives mineral storage access to those who need it
  modular_citadel/code/modules/jobs/job_types/cargo_service.dm
  modular_citadel/code/modules/jobs/job_types/engineering.dm
  tgstation.dme
Labels: Feature

#5538 Sake!
  code/citadel/cit_reagents.dm
  code/citadel/icons/drinks.dmi
  code/game/machinery/vending.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#5579 Blood Red Tie - Donator Loadout
  code/citadel/custom_loadout/custom_items.dm
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Donor Fluff, Sprites

#5577 Make Atmosia Lethal Again
  code/__DEFINES/atmospherics.dm
Labels: Balance/Rebalance, Tweak

#5594 fixes possible missing sprites
  icons/mob/human_parts.dmi
  icons/mob/human_parts_greyscale.dmi
  icons/mob/xeno_parts_greyscale.dmi
Labels: Priority: High, Sprites

#5623 Vore preference fix + Sounds respect wall barriers
  code/modules/client/preferences.dm
  code/modules/vore/eating/belly_vr.dm
  code/modules/vore/eating/bellymodes_vr.dm
  code/modules/vore/eating/living_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
Labels: Fix, Sound

#5618 Changes the HoP to require Service experience
  code/modules/jobs/job_types/captain.dm
  modular_citadel/code/modules/jobs/job_types/captain.dm
Labels: Tweak

#5633 Slimes have no livers!
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Fix

#5655 Revert "Slimes have no livers!"
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Revert/Removal

#5668 Fixes dogborg offsets and gun layering
  code/game/atoms_movable.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Fix, Priority: Normal

#5649 Slimepeople bugfixes and rebalancing
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Balance/Rebalance

#5670 Adds Shock collars back to autolathes
  modular_citadel/code/game/objects/items/devices/radio/shockcollar.dm
Labels: Fix

#5616 Removes xeno stun and stamina immunity
  code/modules/mob/living/carbon/alien/damage_procs.dm
  code/modules/mob/living/carbon/alien/status_procs.dm
Labels: Balance/Rebalance, Revert/Removal

#5617 Makes martial arts use Knockdown() instead of Stun() for their stuns
  code/datums/martial/psychotic_brawl.dm
  code/datums/martial/sleeping_carp.dm
Labels: Balance/Rebalance

#5691 Applies ignore_walls = FALSE to dogborg actions
  code/citadel/dogborgstuff.dm
Labels: Audio/Music

#5727 Adjusting Prayer Beads to be more useful
  modular_citadel/code/game/objects/items/holy_weapons.dm
Labels: Tweak
