Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-03, with the labels that each got.

#5697 The Great Trigonometric Sprite Replacement, Phase 1!
  modular_citadel/code/game/objects/tools.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/revolver.dm
  modular_citadel/code/modules/projectiles/guns/energy/energy_gun.dm
  modular_citadel/code/modules/uplink/uplink_items.dm
  modular_citadel/icons/obj/guns/energy.dmi
  modular_citadel/icons/obj/guns/revolver.dmi
  modular_citadel/icons/obj/tools.dmi
  tgstation.dme
Labels: Feature, Sprites, Tweak

#5741 The Great Trigonometric Sprite Replacement: Phase 1.5
  modular_citadel/code/modules/projectiles/guns/energy/energy_gun.dm
  modular_citadel/code/modules/projectiles/guns/energy/laser.dm
  modular_citadel/icons/mob/inhands/OVERRIDE_guns_lefthand.dmi
  modular_citadel/icons/mob/inhands/OVERRIDE_guns_righthand.dmi
  modular_citadel/icons/obj/guns/OVERRIDE_energy.dmi
  modular_citadel/icons/obj/guns/energy.dmi
  tgstation.dme
Labels: Code Improvement, Sprites

#5696 Adds Pump-Action Particle Blasters!
  modular_citadel/code/modules/jobs/job_types/security.dm
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
  modular_citadel/icons/mob/inhands/guns_lefthand.dmi
  modular_citadel/icons/mob/inhands/guns_righthand.dmi
  modular_citadel/icons/obj/guns/pumpactionblaster.dmi
  modular_citadel/icons/obj/projectiles.dmi
  modular_citadel/sound/weapons/LaserSlugv3.ogg
  modular_citadel/sound/weapons/ParticleBlaster.ogg
  modular_citadel/sound/weapons/laserPump.ogg
  modular_citadel/sound/weapons/laserPumpEmpty.ogg
  tgstation.dme
Labels: Feature, Sound, Sprites

#5725 Dogborg fixes, Borg construction animations!
  code/citadel/dogborgstuff.dm
  code/citadel/icons/robot_transformations.dmi
  code/game/objects/items/defib.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/citadel_refs/borg HUDs.dmi
  icons/mob/citadel_refs/dogborg animations.dmi
  icons/mob/citadel_refs/widerobot_vr.dmi
  icons/mob/robots.dmi
  icons/mob/screen_cyborg.dmi
  icons/mob/widerobot.dmi
  modular_citadel/code/game/machinery/cryopod.dm
  modular_citadel/code/modules/mob/living/silicon/robot/robot.dm
  modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_citadel/icons/mob/robots.dmi
  tgstation.dme
Labels: Enhancement, Feature, Fix, Sprites, Tweak

#5771 What blob
  modular_citadel/code/modules/events/blob.dm
  tgstation.dme
Labels: Tweak

#5740 Tacticool sensors
  modular_citadel/code/modules/clothing/under/syndicate.dm
  tgstation.dme
Labels: Tweak

#5772 Wave 6⅜ of toy guns
  modular_citadel/code/game/objects/effects/temporary_visuals/projectiles/impact.dm
  modular_citadel/code/game/objects/effects/temporary_visuals/projectiles/muzzle.dm
  modular_citadel/code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  modular_citadel/code/modules/projectiles/guns/toys.dm
  modular_citadel/code/modules/research/designs/autoylathe_designs.dm
  modular_citadel/icons/obj/guns/pumpactionblaster.dmi
  modular_citadel/icons/obj/guns/toys.dmi
  modular_citadel/icons/obj/projectiles_impact.dmi
  modular_citadel/icons/obj/projectiles_muzzle.dmi
  modular_citadel/icons/obj/projectiles_tracer.dmi
  tgstation.dme
Labels: Feature

#5777 Balance Pass 5½ for Citadel Guns
  code/citadel/cit_guns.dm
Labels: Balance/Rebalance

#5738 Removes MediHound's Noncon Vore
  code/__DEFINES/preferences.dm
  code/citadel/dogborgstuff.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Drama Overload, Enhancement, Revert/Removal

#5822 Fixes widescreen pref regression
  code/modules/client/client_procs.dm
Labels: Fix, Priority: High

#5722 [READY] Hypospray MK IIs
  code/citadel/hypospraymkii.dm
  code/citadel/hypovial.dm
  icons/obj/citadel/hypospray.dmi
  icons/obj/citadel/vial.dmi
  sound/items/hypospray.ogg
  sound/items/hypospray2.ogg
  sound/items/hypospray_long.ogg
  tgstation.dme
Labels: Feature, Needs Review, Sound, Sprites

#5787 All Maps now have Tesla as a primary engine
  _maps/cit_map_files/BoxStation/BoxStation.dmm
  _maps/cit_map_files/Deltastation/DeltaStation2.dmm
  _maps/cit_map_files/MetaStation/MetaStation.dmm
  _maps/cit_map_files/OmegaStation/OmegaStation.dmm
  _maps/cit_map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/power/tesla/coil.dm
  tgstation.dme
Labels: Feature, Fix, Map Edit

#5789 Vore code to json and more
  code/__DEFINES/preferences.dm
  code/__DEFINES/sound.dm
  code/__DEFINES/voreconstants.dm
  code/__HELPERS/type2type_vr.dm
  code/citadel/dogborgstuff.dm
  code/controllers/subsystem/vore.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_vr.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/examine_vr.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/dragon_vore.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/simple_animal_vr.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/vore_tests.dm
  code/modules/vore/eating/belly_dat_vr.dm
  code/modules/vore/eating/belly_obj_vr.dm
  code/modules/vore/eating/belly_vr.dm
  code/modules/vore/eating/bellymodes_vr.dm
  code/modules/vore/eating/digest_act_vr.dm
  code/modules/vore/eating/living_vr.dm
  code/modules/vore/eating/simple_animal_vr.dm
  code/modules/vore/eating/vore_vr.dm
  code/modules/vore/eating/voreitems.dm
  code/modules/vore/eating/vorepanel_vr.dm
  code/modules/vore/persistence.dm
  modular_citadel/code/modules/client/preferences_toggles.dm
  tgstation.dme
Labels: Balance/Rebalance, Enhancement, Feature, Refactor, Sound

#5817 Filet-O-Sharkpeople
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  modular_citadel/code/modules/food_and_drinks/snacks/meat.dm
  tgstation.dme
Labels: Tweak

#5830 Degradable Darts, Citadel Style
  modular_citadel/code/modules/reagents/chemistry/reagents/other_reagents.dm
  tgstation.dme
Labels: Tweak

#5827 Nymphotrait
  modular_citadel/code/datums/traits/neutral.dm
  tgstation.dme
Labels: Feature

#5843 Trek outfits
  modular_citadel/code/modules/client/loadout/uniform_trek.dm
  modular_citadel/code/modules/clothing/under/trek_under.dm
  modular_citadel/icons/mob/clothing/fed hats n modern.dmi
  modular_citadel/icons/mob/clothing/fedcoats.dmi
  modular_citadel/icons/mob/clothing/trek_item_icon.dmi
  modular_citadel/icons/mob/clothing/trek_mob_icon.dmi
  tgstation.dme
Labels: Feature

#5903 adds two donator items
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#5906 fixes rnd efficiency
  code/modules/research/machinery/_production.dm
Labels: Fix, Priority: High

#5847 Foam Lasertag Darts
  modular_citadel/code/modules/projectiles/ammunition/caseless.dm
  modular_citadel/code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  modular_citadel/code/modules/projectiles/projectiles/reusable.dm
  modular_citadel/code/modules/research/designs/autoylathe_designs.dm
  tgstation.dme
Labels: Feature

#5929 makes traits more paranoid, also removes the double application
  code/controllers/subsystem/processing/traits.dm
  code/modules/client/preferences.dm
Labels: Fix, Priority: High

#5957 Pubbyfix
  _maps/cit_map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Priority: CRITICAL

#5934 Oh that blob
  modular_citadel/code/modules/events/blob.dm
Labels: Tweak

#5937 Small combat balancing: Small crawling nerf, Esword buff
  code/__DEFINES/citadel_defines.dm
  code/modules/mob/living/living.dm
  modular_citadel/code/_onclick/item_attack.dm
  modular_citadel/code/game/objects/items.dm
  modular_citadel/code/game/objects/items/melee/energy.dm
  modular_citadel/code/game/objects/items/melee/transforming.dm
  modular_citadel/code/modules/mob/living/carbon/carbon.dm
  modular_citadel/code/modules/mob/living/living.dm
  tgstation.dme
Labels: Balance/Rebalance, Code Improvement

#5773 [Ready for Review] Revamps Wish Granters
  modular_citadel/code/game/machinery/wishgranter.dm
  modular_citadel/code/game/objects/items/melee/eutactic_blades.dm
  tgstation.dme
Labels: Balance/Rebalance

#5953 Makes xenobio consoles upgradeable via disks obtainable from bluespace research, makes most xenobio console abilities exclusive to disk upgrades
  code/__DEFINES/citadel_defines.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  modular_citadel/code/modules/research/designs/xenobio_designs.dm
  modular_citadel/code/modules/research/techweb/all_nodes.dm
  modular_citadel/code/modules/research/xenobiology/xenobio_camera.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature

#5901 Some minor mood additions
  modular_citadel/code/datums/mood_events/generic_negative_events.dm
  modular_citadel/code/datums/mood_events/generic_positive_events.dm
  modular_citadel/code/datums/mood_events/moodular.dm
  tgstation.dme
Labels: Feature, Tweak

#5904 Ckey locks on Sprite_accessories!
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/sprite_accessories_Citadel.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  icons/mob/human_parts_greyscale.dmi
  icons/mob/mam_body_markings.dmi
  icons/mob/mam_bodyparts.dmi
  icons/mob/mam_taur.dmi
Labels: Feature, Fix, Revert/Removal, Sprites

#5995 sabre and sheath
  icons/mob/custom_w.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/custom.dmi
  modular_citadel/code/game/objects/items/stunsword.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
  modular_citadel/icons/mob/inhands/stunsword_left.dmi
  modular_citadel/icons/mob/inhands/stunsword_right.dmi
Labels: Donor Fluff

#5963 Gives a prompt for people to see who is replying to an mhelp
  modular_citadel/code/modules/mentor/mentorpm.dm
Labels: Enhancement

#5990 Hopefully crushes some runtimes
  code/__DEFINES/misc.dm
  code/controllers/subsystem/vote.dm
  code/datums/brain_damage/mild.dm
  code/game/objects/items/devices/dogborg_sleeper.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/civilian.dm
  modular_citadel/code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  modular_citadel/code/modules/vore/eating/living_vr.dm
Labels: Enhancement, Fix, Priority: High

#5962 Tennis Balls! (and donator stuff)
  modular_citadel/code/game/objects/items/balls.dm
  modular_citadel/code/game/objects/items/melee/eutactic_blades.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/icons/mob/inhands/balls_left.dmi
  modular_citadel/icons/mob/inhands/balls_right.dmi
  modular_citadel/icons/mob/mouthball.dmi
  modular_citadel/icons/obj/balls.dmi
  tgstation.dme
Labels: Donor Fluff, Feature, Sprites

#6036 Donator cloak
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff

#6033 Fixes occupied bluespace bodybags from being put in the analyzer
  code/modules/research/destructive_analyzer.dm
Labels: Fix, Priority: High

#5907 Hypospray kits and reworks!
  cfg/admin.txt
  code/game/machinery/vending.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/vending_items.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_citadel/cit_medkits.dm
  modular_citadel/code/game/machinery/vending.dm
  modular_citadel/code/game/objects/items/storage/firstaid.dm
  modular_citadel/code/game/objects/items/vending_items.dm
  modular_citadel/code/game/objects/structures/crates_lockers/closets/secure/citadel_lockers.dm
  modular_citadel/code/modules/clothing/under/trek_under.dm
  modular_citadel/code/modules/jobs/job_types/medical.dm
  modular_citadel/code/modules/reagents/reagent container/hypospraymkii.dm
  modular_citadel/code/modules/reagents/reagent container/hypovial.dm
  modular_citadel/code/modules/research/designs/autolathe_designs.dm
  modular_citadel/icons/obj/hypospraymkii.dmi
  modular_citadel/icons/obj/vial.dmi
  tgstation.dme
  tgui/assets/tgui.js
  tgui/src/interfaces/chem_master.ract
Labels: Feature, Tweak

#6070 Donator PR, file clean up
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff

#6087 Fix neko ears
  modular_citadel/icons/mob/mutant_bodyparts.dmi
Labels: FUCK, Fix, Priority: CRITICAL

#6091 Donator hotfix
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Donor Fluff

#6049 Adds IPC Antennas
  code/__HELPERS/_cit_helpers.dm
  code/__HELPERS/mobs.dm
  modular_citadel/code/init.dm
  modular_citadel/code/modules/client/preferences.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
  modular_citadel/code/modules/mob/living/carbon/human/species.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/ipc.dm
  modular_citadel/icons/mob/ipc_antennas.dmi
Labels: Feature, Icon/Art

#6089 Temporary Glass of Sake icon fix
  icons/obj/drinks.dmi
Labels: Fix, Test Merge Candidate

#6032 Vore fixes and a few additions
  code/__DEFINES/voreconstants.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/dragon_vore.dm
  modular_citadel/code/modules/vore/eating/belly_obj_vr.dm
  modular_citadel/code/modules/vore/eating/bellymodes_vr.dm
  modular_citadel/code/modules/vore/eating/living_vr.dm
  modular_citadel/code/modules/vore/eating/vore_vr.dm
  modular_citadel/code/modules/vore/eating/vorepanel_vr.dm
Labels: Feature, Fix, Priority: High
