Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-08, with the labels that each got.

#7368 Adds boombox donor item for Raiq/Chefferz
  modular_citadel/code/game/objects/items/boombox.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/icons/obj/boombox.dmi
  tgstation.dme
Labels: Currently Testmerged, Feature

#7405 Small combat tweaks - Removes combat rework training wheels, nerfs boxing gloves
  code/datums/martial/boxing.dm
  modular_citadel/code/datums/status_effects/debuffs.dm
Labels: Balance/Rebalance, Currently Testmerged, Removal

#7360 Replaces plasma in execution syringes with amatoxin
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Currently Testmerged, Tweak

#7401 Hopefully working re-merge of #7391 with some other minor tweaks
  .gitignore
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Currently Testmerged, Map Edit

#7432 Icon Fix
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#7417 doubles hypovial storage
  modular_citadel/code/modules/reagents/reagent container/hypovial.dm
Labels: Currently Testmerged

#7416 halves hypospray times
  modular_citadel/code/modules/reagents/reagent container/hypospraymkii.dm
Labels: Currently Testmerged

#7427 borgis/scrubpups/medihounds aka standard/janitor/medical dogborgs now all have miniextinguishers
  modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Currently Testmerged

#7428 classic/telebatons now deplete the same amount of stamina when harmbatonning as stunbatons
  modular_citadel/game/objects/items/melee/misc.dm
Labels: Currently Testmerged

#7453 spraycan tile thing
  code/game/objects/items/crayons.dm
  icons/effects/crayondecal.dmi
Labels: Currently Testmerged, Sprites

#7429 family heirloom toolboxes are now bulky items but take less stamina to swing, have 2 extra damage, as well as 20 extra damage to structures/objects
  code/game/objects/items/storage/toolbox.dm
Labels: Currently Testmerged

#7439 Manual mirror of sliding puzzles from /tg/, as a lavaland ruin, and an admin smite
  _maps/RandomRuins/LavaRuins/lavaland_surface_puzzle.dmm
  code/__DEFINES/admin.dm
  code/_onclick/click.dm
  code/controllers/subsystem/npcpool.dm
  code/datums/ruins/lavaland.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/ruins/lavalandruin_code/puzzle.dm
  icons/obj/lavaland/artefacts.dmi
  icons/obj/puzzle.dmi
  tgstation.dme
Labels: Currently Testmerged, Map Edit, Sprites

#7441 Blurry eyes just got blurrier
  code/__DEFINES/misc.dm
  code/_onclick/hud/fullscreen.dm
  code/_onclick/hud/plane_master.dm
  code/game/atoms.dm
  code/modules/mob/living/life.dm
  code/modules/mob/status_procs.dm
  icons/mob/screen_gen.dmi
Labels: Currently Testmerged, Sprites, Tweak

#7442 New vending machine UI
  code/modules/vending/_vending.dm
Labels: Currently Testmerged, Tweak

#7444 Changes bomb scaling formula, tier 2 tritium bomb rush nerfed to ~100+k from ~200+k points
  code/game/machinery/doppler_array.dm
Labels: Currently Testmerged

#7458 Buffs jukeboxes - gives music played by jukeboxes double the falloff
  code/controllers/subsystem/jukeboxes.dm
  code/game/machinery/dance_machine.dm
Labels: Balance/Rebalance

#7449 Deep Storage Suit Loot Update. (Alternative to PR #7402)
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
Labels: Currently Testmerged, Map Edit, Tweak

#7454 Clarifies the text in the panic bunker bounce message
  code/modules/admin/IsBanned.dm
  code/modules/client/client_procs.dm
Labels: Currently Testmerged, Tweak

#7467 adds *awoo, *nya, *weh emotes
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/sound/voice/awoo.ogg
  modular_citadel/sound/voice/nya.ogg
  modular_citadel/sound/voice/weh.ogg
Labels: PRB: Reset

#6945 Allows players to commit seppuku with any katana, adds SFX for seppuku
  code/game/objects/items/toys.dm
  code/game/objects/items/weaponry.dm
  code/modules/ninja/energy_katana.dm
Labels: Currently Testmerged, Feature

#7446 Makes Scrapheap cost credits
  code/datums/shuttles.dm
Labels: Currently Testmerged

#7456 lets try to fix this donor item
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Currently Testmerged

#7407 Metachanges
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#7463 removes modularized research override, not needed anymore
  modular_citadel/code/controllers/subsystem/research.dm
  tgstation.dme
Labels: Removal

#7477 Adds antag OOC, off by default.
  code/__DEFINES/misc.dm
  code/_globalvars/configuration.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/verbs/aooc.dm
  code/modules/client/verbs/looc.dm
  tgstation.dme
Labels: Feature, Tweak

#7473 Toxins Lab Quality of Life Improvements.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit, Tweak

#7455 New Alien Lavaland Ruin
  _maps/RandomRuins/LavaRuins/lavaland_surface_alien_nest.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_xeno_nest.dmm
  code/datums/ruins/lavaland.dm
  code/modules/awaymissions/corpse.dm
  code/modules/reagents/reagent_containers/syringes.dm
  config/lavaRuinBlacklist.txt
Labels: Code Improvement, Config Update, Currently Testmerged, Feature, Map Edit, Removal

#7445 Pubby Engineering Improvements
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Tweak

#7450 Bombspear tweaks + embedded item tweaks
  code/__DEFINES/combat.dm
  code/game/objects/items.dm
  code/game/objects/items/grenades/grenade.dm
  code/game/objects/items/twohanded.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Balance/Rebalance, Currently Testmerged, Feature

#7478 Adds emoji support to deadchat and asay.
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/say.dm
Labels: Tweak

#7484 changes maint areas near sec
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit

#7476 fixes the fuckin backwards treadmills in the trash compactor
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#7485 goddamnit
  code/datums/components/storage/concrete/bag_of_holding.dm
Labels: Currently Testmerged

#7482 Open Galaxy
  modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
  modular_citadel/icons/mob/mam_body_markings.dmi
  modular_citadel/icons/mob/mam_bodyparts.dmi
  modular_citadel/icons/mob/mam_taur.dmi
Labels: Currently Testmerged

#7507 Nerfs disablers, buffs tasers
  code/modules/projectiles/projectile/beams.dm
  modular_citadel/code/modules/projectiles/projectile/energy.dm
Labels: Balance/Rebalance

#7521 Fixes Fedoras having armor values
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
Labels: Fix

#7513 adds windoor to atmos flaps
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit
