Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2018-06, with the labels that each got.

#6981 Jar o' Leeches - Donator Item
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#7005 Adds @CitadelBot wheelofsalt command
  modular_citadel/code/modules/admin/chat_commands.dm
  tgstation.dme
Labels: Feature

#7006 Adds table slamming as a right click interaction for tables
  modular_citadel/code/game/objects/structures/tables_racks.dm
  tgstation.dme
Labels: Feature

#6868 Increases head jobs restricted from antag RNG
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/traitor/traitor.dm
Labels: Tweak

#7055 Dark Carapace - Donator Item
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff

#7045 Adds a Cosmetic Flak Jacket and Helmet to the Loadout
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/clothing/head/head.dm
  modular_citadel/code/modules/clothing/suits/suits.dm
  modular_citadel/icons/mob/clothing/space_nam.dmi
  modular_citadel/icons/obj/clothing/space_nam.dmi
  tgstation.dme
Labels: Feature, Sprites

#7062 Quartermaster can no longer be a changeling or traitor
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/traitor/traitor.dm
Labels: Tweak

#7043 Small Cryosleeper Bug Fix and Box Map Fix
  _maps/map_files/BoxStation/BoxStation.dmm
  modular_citadel/code/game/machinery/cryopod.dm
Labels: Map Edit

#7088 Ninja Holding Area Change
  _maps/map_files/generic/CentCom.dmm
Labels: Map Edit

#7146 Prevents the vast majority of IC in LOOC cases
  code/modules/client/verbs/looc.dm
Labels: Tweak

#7151 fixes shock collars
  modular_citadel/code/game/objects/items/devices/radio/shockcollar.dm
Labels: Fix

#7141 Cw's Spaceruins, Maintbar and Kegspawn changes
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomRuins/SpaceRuins/turretedoutpost.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  modular_citadel/code/game/objects/effects/spawner/spawners.dm
Labels: Map Edit

#7148 Makes dogborg tongues reduce firestacks when they lick faces
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
Labels: Balance/Rebalance

#7183 Fixes a merge conflict
  code/modules/clothing/masks/miscellaneous.dm
Labels: Fix

#7078 Adds a tiny "pocket" to the M1 Helmet (flak helmet)
  modular_citadel/code/modules/clothing/head/head.dm
Labels: Balance/Rebalance, Feature

#7108 removes magicarp from gold cores
  modular_citadel/code/modules/events/wizard/magicarp.dm
  tgstation.dme
Labels: Removal

#7110 Adds the Not-Nanotrasen Corporate Uniform and a Silver Bike Horn
  modular_citadel/code/game/objects/items/honk.dm
  modular_citadel/code/modules/clothing/under/under.dm
  modular_citadel/icons/mob/citadel/uniforms.dmi
  modular_citadel/icons/obj/clothing/cit_clothes.dmi
  modular_citadel/icons/obj/honk.dmi
  tgstation.dme
Labels: Feature, Sprites

#7228 adds rubbershot versions for sec rifless
  modular_citadel/code/modules/projectiles/guns/ballistic/rifles.dm
  modular_citadel/code/modules/research/designs/weapon_designs.dm
  modular_citadel/code/modules/research/techweb/all_nodes.dm
  tgstation.dme
Labels: Feature
