Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-01, with the labels that each got.

#7878 Xeno ruin anti-self antagging measures.
  _maps/RandomRuins/LavaRuins/lavaland_surface_alien_nest.dmm
Labels: Map Edit, Tweak

#7866 Makes it possible to instantly get up from resting at a stamina cost equal to your entire stamina buffer
  modular_citadel/code/modules/mob/living/carbon/human/species.dm
Labels: Feature

#7876 Ports tgstation/tgstation#42035 - Notifies admins when Lone Op event chance is changed
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Administration

#7877 [Ready] Makes laser scatter shot cost 5 Tc for a drum
  code/modules/uplink/uplink_items.dm
Labels: Needs Review

#7873 [Ready] New mech weapon, Melon Seed Scatter shot! - Requested and helped made by Elllsiy
  code/game/mecha/equipment/weapons/weapons.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Needs Review, PRB: Reset

#7870 [Ready] Makes the YouTools and Vendomat more useful
  code/modules/vending/assist.dm
  code/modules/vending/youtool.dm
Labels: Needs Review

#7844 Fixes who sorting, removes admin advanced who from non-adminghosted admins
  modular_citadel/code/modules/client/verbs/who.dm
Labels: Priority: High, Test Merge Candidate

#7831 [No this is not just for testmerge]Adds the required assets for the ball map
  code/game/area/areas/centcom.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/signs/signs_maps.dm
  code/game/turfs/closed.dm
  code/game/turfs/open.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/holodeck/turfs.dm
  icons/obj/2x2.dmi
  icons/obj/chairs.dmi
  icons/obj/doors/mineral_doors.dmi
  icons/obj/fluff.dmi
  icons/turf/floors.dmi
Labels: Sprites

#7871 Adds a squeak emote
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/sound/voice/mothsqueak.ogg
Labels: Feature, Sound

#7891 [s] fixes killer tomato logging
  code/modules/hydroponics/grown/tomato.dm
Labels: Priority: High

#7899 [Ready] Makes a few coin items in Getmore Chocolate Corp venders
  code/modules/vending/snack.dm
Labels: Needs Review

#7796 [Ready] Hunting, Anitviro and Russian gear crate!
  code/modules/cargo/packs.dm
Labels: Needs Review

#7879 [Ready] New adv surgery tools!
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/tools.dm
Labels: Needs Review

#7867 [Ready] New Mute quirk as well as Paper bin and crayon box to load-outs! - Requested by Suru
  code/datums/traits/negative.dm
  modular_citadel/code/modules/client/loadout/backpack.dm
Labels: Needs Review

#7858 [Ready] Makes synda paper mask correct eye sight and flash proof
  modular_citadel/code/modules/clothing/glasses/phantomthief.dm
Labels: Needs Review

#7901 [Ready] Moves RCLD to a proper place - Requested by Kevs
  code/modules/cargo/packs.dm
Labels: Needs Review

#7910 Revert "[Ready] Makes synda paper mask correct eye sight and flash proof"
  modular_citadel/code/modules/clothing/glasses/phantomthief.dm
Labels: Needs Review, Revert

#7890 Suicide Messages, Combat Messages, Uniforms Recovered
  code/modules/clothing/under/vg_under.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  modular_citadel/code/modules/arousal/toys/dildos.dm
  sound/weapons/gagging.ogg
Labels: Sound

#7914 Minor reagent_containers clean up on hydroitemdefines.dm
  code/modules/hydroponics/hydroitemdefines.dm
Labels: Code Improvement

#7931 Donator Item - Soul Necklace
  modular_citadel/code/datums/components/souldeath.dm
  modular_citadel/code/game/objects/effects/temporary_visuals/souldeath.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/clothing/neck.dm
  modular_citadel/icons/effects/souldeath.dmi
  modular_citadel/icons/mob/clothing/necks.dmi
  modular_citadel/icons/obj/clothing/cit_neck.dmi
  modular_citadel/sound/misc/souldeath.ogg
  tgstation.dme
Labels: Sound

#7930 Completely tested and working TEG nerf
  code/modules/power/generator.dm
Labels: Balance/Rebalance

#7921 Immersive disposals - Things in disposals will now make sounds when hitting corners
  code/game/sound.dm
  code/modules/recycling/disposal/pipe.dm
  code/modules/recycling/disposal/pipe_sorting.dm
  sound/effects/clang1.ogg
  sound/effects/clang2.ogg
  sound/effects/clangsmall1.ogg
  sound/effects/clangsmall2.ogg
Labels: Feature, Sound

#7920 noisy flashlights - makes flashlights play a sound when toggled
  code/game/objects/items/devices/flashlight.dm
Labels: Feature

#7940 Removes heirloom toolbox extra damage
  code/game/objects/items/storage/toolbox.dm
Labels: Removal

#7945 Fixes a perpetual lack of moisture.
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
  modular_citadel/code/modules/arousal/organs/genitals_sprite_accessories.dm
  modular_citadel/icons/obj/genitals/breasts_onmob.dmi
Labels: Feature, Fix

#7917 [Ready] Adds new Ailurophobia phobia!
  code/controllers/subsystem/traumas.dm
  strings/phobia.json
Labels: Needs Review

#7924 [Ready] Makes paper work for cargo to do for spare credits!
  code/modules/cargo/exports/manifest.dm
  code/modules/cargo/order.dm
  code/modules/cargo/packs.dm
  code/modules/crafting/recipes.dm
Labels: Needs Review

#7964 Adds a Lamp Plushie
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
  modular_citadel/code/modules/client/loadout/backpack.dm
Labels: Code Improvement, Feature, Sprites

#7908 Makes the new player panel display the currently selected character name
  code/modules/mob/dead/new_player/new_player.dm
Labels: Feature

#7911 Makes flashes more useful as a utility item rather than a weapon, as they were meant to be
  code/modules/assembly/flash.dm
Labels: Balance/Rebalance

#7954 Janitor powercreep - buffs mops by axing the delay on their cleaning
  code/game/objects/items/mop.dm
  code/game/sound.dm
  sound/effects/slosh1.ogg
  sound/effects/slosh2.ogg
Labels: Balance/Rebalance, Sound, Tweak

#7958 [Ready] Fixes power tool drill fitting in boots/wallet
  code/datums/components/storage/concrete/pockets.dm
  code/game/objects/items/storage/wallets.dm
Labels: Needs Review

#7956 [Ready] Buffs Cayenne the carp
  code/modules/mob/living/simple_animal/hostile/carp.dm
Labels: Needs Review

#7959 [Ready] Fixes mute trait
  code/datums/traits/negative.dm
Labels: Needs Review
