Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-10, with the labels that each got.

#9367 Totally RADical. Rad levels for Medhud, radiation flags added to storage, suits.
  code/__DEFINES/atom_hud.dm
  code/game/data_huds.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/toolbox.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/living_defines.dm
  code/modules/research/stock_parts.dm
  icons/mob/hud.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites

#9376 Flight Goggles - Donator
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff, Sprites

#9380 refactoring and fixing altdisarm() exploits (ergo pushing people over directional windows etc).
  code/__DEFINES/obj_flags.dm
  code/game/atoms.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/recycling/disposal/bin.dm
Labels: Feature, Fix, Refactor

#9373 Beebalm and Honeybalm plants
  code/modules/hydroponics/grown/flowers.dm
  icons/obj/hydroponics/growing_flowers.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Feature, Sprites

#9365 Fixing an issue with DNA scanners maintenance hatches with sleeper code updates.
  code/game/machinery/Sleeper.dm
  code/game/machinery/dna_scanner.dm
  code/game/machinery/harvester.dm
Labels: Fix, Grammar and Formatting, Tweak

#9393 Fixes AIs being unable to talk through holopads
  code/modules/mob/living/silicon/ai/say.dm
Labels: Fix

#9394 Unfucks Delta's cargo keycard device.
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix, Map Edit

#9385 fixing divine lightblade (chaplain hypereut) having energy reflect
  modular_citadel/code/game/objects/items/melee/eutactic_blades.dm
Labels: Fix

#9407 Adds Cryo QoL with hotkeys
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
Labels: Feature

#9388 Dynamic now auto-deadmin friendly
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Administration

#9401 APC UI autoupdates properly
  code/modules/power/apc.dm
Labels: Fix

#9405 [SPPEEEEDDDDDMERGE] Fixes buffers not doing stuff because oops
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Fix, Tweak

#9382 Borgs are now capable of unbuckling people from chairs, beds and themselves
  code/_onclick/cyborg.dm
Labels: Fix

#9377 [Mild urgency] Fixes melting cleaning grenades found in janitor/cargoboxes.
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#9434 Thinking green on Box Station.
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Fix, Map Edit

#9384 Fixes the Trek uniform/suit sprites
  code/modules/mob/living/carbon/human/update_icons.dm
  modular_citadel/code/modules/clothing/clothing.dm
  modular_citadel/code/modules/clothing/under/trek_under.dm
  modular_citadel/icons/mob/clothing/fed hats n modern.dmi
  modular_citadel/icons/mob/clothing/fedcoats.dmi
  modular_citadel/icons/obj/clothing/trek_item_icon.dmi
Labels: Fix

#9379 Adds unrestricted directional access to the medbay lobby and cloning access airlocks on all maps
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Tweak

#9410 Fixes Cryopod quirks, makes the menu not complete shit
  code/game/machinery/cryopod.dm
  tgstation.dme
Labels: Fix

#9413 Makes Medsprays align with patches
  code/modules/reagents/reagent_containers/medspray.dm
Labels: Balance/Rebalance

#9431 Ports "Makes the illegal tech node harder to unlock"
  code/modules/research/techweb/all_nodes.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#9418 Porting a load of viro, (sentient) disease, symptoms code updates from tg.
  code/__DEFINES/logging.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/_logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/general.dm
  code/datums/components/storage/storage.dm
  code/datums/diseases/_MobProcs.dm
  code/datums/diseases/_disease.dm
  code/datums/diseases/advance/advance.dm
  code/datums/diseases/advance/symptoms/cough.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/diseases/advance/symptoms/oxygen.dm
  code/datums/diseases/advance/symptoms/sneeze.dm
  code/datums/diseases/advance/symptoms/species.dm
  code/datums/diseases/advance/symptoms/symptoms.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/world.dm
  code/modules/antagonists/disease/disease_abilities.dm
  code/modules/antagonists/disease/disease_disease.dm
  code/modules/antagonists/disease/disease_mob.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  config/config.txt
Labels: Balance/Rebalance, Code Improvement, Config Update, Feature, Fix, Tweak

#9406 More Carpet colors and liquid carpet varients
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/table_frames.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  icons/mob/inhands/misc/tiles_lefthand.dmi
  icons/mob/inhands/misc/tiles_righthand.dmi
  icons/obj/smooth_structures/fancy_table_blue.dmi
  icons/obj/smooth_structures/fancy_table_cyan.dmi
  icons/obj/smooth_structures/fancy_table_green.dmi
  icons/obj/smooth_structures/fancy_table_orange.dmi
  icons/obj/smooth_structures/fancy_table_purple.dmi
  icons/obj/smooth_structures/fancy_table_red.dmi
  icons/obj/smooth_structures/fancy_table_royalblack.dmi
  icons/obj/smooth_structures/fancy_table_royalblue.dmi
  icons/obj/structures.dmi
  icons/obj/tiles.dmi
  icons/turf/floors/carpet_blue.dmi
  icons/turf/floors/carpet_cyan.dmi
  icons/turf/floors/carpet_green.dmi
  icons/turf/floors/carpet_orange.dmi
  icons/turf/floors/carpet_purple.dmi
  icons/turf/floors/carpet_red.dmi
  icons/turf/floors/carpet_royalblack.dmi
  icons/turf/floors/carpet_royalblue.dmi
Labels: Feature, Refactor, Sprites

#8937 darkmode/lightmode fixes and tweaks.
  code/__DEFINES/colors.dm
  code/modules/client/asset_cache.dm
  code/modules/client/darkmode.dm
  code/modules/client/verbs/looc.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_dark.css
  code/modules/goonchat/browserassets/css/browserOutput_light.css
  code/modules/goonchat/browserassets/html/browserOutput.html
  code/modules/goonchat/browserassets/js/browserOutput.js
  modular_citadel/interface/skin.dmf
Labels: Approved/Merge Ready, Fix, Tweak

#9032 Ports plasmaman departmental envirosuits and tweaks.
  code/game/machinery/gulag_teleporter.dm
  code/modules/clothing/outfits/plasmaman.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/under/jobs/Plasmaman/civilian_service.dm
  code/modules/clothing/under/jobs/Plasmaman/engineering.dm
  code/modules/clothing/under/jobs/Plasmaman/medsci.dm
  code/modules/clothing/under/jobs/Plasmaman/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
  tgstation.dme
Labels: Balance/Rebalance, Feature, Fix, Removal, Sprites, Work In Progress

#9314 Makes blood gun take 1/4 the blood to use
  code/modules/research/xenobiology/crossbreeding/_weapons.dm
Labels: Tweak

#9287 Adds a markdown parse of all chems for use with github wiki to debug menu.
  code/__HELPERS/files.dm
  code/modules/admin/admin_verbs.dm
  code/modules/reagents/chem_wiki_render.dm
  tgstation.dme
Labels: Feature

#9226 Unmodulars a few things + new sprite + new welder tank(unused
  code/modules/jobs/job_types/captain.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/designs/weapon_designs.dm
  icons/obj/objects.dmi
  modular_citadel/icons/firstaid.dmi
  tgstation.dme
Labels: Code Improvement, Sprites, UI

#9316 [READY] [FermiChem] Turns reaction vars into bitflags and adds a few new procs related to that.
  code/__DEFINES/reagents.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/chemistry/fermi/readme.md
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/impure_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/astrogen.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
  tgstation.dme
Labels: Feature, Needs Review, Refactor

#9404 QM is a head of staff, Cargo ID Console added
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/machinery/computer/card.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  icons/obj/computer.dmi
Labels: Fix, Map Edit, Sprites

#9427 Skeleton and zombie tweaks/balance (featuring "makes halloween skeletons not the overpowered pirate ones")
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/spells/spell_types/lichdom.dm
Labels: Balance/Rebalance, Feature, Removal, Tweak

#9421 Porting some spraycan fixes and tweaks.
  code/game/objects/items/crayons.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Feature, Fix, Tweak

#9391 Rebalances k9borg pounce/bite around the secborg's baton.
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
Labels: Balance/Rebalance

#9389 Ports Beepsky Animations
  icons/mob/aibots.dmi
Labels: Feature, Sprites

#9443 [SPEEDMERGE][PANIC] Fixes all of citadel with supercode.
  code/modules/reagents/chem_wiki_render.dm
Labels: Fix

#9234 [WIP] [TEST-MERGE] Makes clock work reebe less laggy + addtions
  _maps/map_files/generic/City_of_Cogs.dmm
Labels: Feature, Fix, Map Edit, Work In Progress

#8615 Virtual reality componentization.
  code/__DEFINES/components.dm
  code/__HELPERS/game.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/components/virtual_reality.dm
  code/datums/diseases/transformation.dm
  code/datums/mind.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/exp_cloner.dm
  code/modules/VR/vr_human.dm
  code/modules/VR/vr_mob.dm
  code/modules/VR/vr_sleeper.dm
  code/modules/admin/fun_balloon.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/blob/blob/powers.dm
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
  code/modules/antagonists/clockcult/clock_items/construct_chassis.dm
  code/modules/antagonists/clockcult/clock_structures/eminence_spire.dm
  code/modules/antagonists/clockcult/clock_structures/ratvar_the_clockwork_justicar.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/antagonists/disease/disease_event.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/revenant/revenant_spawn_event.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/events/holiday/xmas.dm
  code/modules/events/sentience.dm
  code/modules/events/wizard/imposter.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/mob/transform_procs.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/spells/spell_types/mind_transfer.dm
  modular_citadel/code/modules/mob/living/simple_animal/banana_spider.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
  tgstation.dme
  tgui/src/interfaces/vr_sleeper.ract
Labels: Fix, UI

#9452 Stops non-alphanumeric graffiti decals from being named "letter".
  code/game/objects/items/crayons.dm
Labels: Fix

#9433 Corrects a missing tail state
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  modular_citadel/icons/mob/mam_tails.dmi
Labels: Fix

#9446 abscond can no longer be cast from inside a locker
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
Labels: Fix

#9439 Fixes Dominator countdown continuing after BoH movement, tweaks view amount
  modular_citadel/code/game/gamemodes/gangs/dominator.dm
Labels: Fix, Tweak

#9415 Removes the minimum player cap for the war ops in favour or a more proportional telecrystal bonus.
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
Labels: Removal, Tweak

#9368 Fixes luminescent dark blue major effect and changes the "autoprocess" button to "autoclone"
  code/game/machinery/computer/cloning.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Fix, Tweak

#9257 [READY] Blind quirk without anger
  code/datums/traits/negative.dm
  code/modules/clothing/glasses/_glasses.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Fix, Needs Review, Sprites

#9412 Ports "Makes supermatter melt walls if it finds itself in one"
  code/modules/power/supermatter/supermatter.dm
Labels: Fix

#9324 Ports "Adds toggleable light and blinking charging light to crusher" and "Lets the kinetic crusher be one-hand carried"
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/twohanded.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/machine_vending.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  icons/mob/back.dmi
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
  icons/obj/mining.dmi
Labels: Feature, Sprites

#9458 Nerfs cyborg disabler to hold 25 shots rather than 43, just like a normal disabler.
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/energy/stun.dm
  code/modules/projectiles/guns/energy/stun.dm
Labels: Balance/Rebalance

#9451 standarizes mobs' can_equip arguments.
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/mob/living/simple_animal/friendly/drone/inventory.dm
  code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
Labels: Fix

#9459 Imagine Updating How Tables Work, But Forgetting MY TABLES
  code/game/objects/items/stacks/sheets/glass.dm
Labels: Fix

#9444 [Testmerge first] [Ready] Cleans up holder.dm code and fixes some of the cross bugs from shotgun PR merging.
  code/modules/reagents/chem_wiki_render.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents/impure_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Fix, Needs Review, Refactor, Tweak

#9442 Reverts jetpack efficiency from #9307
  code/modules/mob/living/carbon/human/species.dm
Labels: Revert, Tweak

#9437 Optional Species based clothing restrictions
  code/modules/clothing/clothing.dm
Labels: Feature

#9435 fix fireman carry offhand not automatically deleting itself
  code/datums/components/riding.dm
  code/game/objects/buckling.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#9441 Ports /tg/ advanced surgerytools and tool defines.
  code/__DEFINES/tools.dm
  code/game/mecha/equipment/tools/mining_tools.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/bioware/experimental_dissection.dm
  code/modules/surgery/advanced/brainwashing.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/surgery/advanced/necrotic_revival.dm
  code/modules/surgery/advanced/pacification.dm
  code/modules/surgery/advanced/reconstruction.dm
  code/modules/surgery/advanced/toxichealing.dm
  code/modules/surgery/advanced/viral_bonding.dm
  code/modules/surgery/amputation.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/core_removal.dm
  code/modules/surgery/embalming.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/implant_removal.dm
  code/modules/surgery/limb_augmentation.dm
  code/modules/surgery/lipoplasty.dm
  code/modules/surgery/mechanic_steps.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organic_steps.dm
  code/modules/surgery/plastic_surgery.dm
  code/modules/surgery/tools.dm
  icons/obj/surgery.dmi
Labels: Balance/Rebalance, Refactor, Sprites, Tweak

#9403 Updates Config with Citadel specific links & info
  config/config.txt
Labels: Config Update

#9387 the geese have been unleased
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/sound.dm
  code/game/turfs/turf.dm
  code/modules/cargo/packs.dm
  code/modules/mob/living/simple_animal/hostile/goose.dm
  icons/mob/animal.dmi
  sound/creatures/goose1.ogg
  sound/creatures/goose2.ogg
  sound/creatures/goose3.ogg
  sound/creatures/goose4.ogg
  tgstation.dme
Labels: Feature, Map Edit, Sound, Sprites

#9386 Gives suit storage units the ability to remove radiation from mobs
  code/game/machinery/suit_storage_unit.dm
Labels: Tweak

#9450 Adds more control over species based offsets
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Feature

#9374 ashwalkers now have more messages telling them to not go on station
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Feature

#9467 [s] fixes client analyzation having cid and ip swapped
  code/modules/goonchat/browserOutput.dm
Labels: Fix

#9473 Set clockcult teleport in Captain's Quarters to false.
  code/game/area/Space_Station_13_areas.dm
Labels: Code Improvement

#9463 Updating Kinkmate item-list
  code/modules/clothing/under/accessories.dm
  code/modules/reagents/reagent_containers/bottle.dm
  modular_citadel/code/game/machinery/vending.dm
Labels: Feature, Tweak

#9474 Makes neural nanite programs not drain nanites on things they can't fix
  code/modules/research/nanites/nanite_programs/healing.dm
Labels: Fix

#9464 Re-adds latejoin menu qualifies for rank proc restrictions. Try number 2
  code/__DEFINES/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix

#9416 The niche singularity beacon now also moderately buffs meteor waves.
  code/game/machinery/syndicatebeacon.dm
  code/modules/events/meteor_wave.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#9461 Adding Decorative Wings
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
Labels: Feature

#9339 Removes revenant blight's shabby tox damage in favor of negative mood effects, and necropolis curse if not cured
  code/__DEFINES/components.dm
  code/datums/components/mood.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/status_effects/debuffs.dm
  code/modules/antagonists/revenant/revenant_blight.dm
Labels: Balance/Rebalance, Removal

#9492 Resprites bedsheet bins in 3/4 perspective, adds towel bins subtype.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/structures/bedsheet_bin.dm
  icons/obj/structures.dmi
Labels: Feature, Map Edit, Sprites

#9489 Ports slighty improved drink sprites
  icons/obj/drinks.dmi
Labels: Sprites

#9478 Makes pod people not constantly slightly fat
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
Labels: Tweak

#9488 Adds some missing species_traits for cloth, clockwork and cult golems.
  code/modules/mob/living/carbon/human/species_types/golems.dm
Labels: Fix

#9493 SDGF ghost poll message made terse, other tweaks.
  code/_globalvars/lists/poll_ignore.dm
  code/game/machinery/exp_cloner.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
Labels: Tweak

#9472 [speedmerge] Quickfixforfood and fixes the chem hindenburg
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Fix

#9502 Makes beaker spawn on pandemic instead of on user when hands full
  code/modules/reagents/chemistry/machinery/pandemic.dm
Labels: Tweak

#9499 Add a Blindfold to the loadout list
  modular_citadel/code/modules/client/loadout/glasses.dm
Labels: Feature

#9486 Borgs are now consumable by scrub pups.
  code/game/objects/items/devices/dogborg_sleeper.dm
Labels: Tweak

#9491 Fixes missing decorative wing states
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#9479 fixes bug with new surgerytools examine
  code/modules/surgery/tools.dm
Labels: Fix

#9506 Adds *bark emote
  modular_citadel/code/modules/mob/cit_emotes.dm
Labels: Feature

#9477 [READY] Fixes a few organ code and lets organs freeze based on ambient temperature.
  code/__DEFINES/misc.dm
  code/__DEFINES/obj_flags.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/alien/organs.dm
  code/modules/mob/living/taste.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/surgery/coronary_bypass.dm
  code/modules/surgery/embalming.dm
  code/modules/surgery/graft_synthtissue.dm
  code/modules/surgery/lipoplasty.dm
  code/modules/surgery/organs/autosurgeon.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/stomach.dm
  code/modules/surgery/organs/tongue.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
Labels: Fix, Needs Review

#9517 Gee Nameko, why'd your syndicate employer let you have EIGHT ENERGY CROSSBOWS?
  code/modules/holiday/halloween/halloween.dm
Labels: Fix

#9514 foot fetish content for kevin (ankle coverings)
  code/datums/components/caltrop.dm
  code/datums/components/footstep.dm
  code/modules/clothing/shoes/miscellaneous.dm
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
  modular_citadel/code/modules/client/loadout/shoes.dm
  modular_citadel/icons/mob/digishoes.dmi
Labels: Feature, Sprites, Tweak

#9483 Update toylathe.dm
  modular_citadel/code/game/machinery/toylathe.dm
Labels: Fix, Tweak

#9498 Halloween Dwarves
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
  strings/dwarf_replacement.json
  strings/names/dwarf_first.txt
  strings/names/dwarf_last.txt
  tgstation.dme
Labels: Feature

#9482 Gives chemistry a library (and updates buttons at the top right of the game too).
  code/controllers/configuration/entries/general.dm
  code/game/objects/items/manuals.dm
  icons/obj/library.dmi
  interface/interface.dm
Labels: Config Update, Fix, Sprites, Tweak

#9516 Ports "Fixes morgues being able to consume ghosts, AI-eyes, etc."
  code/game/objects/structures/morgue.dm
Labels: Fix

#9510 Fixing tracking implant teleport issues.
  code/__DEFINES/components.dm
  code/game/machinery/computer/teleporter.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/teleportation.dm
Labels: Fix

#9496 Removes the need of "_l" suffixes for digitigrade clothing on mob states
  code/modules/mob/living/carbon/human/update_icons.dm
  modular_citadel/icons/mob/uniform_digi.dmi
Labels: Removal

#9351 Removes antimagic from holymelon
  code/modules/hydroponics/grown/melon.dm
Labels: Balance/Rebalance, Removal

#9211 [Atomic] Cargo rework - Mat selling nerf, addtion of grater gear to sell MK I
  code/modules/cargo/bounties/assistant.dm
  code/modules/cargo/bounties/botany.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/cargo/bounties/engineering.dm
  code/modules/cargo/bounties/medical.dm
  code/modules/cargo/bounties/mining.dm
  code/modules/cargo/bounties/reagent.dm
  code/modules/cargo/bounties/science.dm
  code/modules/cargo/bounties/security.dm
  code/modules/cargo/bounties/slime.dm
  code/modules/cargo/bounties/special.dm
  code/modules/cargo/bounties/virus.dm
  code/modules/cargo/exports.dm
  code/modules/cargo/exports/gear.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/exports/materials.dm
  code/modules/cargo/exports/orgains_robotics.dm
  code/modules/cargo/exports/parts.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/cargo/exports/tools.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/costumes_toys.dm
  code/modules/cargo/packs/emergency.dm
  code/modules/cargo/packs/engine.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/medical.dm
  code/modules/cargo/packs/misc.dm
  code/modules/cargo/packs/organic.dm
  code/modules/cargo/packs/science.dm
  code/modules/cargo/packs/security.dm
  code/modules/cargo/packs/service.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature, Tweak, Work In Progress

#9343 port just like a ton of surgery changes from tg also abductor too
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/game/machinery/cloning.dm
  code/game/machinery/exp_cloner.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/antagonists/abductor/machinery/camera.dm
  code/modules/antagonists/abductor/machinery/console.dm
  code/modules/antagonists/abductor/machinery/pad.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/mob_helpers.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/bioware/bioware_surgery.dm
  code/modules/surgery/advanced/bioware/experimental_dissection.dm
  code/modules/surgery/advanced/bioware/muscled_veins.dm
  code/modules/surgery/advanced/brainwashing.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/surgery/advanced/pacification.dm
  code/modules/surgery/advanced/reconstruction.dm
  code/modules/surgery/advanced/revival.dm
  code/modules/surgery/advanced/toxichealing.dm
  code/modules/surgery/advanced/viral_bonding.dm
  code/modules/surgery/amputation.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/cavity_implant.dm
  code/modules/surgery/core_removal.dm
  code/modules/surgery/embalming.dm
  code/modules/surgery/experimental_dissection.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/graft_synthtissue.dm
  code/modules/surgery/helpers.dm
  code/modules/surgery/implant_removal.dm
  code/modules/surgery/limb_augmentation.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/prosthetic_replacement.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/surgery_step.dm
  tgstation.dme
Labels: Code Improvement, Feature, Tweak

#9414 nerfs styptic/silversulf/synthflesh to have overdoses
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance

#9505 [READY] Tweaks smartdarts with a few quality of life functions, and add a few new things.
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/modules/crafting/recipes.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/syringes.dm
  icons/obj/guns/projectile.dmi
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/interfaces/chem_master.ract
Labels: Feature, Fix, Needs Review, Sprites, Tweak, UI

#9515 Porting "Moves machine/computer frames and structures below object layer." and lowering trays layer.
  code/__DEFINES/layers.dm
  code/game/objects/structures.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/reflector.dm
  code/game/objects/structures/transit_tubes/transit_tube_pod.dm
  code/modules/antagonists/clockcult/clock_structures/traps/steam_vent.dm
  code/modules/antagonists/clockcult/clock_structures/wall_gear.dm
Labels: Tweak

#9522 Tend Wounds + Make Revival more accessible
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/reconstruction.dm
  code/modules/surgery/healing.dm
  code/modules/surgery/organic_steps.dm
  code/modules/surgery/surgery.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature, Removal

#9503 Taser rework - Gives electrodes a debilitating status effect, makes disabler the default taser mode, and more
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/__HELPERS/mobs.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/status_effect.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/energy/stun.dm
  modular_citadel/code/modules/mob/living/carbon/carbon.dm
  modular_citadel/code/modules/mob/living/living.dm
  modular_citadel/code/modules/projectiles/projectile/energy.dm
  tgstation.dme
Labels: Balance/Rebalance, Tweak

#9466 Adds a config option to determine the minimum alert level for secborgs (defaulting to red alert)
  code/__DEFINES/robots.dm
  code/controllers/configuration/entries/game_options.dm
  code/modules/mob/living/silicon/robot/robot.dm
  config/game_options.txt
  modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Config Update, Tweak

#9537 Magnetic Pistols Fit In Boots
  code/datums/components/storage/concrete/pockets.dm
Labels: Feature

#9545 Ports "UTTERLY CATASTROPHIC pumpkin meteors will now only happen when it's catastrophic meteor wave, instead of 100% ending the round every time any kind of dust appears"
  code/modules/events/meteor_wave.dm
Labels: Fix

#9520 Allow Humans, Felinids, Slimepersons and Lizardpeoples to have Decorative Wings just like Mammals
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
Labels: Feature, PRB: Reset

#9525 Fix decorative angel wings icon
  icons/mob/wings.dmi
Labels: Fix, Sprites

#9524 Colorable decorative wings
  code/__DEFINES/DNA.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
Labels: Feature, Fix, Removal, Tweak

#9536 Change the SEVA suit & Exo-suit's descriptions
  code/modules/mining/equipment/explorer_gear.dm
Labels: Tweak

#8963 healing holoparasites now heals toxlovers
  code/modules/mob/living/simple_animal/guardian/types/support.dm
Labels: Approved/Merge Ready

#9540 Reverts #9189 (Laser Minigun)
  code/modules/crafting/recipes.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/minigun.dm
  code/modules/projectiles/projectile/beams.dm
  sound/weapons/gatling.ogg
  tgstation.dme
Labels: PRB: Reset, Removal, Revert, Sound

#9072 Genpop for security
  code/__DEFINES/access.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/game/machinery/turnstile.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/structures/crates_lockers/closets/genpop.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  icons/obj/closet.dmi
  icons/obj/turnstile.dmi
  tgstation.dme
Labels: Sprites

#8894 T G F U S I O N
  code/__DEFINES/reactions.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/projectiles/projectile/energy/nuclear_particle.dm
Labels: FUCK

#9214 properly ports neovgre from hippie
  code/__DEFINES/clockcult.dm
  code/game/mecha/combat/neovgre.dm
  code/game/mecha/mecha.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_applications.dm
  icons/mecha/neovgre.dmi
  sound/weapons/neovgre_laser.ogg
  tgstation.dme
Labels: Balance/Rebalance, Feature, Sound, Sprites

#9246 [READY] some missing icons + sprite changes for taur suits
  code/modules/clothing/suits/_suits.dm
  code/modules/mining/equipment/explorer_gear.dm
  modular_citadel/icons/mob/taur_canine.dmi
  modular_citadel/icons/mob/taur_hooved.dmi
  modular_citadel/icons/mob/taur_naga.dmi
Labels: Fix, Needs Review

#9534 URGENT fixes for abductors
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/antagonists/abductor/machinery/console.dm
  code/modules/surgery/surgery.dm
Labels: Fix

#9556 Fix not being able to read paper stuck to airlocks, lets AI view paper but with obfuscated text
  code/modules/oracle_ui/hookup_procs.dm
  code/modules/paperwork/paper.dm
Labels: Fix, Tweak

#9551 Fixes recycler deleting all clothing for mobs found inside items (e.g bluespace bodybags)
  code/game/machinery/recycler.dm
Labels: Fix

#9566 Fixes neurotoxin stunning non-carbons
  code/modules/projectiles/projectile/special/neurotoxin.dm
Labels: Fix

#9565 Fixes and nerfs VTEC upgrades
  code/game/objects/items/robot/robot_upgrades.dm
  modular_citadel/code/modules/mob/living/silicon/robot/robot_movement.dm
Labels: Balance/Rebalance

#9561 Fixing some ayy overlays and client images oddities.
  code/game/objects/items/body_egg.dm
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Labels: Fix

#9560 Updates every arrival and escape shuttle with various changes.
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/arrival_box.dmm
  _maps/shuttles/arrival_delta.dmm
  _maps/shuttles/arrival_omega.dmm
  _maps/shuttles/arrival_pubby.dmm
  _maps/shuttles/emergency_airless.dmm
  _maps/shuttles/emergency_asteroid.dmm
  _maps/shuttles/emergency_backup.dmm
  _maps/shuttles/emergency_bar.dmm
  _maps/shuttles/emergency_birdboat.dmm
  _maps/shuttles/emergency_box.dmm
  _maps/shuttles/emergency_cere.dmm
  _maps/shuttles/emergency_clown.dmm
  _maps/shuttles/emergency_cramped.dmm
  _maps/shuttles/emergency_delta.dmm
  _maps/shuttles/emergency_discoinferno.dmm
  _maps/shuttles/emergency_gorilla.dmm
  _maps/shuttles/emergency_luxury.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_mini.dmm
  _maps/shuttles/emergency_narnar.dmm
  _maps/shuttles/emergency_omega.dmm
  _maps/shuttles/emergency_pubby.dmm
  _maps/shuttles/emergency_raven.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/emergency_scrapheap.dmm
  _maps/shuttles/emergency_supermatter.dmm
  _maps/shuttles/emergency_syndicate.dmm
  _maps/shuttles/emergency_wabbajack.dmm
  code/datums/shuttles.dm
Labels: Map Edit

#9583 My shuttle PR got merged before I could push the latest changes so speedmerge this I guess.
  _maps/shuttles/emergency_airless.dmm
  _maps/shuttles/emergency_bar.dmm
  _maps/shuttles/emergency_box.dmm
  _maps/shuttles/emergency_cere.dmm
  _maps/shuttles/emergency_clown.dmm
  _maps/shuttles/emergency_delta.dmm
  _maps/shuttles/emergency_goon.dmm
  _maps/shuttles/emergency_gorilla.dmm
  _maps/shuttles/emergency_luxury.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_omega.dmm
  _maps/shuttles/emergency_pubby.dmm
  _maps/shuttles/emergency_raven.dmm
  _maps/shuttles/emergency_syndicate.dmm
  _maps/shuttles/emergency_wabbajack.dmm
  _maps/shuttles/ferry_fancy.dmm
Labels: Map Edit

#9198 Code stuffs + more framework for cargo rework cuz atomic prs are good
  code/game/objects/items/granters.dm
  code/game/objects/items/religion.dm
  code/modules/crafting/recipes.dm
  code/modules/crafting/recipes/recipes_clothing.dm
  code/modules/crafting/recipes/recipes_misc.dm
  code/modules/crafting/recipes/recipes_primal.dm
  code/modules/crafting/recipes/recipes_robot.dm
  code/modules/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/vending/magivend.dm
  tgstation.dme
Labels: Balance/Rebalance, Code Improvement, Feature, Sprites

#9588 Anthromorph Bat Parts for character customization
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  modular_citadel/icons/mob/mam_ears.dmi
  modular_citadel/icons/mob/mam_markings.dmi
  modular_citadel/icons/mob/mam_snouts.dmi
  modular_citadel/icons/mob/mam_tails.dmi
Labels: Code Improvement, Feature

#9595 Fixes examine strings not properly showing blood-stained status of items
  code/game/atoms.dm
Labels: Fix

#9587 Porting components updates and fixing phantom thief component.
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/vis_overlays.dm
  code/datums/components/_component.dm
  code/datums/components/earprotection.dm
  code/datums/components/mood.dm
  code/datums/components/orbiter.dm
  code/datums/components/phantomthief.dm
  code/datums/components/signal_redirect.dm
  code/datums/components/virtual_reality.dm
  code/datums/components/wearertargeting.dm
  code/datums/components/wet_floor.dm
  code/datums/status_effects/gas.dm
  code/game/objects/effects/proximity.dm
  code/game/objects/items/RCL.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/game/objects/items/his_grace.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/twohanded.dm
  code/modules/antagonists/disease/disease_mob.dm
  code/modules/antagonists/revenant/revenant_blight.dm
  code/modules/assembly/infrared.dm
  code/modules/clothing/gloves/_gloves.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/fields/fields.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/component_tests.dm
  modular_citadel/code/datums/components/phantomthief.dm
  modular_citadel/code/datums/status_effects/chems.dm
  modular_citadel/code/modules/clothing/glasses/phantomthief.dm
  tgstation.dme
Labels: Fix

#9193 Disables crit_threshold changes through mood
  code/datums/components/mood.dm
Labels: Currently Testmerged

#9586 Adds posibrains to the spawners menu for ghosts.
  _maps/RandomRuins/SpaceRuins/augmentationfacility.dmm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/brain/posibrain.dm
Labels: Map Edit

#9585 Fixes artificier lesser magic missile.
  code/modules/spells/spell_types/construct_spells.dm
Labels: Fix

#9550 Fixes temporary transformation sting triggering heart attacks on heartless humans.
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#9548 Fixing radio emotes conflict with drunk memes.
  code/__DEFINES/say.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  modular_citadel/code/modules/mob/mob.dm
Labels: Fix

#9564 The syndicate are led by aliens.
  code/modules/research/research_disk.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Feature, Tweak

#9542 Lowers Cargo most packs down to Pre- MK I Cargo rework*
  code/modules/cargo/exports/manifest.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/emergency.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/cargo/packs/misc.dm
  code/modules/cargo/packs/service.dm
Labels: Tweak

#9582 Adding dynamic rules to the game config
  code/controllers/configuration/config_entry.dm
  code/controllers/configuration/entries/game_options.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  config/game_options.txt
Labels: Config Update, Feature

#9594 Shoes can now hold all pistols
  code/datums/components/storage/concrete/pockets.dm
Labels: Tweak

#9568 [Fix]Make Cells not a viable replacement for the Stock Part Cheese
  code/modules/power/cell.dm
Labels: Fix

#9535 Fixing sniper rifles scope datum action oddity.
  code/game/objects/items.dm
  code/game/objects/items/chrono_eraser.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/devices/traitordevices.dm
  code/game/objects/items/tanks/watertank.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/clockcult/clock_items/judicial_visor.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/spacesuits/flightsuit.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
Labels: Fix

#8654 ports in the Hilbert's Hotel.
  _maps/RandomRuins/SpaceRuins/hilbertshoteltestingsite.dmm
  _maps/templates/hilbertshotel.dmm
  _maps/templates/hilbertshotelempty.dmm
  _maps/templates/hilbertshotellore.dmm
  _maps/templates/hilbertshotelstorage.dmm
  code/controllers/subsystem/mapping.dm
  code/datums/ruins/space.dm
  code/game/objects/items/blueprints.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
  code/modules/shuttle/supply.dm
  code/modules/spells/spell_types/summonitem.dm
  config/spaceRuinBlacklist.txt
  icons/mob/AI.dmi
  icons/mob/actions.dmi
  icons/obj/device.dmi
  icons/obj/items_and_weapons.dmi
  icons/turf/areas.dmi
  icons/turf/space.dmi
  icons/turf/walls.dmi
  sound/ambience/servicebell.ogg
  tgstation.dme
Labels: Config Update, Feature, Map Edit, Refactor, Sound, Sprites

#9593 Fixing gulag teleporter stripping the user of stuff it really shouldn't.
  code/game/machinery/gulag_teleporter.dm
Labels: Fix

#9579 Ports #41638 and #43784, "Wizard Shapeshift now converts damage taken while transformed"
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/silicon/damage_procs.dm
  code/modules/mob/living/silicon/pai/pai_defense.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/spells/spell_types/shapeshift.dm
Labels: Fix, Tweak

#9549 Fixes identity transfer not copying digi legs.
  code/datums/dna.dm
Labels: Fix

#9608 Unmodularize Eutactic Blades.
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/twohanded.dm
  icons/mob/inhands/64x64_righthand.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/1x2.dmi
  icons/obj/items_and_weapons.dmi
  modular_citadel/code/game/objects/items/melee/eutactic_blades.dm
  modular_citadel/icons/eutactic/item/hypereutactic.dmi
  modular_citadel/icons/eutactic/item/noneutactic.dmi
  modular_citadel/icons/eutactic/mob/hypereutactic_left.dmi
  modular_citadel/icons/eutactic/mob/hypereutactic_right.dmi
  modular_citadel/icons/eutactic/mob/noneutactic_left.dmi
  modular_citadel/icons/eutactic/mob/noneutactic_right.dmi
  tgstation.dme
Labels: Sprites

#9603 Unmodularize lavaknights and emags.
  code/game/objects/items/cards_ids.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/card.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/code/game/objects/ids.dm
  modular_citadel/code/modules/awaymissions/citadel_ghostrole_spawners.dm
  modular_citadel/code/modules/clothing/spacesuits/cydonian_armor.dm
  modular_citadel/icons/lavaknight/item/head.dmi
  modular_citadel/icons/lavaknight/item/suit.dmi
  modular_citadel/icons/lavaknight/mob/head.dmi
  modular_citadel/icons/lavaknight/mob/suit.dmi
  modular_citadel/icons/obj/id.dmi
  tgstation.dme
Labels: Fix, Sprites

#9599 Ports "New Revenant icons"
  code/modules/antagonists/revenant/revenant_abilities.dm
  icons/mob/mob.dmi
Labels: Sprites

#9572 Fixes a bunch of CanReach/storage related bugs ("You can no longer stick your hands inside other people and take their things")
  code/_onclick/click.dm
  code/datums/components/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/mob/inventory.dm
Labels: Fix

#9539 TALLY HO! (adds claymores to the uplink)
  code/modules/uplink/uplink_items.dm
Labels: Feature

#9513 medibots are now TOXINLOVER (so slimes) friendly
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Balance/Rebalance

#9619 Buffs engiborg build potential
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/stock_parts.dm
  icons/obj/device.dmi
  icons/obj/storage.dmi
Labels: Sprites

#9613 Port hat tossing
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/throwing.dm
  code/game/atoms_movable.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/hydroponics/beekeeping/beekeeper_suit.dm
Labels: Feature

#9627 Unmodularize MkII hyposprays and other reagent items sprites.
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/hypovial.dm
  code/modules/reagents/reagent_containers/pill.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/syringe.dmi
  modular_citadel/code/modules/reagents/objects/items.dm
  modular_citadel/code/modules/reagents/reagent container/cit_kegs.dm
  modular_citadel/code/modules/reagents/reagent container/hypospraymkii.dm
  modular_citadel/icons/obj/FermiChem.dmi
  modular_citadel/icons/obj/hypospraymkii.dmi
  modular_citadel/icons/obj/modularpills.dmi
  modular_citadel/icons/obj/vial.dmi
  tgstation.dme
Labels: Sprites

#9623 Ports "New Teleporter Station sprites." and "Add teleport station calibration animation."
  code/game/machinery/computer/teleporter.dm
  code/game/machinery/teleporter.dm
  icons/obj/machines/teleporter.dmi
Labels: Feature, Sprites

#9600 Adds two cotten seeds to ash walker home
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
Labels: Feature, Map Edit

#9622 Tweaking the Cyber Sylph's barsign.
  code/game/objects/structures/barsigns.dm
  icons/obj/barsigns.dmi
Labels: Sprites

#9617 Barricade girder walls no longer runtime each tick.
  code/game/machinery/deployable.dm
Labels: Fix

#9630 little camera console fix.
  code/game/machinery/computer/camera.dm
Labels: Fix

#9480 Clarifies ID Console descriptions
  code/modules/jobs/access.dm
Labels: Fix
