Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-03, with the labels that each got.

#8071 Fixes nameless captains being announced with "Captain Captain on deck!"
  code/modules/jobs/job_types/captain.dm
Labels: Fix

#8064 Fixes the IRC not actually displaying the survival rate
  code/__HELPERS/roundend.dm
Labels: Fix

#8062 Increases the atmospherics turf subsystem's wait from 1 to 2 in an attempt to reduce lag
  code/controllers/subsystem/air_turfs.dm
Labels: Tweak

#8052 Makes ling screeches have their own unique screamy sounds, making them much louder.
  code/modules/antagonists/changeling/powers/shriek.dm
  sound/effects/lingempscreech.ogg
  sound/effects/lingscreech.ogg
Labels: Feature, Sound

#8050 Adding a plush
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Sprites

#8051 Reduces the pixel variance of thrown objects by four pixels and attempts to fix bartender glasses tilting uncontrollably
  code/game/objects/items.dm
  code/modules/reagents/reagent_containers.dm
Labels: Fix, Tweak

#8055 Dark Medihound varient & Pup Dozer skin for EngiBorg
  modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_citadel/icons/mob/widerobot.dmi
Labels: Feature

#8054 Adds merp as an emote
  modular_citadel/code/modules/mob/cit_emotes.dm
Labels: Feature

#8053 Makes most synthetic emotes available to humans
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/emote.dm
Labels: Feature

#8059 Makes xeno space ruin have a few non-harmfull orgains
  _maps/RandomRuins/SpaceRuins/derelict1.dmm
Labels: Map Edit

#8080 Buffing sec borg guns.
  code/modules/power/cell.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/stun.dm
Labels: Balance/Rebalance

#8069 Makes the holodeck control room on boxstation compliant with space OSHA
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Tweak

#8095 Adds new and immersive sound for combat
  code/_onclick/item_attack.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/projectile.dm
  sound/weapons/dink.ogg
Labels: Sound

#8083 Fixes genital-less VR people
  code/modules/VR/vr_sleeper.dm
Labels: Fix

#8067 Makes Dinner for two have loot
  _maps/RandomRuins/SpaceRuins/derelict2.dmm
Labels: Map Edit

#8082 Removes Mime insulting
  modular_citadel/code/modules/mob/cit_emotes.dm
Labels: Fix, Removal

#8093 [Ready] Makes Fire extinguisher slip need a screwdriver - Frack & Spensara Request Middle ground by Bhijn
  code/game/objects/items/extinguisher.dm
Labels: Needs Review

#8098 Equalizes security helmet and beret armor
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
Labels: Balance/Rebalance

#8058 Makes jogging let you avoid water slips, but only if you have less than 20% staminaloss
  code/game/turfs/open.dm
Labels: Feature

#8070 Makes bloodcult conversions consensual, similar to Bay.
  code/modules/antagonists/cult/runes.dm
Labels: Feature

#8084 Removes specific names from clone pod reports
  code/game/machinery/cloning.dm
Labels: Removal, Tweak

#8056 Makes the efficiency of the TEG be dependant on how much gas is actively combusting in the hot pipe
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/power/generator.dm
Labels: Balance/Rebalance

#8097 Adds Chilling effects to Slime Crossbreeding
  code/__DEFINES/obj_flags.dm
  code/modules/research/xenobiology/crossbreeding/__corecross.dm
  code/modules/research/xenobiology/crossbreeding/_clothing.dm
  code/modules/research/xenobiology/crossbreeding/_misc.dm
  code/modules/research/xenobiology/crossbreeding/_mobs.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  code/modules/research/xenobiology/crossbreeding/_weapons.dm
  code/modules/research/xenobiology/crossbreeding/chilling.dm
  code/modules/research/xenobiology/xenobiology.dm
  icons/mob/eyes.dmi
  icons/mob/head.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/mask.dmi
  icons/mob/pets.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/food/food.dmi
  icons/obj/slimecrossing.dmi
  tgstation.dme
Labels: Sprites

#8104 Chemical Patches fix.
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/reagent_containers/patch.dm
Labels: Fix

#8110 Revert "Merge pull request #8089 from Trilbyspaceclone/patch-70"
  code/modules/power/port_gen.dm
Labels: Revert

#8114 reduce minimal player age for command jobs
  modular_citadel/code/modules/jobs/job_types/captain.dm
  modular_citadel/code/modules/jobs/job_types/engineering.dm
  modular_citadel/code/modules/jobs/job_types/medical.dm
  modular_citadel/code/modules/jobs/job_types/science.dm
  modular_citadel/code/modules/jobs/job_types/security.dm
Labels: Tweak

#8121 Makes conversions mute victims that are deciding their fate, fixes conversions requiring three culties for refusal to cause a sacrifice
  code/modules/antagonists/cult/runes.dm
Labels: Fix, Tweak

#8119 Properly fixes igniters by increasing the max hotspot expose temperature for sparks to 700 from 300
  code/game/objects/effects/effect_system/effects_sparks.dm
  code/game/objects/items/RPD.dm
  code/modules/power/singularity/emitter.dm
Labels: Fix, Tweak

#8108 Gives space pirates stronger bones.
  _maps/shuttles/pirate_default.dmm
Labels: Feature, Map Edit

#8128 donator beret
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Donor Fluff

#8122 Fixes staminaloss targeted at the head not redirecting to the chest
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#8133 Bye have a beautiful time
  code/controllers/subsystem/ticker.dm
  sound/roundend/haveabeautifultime.ogg
Labels: Sound

#8132 Fixes blood overlay and shield issues for taurs
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/_suits.dm
  modular_citadel/icons/mob/64x32_effects.dmi
Labels: Fix

#8135 Gives RD a multy color pen and the C@ Surgent a NEKO PDA (Yes we have this.)
  _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
  code/game/objects/items/devices/PDA/PDA_types.dm
Labels: Map Edit

#8130 Flavor Text is hidden if your face is obscured
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix

#8141 Nerfs dinks - Ballistic projectiles are now the only projectiles that can emit a dink
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullets/special.dm
Labels: Tweak

#8145 Makes panic bunker toggling and bypassing be logged in IRC
  code/modules/admin/verbs/panicbunker.dm
Labels: Administration

#8118 makes the DNR status affect ghost role (event and spawner roles) eligibility, makes cryopods always apply DNR status, and readds suicide + ghost admin logging
  code/__HELPERS/game.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/verbs/suicide.dm
  code/modules/mob/dead/observer/observer.dm
  modular_citadel/code/game/machinery/cryopod.dm
Labels: Tweak

#8146 Makes OOC and LOOC actually use different toggles
  code/__HELPERS/_cit_helpers.dm
  code/_globalvars/configuration.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/verbs/looc.dm
  code/modules/client/verbs/ooc.dm
Labels: Code Improvement, Tweak

#8160 Lizard Fixes
  icons/mob/human_parts_greyscale.dmi
  modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
Labels: Fix, Sprites

#8169 Taur blood no longer offsets normal suits
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/_suits.dm
Labels: Fix

#8167 Fixes the narsie summon rune not actually looking for the 8 other cult members surrounding it (IN LAYMEN'S TERMS, MAKES IT WORK)
  code/modules/antagonists/cult/runes.dm
Labels: Fix

#8181 PDA Soundpack
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  sound/machines/button.ogg
  sound/machines/button1.ogg
  sound/machines/button2.ogg
  sound/machines/button3.ogg
  sound/machines/button4.ogg
  sound/machines/terminal_eject_disc.ogg
Labels: Sound
