Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-08, with the labels that each got.

#9000 REMOVES SHIELF
  code/modules/uplink/uplink_items.dm
Labels: Fix, Removal

#9001 fix sec and hos skirts
  modular_citadel/code/modules/clothing/under/under.dm
Labels: Removal

#8988 Hallucination Sting Buffs
  code/modules/antagonists/changeling/powers/tiny_prick.dm
Labels: Feature

#8953 Resprites RCDs and RPDs
  code/game/objects/items/RPD.dm
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/tools.dmi
Labels: Feature, Sprites

#8958 Makes a new traitor Emitter gun for Engi memes
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/guns/energy.dmi
Labels: Feature, Sprites

#9026 Alert Level is now displayed at the job selection screen.
  code/modules/mob/dead/new_player/new_player.dm
Labels: Feature

#9008 fix krav maga leg sweep
  code/datums/martial/krav_maga.dm
Labels: Fix

#9005 Adds Key Aunths to each QM room on each map
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Fix, Map Edit

#8994 Makes staminaloss also apply the oxyloss fullscreen overlay.
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
Labels: Tweak

#8942 Changes the Warden's shotgun to instead be foldable, with greatly increased penalties for being folded.
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/obj/guns/projectile.dmi
Labels: Sprites, Tweak

#9018 Ports "Bluespace research updates" and "Teleportation standardization, channels, and interception"
  code/__DEFINES/components.dm
  code/__DEFINES/misc.dm
  code/datums/helper_datums/teleport.dm
  code/game/machinery/computer/camera_advanced.dm
  code/game/machinery/launch_pad.dm
  code/game/machinery/quantum_pad.dm
  code/game/machinery/teleporter.dm
  code/game/mecha/equipment/tools/other_tools.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/effects/blessing.dm
  code/game/objects/effects/effect_system/effects_sparks.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/devices/quantum_keycard.dm
  code/game/objects/items/scrolls.dm
  code/game/objects/items/stacks/bscrystal.dm
  code/game/objects/items/teleprod.dm
  code/modules/antagonists/clockcult/clock_effects/spatial_gateway.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/events/wizard/shuffle.dm
  code/modules/events/wormholes.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/simple_animal/guardian/types/explosive.dm
  code/modules/mob/living/simple_animal/guardian/types/support.dm
  code/modules/projectiles/guns/magic/wand.dm
  code/modules/projectiles/projectile/energy/net_snare.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/experimentor.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  code/modules/research/xenobiology/crossbreeding/burning.dm
  code/modules/research/xenobiology/crossbreeding/consuming.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/spells/spell_types/area_teleport.dm
  code/modules/spells/spell_types/turf_teleport.dm
  icons/effects/effects.dmi
  icons/obj/device.dmi
  tgstation.dme
Labels: Balance/Rebalance, Feature, Fix, Sprites, Tweak

#9044 Adds the ability to construct and deconstruct locker locks
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/bodybag.dm
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
Labels: Feature, Tweak

#9036 fixes combat gloves plus having no icon, allows for shoes to have their item_state set to use a differently named icon on mobs
  code/datums/martial/krav_maga.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Feature, Fix

#9014 undergarment fixes.
  code/game/objects/structures/dresser.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories/undershirt.dm
  code/modules/mob/dead/new_player/sprite_accessories/underwear.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#9009 Fixed WarOps Challenge incorrectly counting players
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
Labels: Fix

#9040 Tweaks cakes, adds in more of them as well as a few more tarts - All hidden
  code/game/objects/items/granters.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/vending/wardrobes.dm
  icons/obj/food/piecake.dmi
  icons/obj/library.dmi
  modular_citadel/icons/obj/food/cake.dmi
Labels: Feature, Sprites

#9033 Fixes Magpistol's Magazine Sprites Being Invisible
  modular_citadel/icons/obj/guns/cit_guns.dmi
Labels: Fix

#9043 [PR 105 BOIS]Connects the Monastery on Pubby to the main station
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit, Tweak

#9030 Fixes a visual glitch with beakers containing water attached to IV stands
  code/game/machinery/iv_drip.dm
  icons/obj/iv_drip.dmi
Labels: Fix, Sprites

#8999 Xenomorph larvae no longer gib and inexplicably delete your brain when hatching
  code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Labels: Balance/Rebalance

#8996 Adds in worn overlays for different types of cuffs.
  code/game/objects/items/handcuffs.dm
  code/modules/antagonists/clockcult/clock_helpers/slab_abilities.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  icons/mob/alien.dmi
  icons/mob/alienqueen.dmi
  icons/mob/inhands/equipment/security_lefthand.dmi
  icons/mob/inhands/equipment/security_righthand.dmi
  icons/mob/mob.dmi
  icons/mob/restraints.dmi
  modular_citadel/code/game/objects/items/handcuffs.dm
  tgstation.dme
Labels: Sprites

#8995 Fixes jogging on wet tiles actually slipping you if you have less than 20 stamloss
  code/game/turfs/open.dm
Labels: Feature

#9024 Ports "Lizardwine drink crafting fix"
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
Labels: Fix

#9042 [ THE FEMUR BREAKER ]
  code/game/objects/structures/femur_breaker.dm
  code/modules/crafting/recipes.dm
  icons/obj/femur_breaker.dmi
  sound/effects/femur_breaker.ogg
  tgstation.dme
Labels: Feature, Sound, Sprites

#8912 Ports "Headset Channel Descriptions Are No Longer Hardcoded"
  code/__DEFINES/radio.dm
  code/__DEFINES/say.dm
  code/datums/saymode.dm
  code/game/communications.dm
  code/game/machinery/bank_machine.dm
  code/game/machinery/cloning.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/hivemind.dm
  code/modules/antagonists/changeling/powers/linglink.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/honkbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/surgery/organs/vocal_cords.dm
  modular_citadel/code/modules/jobs/job_types/captain.dm
Labels: Code Improvement, Feature, Tweak

#9019 Adds in a stereotypical vegetarian MRE. Tweaks the rest.
  code/game/objects/items/storage/boxes.dm
  code/modules/cargo/packs.dm
  icons/obj/storage.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites

#8913 Makes brass/bronze bar stools and stools - Same as normal ones
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/beds_chairs/chair.dm
  icons/obj/chairs.dmi
Labels: Feature, Sprites

#8774 Removes the human check from cap/chap mind on cult conversion.
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
Labels: Balance/Rebalance

#8660 Ummodular a few files - Fixes Freelance Crate costs
  code/modules/cargo/exports/manifest.dm
  code/modules/cargo/packs.dm
  code/modules/crafting/recipes.dm
  code/modules/mining/mine_items.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/uplink/uplink_items.dm
  tgstation.dme
Labels: Code Improvement

#8998 Fixes inactive high luminosity eyes turning back on as soon as you move around.
  code/modules/surgery/organs/eyes.dm
Labels: Fix

#9021 Ports "Adds techpriest robes and adds them to the RoboDrobe"
  code/modules/clothing/suits/jobs.dm
  code/modules/vending/wardrobes.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/icons/mob/muzzled_helmet.dmi
Labels: Feature, Sprites

#9007 Fixes and standarizes sword sheaths/scabbards overlays.
  code/game/objects/items.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/storage/belt.dm
  icons/mob/custom_w.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/custom.dmi
  modular_citadel/code/game/objects/items/stunsword.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#9046 meteor sats are no longer dense objects
  code/modules/station_goals/shield.dm
Labels: Tweak

#8908 Fixes Zelus flasks a bit.
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/antagonists/clockcult/clock_items/clockwork_armor.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
Labels: Balance/Rebalance, Code Improvement

#8900 Abductor Replication Lab space ruin - take 2
  _maps/RandomRuins/SpaceRuins/advancedlab.dmm
  code/datums/ruins/space.dm
  code/datums/wires/_wires.dm
  code/game/area/areas/ruins/space.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  config/spaceRuinBlacklist.txt
  icons/obj/advancedtools.dmi
Labels: Config Update, Feature, Map Edit, Sprites

#9045 Officially ends the non-stop thrill ride of coating the station in your gender fluids for "fun"
  code/__DEFINES/citadel_defines.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
  modular_citadel/code/modules/arousal/organs/testicles.dm
  modular_citadel/code/modules/arousal/organs/womb.dm
  modular_citadel/code/modules/reagents/reagents/cit_reagents.dm
Labels: Tweak

#9050 Fixes combatmode pushing not knocking people down against walls.
  modular_citadel/code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#8923 Removes damage from *dab
  modular_citadel/code/modules/mob/cit_emotes.dm
Labels: Removal

#8673 Makes upgraded prostics worth getting - Re-balances robotic lims
  code/modules/surgery/bodyparts/robot_bodyparts.dm
Labels: Balance/Rebalance

#8986 reworked ninja stealth, made ninja shoes completely silent, cleaned up scarily old code.
  code/__DEFINES/traits.dm
  code/datums/components/footstep.dm
  code/modules/ninja/suit/n_suit_verbs/ninja_stealth.dm
  code/modules/ninja/suit/shoes.dm
  code/modules/ninja/suit/suit.dm
  code/modules/ninja/suit/suit_initialisation.dm
  code/modules/ninja/suit/suit_process.dm
Labels: Code Improvement, Feature

#9022 Ports "More robust dorfs."
  code/datums/mutations/body.dm
Labels: Tweak

#9069 Fixes cults teleportations.
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/cult/runes.dm
Labels: Fix

#9061 Makes the femur breaker use the proper scream emote and makes the femur breaker guarantee the victim falls into crit
  code/game/objects/structures/femur_breaker.dm
Labels: Tweak

#9071 Nerfs Autocloning
  code/game/machinery/computer/cloning.dm
Labels: Balance/Rebalance

#9081 Central Command informs you when a Meteor Storm is about to hit 5 to 10 minutes before it happens
  code/modules/events/meteor_wave.dm
Labels: Balance/Rebalance

#9085 underwear colors fix 2: The revenge of the crunch.
  code/game/objects/structures/dresser.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#9084 Fixes clock cult mass recall.
  code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
Labels: Fix

#9083 Strawbarries, and more
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/hydroponics/grown/berries.dm
  icons/obj/food/food.dmi
  icons/obj/food/piecake.dmi
  icons/obj/hydroponics/growing_fruits.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Feature, Sprites

#9070 adds rainbow knife inhands icon, also normalises knife colour
  icons/mob/inhands/equipment/kitchen_lefthand.dmi
  icons/mob/inhands/equipment/kitchen_righthand.dmi
Labels: Feature, Sprites, Tweak

#9064 Hugs of the North Star
  code/game/machinery/computer/arcade.dm
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Feature

#9078 Changes teleporter machines to apply flyperson (more) equally
  code/game/machinery/teleporter.dm
Labels: Balance/Rebalance, Tweak

#9101 obfuscates specific surgeries, gives generalized areas to anybody in viewing range
  code/game/machinery/computer/Operating.dm
  code/modules/mob/mob.dm
  code/modules/surgery/advanced/bioware/nerve_grounding.dm
  code/modules/surgery/advanced/bioware/nerve_splicing.dm
  code/modules/surgery/advanced/bioware/vein_threading.dm
  code/modules/surgery/advanced/brainwashing.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/surgery/advanced/necrotic_revival.dm
  code/modules/surgery/advanced/pacification.dm
  code/modules/surgery/advanced/revival.dm
  code/modules/surgery/advanced/viral_bonding.dm
  code/modules/surgery/amputation.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/cavity_implant.dm
  code/modules/surgery/core_removal.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/helpers.dm
  code/modules/surgery/implant_removal.dm
  code/modules/surgery/limb_augmentation.dm
  code/modules/surgery/lipoplasty.dm
  code/modules/surgery/mechanic_steps.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organic_steps.dm
  code/modules/surgery/plastic_surgery.dm
  code/modules/surgery/prosthetic_replacement.dm
  code/modules/surgery/remove_embedded_object.dm
  code/modules/surgery/surgery_step.dm
Labels: Feature

#9079 gives ling armblade 20 armor pen to make it more in line with eswords
  code/modules/antagonists/changeling/powers/mutations.dm
Labels: Balance/Rebalance

#9075 Removes a redunant Remove() from high luminosity eyes.
  code/modules/surgery/organs/eyes.dm
Labels: Removal

#9062 Makes smile not as horrable.
  code/datums/mutations/speech.dm
Labels: Grammar and Formatting

#9054 stands now remove trait_nodeath from their user if given by memento mori
  code/modules/mob/living/simple_animal/guardian/guardian.dm
Labels: Balance/Rebalance

#8927 Tones down some items attack stamina costs. kills hypereutactic blades copypasta.
  code/__DEFINES/citadel_defines.dm
  code/__DEFINES/combat.dm
  code/_onclick/item_attack.dm
  code/game/machinery/computer/arcade.dm
  code/game/objects/items.dm
  code/game/objects/items/his_grace.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/melee/transforming.dm
  code/game/objects/items/singularityhammer.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/research/xenobiology/crossbreeding/_weapons.dm
  code/modules/zombie/items.dm
  modular_citadel/code/_onclick/item_attack.dm
  modular_citadel/code/game/machinery/wishgranter.dm
  modular_citadel/code/game/objects/items.dm
  modular_citadel/code/game/objects/items/melee/energy.dm
  modular_citadel/code/game/objects/items/melee/eutactic_blades.dm
  modular_citadel/code/game/objects/items/melee/transforming.dm
  modular_citadel/code/modules/awaymissions/citadel_ghostrole_spawners.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  tgstation.dme
Labels: Balance/Rebalance, Code Improvement

#9010 War Ops now informs the crew where the Nuclear Device is located when activated.
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Balance/Rebalance

#8992 [READY] Hardsuit helmets can now be used as internals masks. Rejoice, CE mains.
  code/__DEFINES/inventory.dm
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items/tanks/tanks.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/life.dm
Labels: Feature, Needs Review, Refactor

#9113 [SUGGESTED TESTMERGE] Fixes rounding errors with chemical reactions
  code/modules/reagents/chemistry/holder.dm
Labels: Fix, Tweak

#9115 Removes wah! from message_admins
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
Labels: Fix, Removal

#9098 Fixes Tea Aspera
  code/modules/hydroponics/grown/tea_coffee.dm
Labels: Fix

#9100 Breasts no longer lactate by default, Lactation is now a preference
  code/__HELPERS/mobs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
Labels: Tweak

#9052 Hmm, today the Hierophant will go sicko mode on shaft miners.
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
Labels: Balance/Rebalance

#9103 Donator item
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff, Sprites

#9126 Adds more variety in virus cures, more consistent difficulty scaling.
  code/datums/diseases/advance/advance.dm
  code/modules/antagonists/disease/disease_disease.dm
Labels: Balance/Rebalance

#9107 Fixes handcuffs being impossible to actually resist out of
  code/modules/mob/living/living.dm
  modular_citadel/code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#9119 Adds mining shuttle console to the techweb.
  code/modules/research/designs/comp_board_designs/comp_board_designs_cargo .dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#9133 Increase the amount of canned peaches that spawn within maintenance
  code/_globalvars/lists/maintenance_loot.dm
Labels: Tweak

#9130 Service QoL
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/storage/belt.dm
  code/modules/cargo/packs.dm
  code/modules/hydroponics/gene_modder.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/designs/power_designs.dm
Labels: Balance/Rebalance, Feature, Tweak

#9088 Fixes some runtimes and removes a holodeck exploit
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/vore.dm
  code/game/world.dm
  code/modules/holodeck/holo_effect.dm
  code/modules/mob/living/simple_animal/simple_animal_vr.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  modular_citadel/code/datums/mood_events/moodular.dm
  modular_citadel/code/modules/vore/eating/belly_obj_vr.dm
  modular_citadel/code/modules/vore/eating/bellymodes_vr.dm
Labels: Removal

#9138 re-adds sugarcane seeds to megaseed vendors
  code/modules/vending/megaseed.dm
Labels: Fix

#9141 Actually fixes warp whistle runtimes
  code/modules/antagonists/wizard/equipment/artefact.dm
Labels: Fix

#9136 strained muscles now costs chems to use, slows chem regen, and drains stacking stamina over time
  code/modules/antagonists/changeling/powers/strained_muscles.dm
Labels: Balance/Rebalance

#9134 Nanite Adv toxin healing now heals slimes
  code/modules/research/nanites/nanite_programs/healing.dm
Labels: Tweak

#9151 Adds chameloen necktie item
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/chameleon.dm
Labels: Feature

#9137 addition of the "assistant response team" a pack of assistants sent in from CComm
  _maps/map_files/generic/CentCom.dmm
  code/datums/ert.dm
  code/modules/antagonists/greybois/greybois.dm
  code/modules/clothing/outfits/ert.dm
  tgstation.dme
Labels: Feature, Fix, Map Edit

#9097 Adds durathread.
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/sheets/sheets.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/loom.dm
  code/modules/clothing/head/beanie.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/crafting/recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/cotton.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/growninedible.dm
  code/modules/vending/megaseed.dm
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/mob/inhands/equipment/belt_lefthand.dmi
  icons/mob/inhands/equipment/belt_righthand.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/storage.dmi
  modular_citadel/icons/mob/uniform_digi.dmi
  tgstation.dme
Labels: Feature, Sprites

#9149 Adds Tatical armor to IAA/Synda uplinks as well as some armor accessorys
  code/modules/clothing/under/accessories.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/accessories.dmi
  icons/obj/clothing/accessories.dmi
Labels: Feature, Sprites

#8763 Reblances bone satchles
  code/game/objects/items/storage/backpack.dm
Labels: Balance/Rebalance

#8636 Fixes missing air in Gas the Lizards in the freezer/surgery
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
Labels: Fix, Map Edit

#8349 Removes Nitryl bounty but adds 7 more in!
  code/modules/cargo/bounties/engineering.dm
Labels: Feature, Removal

#9162 heirloom briefcase resprite & rebalance
  code/game/objects/items/storage/briefcase.dm
  icons/mob/inhands/equipment/briefcase_lefthand.dmi
  icons/mob/inhands/equipment/briefcase_righthand.dmi
  icons/obj/storage.dmi
Labels: Balance/Rebalance, Sprites

#9142 removes glue from nukies/clownops uplinks
  code/modules/uplink/uplink_items.dm
Labels: Removal, Tweak

#9145 gives drones a RPD
  code/game/objects/items/storage/backpack.dm
Labels: Feature

#8968 Fixes dead/used face huggers from still infecting
  code/modules/mob/living/carbon/alien/special/facehugger.dm
Labels: Fix

#9164 lolman fucks up his first pr
  icons/mob/head.dmi
  icons/mob/mask.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/stack_objects.dmi
  modular_citadel/icons/mob/uniform_digi.dmi
Labels: Do Not Merge, Sprites

#9184 Removes an obnoxious temporary overlay var.
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
Labels: Removal

#9074 Donator grouping system
  code/__DEFINES/donator_groupings.dm
  code/__HELPERS/donator_groupings.dm
  code/_globalvars/lists/misc.dm
  code/controllers/configuration/config_entry.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/donator.dm
  code/modules/client/preferences.dm
  config/config.txt
  config/donator_groupings.txt
  modular_citadel/code/controllers/subsystem/job.dm
  modular_citadel/code/modules/client/loadout/_loadout.dm
  tgstation.dme
Labels: Config Update, Testmerge only

#9132 Toricrates: Remastered: Complete Edition 2019
  icons/obj/crates.dmi
Labels: Sprites

#9172 You rack the riot shotgun
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Feature

#9168 Adds looc hotkey - on examination, just makes it better
  code/controllers/subsystem/input.dm
Labels: Feature

#9208 Socks uncolorability fix.
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#9204 Fixes katana's being cursed when not cursed
  code/game/objects/items/weaponry.dm
Labels: Fix

#9200 Fixes Strawberries
  code/modules/hydroponics/grown/berries.dm
Labels: Fix

#9178 fixes the poly tgs command not working at all
  modular_citadel/code/modules/admin/chat_commands.dm
Labels: Fix

#9173 Removes duplicate definition of games and toys nodes and readds autoylathe
  code/modules/research/techweb/all_nodes.dm
Labels: Removal

#9210 [SPEEDMERGE NOW I THINK] Delta Chapel Driver fixes
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix, Map Edit, Tweak

#9216 Fixes "Silver Core Luminescents Can Spawn "Oops" #9215"
  code/__HELPERS/unsorted.dm
Labels: Fix

#9219 Ports "Fixes slimes not feeding #44760"
  code/modules/mob/living/simple_animal/slime/life.dm
Labels: Fix
