Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-05, with the labels that each got.

#8319 Adds Penis Enlargement Pills
  code/__DEFINES/DNA.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/pill.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
Labels: Feature

#8315 Maybe fixes laser carbine sprites
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/research/designs/weapon_designs.dm
Labels: Fix

#8317 [s] Clamps biogen amount to a sane amount
  code/modules/hydroponics/biogenerator.dm
Labels: Tweak

#8162 [Ready] Makes Cursed Katana's be Cursed once more
  code/game/objects/items/weaponry.dm
Labels: Needs Review

#8318 Adds more brain damage text
  strings/traumas.json
Labels: Feature

#8285 vent_clog event now respects vent welding
  code/modules/events/vent_clog.dm
Labels: i ded

#8323 Makes a new COMBAT inducer! - Admin only
  code/game/objects/items/inducer.dm
  code/modules/research/designs/power_designs.dm
  icons/obj/tools.dmi
Labels: Feature, Sprites

#8341 Golden toolboxes.
  code/game/objects/items/storage/toolbox.dm
  code/modules/crafting/recipes.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#8338 Satchel of Holding!
  code/game/objects/items/storage/backpack.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/back.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/obj/storage.dmi
Labels: Sprites

#8335 Quick fiiiix marking
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/helpers.dm
  icons/mob/human_parts_greyscale.dmi
  modular_citadel/icons/mob/muzzled_helmet.dmi
Labels: Fix, Sprites

#8334 Increased music maxlines from 300 to 600
  code/game/objects/structures/musician.dm
Labels: Tweak

#8331 Dildo-shaped circuit assemblies. Because that's what the community needs.
  code/controllers/subsystem/processing/circuit.dm
  code/modules/integrated_electronics/core/assemblies.dm
  icons/obj/assemblies/electronic_setups.dmi
Labels: Sprites

#8322 Buffs mag-gun recharges speed
  modular_citadel/code/modules/projectiles/guns/ballistic/magweapon_energy.dm
Labels: Tweak

#8342 Adds EMP Defensive Traps to Clockcult
  code/game/objects/empulse.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/antagonists/clockcult/clock_structures/trap_triggers/pressure_sensor_mech.dm
  code/modules/antagonists/clockcult/clock_structures/traps/brass_skewer.dm
  code/modules/antagonists/clockcult/clock_structures/traps/power_null.dm
  icons/obj/clockwork_objects.dmi
  strings/clockwork_cult_changelog.txt
  strings/tips.txt
  tgstation.dme
Labels: Feature, Sprites, Tweak

#8316 Better Locked Collar checks
  code/modules/clothing/neck/_neck.dm
  code/modules/research/designs/autolathe_designs.dm
Labels: Tweak

#8352 [S] Fixes a fairly huge vector for server crashes (tgcode edition)
  code/__DEFINES/misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix

#8336 Adds Stun Circuit, Pneumatic Cannon Circuit. Makes Extinguisher and Smoke Reagent circuits work.
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
  code/modules/integrated_electronics/subtypes/weaponized.dm
  modular_citadel/code/modules/integrated_electronics/subtypes/manipulation.dm
  tgstation.dme
Labels: Feature, Fix

#8332 Two new collar types (with lockable variants). All collars are now colorable a'la polychromic stuff.
  code/modules/clothing/neck/_neck.dm
  icons/mob/neck.dmi
  icons/obj/clothing/neck.dmi
  modular_citadel/code/modules/client/loadout/neck.dm
Labels: Sprites

#8330 This is an entire addition to put stargazers back into clock cult.
  code/__DEFINES/clockcult.dm
  code/modules/antagonists/clockcult/clock_items/clockwork_slab.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/clockcult/clock_structures/stargazer.dm
  tgstation.dme
Labels: Balance/Rebalance, Config Update, Feature, Tweak

#8311 Adds new phobias and tweaks others - syndicate, eye phobia
  code/controllers/subsystem/traumas.dm
  strings/phobia.json
Labels: Feature, Tweak

#8268 Makes auto transfer delay loaded from config rather than hardcoded to 2 hours
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/shuttle.dm
Labels: Config Update

#8364 Improved Vent and Scrubber icon port
  icons/obj/atmospherics/components/unary_devices.dmi
  icons/obj/atmospherics/pipes/pipe_item.dmi
Labels: Sprites

#8348 Makes suitcases craftable
  code/game/objects/items/storage/briefcase.dm
  code/modules/crafting/recipes.dm
Labels: Feature

#8303 Vent Clog Event Rebalance and Improvements
  code/modules/events/vent_clog.dm
Labels: Balance/Rebalance, Feature

#8362 Making the Improvised Jetpack recipe less confusing
  code/modules/crafting/recipes.dm
Labels: Tweak

#8388 Quick fix for the colorable collars. I've made the mistake of not testing code after applying a suggestion.
  code/modules/clothing/neck/_neck.dm
Labels: Fix

#8380 SEENGING PAIPZE
  icons/obj/atmospherics/components/unary_devices.dmi
  icons/obj/atmospherics/pipes/pipe_item.dmi
Labels: Sprites

#8377 Improves Recycler code by making it respect indestructible resistance
  code/game/machinery/recycler.dm
Labels: Balance/Rebalance

#8374 Heart Attacks will murder you now
  code/datums/diseases/heart_failure.dm
  code/modules/surgery/organs/heart.dm
Labels: Fix

#8372 Unfucks borg defibs
  code/game/objects/items/defib.dm
Labels: Fix

#8367 [READY] Genital fixes and skintone sync [Adds erections[]
  code/__DEFINES/citadel_defines.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
  modular_citadel/code/modules/arousal/organs/genitals_sprite_accessories.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/arousal/organs/vagina.dm
  modular_citadel/icons/obj/genitals/breasts.dmi
  modular_citadel/icons/obj/genitals/breasts_onmob.dmi
  modular_citadel/icons/obj/genitals/penis.dmi
  modular_citadel/icons/obj/genitals/penis_onmob.dmi
  modular_citadel/icons/obj/genitals/vagina.dmi
  modular_citadel/icons/obj/genitals/vagina_onmob.dmi
Labels: Feature, Fix, Needs Review

#8392 Fixes Kiara's sabre belt icons, fixes armor offsets for taurs
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/custom_loadout/custom_items.dm
  modular_citadel/icons/mob/mam_taur.dmi
Labels: Fix, Sprites

#8376 Ports Oracle's cloning tube
  code/game/machinery/cloning.dm
  code/game/machinery/dna_scanner.dm
  icons/obj/cryo_mobs.dmi
  icons/obj/machines/cloning.dmi
Labels: Feature, Sprites

#8366 Cryopod mapping fixes and additions
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  icons/obj/Cryogenic2.dmi
Labels: Feature, Fix, Map Edit, Sprites, Tweak

#8393 Sleepers now show blood level and type for occupants.
  code/game/machinery/Sleeper.dm
  tgui/assets/tgui.js
  tgui/package-lock.json
  tgui/package.json
  tgui/src/interfaces/sleeper.ract
Labels: Feature, UI

#8378 Nutcracker. Yes, it's big enough to crush heads.
  code/modules/surgery/nutcracker.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/surgery.dmi
  tgstation.dme
Labels: Sprites

#8369 Adds more shuttle curse texts
  code/modules/antagonists/cult/cult_items.dm
Labels: Feature

#8368 Adds more clothing to venders
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
Labels: Feature

#8370 Adds a few more mime names
  strings/names/mime.txt
Labels: Feature

#8179 [Ready]Makes a blue space bike horn HONK
  code/datums/mood_events/generic_positive_events.dm
  code/modules/crafting/recipes.dm
  modular_citadel/code/game/objects/items/honk.dm
  modular_citadel/icons/obj/honk.dmi
Labels: Needs Review

#8253 Removes firing pins from preprinted gravity guns
  code/modules/projectiles/guns/energy/special.dm
Labels: Removal

#8400 Watcher Wing Trophy Effect increase
  code/modules/mining/equipment/kinetic_crusher.dm
Labels: Tweak

#8411 Makes mag guns fire 3 mags before running out of power
  modular_citadel/code/modules/projectiles/guns/ballistic/magweapon_energy.dm
Labels: Balance/Rebalance

#8429 [s] fixes a major exploit involving concatenators
  code/modules/integrated_electronics/subtypes/converters.dm
Labels: Fix

#8420 Fixes shield blobs being completely invulnerable to all forms of damage after reaching a weakened state.
  code/modules/antagonists/blob/blob/blobs/shield.dm
Labels: Fix, Tweak

#8425 Ports TG firebots.
  code/__DEFINES/robots.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/extinguisher.dm
  code/modules/crafting/recipes.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  icons/mob/aibots.dmi
  sound/voice/firebot/detected.ogg
  sound/voice/firebot/extinguishing.ogg
  sound/voice/firebot/keepitcool.ogg
  sound/voice/firebot/nofires.ogg
  sound/voice/firebot/onlyyou.ogg
  sound/voice/firebot/stopdropnroll.ogg
  sound/voice/firebot/tempnominal.ogg
  tgstation.dme
Labels: Sound, Sprites

#8409 Fixes species getting genitals at all if NOGENITAL'd
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
Labels: Fix

#8407 Female Gendered markings and leg sprite fixes
  code/modules/surgery/bodyparts/bodyparts.dm
  icons/mob/human_parts_greyscale.dmi
  modular_citadel/icons/mob/mam_markings.dmi
  modular_citadel/icons/mob/markings_notmammals.dmi
  modular_citadel/icons/mob/mutant_bodyparts.dmi
Labels: Feature, Fix, Sprites

#8397 Changed arousal message styling.
  code/modules/goonchat/browserassets/css/browserOutput.css
  modular_citadel/code/datums/mood_events/generic_positive_events.dm
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/reagents/reagents/cit_reagents.dm
Labels: Fix, Tweak

#8384 Ports new footstep sounds from base /tg/
  code/__DEFINES/footsteps.dm
  code/__DEFINES/is_helpers.dm
  code/datums/components/footstep.dm
  code/game/turfs/open.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/game/turfs/simulated/floor/misc_floor.dm
  code/game/turfs/simulated/floor/plating.dm
  code/game/turfs/simulated/floor/plating/asteroid.dm
  code/game/turfs/simulated/floor/plating/dirt.dm
  code/game/turfs/simulated/floor/plating/misc_plating.dm
  code/game/turfs/simulated/floor/reinf_floor.dm
  code/game/turfs/simulated/lava.dm
  code/game/turfs/simulated/water.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  sound/effects/footstep/carpetbarefoot1.ogg
  sound/effects/footstep/carpetbarefoot2.ogg
  sound/effects/footstep/carpetbarefoot3.ogg
  sound/effects/footstep/carpetbarefoot4.ogg
  sound/effects/footstep/carpetbarefoot5.ogg
  sound/effects/footstep/crawl1.ogg
  sound/effects/footstep/hardbarefoot1.ogg
  sound/effects/footstep/hardbarefoot2.ogg
  sound/effects/footstep/hardbarefoot3.ogg
  sound/effects/footstep/hardbarefoot4.ogg
  sound/effects/footstep/hardbarefoot5.ogg
  sound/effects/footstep/hardclaw1.ogg
  sound/effects/footstep/hardclaw2.ogg
  sound/effects/footstep/hardclaw3.ogg
  sound/effects/footstep/hardclaw4.ogg
  sound/effects/footstep/heavy1.ogg
  sound/effects/footstep/heavy2.ogg
  sound/effects/footstep/slime1.ogg
  sound/effects/footstep/woodbarefoot1.ogg
  sound/effects/footstep/woodbarefoot2.ogg
  sound/effects/footstep/woodbarefoot3.ogg
  sound/effects/footstep/woodbarefoot4.ogg
  sound/effects/footstep/woodbarefoot5.ogg
  sound/effects/footstep/woodclaw1.ogg
  sound/effects/footstep/woodclaw2.ogg
  sound/effects/footstep/woodclaw3.ogg
Labels: Sound

#8296 Nerfs Synda NPC block Rng to 25%
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
Labels: Balance/Rebalance

#8417 Gives space queen's men void jet packs + tweeks
  code/game/objects/items/tanks/jetpack.dm
  code/modules/events/pirates.dm
Labels: Feature, Tweak

#8325 [Ready] Cleaner looking autolathen organization
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_construction.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_electronics.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_medical_and_dinnerware.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tools.dm
  modular_citadel/code/modules/research/designs/autolathe_designs.dm
  tgstation.dme
Labels: Code Improvement, Needs Review

#8419 Rewords Blood Cult 'offer' rune click here prompt.
  code/modules/antagonists/cult/runes.dm
Labels: Tweak

#8435 lazyinitlist on IAA targets stealing.
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
Labels: Fix

#8450 Reduces FRAME cart by 2tc
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#8460 ultra clown fireing pins
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#8448 Makes laser scatter shot cost 4 not 5
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#8454 Adv Syndicate Surgery Duffel Bag tweaks
  code/modules/uplink/uplink_items.dm
Labels: Fix, Tweak

#8455 Binary Translator Key costs 2 from 5
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#8456 suppressors now only cost 1 tc
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#8437 [Ready] Adds more box crafting and white gloves to cloth
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  icons/obj/storage.dmi
Labels: Feature, Fix, Needs Review, Sprites

#8427 Removes color-whitelist blocking custom-colored circuit blueprints from being imported
  code/modules/integrated_electronics/core/saved_circuits.dm
Labels: Removal

#8423 Engineering Showers! (Fixed 4 REALZIES this time)
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#8404 Flavor text with special characters don't get partially unescaped
  code/__HELPERS/text.dm
  code/modules/client/preferences.dm
  code/modules/mob/say_vr.dm
Labels: Fix

#8465 [FIX] Magpistol magazines no longer invisible.
  modular_citadel/icons/obj/guns/cit_guns.dmi
Labels: Fix

#8443 Item stripping no longer gets interrupted by changes in your actively held item
  code/__HELPERS/mobs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Tweak

#8439 stunbaton status rework.
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/teleprod.dm
Labels: Balance/Rebalance

#8408 Fixing cult rounds potentially stalling if the sac target is erased from this realm.
  code/modules/antagonists/cult/cult.dm
  modular_citadel/code/game/machinery/cryopod.dm
Labels: Fix

#8295 [Ready] Nerfs(Not really) Engi printing and organized many designs
  code/modules/research/designs/comp_board_designs.dm
  code/modules/research/designs/comp_board_designs/comp_board_designs_all_misc.dm
  code/modules/research/designs/comp_board_designs/comp_board_designs_cargo .dm
  code/modules/research/designs/comp_board_designs/comp_board_designs_engi.dm
  code/modules/research/designs/comp_board_designs/comp_board_designs_medical.dm
  code/modules/research/designs/comp_board_designs/comp_board_designs_sci.dm
  code/modules/research/designs/comp_board_designs/comp_board_designs_sec.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/designs/machine_desings/machine_designs_all_misc.dm
  code/modules/research/designs/machine_desings/machine_designs_cargo.dm
  code/modules/research/designs/machine_desings/machine_designs_engi.dm
  code/modules/research/designs/machine_desings/machine_designs_medical.dm
  code/modules/research/designs/machine_desings/machine_designs_sci.dm
  code/modules/research/designs/machine_desings/machine_designs_service.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/designs/smelting_designs.dm
  tgstation.dme
Labels: Code Improvement, Needs Review, Removal
