Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-06, with the labels that each got.

#8488 [Ready] High alarm ERT suits
  code/datums/ert.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/icons/mob/muzzled_helmet.dmi
  modular_citadel/icons/mob/suit_digi.dmi
  modular_citadel/icons/mob/taur_naga.dmi
Labels: Feature, Needs Review, Sprites, Tweak

#8470 Undunks pepper spray & teargas.
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Balance/Rebalance

#8436 Allows bio genes to make synth meat
  code/modules/research/designs/biogenerator_designs.dm
Labels: Feature, PRB: Reset

#8466 Fixes atmos and station alert consoles not updating visually
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/computer/station_alert.dm
Labels: Fix

#8459 Syndicate Sentience Potion costing 2 from 4
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#8452 Makes mulligan cost only 3
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#8453 Tuberculosis 12tc - > 8tc
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#8449 Makes PDA bomb cart cost 5 not 6
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#8485 More plushies - Reece Trilby Bhijn Box Justin
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Feature, Sprites, Tweak

#8477 Ports the zulie cloak and blackredgold coat donor items from RP
  code/modules/clothing/suits/toggles.dm
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Feature, Sprites

#8482 fixes pacifism eyestabbing, better this time.
  code/game/objects/items.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/tools/screwdriver.dm
Labels: Fix

#8463 Makeshift Metal shield crafting
  code/game/objects/items/shields.dm
  code/modules/crafting/recipes.dm
  icons/obj/items_and_weapons.dmi
Labels: Feature, Sprites

#8434 I'm tired of my pulls on horizontal spacemen breaking off because of crawling delays.
  code/modules/mob/living/living.dm
Labels: Fix

#8473 [MERGE READY] Taeclowndo. Because Clowns deserve to have their own martial art too.
  code/modules/clothing/shoes/taeclowndo.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/taeclowndo.dm
  code/modules/uplink/uplink_items.dm
  tgstation.dme
Labels: Feature

#8515 Fixes stunbatons' icons not properly updating on cell fiddling, plus cell maxcharge leniency.
  code/game/objects/items/stunbaton.dm
Labels: Fix, Tweak

#8524 Adds a trait that makes you immune to ass slapping: BUNS OF STEEL.
  code/__DEFINES/traits.dm
  code/datums/traits/neutral.dm
  code/modules/mob/living/carbon/human/species.dm
  tgstation.dme
Labels: Feature

#8518 Fixes and updates pod's emergency suits storage.
  code/__DEFINES/components.dm
  code/datums/components/storage/concrete/_concrete.dm
  code/datums/components/storage/concrete/emergency.dm
  code/datums/components/storage/storage.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/obj_defense.dm
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/on_move.dm
  tgstation.dme
Labels: Fix, Tweak

#8517 Adds visible balls and multi-breasts
  code/__DEFINES/citadel_defines.dm
  code/__HELPERS/_cit_helpers.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/eggsack.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
  modular_citadel/code/modules/arousal/organs/genitals_sprite_accessories.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/arousal/organs/testicles.dm
  modular_citadel/code/modules/arousal/organs/vagina.dm
  modular_citadel/code/modules/arousal/organs/womb.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_citadel/icons/obj/genitals/breasts.dmi
  modular_citadel/icons/obj/genitals/breasts_onmob.dmi
  modular_citadel/icons/obj/genitals/penis.dmi
  modular_citadel/icons/obj/genitals/testicles.dmi
  modular_citadel/icons/obj/genitals/testicles_onmob.dmi
  modular_citadel/icons/obj/genitals/vagina.dmi
  modular_citadel/icons/obj/genitals/vagina_onmob.dmi
Labels: Feature, Fix

#8506 Ports RP's deer taur and adds Elven ears to mammals
  code/modules/clothing/suits/_suits.dm
  modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
  modular_citadel/icons/mob/mam_taur.dmi
Labels: Feature

#8504 buffs resonator
  code/modules/mining/equipment/resonator.dm
Labels: Fix

#8489 Makes combat gloves look T A C T I C O O L
  code/modules/clothing/gloves/miscellaneous.dm
  icons/obj/clothing/gloves.dmi
Labels: Feature, Sprites

#8491 zero, , null, and empty text strings, all fulfill the ! operator.
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Fix, Grammar and Formatting

#8516 Makes clockwork wall - sonic jackhammer interaction account the wall's superheating.
  code/game/turfs/simulated/wall/misc_walls.dm
Labels: Balance/Rebalance

#8387 Ports gang mode
  code/__DEFINES/antagonists.dm
  code/__DEFINES/role_preferences.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/implants/implant_mindshield.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/effects/crayondecal.dmi
  icons/mob/hud.dmi
  icons/obj/device.dmi
  modular_citadel/code/game/gamemodes/gangs/dominator.dm
  modular_citadel/code/game/gamemodes/gangs/dominator_countdown.dm
  modular_citadel/code/game/gamemodes/gangs/gang.dm
  modular_citadel/code/game/gamemodes/gangs/gang_datums.dm
  modular_citadel/code/game/gamemodes/gangs/gang_decals.dm
  modular_citadel/code/game/gamemodes/gangs/gang_hud.dm
  modular_citadel/code/game/gamemodes/gangs/gang_items.dm
  modular_citadel/code/game/gamemodes/gangs/gang_pen.dm
  modular_citadel/code/game/gamemodes/gangs/gangs.dm
  modular_citadel/code/game/gamemodes/gangs/gangtool.dm
  modular_citadel/code/game/gamemodes/gangs/implant_gang.dm
  tgstation.dme
Labels: Feature, Sprites

#8472 Boxstation Crew Monitor
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#8528 Fixes prosthetic invisible hands, improves female markings
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  modular_citadel/icons/mob/mam_markings.dmi
Labels: Fix

#8424 Ctrl Alt Click on pipes, port from TG
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
Labels: Feature

#8430 Adds improvised 7.62 rifle
  code/modules/crafting/recipes.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Feature

#8525 Makes cookies loved by all
  code/modules/food_and_drinks/food/snacks_pastry.dm
Labels: Fix

#8534 Pink Panties
  code/modules/mob/dead/new_player/sprite_accessories/underwear.dm
  icons/mob/underwear.dmi
Labels: Feature, Sprites

#8236 [EXPERIMENTAL] Unomos - Listmos except gas mixtures only use one single list for gasses instead of 2 per gas + 1
  code/__DEFINES/atmospherics.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/helper_datums/teleport.dm
  code/game/gamemodes/objective_items.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/mecha/equipment/tools/other_tools.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/effects/spawners/bombspawner.dm
  code/game/objects/items/chrono_eraser.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/tanks/jetpack.dm
  code/game/objects/items/tanks/tank_types.dm
  code/game/objects/structures/transit_tubes/station.dm
  code/game/objects/structures/transit_tubes/transit_tube_pod.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/open.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/assembly/bomb.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/gas_types.dm
  code/modules/atmospherics/gasmixtures/immutable_mixtures.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/atmospherics/machinery/components/unary_devices/tank.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/atmospherics/machinery/other/miner.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/cargo/bounties/engineering.dm
  code/modules/events/spacevine.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/integrated_electronics/subtypes/atmospherics.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/mob/mob.dm
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/power/singularity/collector.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/research/xenobiology/crossbreeding/chilling.dm
  code/modules/surgery/organs/lungs.dm
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
Labels: Refactor, Work In Progress

#8546 Crew Plushies! Redtail, Annie, Paxton, Mason.
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Sprites

#8391 Gives pod lava land ruin a autolathen
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
  code/modules/ruins/lavaland_ruin_code.dm
Labels: Map Edit, Tweak

#8403 Updating the .github folder guidelines.
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Github

#8442 Makes soviet clothing no longer need to be hacked AND emaged
  code/modules/cargo/packs.dm
Labels: Fix

#8432 Buffs stunprods to not have a cooldown
  code/game/objects/items/stunbaton.dm
  code/modules/assembly/assembly.dm
Labels: Balance/Rebalance

#8444 CWC player requirement increase
  code/game/gamemodes/clock_cult/clock_cult.dm
Labels: Balance/Rebalance

#8476 Tweaks/Buffs hierophant
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
Labels: Tweak

#8483 Ports in combat gloves plus.
  code/datums/martial/krav_maga.dm
  code/game/gamemodes/clown_ops/clown_ops.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#8414 New M.A.S.O.N rig
  code/modules/cargo/packs.dm
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Feature

#8493 Fixes THAT Oldstation Tile
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
Labels: Map Edit

#8500 Buffs stun slugs
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance/Rebalance

#8501 Colored boxes, more box icons, and more craftable box types!
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  icons/obj/storage.dmi
Labels: Feature, Sprites

#8503 Changing up the drills/picks/jackhammer a bit
  code/modules/mining/equipment/mining_tools.dm
Labels: Balance/Rebalance, Tweak

#8569 Fox Ears layer tweak
  modular_citadel/icons/mob/mam_ears.dmi
Labels: Tweak

#8543 Makes SNOWCONES!
  code/__DEFINES/construction.dm
  code/modules/crafting/craft.dm
  code/modules/food_and_drinks/food/snacks_frozen.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  icons/obj/food/snowcones.dmi
  tgstation.dme
Labels: Feature, Sprites

#8540 Rebalanced Ass Slapping
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance

#8541 Adds implanter and implanter cases to syndie surgery bags
  code/game/objects/items/storage/backpack.dm
Labels: Feature

#8544 Makes ice cream vats and food carts buy-able via cargo
  code/modules/cargo/packs.dm
Labels: Feature

#8548 Schoolgirl outfits for the loadout menu
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature

#8549 Fixes a unseen paper work exsplote
  code/modules/cargo/exports/manifest.dm
  code/modules/cargo/order.dm
  code/modules/cargo/packs.dm
  code/modules/crafting/recipes.dm
Labels: Fix, Tweak

#8551 Port paradise goonchat uridecode fix
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: Fix

#8552 Ports "Fixes goonchat cookies not saving properly."
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: Fix

#8553 Clarifies a few things about subtler and how it should be used
  code/modules/mob/say_vr.dm
  modular_citadel/code/modules/vore/eating/vorepanel_vr.dm
Labels: Tweak

#8554 Adds AI core screen selection to character preferences and turns icon selection menu into a radial.
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/silicon.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  icons/mob/AI.dmi
Labels: Fix, Grammar and Formatting, Sprites, Tweak

#8555 Updates radials, makes RCD and RCL use em.
  code/_onclick/hud/radial.dm
  code/_onclick/hud/radial_persistent.dm
  code/datums/action.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/RCL.dm
  code/game/turfs/turf.dm
  code/modules/power/cable.dm
  icons/mob/actions/actions_items.dmi
  icons/mob/radial.dmi
  tgstation.dme
Labels: Code Improvement, Feature, Sprites

#8557 Ports the fix for that stupid z-level edge pull breaking bug.
  code/game/atoms_movable.dm
  code/game/turfs/space/space.dm
Labels: Fix

#8558 Ports in the container_type to reagents flags refactor.
  code/__DEFINES/flags.dm
  code/__DEFINES/reagents.dm
  code/_globalvars/bitfields.dm
  code/game/atoms.dm
  code/game/machinery/limbgrower.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/implants/implant_chem.dm
  code/game/objects/items/tanks/watertank.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/mop_bucket.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/food_cart.dm
  code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/hydroponics/fermenting_barrel.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/integrated_electronics/passive/power.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
  code/modules/paperwork/pen.dm
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/guns/misc/chem_gun.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/readme.md
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/medspray.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/machinery/circuit_imprinter.dm
  code/modules/research/machinery/departmental_circuit_imprinter.dm
  code/modules/research/machinery/departmental_protolathe.dm
  code/modules/research/machinery/departmental_techfab.dm
  code/modules/research/machinery/protolathe.dm
  code/modules/research/machinery/techfab.dm
  code/modules/research/xenobiology/crossbreeding/__corecross.dm
  code/modules/research/xenobiology/crossbreeding/burning.dm
  code/modules/research/xenobiology/crossbreeding/charged.dm
  code/modules/research/xenobiology/crossbreeding/chilling.dm
  code/modules/research/xenobiology/crossbreeding/industrial.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Refactor

#8559 Ports in the get_area conversion to define.
  code/__DEFINES/misc.dm
  code/__HELPERS/game.dm
  code/game/objects/items/blueprints.dm
Labels: Code Improvement

#8560 Ports in the fix against hitting oneself with one's own thrown items.
  code/controllers/subsystem/throwing.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/mob/mob_movement.dm
Labels: Fix

#8556 Gives Ninjas back their Weeb speech modification
  code/modules/ninja/suit/mask.dm
Labels: Feature

#8563 Pride-struck Hammer in hands/on back
  code/game/objects/items/holy_weapons.dm
  icons/mob/back.dmi
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
Labels: Sprites

#8566 Different combat mode message if user is on help intent.
  modular_citadel/code/modules/mob/living/carbon/carbon.dm
Labels: Tweak

#8567 You can now use an RPD on windows and Grilles.
  code/game/objects/items/RPD.dm
Labels: Feature

#8590 Fixes master - yeah im hitting the merge on this fuck it
  code/modules/mob/living/carbon/human/examine.dm
Labels: Priority: CRITICAL

#8592 Fixes master pt 2
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Priority: CRITICAL

#8562 Fritz plushie and donor item
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Donor Fluff, Feature, Sprites

#8610 Changes assistant family heirloom to a pair of fingerless insulated gloves
  code/datums/traits/negative.dm
  code/game/objects/items/storage/briefcase.dm
  code/modules/clothing/gloves/color.dm
  icons/mob/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Sprites

#8599 Pacifists can nom things now, but not feed to others
  code/modules/mob/living/living_defense.dm
  modular_citadel/code/modules/vore/eating/bellymodes_vr.dm
Labels: Feature

#8641 port "PR to make travis use xenial and to make it work"
  .travis.yml
  tools/ss13_genchangelog.py
  tools/travis/build_dependencies.sh
  tools/travis/install_build_tools.sh
Labels: Tools

#8624 [READY] Fixes High Alert ERT suits
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Fix, Needs Review, Sprites

#8633 Examine text for pumps and typo fixes.
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
Labels: Feature

#8634 fixes low-charge stunbatons & co.
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/teleprod.dm
  code/modules/power/cell.dm
Labels: Fix

#8611 Digitigrade socks
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/underwear.dmi
Labels: Feature, Sprites

#8625 Blue Kimono for SFox63 - Donator
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff, Sprites

#8612 Makes a small adjustment to the ash walker camp.
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  code/modules/research/research_disk.dm
  code/modules/research/techweb/_techweb.dm
Labels: Map Edit

#8639 Ninja tweaks and improvements. Take two.
  code/game/gamemodes/objective.dm
  code/modules/ninja/suit/gloves.dm
  code/modules/ninja/suit/n_suit_verbs/energy_net_nets.dm
  code/modules/ninja/suit/n_suit_verbs/ninja_net.dm
  code/modules/ninja/suit/ninjaDrainAct.dm
Labels: Balance/Rebalance, Tweak

#8645 stops borgs from sprinting into negative cell charge.
  modular_citadel/code/modules/mob/living/silicon/robot/robot_movement.dm
Labels: Fix

#8598 Fixes Gulag point rewards upon inserting sheets
  code/modules/mining/laborcamp/laborstacker.dm
Labels: Fix

#8623 RD can now suplex a immovable rod.
  code/game/objects/structures/flora.dm
  code/modules/events/immovable_rod.dm
  code/modules/spells/spell_types/rod_form.dm
  icons/obj/flora/pinetrees.dmi
Labels: Feature, Sprites

#8640 Makes baklava pie
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  icons/obj/food/piecake.dmi
Labels: Feature, Sprites

#8605 Adds medical breifcases
  code/game/objects/items/storage/briefcase.dm
  code/modules/vending/medical.dm
  modular_citadel/code/modules/client/loadout/_medical.dm
Labels: Feature

#8479 Krav maga leg sweep tweak.
  code/datums/martial/krav_maga.dm
Labels: Balance/Rebalance

#8591 You smell that? Napalm, son.
  code/datums/mutations/speech.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  strings/canadian_replacement.json
Labels: Feature

#8618 Corrects ammo boxes spawning, as well as buffs cargo shotgun crates
  code/game/objects/items/storage/boxes.dm
  code/modules/cargo/packs.dm
Labels: Feature, Fix, Grammar and Formatting

#8627 Adds more space ruins.
  _maps/RandomRuins/SpaceRuins/arcade.dmm
  _maps/RandomRuins/SpaceRuins/augmentationfacility.dmm
  _maps/RandomRuins/SpaceRuins/bigape.dmm
  code/datums/ruins/space.dm
  config/spaceRuinBlacklist.txt
Labels: Config Update, Map Edit

#8614 Portin "Fix chem dispensers starting with an extra power cell"
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Fix

#8579 Gives gangs a new shield and makes their boots cheaper
  code/game/objects/items/shields.dm
  modular_citadel/code/game/gamemodes/gangs/gang_items.dm
Labels: Feature, Tweak

#8416 Gives sec EVA suits storge some Sec Jetpacks
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/tanks/jetpack.dm
Labels: Feature

#8643 Fixes the sacrificial target icon not displaying on the cult objective alert.
  code/modules/antagonists/cult/cult.dm
Labels: Fix

#8652 Ports "areas_in_z after start population fix"
  code/__HELPERS/areas.dm
  code/controllers/subsystem/mapping.dm
  code/game/area/areas.dm
  code/modules/mapping/map_template.dm
Labels: Fix

#8578 Clears up Extinguisher's slippery instructions.
  code/game/objects/items/extinguisher.dm
Labels: Grammar and Formatting

#8570 Ports origami skills for paper wiz loot
  _maps/RandomRuins/SpaceRuins/originalcontent.dmm
  code/game/objects/items/granters.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/paperwork/paperplane.dm
  icons/mob/actions.dmi
  icons/obj/library.dmi
Labels: Feature, Map Edit, Sprites

#8561 Ports in emoji.dmi updates, plus flushed emoji.
  icons/emoji.dmi
Labels: Feature, Sprites

#8497 Adds Clockwork Reflectors
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/antagonists/clockcult/clock_structures/reflector.dm
  icons/obj/clockwork_objects.dmi
  tgstation.dme
Labels: Feature, Sprites, Tweak

#8505 Clockwork Cult walls can no longer be deconstructed by RCDs when heated.
  code/game/turfs/simulated/wall/misc_walls.dm
Labels: Balance/Rebalance

#8584 Organ Storage box
  code/game/objects/items/storage/firstaid.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#8648 Buffs uplink kits
  code/game/objects/items/storage/uplink_kits.dm
Labels: Balance/Rebalance

#8653 Donator Comm Jacket - [Ready]
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff, Needs Review, Sprites

#8507 Adds Hoverchairs and the paraplegic trait.
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/datums/brain_damage/severe.dm
  code/datums/traits/negative.dm
  code/modules/crafting/recipes.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/ridden.dm
  code/modules/vehicles/wheelchair.dm
  icons/obj/vehicles.dmi
  tgstation.dme
Labels: Sprites

#8650 Ports "Removes firebug from goonchat"
  code/modules/goonchat/browserassets/js/browserOutput.js
  goon/browserassets/css/browserOutput.css
  goon/browserassets/css/font-awesome.css
  goon/browserassets/html/browserOutput.html
  goon/browserassets/js/browserOutput.js
  goon/browserassets/js/json2.min.js
  goon/code/datums/browserOutput.dm
Labels: Removal

#8658 Moving some tablecrafting recipes to the appropriate categories
  code/__DEFINES/construction.dm
  code/modules/crafting/craft.dm
  code/modules/crafting/recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sushi.dm
Labels: Tweak

#8602 Underwear overlays Gentials, can toggle each seperately
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
  modular_citadel/icons/obj/genitals/breasts_onmob.dmi
  modular_citadel/icons/obj/genitals/penis_onmob.dmi
  modular_citadel/icons/obj/genitals/testicles_onmob.dmi
  modular_citadel/icons/obj/genitals/vagina_onmob.dmi
Labels: Feature, Tweak

#8702 Fixes jacket dir
  icons/mob/custom_w.dmi
Labels: Donor Fluff, Sprites

#8690 Fixes empathy antag check exploit.
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix

#8674 fixes plant disk design and hacked autolathen
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
  code/modules/ruins/lavaland_ruin_code.dm
Labels: Fix, Map Edit

#8675 Removes Kaira's dark sabre from arcades
  code/game/machinery/computer/arcade.dm
Labels: Fix, Removal

#8671 Ports "Disembowelment now only works if you are dead/in critical"
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Balance/Rebalance

#8669 Ports "Reorganizes the uplink, adds grenades and explosives category."
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/briefcase.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/uplink/uplink_items.dm
  modular_citadel/code/datums/uplink_items_cit.dm
  modular_citadel/code/modules/uplink/uplink_items.dm
  tgstation.dme
Labels: Tweak

#8733 ports in "Adds radial menu to arm-mounted implants"
  code/modules/surgery/organs/augments_arms.dm
Labels: Feature

#8732 Ports in "makes the abductor console use radials"
  code/modules/antagonists/abductor/machinery/console.dm
Labels: Feature

#8718 allows quick maxing of suit sensors
  code/modules/clothing/clothing.dm
Labels: Feature

#8716 Replaces medical protolathe with medical techfab on Pubbystation.
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#8665 Buffs out certain stun spells.
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/spells/spell_types/inflict_handler.dm
  code/modules/spells/spell_types/wizard.dm
Labels: Balance/Rebalance

#8677 buffs speedy step quirk by a half
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak

#8571 Medical smartdarts.
  code/game/objects/items/storage/belt.dm
  code/modules/crafting/recipes.dm
  code/modules/projectiles/ammunition/special/syringe.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/vending/medical.dm
  code/modules/vending/medical_wall.dm
  icons/obj/clothing/belts.dmi
  icons/obj/dart.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/projectiles.dmi
  icons/obj/syringe.dmi
Labels: Sprites

#8698 Fixes "Penlights Cannot Give Eye Exams"
  code/game/objects/items/devices/flashlight.dm
  modular_citadel/code/game/objects/items/devices/flashlight.dm
  tgstation.dme
Labels: Fix

#8691 Ports in beekini and bee socks.
  code/modules/mob/dead/new_player/sprite_accessories/socks.dm
  code/modules/mob/dead/new_player/sprite_accessories/undershirt.dm
  code/modules/mob/dead/new_player/sprite_accessories/underwear.dm
  icons/mob/underwear.dmi
Labels: Feature, Sprites

#8688 Ports in bee plushes.
  code/datums/traits/negative.dm
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Feature, Fix, Sprites

#8689 Add Red Panda simplemobs.
  code/modules/mob/living/simple_animal/friendly/panda.dm
  icons/mob/pets.dmi
  tgstation.dme
Labels: Feature, Sprites

#8687 Ports "Fixes advanced proc calls not working + various code cleaning"
  code/modules/admin/verbs/debug.dm
Labels: Fix

#8664 Adds another space ruin
  _maps/RandomRuins/SpaceRuins/spacehermit.dmm
  code/datums/ruins/space.dm
  config/spaceRuinBlacklist.txt
Labels: Config Update, Map Edit

#8659 ports "Componentizes orbiting"
  code/__DEFINES/components.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/matrices.dm
  code/controllers/subsystem/augury.dm
  code/controllers/subsystem/orbit.dm
  code/datums/components/orbiter.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/dance_machine.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
  code/modules/orbit/orbit.dm
  code/modules/power/tesla/energy_ball.dm
  tgstation.dme
Labels: Fix

#8711 Greytide Stationwide!
  modular_citadel/code/modules/client/loadout/_service.dm
Labels: Feature

#8722 Makes tower shield be see able
  code/game/objects/items/shields.dm
Labels: Fix

#8695 Porting smartfridge improvements.
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  icons/obj/vending.dmi
Labels: Fix, Sprites, Tweak

#8721 Ports in "Liver removal/failure now also stops passive reagent effects"
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/blob_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#8666 Fixes roffle waffle, mushroom hallucinogen and some invalid reagents.
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#8667 Ports the system for randomized semi-persistent chem reactions.
  _maps/RandomRuins/SpaceRuins/originalcontent.dmm
  code/__DEFINES/food.dm
  code/__HELPERS/reagents.dm
  code/__HELPERS/time.dm
  code/controllers/subsystem/persistence.dm
  code/datums/mood_events/drink_events.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/recipes/special.dm
  code/modules/unit_tests/reagent_recipe_collisions.dm
  tgstation.dme
Labels: Feature, Fix, Map Edit

#8692 [s] Ports "Fixes PDA TK exploits" and "Fixes pride mirror exploit"
  code/__DEFINES/misc.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/structures/mirror.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/modular_computers/computers/item/processor.dm
Labels: Fix

#8715 Pentetic Jelly, the chem we all needed. Anatomic panacea not deadly for slimes! Also, medbeam buff?
  code/modules/antagonists/changeling/powers/panacea.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Feature, Tweak

#8699 fixes CMO cloak offset and normalize cloak size for the other heads
  icons/mob/neck.dmi
Labels: Sprites

#8736 Removes Nudity Permits and replaces them with invisible gear harnesses
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Sprites, Tweak

#8747 [Donner] Luna's Gauntlets for BigManClancy
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Feature, Sprites

#8767 Fixes "Bubbles ate my Cohiba Robusto!"
  code/modules/mob/living/carbon/monkey/combat.dm
Labels: Fix

#8766 Fixing "You can Alt click paper with TK to teleport it to you."
  code/modules/paperwork/paperplane.dm
Labels: Fix

#8764 Allows shoulder holster to hold cap gun and mini-eguns
  code/game/objects/items/storage/belt.dm
Labels: Tweak

#8762 New sprites for two of the most codersprite guns in the game.
  modular_citadel/icons/obj/guns/cit_guns.dmi
Labels: Sprites

#8756 Outfits the Boxstation HoS office with blast doors and r-walls.
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Balance/Rebalance, Map Edit

#8755 Fixes errant ball behaviour
  code/__HELPERS/mobs.dm
  code/modules/client/preferences.dm
  modular_citadel/code/modules/arousal/organs/testicles.dm
Labels: Fix, Tweak

#8745 Port of tg pull #44158, the fix of Cards Against Space!
  code/game/objects/items/toys.dm
  code/modules/games/cas.dm
  strings/cas_black.txt
  strings/cas_white.txt
Labels: Feature, Fix

#8753 [PORT] Non-station AI can no longer interact off their z-level.
  code/_onclick/ai.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Balance/Rebalance

#8744 fix atmos helmet
  modular_citadel/icons/mob/muzzled_helmet.dmi
Labels: Fix

#8741 ports "Stockings"
  code/modules/mob/dead/new_player/sprite_accessories/socks.dm
  icons/mob/underwear.dmi
Labels: Sprites

#8727 Porting in the "Mediborg's Amputation Adventure" and Minesweeper arcades.
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/arcade/battle.dm
  code/game/machinery/computer/arcade/minesweeper.dm
  code/game/machinery/computer/arcade/misc_arcade.dm
  code/game/machinery/computer/arcade/orion_trail.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/cargo/packs.dm
  code/modules/client/asset_cache.dm
  code/modules/research/designs/comp_board_designs/comp_board_designs_all_misc.dm
  icons/misc/minesweeper_tiles/eight.png
  icons/misc/minesweeper_tiles/empty.png
  icons/misc/minesweeper_tiles/five.png
  icons/misc/minesweeper_tiles/flag.png
  icons/misc/minesweeper_tiles/four.png
  icons/misc/minesweeper_tiles/hidden.png
  icons/misc/minesweeper_tiles/mine.png
  icons/misc/minesweeper_tiles/minehit.png
  icons/misc/minesweeper_tiles/one.png
  icons/misc/minesweeper_tiles/seven.png
  icons/misc/minesweeper_tiles/six.png
  icons/misc/minesweeper_tiles/three.png
  icons/misc/minesweeper_tiles/two.png
  modular_citadel/code/modules/research/techweb/all_nodes.dm
  sound/arcade/minesweeper_boardpress.ogg
  sound/arcade/minesweeper_emag1.ogg
  sound/arcade/minesweeper_emag2.ogg
  sound/arcade/minesweeper_explosion1.ogg
  sound/arcade/minesweeper_explosion2.ogg
  sound/arcade/minesweeper_explosion3.ogg
  sound/arcade/minesweeper_menuselect.ogg
  sound/arcade/minesweeper_startup.ogg
  sound/arcade/minesweeper_win.ogg
  sound/arcade/minesweeper_winfail.ogg
  tgstation.dme
Labels: Feature, Sound, Sprites

#8738 porting pizza fixes.
  code/modules/food_and_drinks/pizzabox.dm
Labels: Fix

#8760 Makes ling's adrendals have a loudness 2
  code/modules/antagonists/changeling/powers/adrenaline.dm
Labels: Balance/Rebalance

#8726 Tweaks to chaplain bible heals. Time to pull out the old brainbuster.
  code/game/objects/items/storage/book.dm
Labels: Balance/Rebalance

#8708 Corrects the "Durasteel" to be plastitanium tool boxes
  code/game/objects/items/storage/toolbox.dm
  code/modules/uplink/uplink_items.dm
Labels: Grammar and Formatting

#8731 Ports in microwave updates and its radial menu.
  code/datums/wires/microwave.dm
  code/game/machinery/_machinery.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  tgstation.dme
Labels: Feature
