Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-12, with the labels that each got.

#9893 [DYNAMIC] Roundend threat log only shows changes that fully happened
  code/__HELPERS/roundend.dm
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Fix

#9895 [READY] Organ quality of life fixes. Adds Organ fridges with items, Tweaks scanner, new surgery, tweaks chems
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/_globalvars/lists/typecache.dm
  code/game/data_huds.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/reagent_containers/medspray.dm
  code/modules/surgery/advanced/revival.dm
  code/modules/surgery/emergency_cardioversion_recovery.dm
  code/modules/surgery/graft_synthtissue.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/organ_internal.dm
  icons/mob/hud.dmi
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
  tgstation.dme
Labels: Feature, Map Edit, Needs Review, Sprites, Tweak

#9977 [FIX] Another patch for the recently added tg plants.
  code/modules/hydroponics/grown/citrus.dm
Labels: Feature, Fix

#10005 Adds plaid skirt, pens, stripper outfits,athletic shorts to loadout. also keyhole sweater
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/code/modules/client/loadout/mask.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature

#9981 Rags are no longer transparent reagent containers. Also allows squeezing their reagents into another container.
  code/modules/reagents/reagent_containers/rags.dm
Labels: Tweak

#9972 Fixed double whitespace gap in human, ai and carbon examine.
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/silicon/ai/examine.dm
Labels: Fix

#10017 Makes filters volume-based
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  tgui/assets/tgui.js
  tgui/src/interfaces/atmos_filter.ract
Labels: Balance/Rebalance, UI

#10016 Mousedrop fixes - Adds return value to item mousedrop and fixes bugs with the few things that override it
  code/game/objects/items.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/pet_carrier.dm
  code/game/objects/items/toys.dm
  code/modules/clothing/clothing.dm
  code/modules/paperwork/paper_cutter.dm
  code/modules/paperwork/paperbin.dm
  modular_citadel/code/modules/reagents/objects/clothes.dm
Labels: Code Improvement, Fix

#9980 Ports "Removes phantom gas effects on space tiles"
  code/game/turfs/space/space.dm
Labels: Fix, Removal

#10010 Fixes implant pads and updates them a little (WHY THE HELL DO WE STILL HAVE THIS OLDCODE CRAP LINGERING AROUND?)
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implantpad.dm
Labels: Fix, Tweak

#9989 Ports the energy gun empty state overlay fix.
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#9976 Ports "Fixes transit tube barricade spam"
  code/game/objects/structures/transit_tubes/transit_tube_construction.dm
Labels: Fix

#9946 Removes hyperspeed from light pink stabilized for -4.5 stam/tick + free sprint
  code/__DEFINES/traits.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  modular_citadel/code/modules/mob/living/carbon/human/human_movement.dm
Labels: Balance/Rebalance, Removal

#9915 Janitor QoL, Vendor Updates, and some tweaks.
  code/game/objects/items/storage/belt.dm
  code/modules/cargo/bounties/assistant.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/drinnerware.dm
  code/modules/vending/snack.dm
  code/modules/vending/wardrobes.dm
  modular_citadel/code/game/machinery/vending.dm
  modular_citadel/code/modules/client/loadout/backpack.dm
Labels: Balance/Rebalance, Feature, Tweak

#10031 Fixes holodeck sleepers leaving sleeper buffers behind when deleted.
  code/game/machinery/Sleeper.dm
Labels: Fix

#10004 Unmodularizing first aid kits.
  code/game/objects/items/storage/firstaid.dm
  icons/obj/storage.dmi
  modular_citadel/code/game/objects/items/storage/firstaid.dm
  modular_citadel/icons/firstaid.dmi
  tgstation.dme
Labels: Sprites

#9988 Fixes ED-209 being unbuildable past the welding step.
  code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
Labels: Fix

#9992 Fixes ai displays status being reset to "Neutral" on login, regardless of choice.
  code/modules/jobs/job_types/ai.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/login.dm
Labels: Fix

#9941 Personal closets can use PDAs/tablets now
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
Labels: Fix

#10039 makes traitor antag datum and descendents removable by admins
  code/modules/antagonists/traitor/datum_traitor.dm
Labels: Fix

#10021 Makes glowsticks no longer radioactively contaminable.
  code/game/objects/items/devices/flashlight.dm
Labels: Salt, Tweak

#9913 Gives the hotel staff some fine silk threads, and adds a new hat
  code/datums/dog_fashion.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#9372 [Ready] [Test Merge] Ports Xenobio Hotkeys
  code/__DEFINES/components.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  icons/mob/actions/actions_silicon.dmi
Labels: Feature, Needs Review, Sprites, Tweak

#9884 Black powder fix. Alternative to #9861
  code/modules/hydroponics/grown/misc.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Labels: Fix, Test Merge Candidate, Tweak

#10025 refactor butchering component
  code/__DEFINES/components.dm
  code/_onclick/item_attack.dm
  code/datums/components/butchering.dm
  code/game/machinery/recycler.dm
  code/game/mecha/equipment/tools/mining_tools.dm
  code/game/objects/items.dm
  code/game/objects/items/melee/transforming.dm
  code/modules/paperwork/pen.dm
Labels: Code Improvement, Refactor

#10033 Fixes traitor codewords highlight and some other hear signal hooks.
  code/datums/brain_damage/hypnosis.dm
  code/datums/brain_damage/mild.dm
  code/datums/brain_damage/phobia.dm
  code/datums/brain_damage/split_personality.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/mob/living/say.dm
Labels: Fix

#10042 fixes sofa overlays doing nothing, because their layer wasn't properly set.
  code/game/objects/structures/beds_chairs/chair.dm
Labels: Fix

#10019 Adds CentCom, Assistant's formal, ratvarian and narsian winter coats + loadout for formal
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/suit_digi.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/code/modules/client/loadout/suit.dm
Labels: Feature, Sprites

#9575 Box Beautification & Bar Rework & Issue 9706 Fix
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#9805 Uplink items are now automatically sorted alphabetically.
  code/__HELPERS/cmp.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/objects.dm
  code/modules/holiday/halloween/halloween.dm
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#10049 Colored fairy grass, because fuck your eyes.
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/plant_genes.dm
  icons/obj/hydroponics/seeds.dmi
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
Labels: Feature, Fix, Sprites

#9993 Ports tgstation loom changes, and durathred golems.
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/game/objects/structures/loom.dm
  code/modules/cargo/packs/materials.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/ruins/lavaland_ruin_code.dm
Labels: Feature, Fix, Tweak

#9990 Fixes to strange reagent and very slight nerf I guess.
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Feature, Fix

#10008 adds sleeping carp wrist wrench/violent grab hallucination
  code/modules/flufftext/Hallucination.dm
Labels: Feature

#9975 Merging, tweaking or otherwise removing a few of the stupidest cargo packs.
  code/game/objects/items/inducer.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/cargo/packs/medical.dm
  code/modules/cargo/packs/misc.dm
  code/modules/cargo/packs/service.dm
  code/modules/power/cell.dm
Labels: Removal, Tweak

#9997 removes superspeed from nuka cola
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Removal

#10045 Makes wallets hold more stuff
  code/game/objects/items/storage/wallets.dm
Labels: Feature

#10038 Makes trash carts craftable with plastic
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/crates_lockers/crates/bins.dm
Labels: Feature

#9919 Fixes several "behind" layer tail sprites skipping areas normally covered by bodyparts.
  icons/mob/mutant_bodyparts.dmi
  modular_citadel/icons/mob/mam_tails.dmi
Labels: Fix, Sprites

#9955 Updating supply pods code.
  code/__DEFINES/admin.dm
  code/__DEFINES/cargo.dm
  code/__DEFINES/flags.dm
  code/datums/explosion.dm
  code/game/atoms.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/cargo/expressconsole.dm
  code/modules/cargo/gondolapod.dm
  code/modules/cargo/supplypod.dm
  code/modules/events/immovable_rod.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/power/supermatter/supermatter.dm
  html/create_object.html
  sound/weapons/mortar_long_whistle.ogg
  sound/weapons/mortar_whistle.ogg
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/interfaces/centcom_podlauncher.ract
  tgui/src/util/tooltip.styl
Labels: Administration, Fix, Sound, Tweak, UI

#10043 PDA cartridges and their contents can no longer be contaminated
  code/game/objects/items/devices/PDA/cart.dm
Labels: Tweak

#10034 Fixes the incongruent bone satchel description.
  code/game/objects/items/storage/backpack.dm
Labels: Grammar and Formatting

#9947 Removes Clockie Surgical capabilities
  _maps/map_files/generic/City_of_Cogs.dmm
Labels: Map Edit, Removal

#10056 Ports "Slightly improves visible and audible messages."
  code/__DEFINES/combat.dm
  code/__DEFINES/say.dm
  code/datums/components/storage/storage.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/virus_cart.dm
  code/game/objects/items/grenades/flashbang.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/teleportation.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/loom.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/hydroponics/grown/cotton.dm
  code/modules/hydroponics/grown/pumpkin.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/mob.dm
  code/modules/mob/say_vr.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/projectiles/pins.dm
  code/modules/recycling/disposal/holder.dm
  code/modules/vore/eating/belly_obj.dm
Labels: Fix

#10064 Fixes silicon hearing - "Wow I do good work when I'm not literally spamming reverts without looking, I didn't even make the reverts for the right PRs"
  code/modules/mob/living/silicon/silicon.dm
Labels: Priority: High, Revert

#9932 Make organs no longer radiaoctively contaminable.
  code/modules/surgery/organs/organ_internal.dm
Labels: Fix

#9912 Added 15+ new crates, fixed issues raised in #9901
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/emergency.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/medical.dm
  code/modules/cargo/packs/misc.dm
  code/modules/cargo/packs/organic.dm
  code/modules/cargo/packs/science.dm
  code/modules/cargo/packs/service.dm
  code/modules/events/shuttle_loan.dm
Labels: Feature

#10100 [READY] Tweaks botany related reagent pHes so they don't negatively affect botany.
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Needs Review, Tweak

#10057 fixes on_mob eyes overlays not updating properly in certain cases.
  code/game/objects/structures/mirror.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/surgery/organs/eyes.dm
Labels: Fix

#10068 Ports "Makes the windup toolbox more similar to His Grace".
  code/game/objects/items/toys.dm
Labels: Fix, Tweak

#10071 Fixes bubblegum's death not unlocking the arena shuttle buyment since the medals subsystem is not hub enabled
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Fix

#10075 Demodularize defib disks and projectiles icons.
  code/game/objects/effects/temporary_visuals/projectiles/impact.dm
  code/game/objects/effects/temporary_visuals/projectiles/muzzle.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/game/objects/items/defib.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/megabuster.dm
  code/modules/projectiles/projectile/plasma.dm
  icons/mob/inhands/equipment/idcards_lefthand.dmi
  icons/mob/inhands/equipment/idcards_righthand.dmi
  icons/obj/module.dmi
  icons/obj/projectiles.dmi
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/obj/projectiles_tracer.dmi
  modular_citadel/code/game/objects/effects/temporary_visuals/projectiles/impact.dm
  modular_citadel/code/game/objects/effects/temporary_visuals/projectiles/muzzle.dm
  modular_citadel/code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
  modular_citadel/icons/obj/VGProjectile.dmi
  modular_citadel/icons/obj/defib_disks.dmi
  modular_citadel/icons/obj/projectiles.dmi
  modular_citadel/icons/obj/projectiles_impact.dmi
  modular_citadel/icons/obj/projectiles_muzzle.dmi
  modular_citadel/icons/obj/projectiles_tracer.dmi
  tgstation.dme
Labels: Sprites

#10044 Made wooden cabinet/closets... actually made of wood.
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Tweak

#10099 Fixes a few holo barriers lacking transparency.
  code/game/objects/structures/holosign.dm
Labels: Fix

#9903 Removes the night vision quirk
  code/datums/traits/good.dm
Labels: Removal

#9538 Brings the combat back in combat defibrillator (DOES NOT BUFF CMO DO NOT YELL AT ME)
  code/game/objects/items/defib.dm
Labels: Balance/Rebalance

#10114 Add a N2O Pressure Tank
  code/modules/atmospherics/machinery/components/unary_devices/tank.dm
Labels: Feature

#10053 Fixes some means of eyes blindness not working, removes legacy code.
  code/modules/antagonists/changeling/powers/headcrab.dm
  code/modules/antagonists/clockcult/clock_items/wraith_spectacles.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/status_procs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/status_procs.dm
  code/modules/paperwork/paperplane.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/organs/eyes.dm
  modular_citadel/code/game/machinery/wishgranter.dm
  modular_citadel/code/modules/arousal/toys/dildos.dm
Labels: Fix, Removal

#10108 Screaming no longer is a viable strategy against clockies
  code/datums/status_effects/debuffs.dm
Labels: Balance/Rebalance

#10132 Makes meat hook fit in boh again
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Tweak

#10094 Fixes eletroplating of brozne/golden tool box
  code/modules/crafting/recipes/recipes_misc.dm
Labels: Fix

#9629 can we not tell all the nonantags that antagonist ooc is enabled please
  code/modules/client/verbs/aooc.dm
Labels: Fix

#10037 Doubles locomotion circuit ext cooldown. Nerfs gun & pneumatic cannons circuits with sanity checks.
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/integrated_circuit.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/integrated_electronics/subtypes/weaponized.dm
  code/modules/projectiles/gun.dm
Labels: Balance/Rebalance, Fix

#10130 unmodularize hulk
  code/datums/mutations/hulk.dm
  modular_citadel/code/datums/mutations/hulk.dm
  tgstation.dme
Labels: Code Improvement

#10086 Fixes AI core display I may have broken with my coding extravaganza.
  code/modules/jobs/job_types/ai.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#10083 Fixes space hermit asteroid rocks unintendedly spawning airless asteroid turf when mined, save for the perimeter.
  _maps/RandomRuins/SpaceRuins/spacehermit.dmm
  code/game/turfs/simulated/minerals.dm
  icons/turf/smoothrocks.dmi
Labels: Fix, Map Edit, Sprites

#10082 Bluespace launchpad QoL (read: powercreep)
  code/game/machinery/computer/launchpad_control.dm
Labels: Feature

#9747 Fixing AI holopad speech text being small and whispers ending in multiple exclamation marks oxymoron.
  code/__DEFINES/components.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/game/machinery/doors/passworddoor.dm
  code/game/machinery/hologram.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/eightball.dm
  code/game/say.dm
  code/modules/antagonists/clockcult/clock_mobs/_eminence.dm
  code/modules/antagonists/disease/disease_mob.dm
  code/modules/assembly/voice.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/slime/say.dm
  modular_citadel/code/modules/mob/mob.dm
Labels: Fix

#10116 Makes genital enlargement chems properly opt-outable
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
Labels: Fix

#10143 Dynamic no longer double dips on refunds for ghost antags with not enough applicants
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: FUCK, Fix

#10140 Makes secret's dynamic roundstart report not tell people to contact a coder
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Fix

#10085 Fixes reviver implant having been a crapshot ever since soft-crit was introduced years ago.
  code/modules/surgery/organs/augments_chest.dm
Labels: Fix, Tweak

#10156 Fixing character setup preview icons.
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/dummy.dm
Labels: Fix

#10121 plasmafist wizard plasmafist wizard
  code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Approved/Merge Ready, Feature

#9894 [TESTMERGE] Explosion/bomb armor rework
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance/Rebalance

#10137 New delta alert sound but It works this time I swear
  sound/misc/deltakalaxon.ogg
Labels: Sound

#10161 Fixes raven's shuttle computer not being of the emergency shuttle type.
  _maps/shuttles/emergency_raven.dmm
Labels: Fix, Map Edit

#9757 porting "Split Travis shell scripts by job" and "Remove unneeded import from travis python script" with the power of patches. Also DreamChecker.
  .editorconfig
  .travis.yml
  dependencies.sh
  tools/json_verifier.py
  tools/travis/before_build_tools.sh
  tools/travis/build_bsql.sh
  tools/travis/build_byond.sh
  tools/travis/build_dependencies.sh
  tools/travis/build_tgui.sh
  tools/travis/build_tools.sh
  tools/travis/check_changelogs.sh
  tools/travis/check_grep.sh
  tools/travis/install_build_tools.sh
  tools/travis/install_byond.sh
  tools/travis/install_dreamchecker.sh
  tools/travis/install_libmariadb.sh
  tools/travis/install_rust_g.sh
  tools/travis/run_server.sh
  tools/travis/template_dm_generator.py
Labels: Tools

#10162 Removes medihounds (actually just makes them a medical aux sprite)
  code/game/objects/items/devices/dogborg_sleeper.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg archive.dm
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
Labels: Removal

#10050 Adds view and viewers checks for ranged construction devices such as ARCD and RLD.
  code/game/objects/items/RCD.dm
Labels: Tweak

#10171 Who the fuck put 10 shielding when you need 9?
  code/modules/cargo/packs/engine.dm
Labels: Removal

#10163 Allows blood bank generators to be wrenched and unwrenched.
  code/game/machinery/bloodbankgen.dm
Labels: Tweak

#10150 Corrects telegram hat icon, adds a new dog fashion to telegram hat
  code/modules/clothing/head/misc.dm
Labels: Fix

#10122 nerfs factorio (conveyors can no longer stack more than 150 items on one tile)
  code/modules/recycling/conveyor2.dm
Labels: Removal

#9970 Removes literally atrocious polka dotted accessories.
  code/modules/clothing/under/accessories.dm
  code/modules/vending/clothesmate.dm
  icons/mob/accessories.dmi
  icons/obj/clothing/accessories.dmi
Labels: Removal, Sprites

#10166 Ports "Roundstart borg brains no longer decay."
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Fix

#10144 makes the officer's sabre play the un/sheating noise properly
  code/game/objects/items/melee/misc.dm
Labels: Fix

#10197 fixing double-flavour (and bland custom) ice creams.
  code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
Labels: Fix

#10195 Fixes a few quirks not being properly removed when deleted, also bringing them in line with the rest instead of being removable through surgery.
  code/datums/traits/negative.dm
Labels: Fix, Tweak

#10198 Fixes ranged syndicate mobs stormtrooper training: The port.
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Fix

#10177 NUCLEAR FIST. A new wizard spell involving punching people so hard they explode.
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/granters.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/touch_attacks.dm
  icons/effects/96x96.dmi
  icons/mob/actions/actions_spells.dmi
  icons/obj/library.dmi
  icons/obj/projectiles.dmi
  sound/weapons/nuclear_fist.ogg
Labels: Sound, Sprites

#9971 Adds the Christmas Clothes you never knew you wanted.
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/dead/new_player/sprite_accessories/socks.dm
  code/modules/vending/clothesmate.dm
  icons/mob/feet.dmi
  icons/mob/feet_digi.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/underwear.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/shoes.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature, Sprites

#9736 I want to have a word with whoever wrote the original antagonist reputation proc
  code/game/gamemodes/game_mode.dm
Labels: Code Improvement

#10115 [READY] Ported lavaland tumors and elites from tg.
  _maps/RandomRuins/LavaRuins/lavaland_surface_elite_tumor.dmm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/lavaland_elite.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/ruins/lavaland.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/legionnaire.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/pandora.dm
  code/modules/mob/mob_defines.dm
  icons/mob/accessories.dmi
  icons/mob/actions/actions_elites.dmi
  icons/mob/lavaland/lavaland_elites.dmi
  icons/mob/neck.dmi
  icons/mob/screen_elite.dmi
  icons/obj/lavaland/artefacts.dmi
  icons/obj/lavaland/elite_trophies.dmi
  icons/obj/lavaland/legionnaire_bonfire.dmi
  icons/obj/lavaland/tumor.dmi
  sound/magic/curse.ogg
  tgstation.dme
Labels: Feature, Map Edit, Needs Review, Sound, Sprites

#10180 [s] virtual reality component improvements, fixes and documentation.
  code/__DEFINES/components.dm
  code/datums/components/_component.dm
  code/datums/components/bane.dm
  code/datums/components/bouncy.dm
  code/datums/components/decal.dm
  code/datums/components/fantasy/_fantasy.dm
  code/datums/components/igniter.dm
  code/datums/components/knockback.dm
  code/datums/components/lifesteal.dm
  code/datums/components/nanites.dm
  code/datums/components/orbiter.dm
  code/datums/components/shrapnel.dm
  code/datums/components/summoning.dm
  code/datums/components/tactical.dm
  code/datums/components/virtual_reality.dm
  code/datums/components/wet_floor.dm
  code/datums/mind.dm
  code/game/machinery/_machinery.dm
  code/modules/VR/vr_mob.dm
  code/modules/VR/vr_sleeper.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/death.dm
  code/modules/mob/mob.dm
Labels: Fix

#10181 Fixing a few pill bottle issues with the ChemMaster.
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Fix

#10072 Ported bamboo stuff from tg.
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/cargo/packs/organic.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/stack_objects.dmi
Labels: Feature, Sprites

#10225 Two slimepeople fixes.
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Fix

#10203 Nukies and deathsquaddies can now finally fix their mechs internal fires
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/honker.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/neovgre.dm
  code/game/mecha/combat/reticence.dm
  code/game/mecha/mecha.dm
Labels: Tweak

#10157 Ports "Fixes powernet avail checks"
  code/modules/power/apc.dm
  code/modules/power/cable.dm
  code/modules/power/power.dm
Labels: Fix

#10155 adds some distance checks to some things
  code/game/objects/structures/window.dm
  code/modules/modular_computers/hardware/ai_slot.dm
  code/modules/modular_computers/hardware/card_slot.dm
Labels: Fix

#10111 send help please, or how i vowed to kill kevinz (you can now strip people while aggrograbbing)
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#10066 neovgre qol changes
  code/game/mecha/combat/neovgre.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_applications.dm
  sound/effects/neovgre_exploding.ogg
Labels: Sound

#10216 Porting a few martial art code updates.
  code/__DEFINES/traits.dm
  code/datums/martial.dm
  code/datums/martial/cqc.dm
  code/datums/martial/sleeping_carp.dm
  code/datums/mutations/hulk.dm
  code/game/objects/items/devices/laserpointer.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
Labels: Balance/Rebalance, Code Improvement, Fix, Grammar and Formatting, Tweak

#10172 Porting several quirks code updates.
  code/__HELPERS/cmp.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/processing/quirks.dm
  code/controllers/subsystem/ticker.dm
  code/datums/components/mood.dm
  code/datums/datacore.dm
  code/datums/datumvars.dm
  code/datums/traits/good.dm
  code/datums/traits/negative.dm
  code/datums/traits/neutral.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/status_procs.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Code Improvement, Feature, Fix, Grammar and Formatting, Tweak

#10076 Fixes alien tech node not being unlockable with subtypes of the accepted items.
  code/modules/research/techweb/all_nodes.dm
Labels: Fix

#10153 make unable to carry fireman message more clear when unable to carry non-humans
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#10227 Probably fixes only neutral traits existing
  code/controllers/subsystem/processing/quirks.dm
Labels: Fix

#10228 fixes quirks (again)
  code/controllers/subsystem/processing/quirks.dm
Labels: Fix

#10223 Removes Security K9 dogborg. The last of the infinity dogborg removals. (same treatment as the others)
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg archive.dm
  modular_citadel/icons/mob/widerobot.dmi
Labels: Removal

#10204 Port boops and handshakes
  code/modules/mob/living/carbon/carbon_defense.dm
  sound/items/Nose_boop.ogg
Labels: Feature, Sound

#10090 the one where the combat medic kit gets buffed
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Tweak

#10067 You can change a plant's name, description and its seed's description by using a pen on the seed
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seeds.dm
Labels: Feature

#10160 Ports improved and simplier fire alarms.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/firealarm.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  icons/obj/monitors.dmi
  modular_citadel/code/game/machinery/firealarm.dm
  tgstation.dme
  tgui/assets/tgui.js
  tgui/src/interfaces/firealarm.ract
Labels: Fix, Map Edit, Sprites, Tweak, UI

#9722 Umodularize saycode and meat slabs.
  code/game/say.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
  icons/obj/food/food.dmi
  modular_citadel/code/modules/food_and_drinks/snacks/meat.dm
  modular_citadel/code/modules/mob/mob.dm
  modular_citadel/icons/obj/foods.dmi
  tgstation.dme
Labels: Sprites

#10079 Fixes reactive armor onmob overlays not updating when toggled and reactive teleport armor still using forceMove()
  code/modules/clothing/suits/reactive_armour.dm
Labels: Fix

#10207 Fixes pubby wall meds being var-edited snowflakes.
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#10214 Brings carbon action intent hotkeys down to living.
  code/modules/keybindings/bindings_carbon.dm
  code/modules/keybindings/bindings_living.dm
Labels: Fix

#10173 Fixing a boxstation pipenet mapping issue.
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#10054 autolathe .357 speedloaders->bullets, surplus rifle bullets in hacked lathe
  code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Tweak

#10126 Makes HE pipes realistically radiate away heat
  code/__DEFINES/atmospherics.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
Labels: Balance/Rebalance

#10142 Feast or Famine is shit. Makes CE hardsuit raditation proof hat wise, buffes its rest of body by 5
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Tweak

#10051 puts our legion more up to date with tg's
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
Labels: Balance/Rebalance

#9925 change cosmic coat crafting recipe
  code/modules/crafting/recipes/recipes_clothing.dm
Labels: Tweak

#9563 [TESTMERGE] Goodbye, superpH, you were too wild for our world.
  code/modules/reagents/reagent_containers.dm
Labels: Sprites, Tweak

#9798 Radiation storms no longer do random mutations in of itself, but are far more lethal
  code/datums/weather/weather_types/radiation_storm.dm
Labels: Test Merge Candidate

#10231 fixes the sprites for some winter coats
  icons/mob/head.dmi
Labels: Fix, Sprites

#10235 flashbangs process flash/bang separately based on blindness/hearing and uses viewers(), which means xray users suffer too if they see them go off
  code/game/objects/items/grenades/flashbang.dm
Labels: Balance/Rebalance

#10200 Adds 8 character save slots
  code/modules/client/preferences.dm
Labels: Feature

#10058 Spinfusor nerf, cause a 7k cost supply pack containing 32 explosive munitions that work just fine without the gun is just pure balance.
  modular_citadel/code/modules/projectiles/guns/ballistic/spinfusor.dm
Labels: Balance/Rebalance

#10059 you can pick up corgis now
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/washing_machine.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/inhand_holder.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/sloth.dm
  code/modules/recycling/disposal/bin.dm
  icons/mob/animals_held.dmi
  icons/mob/animals_held_lh.dmi
  icons/mob/animals_held_rh.dmi
Labels: Feature, Sprites

#9596 Bring abductors up-to-date with /tg/.
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/movespeed_modification.dm
  code/_onclick/hud/alert.dm
  code/controllers/subsystem/traumas.dm
  code/datums/components/shrink.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/abductor/equipment/abduction_outfits.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/antagonists/abductor/equipment/glands/access.dm
  code/modules/antagonists/abductor/equipment/glands/blood.dm
  code/modules/antagonists/abductor/equipment/glands/chem.dm
  code/modules/antagonists/abductor/equipment/glands/egg.dm
  code/modules/antagonists/abductor/equipment/glands/electric.dm
  code/modules/antagonists/abductor/equipment/glands/heal.dm
  code/modules/antagonists/abductor/equipment/glands/mindshock.dm
  code/modules/antagonists/abductor/equipment/glands/plasma.dm
  code/modules/antagonists/abductor/equipment/glands/quantum.dm
  code/modules/antagonists/abductor/equipment/glands/slime.dm
  code/modules/antagonists/abductor/equipment/glands/spider.dm
  code/modules/antagonists/abductor/equipment/glands/transform.dm
  code/modules/antagonists/abductor/equipment/glands/trauma.dm
  code/modules/antagonists/abductor/equipment/glands/ventcrawl.dm
  code/modules/antagonists/abductor/equipment/glands/viral.dm
  code/modules/antagonists/abductor/machinery/console.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/tongue.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/screen_alert.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_digi.dmi
  icons/obj/abductor.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/guns/energy.dmi
  sound/weapons/shrink_hit.ogg
  tgstation.dme
Labels: Feature, Sound, Sprites

#9940 Dynamic rulesets that have fired in recent rounds have lower weight
  code/controllers/subsystem/persistence.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Tweak

#10232 All heads of staff can now spam CC.
  code/game/machinery/computer/communications.dm
Labels: Tweak

#10141 Adds a bunch of statbus logging to dynamic
  code/__HELPERS/roundend.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Administration, Needs Review

#10164 What ho, Muscle Wizard! Might you cast us a spell?
  code/__DEFINES/antagonists.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/wizard/wizard.dm
Labels: Feature

#10120 Night vision trait but it just boosts barely-lit visibility
  code/__DEFINES/lighting.dm
  code/datums/traits/good.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/surgery/organs/eyes.dm
Labels: Feature

#10257 Removes a magicnumber
  code/game/machinery/computer/communications.dm
Labels: Code Improvement, Removal

#10096 nanites can no longer spread through atmospherics-blocking objects
  code/modules/research/nanites/nanite_programs/utility.dm
Labels: Balance/Rebalance

#9950 Nerfs the Clockwork Marauder meta
  code/controllers/configuration/entries/game_options.dm
  code/modules/antagonists/clockcult/clock_mobs/clockwork_marauder.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_applications.dm
Labels: Balance/Rebalance, Config Update

#10190 The new buzz around the new soft drink
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/vending/cola.dm
  icons/obj/drinks.dmi
  icons/obj/vending.dmi
Labels: Feature, Sprites

#9830 Stun warfare rebalance - CBT edition
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
  code/modules/antagonists/clockcult/clock_helpers/slab_abilities.dm
  code/modules/antagonists/clockcult/clock_items/clock_weapons/ratvarian_spear.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
Labels: Balance/Rebalance

#10241 Ports "Added TRAIT_DISK_VERIFIER, refactors how fake disk checks work slightly
  code/__DEFINES/traits.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/jobs/job_types/captain.dm
Labels: Refactor

#10263 Makes Buzz Fuzz less coma'enducing
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Tweak

#10254 Fix the nose boop
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Fix

#10093 [Ready] Hey why dont I port that one donut pr? Ye just the one food related pr... Just the one... Oh no
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/__DEFINES/food.dm
  code/datums/components/sizzle.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/items/gift.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/trash.dm
  code/modules/cargo/packs/organic.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/food.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/food/snacks_bread.dm
  code/modules/food_and_drinks/food/snacks_burgers.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/food_and_drinks/food/snacks_frozen.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_salad.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/vending/cola.dm
  icons/obj/drinks.dmi
  icons/obj/food/burgerbread.dmi
  icons/obj/food/donut.dmi
  icons/obj/food/food.dmi
  icons/obj/food/piecake.dmi
  icons/obj/food/snowcones.dmi
  icons/obj/food/soupsalad.dmi
  icons/obj/janitor.dmi
  icons/obj/kitchen.dmi
  tgstation.dme
Labels: Balance/Rebalance, Code Improvement, Feature, Grammar and Formatting, Map Edit, Needs Review, Removal, Sound, Sprites, Tweak

#10210 Cargo shuttle now silently leaves behind slaughter demons + revenants
  code/modules/shuttle/supply.dm
Labels: Feature

#10246 Makes mob/Stat on a 1 second timer rather than fast-as-possible to tone down highpop lag
  code/modules/mob/mob.dm
Labels: Tweak

#10139 Donator Item - Ready For Review
  icons/mob/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Donor Fluff, Sprites

#10267 Fills white first aid kits to the brim. Ergo how I was fooled into believing it was a tweak and not a nerf.
  code/game/objects/items/stacks/medical.dm
Labels: Kneejerk Change, Salt, Tweak
