Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-09, with the labels that each got.

#9227 Fixes missing peach and peach seed sprites
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Fix, Sprites

#8919 Increases click resolution to 0.5 seconds
  code/_onclick/click.dm
Labels: Approved/Merge Ready, Test Merge Candidate

#8932 Adds a gun range to Box Station.
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Approved/Merge Ready, Feature, Map Edit, Removal, Test Merge Candidate, Tweak

#8649 Increases the default space ruin z-level count to 2
  code/datums/map_config.dm
Labels: Approved/Merge Ready, Test Merge Candidate, Tweak

#9041 Buffs cult/clockcult wall explosion_block
  code/game/turfs/simulated/wall/misc_walls.dm
Labels: Approved/Merge Ready

#9104 classic & telebaton no longer have attack delay
  code/game/objects/items/melee/misc.dm
  modular_citadel/code/game/objects/items/melee/misc.dm
Labels: Approved/Merge Ready

#9212 Plasmaglass Tables, Spears, Shards (Take 2)
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/table_frames.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/modules/crafting/recipes.dm
  icons/mob/back.dmi
  icons/mob/inhands/weapons/polearms_lefthand.dmi
  icons/mob/inhands/weapons/polearms_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/shards.dmi
  icons/obj/smooth_structures/plasmaglass_table.dmi
Labels: Approved/Merge Ready, Sprites

#9209 Adds support for trit, bz, and pluox to the SM
  code/modules/power/supermatter/supermatter.dm
Labels: Approved/Merge Ready, Feature

#9235 Nerfs Autocloning Pt. 2.1: Autoscan
  code/game/machinery/computer/cloning.dm
Labels: Balance/Rebalance

#9239 Nerfs earths blood stam regen from 30 - > 13
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#9242 cultist boot cultist boot?
  code/datums/components/storage/concrete/pockets.dm
Labels: Tweak

#9221 adds some new nullrods with some back end null rod refactors
  code/game/objects/items.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/pins.dm
  code/modules/projectiles/projectile/beams.dm
  modular_citadel/code/game/objects/items/holy_weapons.dm
  modular_citadel/code/game/objects/items/melee/eutactic_blades.dm
Labels: Fix, Refactor, Work In Progress

#9089 RCDs can be upgraded to create computer/machine frames, moved deconstruction to the upgrade tier
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  code/__DEFINES/construction.dm
  code/game/objects/items/RCD.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/turfs/simulated/floor.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Approved/Merge Ready, Feature, Map Edit, Tweak

#9229 Gives emags 5 more uses on buy
  modular_citadel/code/game/objects/ids.dm
Labels: Tweak

#9238 Adds two more surgerys - Embalming and Body Rejuvenation
  code/game/objects/items/storage/backpack.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/toxichealing.dm
  code/modules/surgery/embalming.dm
  tgstation.dme
Labels: Feature

#9248 NT/Synda* no longer commits war crimes back on Earth
  icons/mob/robots.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/machines/harvester.dmi
  icons/obj/machines/sleeper.dmi
  icons/obj/storage.dmi
  modular_citadel/icons/firstaid.dmi
  modular_citadel/icons/mob/citadel_refs/widerobot_vr.dmi
  modular_citadel/icons/mob/widerobot.dmi
Labels: Sprites

#9254 Adds Gloria Redwood plushie as well as heichou's plushies.
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Sprites

#9249 Clean bot now cleans Cumstains, glitter, tiny glass shards and more!
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
Labels: Fix

#9247 Partially fixes tiny runaway decimals in reagents.
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Fix

#9077 No ID insertion for everything except the hop console
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/apc_control.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/prisoner.dm
  code/game/machinery/computer/prisoner/_prisoner.dm
  code/game/machinery/computer/prisoner/gulag_teleporter.dm
  code/game/machinery/computer/prisoner/management.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/gulag_item_reclaimer.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/mining/laborcamp/laborstacker.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_vending.dm
  tgstation.dme
  tgui/src/interfaces/gulag_item_reclaimer.ract
  tgui/src/interfaces/labor_claim_console.ract
  tgui/src/interfaces/ore_redemption_machine.ract
Labels: Approved/Merge Ready, Fix, Map Edit, Test Merge Candidate, Tweak, UI

#9147 The art of drunken captaining
  code/__DEFINES/traits.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
Labels: Approved/Merge Ready, Feature, Sprites

#9260 Ports trim decals
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  icons/turf/decals.dmi
Labels: Feature, Sprites

#9086 Ports dynamic gamemode from /vg/ + also normalizes head/antag restrictions
  code/__DEFINES/maths.dm
  code/__HELPERS/roundend.dm
  code/__HELPERS/time.dm
  code/game/gamemodes/brother/traitor_bro.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/readme.md
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/overthrow/overthrow.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/traitor.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  tgstation.dme
Labels: FUCK, Feature

#9251 Allow all chaplain gear to equip the same things in their suit storage
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/misc.dm
  code/game/objects/effects/spawners/bundle.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/wardrobes.dm
  modular_citadel/code/game/gamemodes/gangs/gang_datums.dm
Labels: Code Improvement, Map Edit, Tweak

#9276 Adds clip on pokadoted pants, only in 4 types for now
  code/modules/clothing/under/accessories.dm
  code/modules/vending/clothesmate.dm
  icons/mob/accessories.dmi
  icons/obj/clothing/accessories.dmi
Labels: Feature, Sprites

#9275 Fixes analyse function on ChemMasters to correctly display purity and fixes the custom transfer for buffer to beaker button.
  code/modules/reagents/chemistry/machinery/chem_master.dm
  tgui/assets/tgui.js
  tgui/src/interfaces/chem_master.ract
Labels: Fix, UI

#9279 Fixing undergarments color preferences resetting each round.
  code/game/objects/structures/dresser.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix

#9241 Ports Oracle UI framework, and updates UI for paper and disposal bins.
  code/controllers/subsystem/assets.dm
  code/modules/oracle_ui/README.md
  code/modules/oracle_ui/assets.dm
  code/modules/oracle_ui/hookup_procs.dm
  code/modules/oracle_ui/oracle_ui.dm
  code/modules/oracle_ui/themed.dm
  code/modules/paperwork/paper.dm
  code/modules/recycling/disposal/bin.dm
  html/oracle_ui/content/disposal_bin/index.html
  html/oracle_ui/editor_tool.html
  html/oracle_ui/themes/nano/index.html
  html/oracle_ui/themes/nano/sui-nano-common.css
  html/oracle_ui/themes/nano/sui-nano-common.js
  html/oracle_ui/themes/nano/sui-nano-jquery.min.js
  tgstation.dme
Labels: Feature, Refactor

#9199 I Used The Shotgun, You Know Why? (Shotgun Balance Pass)
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Approved/Merge Ready, Balance/Rebalance

#9109 Adds Catnip plants and tea
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/hydroponics/grown/tea_coffee.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  icons/obj/hydroponics/growing_flowers.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Feature, Sprites

#9289 chem fix for strained muscles edge cases
  code/modules/antagonists/changeling/powers/strained_muscles.dm
Labels: Fix

#9288 Fixes orical UI being broken and taking modular files that are not a thing
  code/modules/oracle_ui/themed.dm
Labels: Fix

#9302 fixes roundstart runtimes by job_preferences index checks be explicit key checks instead, plus some extra sanity checks
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
Labels: Fix

#9295 Raising police baton and tele baton cooldown from 0.8 to 1.4 seconds.
  code/game/objects/items/melee/misc.dm
  modular_citadel/code/game/objects/items/melee/misc.dm
  tgstation.dme
Labels: Balance/Rebalance

#9099 [Ready] [Please merge me] Fixes Neurotoxin and makes it a fermireaction. Additionally merges Fermireactions mechanics with all chems, making it possible for people to port chems over.
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Balance/Rebalance, Config Update, Do Not Merge, Fix, Needs Review, Sound, Sprites, Tweak, UI

#9203 Makes brass tools look better*
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/tools.dmi
  modular_citadel/icons/obj/tools.dmi
Labels: Sprites

#9312 ports ligament surgeries as well as dissection
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/modules/antagonists/abductor/equipment/abduction_surgery.dm
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/bioware/experimental_dissection.dm
  code/modules/surgery/advanced/bioware/ligament_hook.dm
  code/modules/surgery/advanced/bioware/ligament_reinforcement.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  tgstation.dme
Labels: Feature, Tweak

#9293 leftover legcuffs/handcuffs overlays fix.
  code/modules/mob/living/carbon/update_icons.dm
Labels: Fix

#9306 Abductor batteries can be used to unlock abductor research
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Tweak

#9304 Its a blood bath! A BlueSpace Blood Bath!
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/bloodpack.dmi
Labels: Feature, Sprites

#9292 Fixes clown shoes and work boots.
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/ninja/suit/shoes.dm
  icons/mob/feet.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  modular_citadel/icons/mob/digishoes.dmi
Labels: Fix, Sprites

#9298 Fixes undershirts n socks colors prefs.
  code/modules/client/preferences_savefile.dm
Labels: Fix

#9282 Fixed a few dozen suits' body coverage inconsistencies.
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  modular_citadel/code/modules/clothing/suits/suits.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Fix

#9283 Removes a lot of unused files
  code/modules/clothing/glasses/vg_glasses.dm
  code/modules/clothing/head/cit_hats.dm
  code/modules/clothing/head/vg_hats.dm
  code/modules/clothing/masks/vg_masks.dm
  code/modules/clothing/shoes/vg_shoes.dm
  modular_citadel/code/game/machinery/plasmacases.dm
  modular_citadel/code/game/objects/items/devices/genemods.dm
  modular_citadel/code/modules/antagonists/cit_crewobjectives.dm
  modular_citadel/code/modules/antagonists/cit_miscreants.dm
  modular_citadel/code/modules/antagonists/crew_objectives/cit_crewobjectives_cargo.dm
  modular_citadel/code/modules/antagonists/crew_objectives/cit_crewobjectives_civilian.dm
  modular_citadel/code/modules/antagonists/crew_objectives/cit_crewobjectives_command.dm
  modular_citadel/code/modules/antagonists/crew_objectives/cit_crewobjectives_engineering.dm
  modular_citadel/code/modules/antagonists/crew_objectives/cit_crewobjectives_medical.dm
  modular_citadel/code/modules/antagonists/crew_objectives/cit_crewobjectives_science.dm
  modular_citadel/code/modules/antagonists/crew_objectives/cit_crewobjectives_security.dm
  modular_citadel/code/modules/cargo/packs.dm
  modular_citadel/code/modules/crafting/recipes.dm
  modular_citadel/code/modules/mining/mine_items.dm
  modular_citadel/code/modules/mob/living/simple_animal/pokemon.dm
  modular_citadel/code/modules/research/techweb/all_nodes.dm
  modular_citadel/code/modules/research/techweb/all_nodes.dme.dm
  modular_citadel/icons/misc/misc.dmi
  modular_citadel/icons/mob/citadel/glasses.dmi
  modular_citadel/icons/mob/citadel/head.dmi
  modular_citadel/icons/mob/citadel/masks.dmi
  modular_citadel/icons/mob/citadel/shoes.dmi
  modular_citadel/icons/mob/werenerd.dmi
  modular_citadel/icons/mob/werenerdleap.dmi
  modular_citadel/icons/obj/structures.dmi
Labels: Removal

#9269 Re-enables fermichem mechanics for grenades, nuances heat for general handling and enables SDGF/hatmium explosions.
  code/modules/reagents/chemistry/holder.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Tweak

#9253 Doubles stamina regen when standing/laying down
  code/modules/mob/living/carbon/life.dm
Labels: Balance/Rebalance, Test Merge Candidate

#9310 Adds Windoors to all the flaps on DeltaStation
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature, Map Edit

#9263 Adds a new traitor bundle - Synda Major Leage Player
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/items/weaponry.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/surgery/organs/autosurgeon.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/syringe.dmi
Labels: Feature, Sprites

#9307 Reduces jetpack speed bonus on CERTAIN jetpacks while doubling efficiency
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance

#9296 Renovates Delta Station's maintenance garden.
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Config Update, Feature, Map Edit, Tweak

#9122 nerf gygax melee damage, removes mech KO punches and replaces with extra knockback (and also neuters actuator overload)
  code/game/mecha/combat/gygax.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance/Rebalance, Feature, Removal

#9331 Fixing machinery's alt-click rotation.
  code/game/machinery/_machinery.dm
Labels: Fix

#9332 Prevents sofas being wielded and thus transformed into normal chairs.
  code/game/objects/structures/beds_chairs/chair.dm
  modular_citadel/code/game/objects/structures/beds_chairs/sofa.dm
  tgstation.dme
Labels: Fix

#9334 Enables emojis for PDA messages.
  code/game/machinery/telecomms/computers/message.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Feature

#9333 Fixes clown shoes icon_state.
  icons/obj/clothing/shoes.dmi
Labels: Sprites

#9342 Updating tgui.css because someone didn't do so when reworking consoles/ID interactions.
  tgui/assets/tgui.css
Labels: Fix, UI

#9338 Reverts an undocumented change
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
Labels: Fix, Kneejerk Change, Revert

#9356 Delta chapel rearrangements, janitorial office cleanup, and more.
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature, Fix, Map Edit, Tweak

#9352 Re-adds the Qualifies for Rank Proc Checks.
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak

#9348 Reduces holy water message spam for blood/clock cultists.
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak

#9341 Blood cult altar, forge and archives now use radial menus.
  code/modules/antagonists/cult/cult_structures.dm
Labels: Tweak

#9318 [Fix] Fixes small residues of chems sitting in holders without breaking slow reactions.
  code/modules/reagents/chemistry/holder.dm
Labels: Fix

#9335 Guardian/Holoparasite Buffs
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/guardian/types/assassin.dm
  code/modules/mob/living/simple_animal/guardian/types/charger.dm
  code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
  code/modules/mob/living/simple_animal/guardian/types/explosive.dm
  code/modules/mob/living/simple_animal/guardian/types/fire.dm
  code/modules/mob/living/simple_animal/guardian/types/lightning.dm
  code/modules/mob/living/simple_animal/guardian/types/protector.dm
  code/modules/mob/living/simple_animal/guardian/types/ranged.dm
  code/modules/mob/living/simple_animal/guardian/types/standard.dm
  code/modules/mob/living/simple_animal/guardian/types/support.dm
Labels: Balance/Rebalance, Grammar and Formatting, Tweak

#9170 Makes peaches used in crafting a lot more, grammer fixes and new icecreams and floats - Remakes charrie shakes into icecreams rather then drinks
  code/game/objects/items/granters.dm
  code/game/objects/items/trash.dm
  code/modules/cargo/bounties/reagent.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/food/snacks_frozen.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/vending/drinnerware.dm
  code/modules/vending/wardrobes.dm
  icons/obj/drinks.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  icons/obj/food/piecake.dmi
  icons/obj/food/snowcones.dmi
  icons/obj/janitor.dmi
Labels: Feature, Grammar and Formatting, Relies on another PR, Sprites

#9359 Rad collector tweaks - Reverts point production to its original behavior, clears up examine text
  code/modules/power/singularity/collector.dm
Labels: Balance/Rebalance, Tweak

#9344 Makes abandoned crates less prone to explosions.
  code/modules/mining/abandoned_crates.dm
Labels: Fix, Tweak

#9317 Ports sleepy pens and emagged borg cookies buffs (also "chloralhydratedelayed" removal), plus tirizene buff.
  code/game/objects/items/RSF.dm
  code/modules/paperwork/pen.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Balance/Rebalance, Removal, Tweak

#9320 ports "Resisting out of bucklecuffs takes an amount of time dependent on cuffs used", also toy handcuffs no longer demoralize the wearer.
  code/game/objects/items/handcuffs.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Balance/Rebalance, Tweak

#9349 Fixes advanced med scanner upgrades, and other cyborg upgrades' incompatibility with dogborgs.
  code/game/objects/items/robot/robot_upgrades.dm
  modular_citadel/code/game/objects/items/robot/robot_upgrades.dm
  tgstation.dme
Labels: Fix

#9326 Advanced energy guns glow more
  code/modules/projectiles/guns/energy/energy_gun.dm
Labels: Tweak

#9322 blood cult conversion no longer requires consent
  code/modules/antagonists/cult/runes.dm
Labels: Fix

#9321 some cult fixes + cult qol
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
Labels: Feature, Fix, Grammar and Formatting

#9336 Tweaks how beakers melt in response to poll and feedback. Allows syringe/dropper use on beakers in heaters.
  code/modules/reagents/chemistry/machinery/chem_heater.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/obj/chemical.dmi
  icons/obj/drinks.dmi
  icons/obj/janitor.dmi
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  sound/FermiChem/SoundSources.txt
  sound/FermiChem/heatdam.ogg
Labels: Fix, Refactor, Sound, Sprites, Tweak

#9267 Gives the Endivend Upgraded RCDs by default, instead of Autolathe ones.
  code/modules/vending/engivend.dm
Labels: Balance/Rebalance

#9191 Ports fireman carrying from /tg/
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/datums/components/footstep.dm
  code/datums/components/riding.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob.dm
Labels: Awaiting further discussion/approval, Feature

#9189 [READY] craftable laser minigun, because why not
  code/modules/crafting/recipes.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/minigun.dm
  code/modules/projectiles/projectile/beams.dm
  sound/weapons/gatling.ogg
  tgstation.dme
Labels: Awaiting further discussion/approval, Feature, Needs Review, Sound
