Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-11, with the labels that each got.

#8948 Cleaning up the arousal module.
  code/__DEFINES/DNA.dm
  code/__DEFINES/citadel_defines.dm
  code/__DEFINES/inventory.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/_cit_helpers.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/bitfields.dm
  code/datums/traits/neutral.dm
  code/game/objects/items/devices/compressionkit.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/organs/organ_internal.dm
  modular_citadel/code/datums/status_effects/chems.dm
  modular_citadel/code/datums/traits/neutral.dm
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/arousal/genitals.dm
  modular_citadel/code/modules/arousal/genitals_sprite_accessories.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/eggsack.dm
  modular_citadel/code/modules/arousal/organs/genitals.dm
  modular_citadel/code/modules/arousal/organs/ovipositor.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/arousal/organs/testicles.dm
  modular_citadel/code/modules/arousal/organs/vagina.dm
  modular_citadel/code/modules/arousal/organs/womb.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
  modular_citadel/icons/obj/genitals/hud.dmi
  modular_citadel/icons/obj/genitals/testicles_onmob.dmi
  tgstation.dme
Labels: Code Improvement, Refactor

#9677 Makes clone scans lock while processing
  code/game/machinery/computer/cloning.dm
Labels: Tweak

#9686 Fixing storage implant transplant.
  code/game/objects/items/implants/implant_storage.dm
Labels: Fix

#9678 Resprited the ore redemption and miner vending machines.
  icons/obj/machines/mining_machines.dmi
Labels: Sprites

#9675 Patches an exploit that allows the crew to shoot the Ark from the Ree…
  _maps/map_files/generic/City_of_Cogs.dmm
Labels: Map Edit, Tweak

#9674 Updating ratvarian computer sprites.
  code/game/machinery/computer/_computer.dm
  icons/obj/computer.dmi
Labels: Sprites

#9670 Mapping in arcade dirs.
  _maps/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/research.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/emergency_cere.dmm
  code/game/machinery/computer/arcade.dm
Labels: Map Edit

#9668 Gives ways for various slime-killing healing viruses not to do that.
  code/datums/diseases/advance/symptoms/heal.dm
Labels: Balance/Rebalance

#9665 Removing references to national socialism
  code/modules/clothing/head/vg_hats.dm
  code/modules/clothing/spacesuits/vg_spess.dm
  icons/obj/citvending.dmi
  modular_citadel/code/game/machinery/vending.dm
Labels: Sprites

#9659 Fixing deep space gorilla runtimes, how ape...
  _maps/RandomRuins/SpaceRuins/bigape.dmm
  code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
Labels: Fix, Map Edit

#9658 Fixing dogborg sleepers runtimes, how atrocious...
  code/game/objects/items/devices/dogborg_sleeper.dm
Labels: Fix

#9654 Adds dynamic antag injection to config
  code/controllers/configuration/entries/game_options.dm
  code/game/gamemodes/dynamic/dynamic.dm
  config/game_options.txt
Labels: Config Update

#9687 Refactoring how Jacqueen teleportation destination is selected.
  code/game/machinery/hologram.dm
  code/modules/holiday/halloween/jacqueen.dm
Labels: Fix, Refactor

#9574 Add departemental Winter Coats to loadout
  modular_citadel/code/modules/client/loadout/suit.dm
Labels: Feature

#9611 Adds passive point generation to cargo. Nerfs miasma selling. Increases mindshield crate price.
  code/controllers/subsystem/shuttle.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/packs/armory.dm
Labels: Balance/Rebalance, Feature

#9705 thanks major
  code/modules/uplink/uplink_items.dm
Labels: Tweak

#9724 Fixes free real estate paraplegic trait and bolas.
  code/modules/surgery/bodyparts/helpers.dm
Labels: Fix

#9726 Fixing several minor runtimes.
  code/datums/traits/neutral.dm
  code/game/objects/items/RCD.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/organ_internal.dm
Labels: Fix

#9717 Makes SDGF transfer notes/memories.
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
Labels: Tweak

#9716 Porting objective code refactor (ergo fixing abductors/abductees objective by updating the code)
  code/__HELPERS/roundend.dm
  code/datums/mind.dm
  code/game/gamemodes/devil/devil agent/devil_agent.dm
  code/game/gamemodes/devil/game_mode.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/cryopod.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/blob/blob.dm
  code/modules/antagonists/blood_contract/blood_contract.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/devil/devil.dm
  code/modules/antagonists/devil/imp/imp.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/antagonists/disease/disease_datum.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/greentext/greentext.dm
  code/modules/antagonists/highlander/highlander.dm
  code/modules/antagonists/magic_servant/magic_servant.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/antagonists/ninja/ninja.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/antagonists/official/official.dm
  code/modules/antagonists/overthrow/overthrow.dm
  code/modules/antagonists/overthrow/overthrow_team.dm
  code/modules/antagonists/pirate/pirate.dm
  code/modules/antagonists/revenant/revenant_antag.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/santa/santa.dm
  code/modules/antagonists/slaughter/slaughter_antag.dm
  code/modules/antagonists/survivalist/survivalist.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/valentines/heartbreaker.dm
  code/modules/antagonists/valentines/valentine.dm
  code/modules/antagonists/wishgranter/wishgranter.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/awaymissions/corpse.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/events/holiday/xmas.dm
  code/modules/events/wizard/greentext.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/mob.dm
  tgstation.dme
Labels: Fix, Refactor

#9715 Ports CEV-Eris resprited matchbox, also respriting cigar boxes myself.
  code/game/objects/items/storage/fancy.dm
  icons/obj/cigarettes.dmi
Labels: Sprites

#9713 Makes catnip have sprites
  code/modules/hydroponics/grown/tea_coffee.dm
Labels: Fix

#9709 Adds 8 more sci crates to cargo
  code/game/objects/items/theft_tools.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/cargo/packs/science.dm
  icons/obj/nuke_tools.dmi
Labels: Feature, Sprites, Tweak

#9704 Minor ninja tweaks and stealth nerf.
  code/__DEFINES/components.dm
  code/datums/dash_weapon.dm
  code/datums/helper_datums/teleport.dm
  code/modules/ninja/suit/n_suit_verbs/ninja_stealth.dm
  code/modules/ninja/suit/suit.dm
  code/modules/ninja/suit/suit_process.dm
  code/modules/projectiles/gun.dm
Labels: Balance/Rebalance

#9696 clock welder overlay fix.
  code/modules/holiday/halloween/jacqueen.dm
  icons/obj/tools.dmi
Labels: Fix, Sprites

#9695 Unmodularize and update pAI/Intellicards very slighty.
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/devices/paicard.dm
  code/modules/crafting/recipes/recipes_misc.dm
  code/modules/crafting/recipes/recipes_robot.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/pai/software.dm
  icons/obj/aicards.dmi
  modular_citadel/code/game/objects/items/devices/aicard.dm
  modular_citadel/icons/aicards.dmi
  modular_citadel/icons/obj/aicards.dmi
  tgstation.dme
Labels: Feature, Sprites, Tweak

#9694 Buffs security, nerfs antags
  code/modules/projectiles/guns/energy/energy_gun.dm
Labels: Fix

#9746 Ports "Cleans up the new alt clicking functionality" from /tg/
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/gulag_teleporter.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/modules/mining/machine_redemption.dm
  tgstation.dme
Labels: Fix

#9745 rad flags fixes.
  code/datums/radiation_wave.dm
Labels: Fix

#9744 makes meteor hallucinations have an ETA now
  code/modules/flufftext/Hallucination.dm
Labels: Fix

#9734 Ports CEV-eris delivery packages sprites, also dunking old syndie cybernetics box sprite.
  code/modules/surgery/organs/augments_internal.dm
  code/modules/surgery/organs/autosurgeon.dm
  icons/obj/storage.dmi
Labels: Sprites

#9779 A few clock cult improvements.
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/clockcult/clock_structures/_trap_object.dm
  code/modules/antagonists/clockcult/clock_structures/ocular_warden.dm
  code/modules/antagonists/clockcult/clock_structures/trap_triggers/pressure_sensor.dm
Labels: Balance/Rebalance, Feature, Fix

#9772 Adds eight new plushies to the game while integrating kevs' plush PR
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Feature, Grammar and Formatting, Removal, Sprites

#9765 Ports Closet & Crate Initialization Fixes
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
Labels: Fix, Removal

#9773 Adding a new PDA reskin, sprites from CEV-Eris (plus bits from Beestation and Cit-RP)
  code/__DEFINES/misc.dm
  code/game/objects/items/devices/PDA/PDA.dm
  icons/obj/pda_minimal.dmi
Labels: Feature, Sprites

#9771 Porting Robustin's Syndicate Infiltrator PR from tee-gee
  _maps/shuttles/infiltrator_basic.dmm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/turfs/simulated/wall/reinf_walls.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/projectiles/projectile/bullets/sniper.dm
  code/modules/shuttle/syndicate.dm
  icons/turf/walls/plastitanium_wall.dmi
Labels: Balance/Rebalance, Fix, Map Edit, Sprites

#9755 lentext to length, yet another 513 requirement.
  code/__DEFINES/typeids.dm
  code/__HELPERS/text.dm
  code/__HELPERS/text_vr.dm
  code/datums/mutations.dm
  code/game/machinery/newscaster.dm
  code/game/machinery/status_display.dm
  code/game/objects/structures/musician.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/say_vr.dm
  tools/Redirector/textprocs.dm
Labels: Tools

#9807 Fixes Nuclear Operatives being scared to death. (Removes halloween.dm. No more locker ghosts)
  tgstation.dme
Labels: Removal

#9791 ports TG's nicer revolver sprites for russian revolvers, normal .357 revolvers, and golden .357
  code/controllers/subsystem/traumas.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/guns/projectile.dmi
  modular_citadel/code/modules/projectiles/guns/ballistic/revolver.dm
  modular_citadel/icons/obj/guns/revolver.dmi
  tgstation.dme
Labels: Sprites

#9775 ports "Adds superlube to the clown ruin", "Replaces the slime extract in the clown biodome with a superlube sprayer." and buffs clown PDAs
  _maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
  code/__DEFINES/misc.dm
  code/__DEFINES/mobs.dm
  code/datums/components/wet_floor.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/turfs/open.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/obj/chemical.dmi
Labels: Balance/Rebalance, Feature, Map Edit, Removal, Sprites, Tweak

#9554 [READY] Desperate Assistance Battleforce
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/code/modules/client/loadout/_service.dm
  modular_citadel/icons/mob/suit_digi.dmi
Labels: Feature, Needs Review, Sprites

#9430 Ports "Adds three new .38 ammo types", also lazily adding .357 AP
  code/game/machinery/computer/teleporter.dm
  code/game/objects/items/implants/implant_track.dm
  code/game/objects/items/teleportation.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Code Improvement, Feature, Tweak

#9453 Mitigates the ghost roles/mid-round antag lock out for suicide/cryo. And related fixes.
  code/__HELPERS/game.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/pai.dm
  code/game/machinery/cryopod.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/antagonists/clockcult/clock_items/construct_chassis.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/verbs/suicide.dm
  code/modules/events/pirates.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm
  code/modules/mob/living/simple_animal/hostile/banana_spider.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/mob_helpers.dm
  config/game_options.txt
Labels: Config Update, Fix, Tweak

#9544 Changes brain damage lines
  strings/traumas.json
Labels: Tweak

#9690 Unmodularize configuration, _globalvars and subsystems.
  code/_globalvars/lists/mobs.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/shuttle.dm
  modular_citadel/code/_globalvars/lists/mobs.dm
  modular_citadel/code/controllers/configuration/entries/general.dm
  modular_citadel/code/controllers/subsystem/job.dm
  modular_citadel/code/controllers/subsystem/shuttle.dm
  tgstation.dme
Labels: Config Update

#9689 How many times I have encountered this sort of issue in the past and how much of a meme it was...
  code/game/objects/items/storage/dakis.dm
Labels: Fix

#9688 Fixing gibspawner runtimes and improving them, how gruesome...
  code/game/machinery/cloning.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/game/objects/items/melee/misc.dm
  code/modules/mob/living/carbon/alien/death.dm
  code/modules/mob/living/carbon/alien/larva/death.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/silicon/death.dm
  code/modules/mob/living/simple_animal/hostile/netherworld.dm
  code/modules/power/singularity/singularity.dm
  code/modules/projectiles/guns/ballistic.dm
Labels: Feature, Fix

#9683 Dullahans fixes and QoL.
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/game.dm
  code/_onclick/click.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/game/machinery/recycler.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/surgery/bodyparts/dismemberment.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/helpers.dm
Labels: Fix

#9680 Reworked a bit of bounty stuff.
  code/modules/cargo/bounties/assistant.dm
  code/modules/cargo/bounties/botany.dm
  code/modules/cargo/bounties/chef.dm
  code/modules/cargo/bounties/gardencook.dm
  code/modules/cargo/bounties/silly.dm
  code/modules/cargo/bounty.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature, Removal, Tweak

#9666 Shameless late game crew nerf
  code/modules/events/blob.dm
Labels: Balance/Rebalance

#9663 Buffs/Fixes embalming
  code/modules/surgery/embalming.dm
Labels: Fix

#9632 Porting multi-z support updates.
  _maps/map_files/debug/multiz.dmm
  _maps/multiz_debug.dm
  _maps/multiz_debug.json
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/turf_flags.dm
  code/_globalvars/lists/mapping.dm
  code/_onclick/hud/plane_master.dm
  code/controllers/subsystem/adjacent_air.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/throwing.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/decals/decal.dm
  code/game/objects/effects/effects.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/open.dm
  code/game/turfs/openspace/openspace.dm
  code/game/turfs/turf.dm
  code/modules/atmospherics/environmental/LINDA_system.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/atmospherics/multiz.dm
  code/modules/holodeck/area_copy.dm
  code/modules/mapping/ruins.dm
  code/modules/mapping/space_management/multiz_helpers.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/observer_movement.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob_movement.dm
  code/modules/power/gravitygenerator.dm
  code/modules/power/multiz.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/recycling/disposal/multiz.dm
  code/modules/shuttle/shuttle.dm
  config/maps.txt
  icons/obj/atmos.dmi
  icons/obj/atmospherics/pipes/disposal.dmi
  icons/obj/power.dmi
  icons/obj/stairs.dmi
  tgstation.dme
Labels: Config Update, Feature, Fix, Map Edit, Sprites

#9628 [Ready] [Testmerge] MK II Cargo Rework - Sell harder edition
  code/__DEFINES/machines.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/cargo/console.dm
  code/modules/cargo/export_scanner.dm
  code/modules/cargo/exports.dm
  code/modules/cargo/exports/food_wine.dm
  code/modules/cargo/exports/gear.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/exports/materials.dm
  code/modules/cargo/exports/organs_robotics.dm
  code/modules/cargo/exports/parts.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/cargo/exports/tools.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/organic.dm
  code/modules/cargo/packs/science.dm
  code/modules/food_and_drinks/autobottler.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/hydroponics/fermenting_barrel.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/designs/autobotter_designs.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/shuttle/supply.dm
  icons/mob/screen_gen.dmi
  icons/obj/drinks.dmi
  icons/obj/stack_objects.dmi
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature, Needs Review, Sprites, Tweak

#9614 Lowers ghosts and insain clowns hp to 120 from 1e6
  code/modules/holiday/halloween/halloween.dm
Labels: Tweak

#9780 the one PR about making big red buttons detonate syndibombs faster
  code/game/machinery/syndicatebomb.dm
Labels: Tweak

#9781 northstar works on all intents, is slightly better than help intenting people with the hugs hands
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Tweak

#9783 Fixing Aux base camera RCD door settings and toggle window type actions.
  code/game/objects/items/RCD.dm
  code/modules/mining/aux_base_camera.dm
Labels: Fix

#9785 tweaked towel sprites tonalities and fixing their onmob suit overlay.
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/obj/items_and_weapons.dmi
Labels: Sprites

#9786 Fixing some reagents taste descriptions.
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Grammar and Formatting

#9788 Makes tapered penises look more tapered
  modular_citadel/icons/obj/genitals/penis_onmob.dmi
Labels: Tweak

#9790 Reducing meteor warning time
  code/modules/events/meteor_wave.dm
  code/modules/flufftext/Hallucination.dm
Labels: Tweak

#9795 Unmodularize areas.
  code/game/area/Space_Station_13_areas.dm
  icons/turf/areas.dmi
  modular_citadel/code/game/area/areas.dmi
  modular_citadel/code/game/area/cit_areas.dm
  tgstation.dme
Labels: Sprites

#9797 Adds two VR sleepers to all current maps' perma.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#9801 Fixing anti-meta hidden random event reports.
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  code/modules/events/blob.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/carp_migration.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/major_dust.dm
  code/modules/events/mice_migration.dm
  code/modules/events/prison_break.dm
  code/modules/events/shuttle_loan.dm
Labels: Fix

#9803 Ports Improved beach away mission and some fluff mapping items.
  _maps/RandomZLevels/TheBeach.dmm
  _maps/RandomZLevels/beach.dmm
  _maps/RandomZLevels/beach2.dmm
  code/game/objects/effects/decals/turfdecal/weather.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/fluff.dm
  config/awaymissionconfig.txt
  icons/effects/32x96.dmi
  icons/misc/beach.dmi
  icons/obj/fluff.dmi
  icons/turf/decals.dmi
  icons/turf/floors/dirt.dmi
Labels: Config Update, Feature, Map Edit, Removal, Sprites

#9742 makes gps show location on examine
  code/game/objects/items/devices/gps.dm
Labels: Feature

#9737 Ports techweb backend refactor & co.
  code/__DEFINES/misc.dm
  code/__HELPERS/_lists.dm
  code/controllers/subsystem/research.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/computer/Operating.dm
  code/game/machinery/limbgrower.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/items.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_redemption.dm
  code/modules/research/designs.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/research/experimentor.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/nanites/nanite_program_hub.dm
  code/modules/research/rdconsole.dm
  code/modules/research/techweb/__techweb_helpers.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/research/techweb/_techweb_node.dm
  modular_citadel/code/game/machinery/toylathe.dm
Labels: Refactor

#9723 Riding component fix and hacky mood runtimes workaround.
  code/datums/components/mood.dm
  code/datums/components/riding.dm
Labels: Fix

#9557 Dynamic voting (needs testing)
  code/__DEFINES/preferences.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/dynamic.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/disease/disease_event.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/revenant/revenant_spawn_event.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/slaughter/slaughterevent.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/events/abductor.dm
  code/modules/events/alien_infestation.dm
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  code/modules/events/blob.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/carp_migration.dm
  code/modules/events/communications_blackout.dm
  code/modules/events/dust.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/heart_attack.dm
  code/modules/events/ion_storm.dm
  code/modules/events/nightmare.dm
  code/modules/events/pirates.dm
  code/modules/events/radiation_storm.dm
  code/modules/events/spider_infestation.dm
  code/modules/events/vent_clog.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/ninja/ninja_event.dm
  config/config.txt
  config/dynamic_config.txt
  config/game_options.txt
  html/changelogs/AutoChangeLog-pr-9724.yml
  tgstation.dme
Labels: Config Update, Feature

#9769 ID console fixes and other tweaks.
  code/__DEFINES/is_helpers.dm
  code/game/machinery/computer/apc_control.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/communications.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/storage/wallets.dm
  code/modules/cargo/bounty_console.dm
  code/modules/cargo/console.dm
  code/modules/cargo/expressconsole.dm
  code/modules/jobs/access.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/programs/card.dm
  code/modules/modular_computers/hardware/card_slot.dm
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/special.dm
  modular_citadel/code/game/machinery/computer/card.dm
  tgstation.dme
Labels: Code Improvement, Feature, Fix, Tweak

#9813 Ports "Ghosts can now see the AI's camera" and "Removes error message while shunting [fix]"
  code/datums/components/lockon_aiming.dm
  code/game/machinery/computer/camera_advanced.dm
  code/modules/antagonists/abductor/machinery/camera.dm
  code/modules/antagonists/blob/blob/overmind.dm
  code/modules/antagonists/disease/disease_mob.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/ai/logout.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  icons/mob/blob.dmi
  icons/mob/cameramob.dmi
  icons/obj/abductor.dmi
Labels: Removal, Sprites, Tweak

#9730 kinetic crushers no longer drop if you try to use it with one hand
  code/modules/mining/equipment/kinetic_crusher.dm
Labels: Balance/Rebalance

#9802 Unmodularize bikehorns and holy weapons.
  code/game/objects/items/clown_items.dm
  code/game/objects/items/holy_weapons.dm
  icons/obj/items_and_weapons.dmi
  modular_citadel/code/game/objects/items/holy_weapons.dm
  modular_citadel/code/game/objects/items/honk.dm
  modular_citadel/code/game/objects/items/vending_items.dm
  modular_citadel/icons/obj/honk.dmi
  modular_citadel/icons/obj/items_and_weapons.dmi
  tgstation.dme
Labels: Fix, Sprites, Tweak

#9782 fixing stupid pink milk and tea missing sprites.
  icons/obj/drinks.dmi
  modular_citadel/icons/obj/drinks.dmi
Labels: Fix, Sprites

#9806 Borg changes. Compresses Service/Janitor/Scrubpuppy borgs together. Removes borgi. Adds vore sleepers to service and engi dogborgs. Demodularizes some dogborg stuff too.
  code/game/objects/items/devices/dogborg_sleeper.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
  icons/mob/dogborg.dmi
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
  modular_citadel/code/modules/mob/living/silicon/robot/robot.dm
  modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_citadel/icons/mob/widerobot.dmi
  tgstation.dme
Labels: Removal, Sprites

#9824 Adds Marisa plushie
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Sprites

#9814 modifies donator config entry to allow multiple ckeys per line
  code/__DEFINES/donator_groupings.dm
  code/controllers/configuration/config_entry.dm
  code/controllers/configuration/entries/donator.dm
Labels: Config Update

#9818 Ports the Saboteur borg for nukeops and new cyborg tools/weapon icons.
  code/game/objects/items/RCD.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/nukeop/equipment/borgchameleon.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/recycling/disposal/holder.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/robots.dmi
  icons/obj/items_cyborg.dmi
  tgstation.dme
Labels: Feature, Sprites, Tweak

#9822 Reworked how wizard spells interact with dynamic
  code/controllers/configuration/entries/dynamic.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  config/dynamic_config.txt
Labels: Config Update, Refactor

#9819 Fixing the ghost roles/mid-round antag lock out suicide/cryo refactor.
  code/modules/mob/dead/observer/observer.dm
  config/game_options.txt
Labels: Config Update, Refactor

#9846 IKEA Station 13: Import TG's Pews
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/beds_chairs/pew.dm
  icons/obj/sofa.dmi
  tgstation.dme
Labels: Feature, Sprites

#9844 Dynamic summon events tweaks
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/events/_event.dm
  code/modules/events/wizard/curseditems.dm
  code/modules/events/wizard/departmentrevolt.dm
  code/modules/events/wizard/race.dm
  code/modules/events/wizard/shuffle.dm
  code/modules/events/wizard/summons.dm
Labels: Fix, Tweak

#9842 Fixes D.A.B. loadout name
  code/modules/clothing/suits/miscellaneous.dm
  modular_citadel/code/modules/client/loadout/_service.dm
Labels: Feature, Tweak

#9838 Ports "restores legacy sends to SSChat"
  code/controllers/subsystem/chat.dm
Labels: Fix

#9837 Ports "Fixes an Ancient LINDA Bug"
  code/modules/atmospherics/environmental/LINDA_fire.dm
Labels: Fix

#9835 Ports "Self sustaining fix"
  code/modules/research/xenobiology/crossbreeding/selfsustaining.dm
Labels: Fix

#9858 Fixing gasping xenos.
  code/modules/mob/living/carbon/life.dm
Labels: Fix

#9853 Adds a few extra cardboard cutout variants.
  code/game/objects/items/cardboard_cutouts.dm
  icons/obj/cardboard_cutout.dmi
Labels: Feature, Sprites

#9850 fixing a few minor issues with console frames building.
  code/game/machinery/computer/buildandrepair.dm
Labels: Fix

#9852 Fixing some wizard den teleportation issues.
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/spells/spell_types/area_teleport.dm
Labels: Fix, Tweak

#9869 what if i gave botanists the ability to get the fancy alien dna manipulator. haha, just kidding. ...unless?
  code/modules/research/designs/machine_desings/machine_designs_service.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#9877 Unmodularize pAI holo-chassis icons.
  code/modules/mob/living/silicon/pai/pai.dm
  icons/mob/pai.dmi
  modular_citadel/icons/mob/pai.dmi
Labels: Fix, Sprites

#9876 Unmodularize tools and apc icons.
  icons/obj/power.dmi
  icons/obj/tools.dmi
  modular_citadel/code/game/objects/tools.dm
  modular_citadel/icons/obj/power.dmi
  modular_citadel/icons/obj/tools.dmi
  tgstation.dme
Labels: Sprites

#9875 Makes from-ghosts rulesets cancel if fewer than required candidates
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Fix

#9873 Fixing aux-base construction RCD door access settings menu and reverting another non-functional bit
  code/game/objects/items/RCD.dm
  code/modules/mining/aux_base_camera.dm
Labels: Fix, Removal, Revert

#9812 Fixing missing delivery packages sprites
  icons/obj/storage.dmi
Labels: Fix, Sprites

#9720 Is it the time of year to buff disablers again?
  code/modules/projectiles/projectile/beams.dm
Labels: Balance/Rebalance

#9703 emagged medibots now murder the everloving fuck out of slimepeople
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Balance/Rebalance

#9828 Makes meteor not repeatable in dynamic.
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
Labels: Tweak

#9831 Makes dynamic nukeops population scaling more like secret
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Tweak

#9323 adds poll ignore for magical antagonists
  code/_globalvars/lists/poll_ignore.dm
  code/modules/antagonists/_common/antag_spawner.dm
Labels: Feature

#9868 Fixes superlube waterflower.
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Fix

#9865 Glitchfix. Prevents storage bags from changing the order of their numbered contents when items are removed.
  code/__HELPERS/cmp.dm
  code/datums/components/storage/storage.dm
Labels: Fix

#9866 Adds strange seeds as a buyable traitor botanist item.
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature

#9880 Makes sure every dynamic-triggered event isn't random on dynamic
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  code/modules/events/major_dust.dm
  code/modules/events/meteor_wave.dm
  code/modules/events/processor_overload.dm
Labels: Fix

#9889 Fixes gold toolbox inhand sprite having the wrong name
  code/game/objects/items/storage/toolbox.dm
Labels: Fix

#9871 Sound rework: Gunsounds edition
  sound/weapons/Gunshot.ogg
  sound/weapons/Gunshot2.ogg
  sound/weapons/Gunshot3.ogg
  sound/weapons/Gunshot4.ogg
  sound/weapons/Gunshot_silenced.ogg
  sound/weapons/Gunshot_smg.ogg
  sound/weapons/IonRifle.ogg
  sound/weapons/Laser.ogg
  sound/weapons/LaserSlugv3.ogg
  sound/weapons/Taser.ogg
  sound/weapons/laser3.ogg
  sound/weapons/lasercannonfire.ogg
  sound/weapons/magpistol.ogg
  sound/weapons/magrifle.ogg
  sound/weapons/pulse.ogg
  sound/weapons/pulse2.ogg
  sound/weapons/pulse3.ogg
  sound/weapons/smg_empty_alarm.ogg
  sound/weapons/taser2.ogg
Labels: Removal, Sound

#9823 Adds HoS, HoP, CE, CMO, QM, RD, chemistry, genetics, virology, robotics, janitor and cosmic winter coats - Try 2
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/crafting/recipes/recipes_clothing.dm
  code/modules/mining/mine_items.dm
  code/modules/vending/wardrobes.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/icons/mob/suit_digi.dmi
Labels: Feature, Sprites

#9518 Ports "You can now click on objects and mobs below flaps and signs"
  code/controllers/subsystem/vis_overlays.dm
  code/game/objects/structures/holosign.dm
  code/game/objects/structures/plasticflaps.dm
Labels: Fix

#9530 Touching up job outfits equip procs, little PDA fix.
  code/datums/outfit.dm
  code/game/gamemodes/clown_ops/clown_ops.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/antagonists/abductor/equipment/abduction_outfits.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/preferences.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/event.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/outfits/vr.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/ninja/outfit.dm
  code/modules/ruins/lavaland_ruin_code.dm
Labels: Fix, Tweak

#9887 Martial arts pacifism fixes and boxing buff, more ported pacifist fixes.
  code/datums/martial.dm
  code/datums/martial/boxing.dm
  code/datums/martial/cqc.dm
  code/datums/martial/krav_maga.dm
  code/datums/martial/psychotic_brawl.dm
  code/datums/martial/sleeping_carp.dm
  code/datums/martial/wrestling.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living_defense.dm
Labels: Balance/Rebalance, Fix

#9908 Little APC overlays tweak. Removing rogue pixels from the energy gun.
  icons/obj/guns/energy.dmi
  icons/obj/power.dmi
Labels: Fix, Sprites

#9886 chem dispenser beakers and bikehorn fixes.
  code/game/objects/items/clown_items.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Fix

#9896 Fixing cyborg camera interaction for real
  code/game/machinery/computer/camera.dm
Labels: Fix

#9898 Dreamchecker compatibility changes, part 3.
  code/modules/client/verbs/suicide.dm
  code/modules/events/_event.dm
  code/modules/mob/dead/observer/observer.dm
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
Labels: Fix

#9864 Able to use Legion Cores in-hand
  code/modules/mining/equipment/regenerative_core.dm
Labels: Feature

#9749 What do you mean I cant hold the armory on my back? -BOH nerf
  code/__DEFINES/inventory.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/weaponry.dm
Labels: Awaiting further discussion/approval, Balance/Rebalance, Do Not Merge

#9909 Anthromorphic Insect Revert
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  icons/mob/wings.dmi
  modular_citadel/icons/mob/mutant_bodyparts.dmi
Labels: Balance/Rebalance, Removal, Revert, Sprites

#9881 Allows extended voting on dynamic if recent rounds too chaotic
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/vote.dm
Labels: Feature

#9891 [DYNAMIC] Reverted making latejoiners count for roundstart rulesets
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Revert, Tweak

#9874 Honkbot slip and slide fun ride.
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/honkbot.dm
Labels: Feature

#9907 [DYNAMIC] Prevents VR mobs from being midround antags.
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Fix

#9902 [TESTMERGE READY] Ported a bunch of tg hydroponics content.
  code/__DEFINES/machines.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/modules/hydroponics/gene_modder.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/cannabis.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/hydroponics/grown/cocoa_vanilla.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/grown/melon.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/mushrooms.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/hydroponics/seeds.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/growing_flowers.dmi
  icons/obj/hydroponics/growing_fruits.dmi
  icons/obj/hydroponics/growing_mushrooms.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
Labels: Feature, Sprites

#9922 Ports new Brain Traumas from /tg/. Does not include the shitty creeper antag or Wizard Traumas, i'm porting wizard traumas later. Also adds the Desynchronizer and changes the way some heaRing args are handled.
  code/__DEFINES/components.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/poll_ignore.dm
  code/_onclick/hud/alert.dm
  code/datums/brain_damage/brain_trauma.dm
  code/datums/brain_damage/hypnosis.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/mild.dm
  code/datums/brain_damage/phobia.dm
  code/datums/brain_damage/severe.dm
  code/datums/brain_damage/special.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/components/nanites.dm
  code/datums/components/stationloving.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/neutral.dm
  code/datums/status_effects/status_effect.dm
  code/game/atoms.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/devices/desynchronizer.dm
  code/game/say.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/client/client_colour.dm
  code/modules/mob/living/carbon/say.dm
  code/modules/mob/living/emote.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/screen_alert.dmi
  icons/obj/device.dmi
  tgstation.dme
Labels: Feature, Sprites, Tweak

#9942 [Hotfix] Fixed the reagents in the new plants.
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/cocoa_vanilla.dm
  code/modules/hydroponics/grown/flowers.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/mushrooms.dm
  code/modules/hydroponics/plant_genes.dm
Labels: Fix

#9920 Ports a bunch of VG's AI sprites
  code/_globalvars/lists/flavor_misc.dm
  code/modules/mob/living/silicon/ai/ai.dm
  icons/mob/AI.dmi
Labels: Sprites

#9268 [READY] [Please merge me] Fermichem tweaks: Purity, Astral, RNG, MK, SMilk, SDGF, furranium, hatmium, eigen, nanite.
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/hydroponics/grown/cotton.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/astral.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/surgery/organs/vocal_cords.dm
  modular_citadel/code/datums/status_effects/chems.dm
  modular_citadel/code/modules/arousal/genitals.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/client/preferences.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/astrogen.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/eigentstasium.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
  modular_citadel/code/modules/reagents/objects/clothes.dm
Labels: Config Update, Fix, Needs Review, Sound, Sprites, Tweak, UI

#9882 [READY] Allows addition of reagents to sleepers for injection and detection of failed organs (minor GUI tweak.)
  code/game/machinery/Sleeper.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/reagents/reagent_containers/sleeper_buffer.dm
  icons/obj/chemical.dmi
  tgstation.dme
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/components/section.styl
  tgui/src/interfaces/sleeper.ract
Labels: Needs Review, Refactor, Sprites, UI

#9906 [Ready] Ports/Adds new berets but I don't break the branch somehow
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Needs Review, Sprites

#9943 Ports AI console focus loss fix and fixes an error in my trimline code
  code/game/machinery/computer/communications.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
Labels: Fix

#9948 Morgues no longer go "ammunition depleted"
  code/game/objects/structures/morgue.dm
  sound/machines/beeping_alarm.ogg
Labels: Fix, Sound

#9959 patching some combat mode edge cases and issues.
  code/datums/mind.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/death.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/mob.dm
  modular_citadel/code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#9957 fixes missing hypereutactic left inhand sprites.
  icons/mob/inhands/64x64_lefthand.dmi
Labels: Fix, Sprites

#9693 Unmodularize phantom thief glasses, missing durathread headwear sprites and space-nam clothing.
  code/modules/clothing/glasses/phantomthief.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/code/modules/clothing/head/head.dm
  modular_citadel/code/modules/clothing/suits/suits.dm
  modular_citadel/icons/mob/clothing/space_nam.dmi
  modular_citadel/icons/obj/clothing/hats.dmi
  modular_citadel/icons/obj/clothing/space_nam.dmi
  tgstation.dme
Labels: Sprites

#9969 revert knocking people's hats off
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/spacesuits/_spacesuits.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/hydroponics/beekeeping/beekeeper_suit.dm
Labels: Revert, Tweak

#9966 Ports elements: Lightweight shared/global components.
  code/__DEFINES/components.dm
  code/controllers/subsystem/dcs.dm
  code/controllers/subsystem/garbage.dm
  code/datums/components/earhealing.dm
  code/datums/components/mood.dm
  code/datums/components/virtual_reality.dm
  code/datums/elements/_element.dm
  code/datums/elements/cleaning.dm
  code/datums/elements/earhealing.dm
  code/modules/clothing/ears/_ears.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/vehicles/pimpin_ride.dm
  tgstation.dme
Labels: Fix

#9967 Ports "Plasmamen get plasma in their box"
  code/game/objects/items/storage/boxes.dm
Labels: Feature

#9965 Adds Fun to the Kitchen's stacking skills
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
Labels: Tweak

#9962 Fixes limbs' set_disabled.
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#9960 Ports custom reagent icecreams.
  code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
  icons/obj/kitchen.dmi
Labels: Feature, Sprites, Tweak

#9996 Fixes tinfoil hats giving random traumas.
  code/controllers/subsystem/traumas.dm
  code/modules/clothing/head/misc_special.dm
Labels: Fix

#9964 Fixes Codewords not changing color and MkUltra enthrall not having the proper hearing_args
  code/modules/antagonists/traitor/datum_traitor.dm
  modular_citadel/code/datums/status_effects/chems.dm
Labels: Fix

#10015 [SPEEDMERGE] Fixes traitor unassigning incorrectly and spamming
  code/modules/antagonists/traitor/datum_traitor.dm
Labels: Fix
