Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-07, with the labels that each got.

#8813 Bedsheet for Donator [T2]
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Donor Fluff

#8793 Fixes PDA skin preference not saving up.
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix, Tweak

#8797 Emitters can be rotated instead of only flipped
  code/modules/power/singularity/emitter.dm
Labels: Fix

#8799 Adds Promiscuous Organs crate to cargo
  code/_globalvars/lists/maintenance_loot.dm
  code/modules/cargo/packs.dm
  code/modules/surgery/organs/autosurgeon.dm
Labels: Feature

#8781 Adds plasteel to medical and security techfabs.
  code/modules/research/designs/smelting_designs.dm
Labels: Tweak

#8783 Fixing some emergency pod storage refactor fuck ups.
  code/datums/components/storage/concrete/emergency.dm
  code/datums/components/storage/storage.dm
Labels: Fix, Refactor

#8801 Updated miasma canister sprites
  icons/obj/atmos.dmi
Labels: Sprites, Tweak

#8798 Action button swapping
  code/_onclick/hud/action_button.dm
Labels: Feature

#8776 Porting in donut fixes, beepsky smash and Neurotoxin reworks.
  code/__DEFINES/traits.dm
  code/controllers/subsystem/traumas.dm
  code/datums/brain_damage/brain_trauma.dm
  code/datums/brain_damage/phobia.dm
  code/datums/brain_damage/special.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/civilian_chaplain.dm
  code/modules/jobs/job_types/job.dm
  code/modules/jobs/job_types/security.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Balance/Rebalance, Code Improvement, Fix

#8775 crew monitor indexing pet peeve.
  code/game/machinery/computer/crew.dm
Labels: Tweak

#8773 Podweak now have all customization options.
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
Labels: Tweak

#8778 Porting in 18 new drinks from the TGstation, plus tweaking and fixes.
  code/__DEFINES/misc.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/turfs/turf.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/hydroponics/grown/root.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/vending/boozeomat.dm
  code/modules/vending/cola.dm
  code/modules/vending/drinnerware.dm
  icons/effects/blood.dmi
  icons/obj/drinks.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
Labels: Feature, Fix, Sprites, Tweak

#8769 Alt now tempoarily disables strafing for mechs.
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
Labels: Feature

#8768 New sprites for the some pda cartridges.
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/PDA/virus_cart.dm
  icons/obj/pda.dmi
Labels: Sprites

#8815 adds a 🅱
  icons/emoji.dmi
Labels: Sprites

#8790 Tweaks dogborg sleeper insert/resist values, and adds the ability to pry open dogborg sleepers via crowbar
  code/game/objects/items/devices/dogborg_sleeper.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Feature, Tweak

#8663 Peanuts, peanut butter, and PB&J sandwiches.
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  code/modules/hydroponics/grown/peanuts.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/vending/megaseed.dm
  icons/obj/food/burgerbread.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  icons/obj/hydroponics/growing_vegetables.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  tgstation.dme
Labels: Feature, Sprites

#8794 Fixes the uplink category indexing.
  code/datums/martial/krav_maga.dm
  code/modules/uplink/uplink_items.dm
Labels: Fix

#8805 fixes some displays being on the ground
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#8632 Ports traitor codeword highlighting
  code/controllers/subsystem/ticker.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mob/living/carbon/say.dm
  code/modules/mob/living/say.dm
Labels: Feature

#8808 Yellow Outfit - Donator [T2]
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Donor Fluff

#8827 Ports "Makes looping sounds use client time"
  code/controllers/subsystem/timer.dm
  code/datums/looping_sounds/_looping_sound.dm
  tgstation.dme
Labels: Fix

#8824 Ports "Fixes damp rag not smothering people"
  code/modules/reagents/reagent_containers/glass.dm
Labels: Fix

#8826 Ports "Adds safer helper for alt-click turf listing"
  code/_onclick/click.dm
  code/_onclick/observer.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
Labels: Code Improvement, Fix, Tweak

#8825 Ports "Fixes default supplypods exploding their contents" & co.
  code/datums/explosion.dm
  code/game/atoms.dm
  code/modules/cargo/supplypod.dm
  code/modules/events/immovable_rod.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Fix

#8800 Adds click interactions to atmos heater/freezer
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Labels: Feature

#8802 Ports in RPGs for nuke ops, failsafe uplink codes, some carp plushie exploit fix etc.
  code/datums/components/uplink.dm
  code/datums/mind.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/items/dehy_carp.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/virus_cart.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/briefcase.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/ammunition/caseless/rocket.dm
  code/modules/projectiles/boxes_magazines/internal/grenade.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special/rocket.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/spells/spell_types/rightandwrong.dm
  code/modules/surgery/organs/augments_chest.dm
  code/modules/uplink/uplink_devices.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/ammo.dmi
  icons/obj/projectiles.dmi
  sound/vehicles/rocketlaunch.ogg
Labels: Feature, Grammar and Formatting, Sound, Sprites

#8819 All maps in rotation now have a public autolathe.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#8834 Fixes up space ninja's energy net.
  code/modules/ninja/suit/n_suit_verbs/energy_net_nets.dm
  code/modules/ninja/suit/n_suit_verbs/ninja_net.dm
Labels: Fix

#8835 normalises hop and cap's berets to not hide hair
  code/modules/clothing/head/jobs.dm
Labels: Tweak

#8841 Adding one pAI to the wizard shuttle and ERT prep rooms.
  _maps/map_files/generic/CentCom.dmm
Labels: Map Edit

#8828 Ports "Makes ventcrawl much easier on the client"
  code/modules/mob/living/ventcrawling.dm
Labels: Fix

#8821 Ports "Updates corgi & parrot inventory panels to the same formatting as other mobs"
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/pet.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Fix, Tweak

#8823 Ports "fixes spontaneous appendicitis picking incompatible biotypes"
  code/modules/events/spontaneous_appendicitis.dm
Labels: Fix

#8820 Ports "Add cancel button to assault pod destination selector"
  code/modules/shuttle/assault_pod.dm
Labels: Fix

#8837 Revert "Adds a can_inject check to IV Drips"
  code/game/machinery/iv_drip.dm
Labels: Revert

#8765 Merging the end-of-shift and its shuttle autocall announcements into one.
  code/modules/shuttle/emergency.dm
  modular_citadel/code/controllers/subsystem/shuttle.dm
Labels: Tweak

#8740 ports "More variety for dorms bedsheets" + 3 new bed sheets.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/pirate_default.dmm
  _maps/shuttles/ruin_pirate_cutter.dmm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/structures/bedsheet_bin.dm
  icons/mob/neck.dmi
  icons/obj/bedsheets.dmi
Labels: Feature, Map Edit, Sprites, Test Merge Candidate, Tweak

#8750 Fixes trauma healing nanites.
  code/modules/research/nanites/nanite_programs/healing.dm
Labels: Fix

#8704 [s] RCD logging
  code/__DEFINES/logging.dm
  code/game/objects/items/RCD.dm
  code/modules/admin/admin_investigate.dm
Labels: Exploit, Priority: High

#8709 Ports "Fixes every issue in the slimes milestone. #44450"
  code/__HELPERS/unsorted.dm
  code/modules/food_and_drinks/food.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/research/xenobiology/crossbreeding/chilling.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/surgery/organs/lungs.dm
Labels: Fix

#8844 Fixes rocket launchers, buffing their accuracy etc.
  code/game/machinery/computer/arcade/minesweeper.dm
  code/modules/projectiles/ammunition/caseless/rocket.dm
  code/modules/projectiles/boxes_magazines/internal/grenade.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/projectile/special/rocket.dm
  modular_citadel/code/modules/projectiles/gun.dm
Labels: Balance/Rebalance, Fix, Tweak

#8858 Makes unholy water not do toxin damage to fellow slime cultys
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#8761 [Ready] Tweaks shields
  code/game/objects/items/shields.dm
  icons/mob/inhands/equipment/shields_lefthand.dmi
  icons/mob/inhands/equipment/shields_righthand.dmi
Labels: Fix, Needs Review, Sprites, Tweak

#8852 Removes a plush representing the character of an underage player.
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
  modular_citadel/code/modules/admin/chat_commands.dm
Labels: Removal, Sprites

#8843 Makes combat boots look T A C T I C O O L
  code/modules/clothing/shoes/miscellaneous.dm
  icons/obj/clothing/shoes.dmi
Labels: Sprites

#8872 Janitors are no longer diabetic - nerfs mop stamina usage to be in-line with how much effort mopping takes IRL
  code/game/objects/items/mop.dm
Labels: Balance/Rebalance

#8846 Rubber toolboxes.
  code/__HELPERS/unsorted.dm
  code/datums/components/bouncy.dm
  code/game/objects/items/his_grace.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/toys.dm
  icons/mob/inhands/equipment/toolbox_lefthand.dmi
  icons/mob/inhands/equipment/toolbox_righthand.dmi
  icons/obj/storage.dmi
  tgstation.dme
Labels: Feature, Sprites

#8854 Stamina damage melee weaponry fixes.
  code/_onclick/item_attack.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/grille.dm
Labels: Fix

#8847 Porting in two bar signs.
  code/game/objects/structures/barsigns.dm
  icons/obj/barsigns.dmi
Labels: Feature, Sprites

#8842 allows pais to activate holoform while in a pai connector
  code/modules/mob/living/silicon/pai/pai_shell.dm
Labels: Fix

#8870 toning down many species' standard female chest.
  icons/mob/human_parts.dmi
  icons/mob/human_parts_greyscale.dmi
  modular_citadel/icons/mob/mutant_bodyparts.dmi
Labels: Sprites, Tweak

#8860 Zelus oil - CWC gear
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/antagonists/clockcult/clock_items/clockwork_armor.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#8812 Using the wrong tool during surgery won't hit the patient with it. Also stops medical borgs from attacking with surgical tools outside of harm intent.
  code/__DEFINES/obj_flags.dm
  code/modules/surgery/surgery.dm
  code/modules/surgery/tools.dm
Labels: Feature

#8734 Sort of porting "Changes the type pathing of some "random" items"
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/clothing/gloves/color.dm
Labels: Code Improvement, Map Edit

#8752 Slimepeople can now morph the shape and size of their genitalia.
  modular_citadel/code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Feature, Fix

#8885 Ports "Renames SSsqueak to SSminor_mapping"
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/minor_mapping.dm
  code/modules/events/mice_migration.dm
  tgstation.dme
Labels: Code Improvement

#8874 Ports the Chem Master choose your pill PR plus post-improvements
  code/game/objects/items/RPD.dm
  code/modules/client/asset_cache.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/tgui/external.dm
  code/modules/tgui/tgui.dm
  icons/UI_Icons/Pills/pill1.png
  icons/UI_Icons/Pills/pill10.png
  icons/UI_Icons/Pills/pill11.png
  icons/UI_Icons/Pills/pill12.png
  icons/UI_Icons/Pills/pill13.png
  icons/UI_Icons/Pills/pill14.png
  icons/UI_Icons/Pills/pill15.png
  icons/UI_Icons/Pills/pill16.png
  icons/UI_Icons/Pills/pill17.png
  icons/UI_Icons/Pills/pill18.png
  icons/UI_Icons/Pills/pill19.png
  icons/UI_Icons/Pills/pill2.png
  icons/UI_Icons/Pills/pill20.png
  icons/UI_Icons/Pills/pill21.png
  icons/UI_Icons/Pills/pill22.png
  icons/UI_Icons/Pills/pill3.png
  icons/UI_Icons/Pills/pill4.png
  icons/UI_Icons/Pills/pill5.png
  icons/UI_Icons/Pills/pill6.png
  icons/UI_Icons/Pills/pill7.png
  icons/UI_Icons/Pills/pill8.png
  icons/UI_Icons/Pills/pill9.png
  icons/UI_Icons/minesweeper_tiles/eight.png
  icons/UI_Icons/minesweeper_tiles/empty.png
  icons/UI_Icons/minesweeper_tiles/five.png
  icons/UI_Icons/minesweeper_tiles/flag.png
  icons/UI_Icons/minesweeper_tiles/four.png
  icons/UI_Icons/minesweeper_tiles/hidden.png
  icons/UI_Icons/minesweeper_tiles/mine.png
  icons/UI_Icons/minesweeper_tiles/minehit.png
  icons/UI_Icons/minesweeper_tiles/one.png
  icons/UI_Icons/minesweeper_tiles/seven.png
  icons/UI_Icons/minesweeper_tiles/six.png
  icons/UI_Icons/minesweeper_tiles/three.png
  icons/UI_Icons/minesweeper_tiles/two.png
  strings/redpill.json
  tgui/assets/tgui.js
  tgui/src/interfaces/chem_master.ract
  tgui/tgui.html
Labels: Feature, Sprites, UI

#8883 Hexacrocin overdose no longer forces climax
  modular_citadel/code/modules/reagents/reagents/cit_reagents.dm
Labels: Tweak

#8884 Ports "About that beer I owed ya. Adds blueshirt items to sectech and defines them better."
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/vending/security.dm
  modular_citadel/code/game/machinery/vending.dm
Labels: Feature

#8873 Ports "Fixes clockwork armor armor"
  code/modules/antagonists/clockcult/clock_items/clockwork_armor.dm
Labels: Fix

#8857 Refactoring underwear to allow custom color preferences.
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/objects/structures/dresser.dm
  code/modules/VR/vr_sleeper.dm
  code/modules/admin/create_mob.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/socks.dm
  code/modules/mob/dead/new_player/sprite_accessories/undershirt.dm
  code/modules/mob/dead/new_player/sprite_accessories/underwear.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/underwear.dmi
Labels: Feature, Refactor, Removal, Sprites

#8887 Gang victory news report and last words for discord bot
  code/__DEFINES/misc.dm
  code/controllers/subsystem/ticker.dm
  modular_citadel/code/game/gamemodes/gangs/dominator.dm
  modular_citadel/code/game/gamemodes/gangs/gang.dm
Labels: Feature, Fix

#8785 Makes Clowns and HonkMother Chaplins smile!
  code/game/gamemodes/clown_ops/bananium_bomb.dm
  code/game/gamemodes/clown_ops/clown_ops.dm
  code/game/objects/items/storage/book.dm
  code/modules/jobs/job_types/civilian.dm
Labels: Feature

#7544 Nerfs nanite pools
  code/datums/components/nanites.dm
Labels: Awaiting further discussion/approval, Balance/Rebalance

#8724 Brakes up Blue space Rnd tech nodes
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Feature

#8880 Makes Air Alarms Green
  code/modules/atmospherics/machinery/airalarm.dm
  icons/obj/monitors.dmi
Labels: Sprites, Tweak

#8796 Russian Paratrooper Jumper Uniform fix
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Fix

#8725 Adds more bronze tools
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/crafting/recipes.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tools.dm
Labels: Feature

#8877 REMOVE #C8A5DC. COLOR STRONG.
  code/game/objects/effects/decals/cleanable/misc.dm
  code/modules/reagents/chemistry/reagents/blob_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#8693 Ports "clothes burning only spam You of Your clothes"
  code/modules/clothing/clothing.dm
Labels: Fix

#8882 Adds discount plushies and a way to get random plushies at shift start
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
  modular_citadel/code/modules/client/loadout/backpack.dm
Labels: Sprites

#8881 Fixing a reagent ID typo.
  code/modules/food_and_drinks/food/snacks_pie.dm
Labels: Fix

#8867 Nerfs chain detonation (removes dev radius)
  code/modules/research/nanites/nanite_programs/weapon.dm
Labels: Removal

#8866 Fixes nanites getting instant nuked by EMPs and shocks and removes the random drain in favor of a scaled drain
  code/datums/components/nanites.dm
Labels: Balance/Rebalance, Fix, Removal

#8915 Gives cult conversions an alert popup and four extra seconds wait time.
  code/modules/antagonists/cult/runes.dm
Labels: Feature, Grammar and Formatting

#8415 Adds a sprint buffer - 35 tiles, regen 2 tiles/second (always active), 0.3 stamcost per tile if empty (as old) directly applied to staminaloss rather than stamina action buffer (unlike old)
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/human.dm
  modular_citadel/code/_onclick/hud/screen_objects.dm
  modular_citadel/code/_onclick/hud/sprint.dm
  modular_citadel/code/modules/mob/living/carbon/damage_procs.dm
  modular_citadel/code/modules/mob/living/carbon/human/human_movement.dm
  modular_citadel/code/modules/mob/living/carbon/life.dm
  modular_citadel/code/modules/mob/living/damage_procs.dm
  modular_citadel/code/modules/mob/living/living.dm
  tgstation.dme
Labels: Currently Testmerged, Feature, Tweak/Balance

#8910 Ports "Removes some getflaticon calls from things that don't draw browser interfaces"
  code/modules/photography/photos/frame.dm
  code/modules/surgery/organs/augments_arms.dm
Labels: Removal

#8925 Makes the autolathe shock wire actually shock you
  code/datums/wires/autolathe.dm
Labels: Fix

#8906 Sweaters now cover the groins too.
  modular_citadel/code/modules/clothing/under/turtlenecks.dm
Labels: Tweak

#8922 Gamemode Voting Results are now displayed at the end of round screen
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/vote.dm
Labels: Feature

#8898 Batch check injuries
  code/modules/mob/living/carbon/human/human_defense.dm
  icons/obj/clothing/belts.dm
Labels: Sprites, Tweak

#8917 Fixes warp whistles
  code/modules/antagonists/wizard/equipment/artefact.dm
Labels: Fix

#8829 Changeling Transformation Sting (transforming others) is now temporary, just like this server's love for transformation fetishes
  code/game/objects/items/devices/scanners.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Balance/Rebalance, Code Improvement

#8903 Re-words brass flasks to not be wrong
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
Labels: PRB: Reset

#8920 Towels.
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/bus.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomZLevels/VR/syndicate_trainer.dmm
  _maps/RandomZLevels/beach.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/obj_flags.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/artstuff.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/watercloset.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/gloves/_gloves.dm
  code/modules/crafting/recipes.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_defines.dm
  code/modules/reagents/reagent_containers/rags.dm
  code/modules/surgery/helpers.dm
  code/modules/vending/wardrobes.dm
  icons/mob/belt.dmi
  icons/mob/head.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/items_and_weapons.dmi
  sound/items/towelwhip.ogg
  sound/items/towelwipe.ogg
  tgstation.dme
Labels: Feature, Map Edit, Sound, Sprites

#8926 Secbats
  code/game/objects/items/storage/boxes.dm
  code/modules/cargo/packs.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
  code/modules/vending/security.dm
  icons/mob/animal.dmi
Labels: Feature, Sprites

#8909 Fixes named arg Knockdown calls.
  code/datums/martial/krav_maga.dm
  code/modules/mob/living/carbon/human/status_procs.dm
  code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
  code/modules/mob/living/status_procs.dm
  modular_citadel/code/modules/mob/living/status_procs.dm
  tgstation.dme
Labels: Fix

#8940 Borg Plush - Donator
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Donor Fluff

#8934 Removes a Rando plushies from loadout and adds in a few more items
  modular_citadel/code/modules/client/loadout/backpack.dm
Labels: Feature, Removal

#8939 Fixing towels and improving them.
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/washing_machine.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/reagents/reagent_containers/rags.dm
  icons/obj/items_and_weapons.dmi
Labels: Feature, Fix, Map Edit, Sprites, Tweak

#8949 Removes armor from all star treck outfits/suits
  modular_citadel/code/modules/clothing/under/trek_under.dm
Labels: Fix, Removal

#8933 Mild Cloning Nerf
  code/game/machinery/cloning.dm
Labels: Balance/Rebalance

#8929 Fixing Shredder guns not accepting standard flechette mags, and magpistol mag sprites.
  modular_citadel/code/modules/projectiles/guns/ballistic/flechette.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/magweapon.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/magweapon_energy.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/rifles.dm
  modular_citadel/icons/obj/guns/cit_guns.dmi
  tgstation.dme
Labels: Fix

#8931 3 New cargocrates - Security EVA jetpacks, woodstock shotguns, and russian clothing + guns (that totally is balanced)
  code/modules/cargo/packs.dm
Labels: Feature

#8928 Reverts a commit that reverted a fix.
  code/game/machinery/computer/arcade/minesweeper.dm
  code/modules/projectiles/ammunition/caseless/rocket.dm
  code/modules/projectiles/boxes_magazines/internal/grenade.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/projectile/special/rocket.dm
  modular_citadel/code/modules/projectiles/gun.dm
Labels: Revert

#8952 Cloning console board memory
  code/game/machinery/computer/cloning.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
Labels: Feature

#8970 ports jumpskirts and jumpskirt prefs from teegeestation
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/job.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#8972 Port TG new NVGs sprites
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Sprites

#8969 chemmaster now spits out 60u hypovials
  code/modules/reagents/chemistry/machinery/chem_master.dm
  tgui/assets/tgui.js
  tgui/src/interfaces/chem_master.ract
Labels: UI

#8795 Buffs tracking beacon EMPs, and makes EMP damage temporarily disable mech equipment
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_control_console.dm
  code/game/mecha/mecha_defense.dm
  code/game/mecha/medical/medical.dm
  code/game/mecha/working/working.dm
  icons/mecha/mecha_mouse-disable.dmi
Labels: Balance/Rebalance, Sprites

#8979 Fixes CHECK_BITFIELD macro.
  code/__DEFINES/flags.dm
Labels: Fix

#8984 allows the captain sabre sheat to hold stunswords.
  code/game/objects/items/storage/belt.dm
  icons/mob/belt.dmi
  icons/obj/clothing/belts.dmi
Labels: Feature, Sprites

#8982 [s] ports "Fixes ore satchel exploits, various storage size circumventions."
  code/game/objects/items/storage/storage.dm
  code/modules/jobs/job_types/cargo_service.dm
Labels: Fix

#8976 Fixes combatmode disarm pushing people on inaccessible tables and more.
  code/modules/mob/living/carbon/human/human.dm
  modular_citadel/code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#8978 Removes stealth implant box integrity
  code/game/objects/items/implants/implant_stealth.dm
Labels: Balance/Rebalance, Removal

#8971 makes slimepeople like toxic food
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Tweak

#8974 Fixes the blood chiller's inhand sprite
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
Labels: Fix, Sprites

#8965 Ports "Security can access gulag equipment reclaimer #45298"
  code/game/machinery/gulag_item_reclaimer.dm
Labels: Fix

#8966 Gives RLD adaptive overlays, adds cable color to RCL sprites
  code/game/objects/items/RCD.dm
  code/game/objects/items/RCL.dm
  icons/obj/tools.dmi
Labels: Fix, Sprites

#8959 Ports "Anti-magic items now work properly in the suit storage slot #45333"
  code/__DEFINES/inventory.dm
Labels: Fix

#8964 Makes steal a few steal objectives better worded and role restricted better
  code/game/gamemodes/objective_items.dm
Labels: Balance/Rebalance, Grammar and Formatting

#8980 Fixes hypovials unable to dump liquids and chem master unable to dispense in pill bottles.
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Fix

#8985 fix trenchcloak having no icon on digi characters
  modular_citadel/icons/mob/suit_digi.dmi
Labels: Fix

#8950 Ports "Fixes slime lungs runtime. #45057"
  code/modules/surgery/organs/lungs.dm
Labels: Fix

#8956 Updates inventory plates
  icons/mob/screen_gen.dmi
Labels: Sprites, Tweak

#8945 Pubby disposal and lawyer spawner fixes.
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#8921 Updates RuntimeStation bugtesting map to be more usefull
  _maps/map_files/debug/runtimestation.dmm
Labels: Administration, Map Edit
