Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2019-02, with the labels that each got.

#7976 Adds a new security level: Amber
  code/__DEFINES/misc.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/shuttle.dm
  code/game/machinery/computer/communications.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/security_levels/security_levels.dm
  code/modules/shuttle/emergency.dm
  config/game_options.txt
  icons/obj/monitors.dmi
Labels: Config Update, Feature, Sprites, Tweak

#7978 Pretty late join menu memes
  code/modules/mob/dead/new_player/new_player.dm
Labels: Feature

#7951 Fixes invisible limb sprites.
  code/modules/surgery/bodyparts/bodyparts.dm
  modular_citadel/code/modules/mob/living/carbon/human/species.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/ipc.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  modular_citadel/icons/mob/mutant_bodyparts.dmi
Labels: Code Improvement, Fix, Removal, Sprites

#7968 Fixing Star Trek DS9 uniforms
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/icons/mob/clothing/trek_item_icon.dmi
  modular_citadel/icons/mob/clothing/trek_mob_icon.dmi
  modular_citadel/icons/mob/uniform_digi.dmi
  modular_citadel/icons/obj/clothing/trek_item_icon.dmi
Labels: Sprites

#7943 [Ready] Adds new huds that help correct vision.
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/glasses/engine_goggles.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Needs Review

#7957 [Ready] More useful tips.
  strings/tips.txt
Labels: Needs Review

#7953 [Ready] Gives large compressed matter its own name and desc, Also ports Tg #41256
  code/game/objects/items/RCD.dm
Labels: Needs Review

#7969 [Ready] Fixes price of Paperwork and makes the not have 2 spare pens
  code/modules/cargo/exports/manifest.dm
  code/modules/cargo/packs.dm
Labels: Needs Review

#7970 [Honk] [Ready] Adds a ton of new clown names
  strings/names/clown.txt
Labels: Needs Review

#7971 [Ready] Makes small chocolate have aphro in it
  code/modules/food_and_drinks/food/snacks_other.dm
Labels: Needs Review

#7979 Adds two crusader variants for chaplain
  code/game/objects/items/holy_weapons.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/icons/mob/suit_digi.dmi
Labels: Sprites

#7973 reduces stamloss for shotgun pumping from 5 to 2
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Balance/Rebalance

#7977 Low plasma concentration does not damage anymore
  code/modules/surgery/organs/lungs.dm
Labels: Balance/Rebalance, Fix

#7960 [Ready] Janitor buff, they can now get a spray bottle of drying agent
  code/modules/cargo/packs.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Needs Review

#7938 [Ready] Makes Adv surgery tools more common around the station!
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/cargo/packs.dm
  code/modules/uplink/uplink_items.dm
Labels: Needs Review

#7983 ISINRANGE_EX fix
  code/__DEFINES/maths.dm
Labels: Code Improvement

#7981 Gives plushes a seperate cargo crate, and makes them rarer rewards from arcades.
  code/game/machinery/computer/arcade.dm
  code/modules/cargo/packs.dm
Labels: Tweak

#7982 Fixes clockcult to be actually playable on citadel.
  code/datums/status_effects/buffs.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/modules/antagonists/clockcult/clock_helpers/slab_abilities.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
Labels: Balance/Rebalance, Feature, Tweak

#7994 QOL for pickpocketing - Stripping items off of someone will now place them in your hands if possible
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Tweak

#7995 Gives combat mode examine text along with a visible message on activation
  code/modules/mob/living/carbon/examine.dm
  modular_citadel/code/modules/mob/living/carbon/carbon.dm
Labels: Feature

#7996 Knockdowns will now force people to be dismounted from ridden vehicles
  modular_citadel/code/datums/status_effects/debuffs.dm
Labels: Balance/Rebalance

#7997 Fancier throws, bullet casings, and more
  code/game/objects/items.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/mob/inventory.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/reagents/reagent_containers.dm
Labels: Feature

#8006 Adds a modified ckey-locked hairstyle for Fractious
  code/modules/mob/dead/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#7993 Cyborg upgrades rework v01
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_citadel/code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature, Tweak

#8022 Plushtide 2: Electric Boogaloo
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/plushes.dm
  code/modules/cargo/packs.dm
  icons/obj/plushes.dmi
  modular_citadel/sound/voice/hiss.ogg
  modular_citadel/sound/voice/merp.ogg
Labels: Sprites

#8028 FUCK (Speedmerge plz)
  icons/obj/plushes.dmi
Labels: Sprites

#8001 Revert "Adds realism to pleasure" - "Kev people are two hitting each other with sex circuits"
  modular_citadel/code/modules/arousal/arousal.dm
Labels: Revert, Testmerge only

#7955 [Ready] More cargo bounties.
  code/modules/cargo/bounties/engineering.dm
  code/modules/cargo/bounties/medical.dm
  code/modules/cargo/bounties/mining.dm
  code/modules/cargo/bounties/science.dm
  code/modules/cargo/bounties/security.dm
Labels: Needs Review

#7999 Clockwork kindle stun now respects the owner's remaining health
  code/datums/status_effects/debuffs.dm
  code/modules/antagonists/clockcult/clock_helpers/slab_abilities.dm
Labels: Tweak

#7987 Character Creation Overhaul
  code/__DEFINES/DNA.dm
  code/__DEFINES/citadel_defines.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/_cit_helpers.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/mobs.dm
  code/datums/browser.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/status_procs.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/helpers.dm
  icons/mob/human_parts_greyscale.dmi
  interface/skin.dmf
  modular_citadel/code/init.dm
  modular_citadel/code/modules/client/preferences.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
  modular_citadel/code/modules/mob/living/carbon/human/species.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  modular_citadel/icons/mob/citadel_refs/mam_body_markings Matrixed Ref.dmi
  modular_citadel/icons/mob/mam_body_markings.dmi
  modular_citadel/icons/mob/mam_ears.dmi
  modular_citadel/icons/mob/mam_markings.dmi
  modular_citadel/icons/mob/mam_snouts.dmi
  modular_citadel/icons/mob/mam_tails OLD.dmi
  modular_citadel/icons/mob/mam_tails.dmi
  modular_citadel/icons/mob/mam_taur.dmi
  modular_citadel/icons/mob/markings_notmammals.dmi
  modular_citadel/icons/mob/mutant_bodyparts.dmi
  modular_citadel/interface/skin.dmf
  tools/HumanScissors/!README.txt
  tools/HumanScissors/CookieCutter.dmi
  tools/HumanScissors/HumanScissors.dm
  tools/HumanScissors/HumanScissors.dme
  tools/HumanScissors/SpritesToSnip.dmi
Labels: Currently Testmerged, Feature, Sprites, Tools, Tweak

#8021 fixes runtimes that occur when mobs without clients try to update their eyeblur
  code/modules/mob/status_procs.dm
Labels: Fix

#8008 Nerfs the effects of slime speed potions on vehicles by limiting the speed gain to sprinting speed
  code/modules/research/xenobiology/xenobiology.dm
Labels: Balance/Rebalance

#8025 Makes the temperature notification act realistically (and more responsive!)
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak

#8012 Fixes it being plausible to zoom guns that are in your pockets, on your back, in your suit slot, or anywhere else that isn't your hands
  code/modules/projectiles/gun.dm
Labels: Fix

#8011 Nerfs lings by making hivemind require one DNA point to obtain
  code/modules/antagonists/changeling/powers/hivemind.dm
  code/modules/antagonists/changeling/powers/linglink.dm
Labels: Balance/Rebalance, Code Improvement

#8023 Adds changeling blood tests (heat up blood samples to test if someone's a ling or not)
  code/game/sound.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/changeling_power.dm
  code/modules/antagonists/changeling/powers/biodegrade.dm
  code/modules/antagonists/changeling/powers/digitalcamo.dm
  code/modules/antagonists/changeling/powers/headcrab.dm
  code/modules/antagonists/changeling/powers/lesserform.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/changeling/powers/shriek.dm
  code/modules/antagonists/changeling/powers/spiders.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/mob/living/blood.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  sound/effects/lingbloodhiss.ogg
  sound/effects/lingreadapt.ogg
Labels: Feature, Sound

#8030 Enables AI Multicam in Config and Adds an Admin Verb
  code/controllers/configuration/entries/game_options.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/multicam.dm
Labels: Administration, Config Update

#8031 Expands shuttle transit borders from 8 tiles to 10 tiles
  code/__DEFINES/shuttles.dm
Labels: Tweak

#8033 fixes the bug where you can sometimes get permanently stuck sprinting while using the sprint hotkey
  modular_citadel/code/modules/keybindings/bindings_human.dm
  modular_citadel/code/modules/keybindings/bindings_robot.dm
  modular_citadel/code/modules/mob/living/carbon/human/human_movement.dm
  modular_citadel/code/modules/mob/living/silicon/robot/robot_movement.dm
Labels: Fix

#8034 makes it plausible to hear most sounds while inside of a VR sleeper (including messages)
  code/game/sound.dm
  code/modules/VR/vr_human.dm
  code/modules/VR/vr_sleeper.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Feature

#8010 Disables changeling team objectives (We always delete team objectives so this just automates our work for us)
  code/game/gamemodes/changeling/changeling.dm
  code/modules/antagonists/changeling/changeling.dm
Labels: Removal

#7933 [Ready]Adds 2 new quirks! Quick step and Light Sensitivity
  code/__DEFINES/traits.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/traits/good.dm
  code/datums/traits/negative.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Needs Review

#8009 Correctly removes the changeling brain test
  code/modules/mob/living/brain/brain_item.dm
Labels: Currently Testmerged, Removal

#7990 Making player requirement for some gamemodes slightly lower so that they actually appear in the game.
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: Tweak

#8047 fixes body_markings being assigned as a list when in reality its a string and everything uses it as a string
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#8039 [s] Fixes xenos being able to pick up and use literally any item in the game so long as they strip it off someone else first
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Fix

#8037 Tweaking some cyborg mounted energy guns.
  code/__DEFINES/combat.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/megabuster.dm
  code/modules/projectiles/guns/energy/mounted.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  modular_citadel/code/game/machinery/cryopod.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/handguns.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/magweapon.dm
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
  modular_citadel/code/modules/projectiles/guns/toys.dm
  modular_citadel/code/modules/vore/resizing/sizegun_vr.dm
Labels: Tweak

#8035 Adds the ability for characters to be nameless
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/job.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: Feature

#8032 Makes transit areas physically throw you out of the transit area instead of simply teleporting you
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/shuttle.dm
  code/game/turfs/space/transit.dm
  code/modules/mapping/space_management/space_reservation.dm
Labels: Feature, Tweak

#8024 Atomizes the med rework's blood effect changes (most things that make a blood effect will now make you actually lose blood) and makes the blood reagent act more like you'd expect
  code/_onclick/item_attack.dm
  code/game/machinery/doors/door.dm
  code/game/objects/structures/kitchen_spike.dm
  code/modules/detectivework/detective_work.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/bodyparts/dismemberment.dm
Labels: Feature, Tweak

#8057 Makes the PB more robust by allowing admins to let specific ckeys bypass the panic bunker
  code/_globalvars/lists/mobs.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client_procs.dm
Labels: Administration

#8043 Adds a "salty cream" donut.
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  icons/mob/inhands/misc/food_lefthand.dmi
  icons/mob/inhands/misc/food_righthand.dmi
  icons/obj/food/food.dmi
Labels: Feature, Sprites

#8044 Experimental fix to a currently unreproducable bug where you can become immune to stamloss
  code/modules/mob/living/carbon/life.dm
Labels: Fix

#8038 Makes the roundend notification in IRC a little more verbose
  code/__HELPERS/roundend.dm
Labels: Administration

#8042 Dog sprites
  modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
  modular_citadel/icons/mob/mam_markings.dmi
Labels: Feature

#8041 Fixes a mob's last word never actually being properly tracked
  code/modules/mob/living/say.dm
Labels: Fix
