Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-08, with the labels that each got.

#12966 CentCom Galactic Ban DB
  code/controllers/configuration/entries/general.dm
  code/datums/http.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  config/config.txt
  tgstation.dme
Labels: Config Update, Feature

#12979 Adds roboticist cartridge to the PDA vendor
  code/modules/vending/cartridge.dm
Labels: Feature

#12742 Clockwork Cult rework
  _maps/map_files/generic/City_of_Cogs.dmm
  code/__DEFINES/clockcult.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/clockwork_marauder.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/machinery/computer/camera_advanced.dm
  code/game/mecha/combat/neovgre.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/storage/belt.dm
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
  code/modules/antagonists/clockcult/clock_effects/spatial_gateway.dm
  code/modules/antagonists/clockcult/clock_items/clock_weapons/_call_weapon.dm
  code/modules/antagonists/clockcult/clock_items/clock_weapons/ratvarian_spear.dm
  code/modules/antagonists/clockcult/clock_items/clockwork_armor.dm
  code/modules/antagonists/clockcult/clock_items/clockwork_slab.dm
  code/modules/antagonists/clockcult/clock_items/integration_cog.dm
  code/modules/antagonists/clockcult/clock_mobs/clockwork_marauder.dm
  code/modules/antagonists/clockcult/clock_scripture.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_applications.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_cyborg.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_judgement.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_scripts.dm
  code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
  code/modules/antagonists/clockcult/clock_structures/clockwork_obelisk.dm
  code/modules/antagonists/clockcult/clock_structures/eminence_spire.dm
  code/modules/antagonists/clockcult/clock_structures/heralds_beacon.dm
  code/modules/antagonists/clockcult/clock_structures/prolonging_prism.dm
  code/modules/antagonists/clockcult/clock_structures/ratvar_the_clockwork_justicar.dm
  code/modules/power/apc.dm
  icons/mob/clockwork_mobs.dmi
  icons/obj/clockwork_objects.dmi
  icons/obj/tools.dmi
  sound/machines/clockcult/ratvar_scream.ogg
  sound/magic/abomscream.ogg
  sound/mecha/neostep1.ogg
  sound/mecha/neostep2.ogg
  sound/mecha/powerloader_step.ogg
  tgstation.dme
Labels: Feature, Map Edit, Removal, Sound, Sprites, Tweak

#12975 Changes to abductors spawntext
  code/modules/antagonists/abductor/abductor.dm
Labels: Tweak

#12939 Reflavors IAA, removes certain items from IAA uplinks, adds TC stealing functionality to uplinks
  code/datums/components/uplink.dm
  code/game/objects/items/granters.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/uplink/uplink_items/uplink_bundles.dm
  code/modules/uplink/uplink_items/uplink_dangerous.dm
  code/modules/uplink/uplink_items/uplink_explosives.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
  code/modules/uplink/uplink_items/uplink_stealth.dm
Labels: Removal

#12947 replica pod fix bounty
  code/modules/hydroponics/grown/replicapod.dm
  icons/obj/hydroponics/growing.dmi
Labels: Fix, Sprites

#12965 drastically lowers the damage-related benefits of combat mode
  code/__DEFINES/combat.dm
  code/_onclick/item_attack.dm
  code/datums/martial/_martial.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak

#12970 salt pr
  code/modules/antagonists/clockcult/clock_scriptures/scripture_applications.dm
Labels: Fix

#12980 Map Edits Three: The Mappening
  _maps/RandomRuins/LavaRuins/lavaland_surface_wizard.dmm
  _maps/RandomRuins/SpaceRuins/spacehermit.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix, Map Edit

#12976 Durathread Reinforcement Kits
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/game/objects/items/armor_kits.dm
  icons/obj/clothing/reinf_kits.dmi
  tgstation.dme
Labels: Feature, Sprites

#12983 fixes nukeops timer being from server start instead of roundstart which gives them 5 free minutes am i salty maybe just a little (no i'm not but we should fix this anyways)
  code/modules/shuttle/syndicate.dm
Labels: Tweak

#12999 Removes clockwork guardian's projectile deflection. OOPS!
  code/modules/antagonists/clockcult/clock_mobs/clockwork_marauder.dm
Labels: Fix, Removal

#12912 uv penlight icon
  icons/obj/lighting.dmi
Labels: Fix, Sprites

#12925 buffs shoving
  code/__DEFINES/combat.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/status_procs.dm
  code/modules/movespeed/modifiers/mobs.dm
  code/modules/recycling/disposal/bin.dm
Labels: Balance/Rebalance, Feature

#12989 You Thought I Was Done Fucking With Box BUT YOU WERE WRONG!
  _maps/RandomRuins/LavaRuins/lavaland_surface_alien_nest.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#12954 bomb stands now use components
  code/datums/components/killerqueen.dm
  code/modules/mob/living/simple_animal/guardian/types/explosive.dm
  tgstation.dme
Labels: Balance/Rebalance, Code Improvement

#13004 prefs for headpat wagging
  code/__DEFINES/citadel_defines.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Feature

#13010 lizards no longer break their spines ~~roundstart~~ EVER AGAIN I FUCKING FIXED THE DOUBLE SET_SPECIES LIZARD BUG
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/surgery/organs/tails.dm
Labels: Fix

#13036 fixes ashwalker languages
  code/modules/language/language_holder.dm
Labels: Fix

#13028 AI Open
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit, Tweak

#13025 Tea Party
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/vending/coffee.dm
Labels: Feature

#13017 door charges no longer unconscious() you
  code/game/machinery/doors/airlock.dm
Labels: Balance/Rebalance

#13009 Total law changes: 110
  code/modules/uplink/uplink_items/uplink_devices.dm
Labels: Feature

#13008 nukies can buy holoparasites not including support ones
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/uplink/uplink_items/uplink_dangerous.dm
Labels: Feature

#12889 minor quirk changes
  code/datums/traits/negative.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
Labels: Tweak

#12926 Adds a new fun round end sound
  code/controllers/subsystem/ticker.dm
  sound/roundend/CitadelStationHasSeenBetterDays.ogg
Labels: Sound

#13003 Proto-Kinetic Glaives - a crusher reskin
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/machine_vending.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
  icons/obj/mining.dmi
Labels: Feature, Sprites

#12990 make tongue preference pass through cloning
  code/modules/client/preferences.dm
Labels: Tweak

#12991 I wanna be tracer
  code/game/objects/items/implants/implant_misc.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/uplink/uplink_items/uplink_implants.dm
  html/changelogs/AutoChangeLog-pr-12979.yml
  icons/obj/implants.dmi
Labels: Feature, Sprites

#12994 removes dildo
  code/controllers/subsystem/processing/circuit.dm
  code/modules/integrated_electronics/core/assemblies.dm
Labels: Removal

#12995 a few small tweaks to travelling traders
  code/modules/events/travelling_trader.dm
Labels: Tweak

#12963 ghost chilis fixed
  code/modules/hydroponics/grown/chili.dm
Labels: Fix

#13006 2x's volumetric storage minimum size because i'm going to stop pretending this ugly shit is usable when even i myself use opt-out to old interface
  code/__DEFINES/storage/_storage.dm
Labels: Tweak

#12969 someone asked i code holoparasites playing music so here we are???
  code/modules/instruments/songs/_song.dm
  code/modules/instruments/songs/editor.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
Labels: Feature

#13001 makes explosions only recurse one level into storage at full power before dropping 1 level per storage object recursed
  code/game/objects/items/storage/_storage.dm
Labels: Balance/Rebalance

#13032 podpeople obesity fix (this time citbot properly will do the feature delta)
  code/datums/elements/photosynthesis.dm
Labels: Fix, PRB: Reset

#13035 ""fixes"" an ""issue"" with vendors
  code/modules/vending/_vending.dm
Labels: Fix

#13029 attempting to send an emote above 2048 characters will now reflect it back to you without sending instead of rudely cutting off your emote mid-message.
  code/__HELPERS/text.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/say.dm
  code/modules/mob/say_vr.dm
Labels: Feature

#13033 how about we not gib slimepeople for having too much blood that is a little unfun eh now they'll just take damage and bleed the excess
  code/modules/mob/living/blood.dm
Labels: Balance/Rebalance

#13030 off balanace
  code/game/objects/items/shields.dm
Labels: Grammar and Formatting

#13026 More Active Turf Fixes
  _maps/RandomRuins/SpaceRuins/arcade.dmm
  _maps/RandomRuins/SpaceRuins/augmentationfacility.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid6.dmm
  _maps/RandomZLevels/VR/murderdome.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#13039 reduces all cuts bleed rate by 25% and stops blood gibbing you
  code/datums/wounds/slash.dm
  code/modules/mob/living/blood.dm
Labels: Tweak

#13041 No murderbone please
  strings/abductee_objectives.txt
Labels: Feature, Removal

#13043 🅱️oneless
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Tweak

#13038 adds *blorble and *blurp as carbon emotes
  code/modules/mob/living/emote.dm
Labels: Feature

#13013 N tvsg sebz Nezbere (or: a bunch of clockcult related stuff)
  code/__DEFINES/clockcult.dm
  code/datums/status_effects/debuffs.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
  code/modules/antagonists/clockcult/clock_helpers/clock_rites.dm
  code/modules/antagonists/clockcult/clock_items/clock_augments.dm
  code/modules/antagonists/clockcult/clock_items/clock_weapons/brass_claw.dm
  code/modules/antagonists/clockcult/clock_items/clock_weapons/ratvarian_spear.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_scripts.dm
  icons/mob/inhands/antag/clockwork_lefthand.dmi
  icons/mob/inhands/antag/clockwork_righthand.dmi
  icons/obj/clockwork_objects.dmi
  icons/obj/surgery.dmi
  tgstation.dme
Labels: Balance/Rebalance, Feature, Fix, Sprites

#12992 unatomic as shit PR about nukie guns
  code/game/objects/items/granters.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/projectiles/boxes_magazines/external/shotgun.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/uplink/uplink_items/uplink_ammo.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites

#12960 loadout changes part 1: adds subcategories to the loadout
  code/__DEFINES/loadout.dm
  code/_globalvars/lists/loadout_categories.dm
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/_loadout.dm
  modular_citadel/code/modules/client/loadout/_medical.dm
  modular_citadel/code/modules/client/loadout/_security.dm
  modular_citadel/code/modules/client/loadout/_service.dm
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/code/modules/client/loadout/glasses.dm
  modular_citadel/code/modules/client/loadout/gloves.dm
  modular_citadel/code/modules/client/loadout/hands.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/mask.dm
  modular_citadel/code/modules/client/loadout/neck.dm
  modular_citadel/code/modules/client/loadout/shoes.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
  tgstation.dme
Labels: Feature, Sprites

#13056 emergency loadout fix
  code/__DEFINES/loadout.dm
  code/_globalvars/lists/loadout_categories.dm
  code/modules/client/preferences.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/_loadout.dm
  modular_citadel/code/modules/client/loadout/_medical.dm
  modular_citadel/code/modules/client/loadout/_security.dm
  modular_citadel/code/modules/client/loadout/_service.dm
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/code/modules/client/loadout/glasses.dm
  modular_citadel/code/modules/client/loadout/gloves.dm
  modular_citadel/code/modules/client/loadout/hands.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/mask.dm
  modular_citadel/code/modules/client/loadout/neck.dm
  modular_citadel/code/modules/client/loadout/shoes.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Priority: CRITICAL

#13048 Proto-Kinetic Glaives Phase 2 - Parrying
  code/modules/mining/equipment/kinetic_crusher.dm
Labels: Feature

#13046 Adds a second shutter to the hopline on boxstation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit, PRB: Reset

#13057 Fixes telekinesis being able to be used to wield objects
  code/datums/components/twohanded.dm
Labels: Fix

#13059 immovable rods no longer drop down chasms
  code/modules/events/immovable_rod.dm
Labels: Fix

#13052 fixes laptops not being able to be picked up
  code/modules/modular_computers/computers/item/laptop.dm
Labels: Fix, Priority: High

#13055 squeaking objects including air horns and clockwork boots now have a default 1 second cooldown. squeaking objects crossing each other will on average only allow 3 squeaks to occur, because if byond is literally running out of sound channels you know the fun has went too far
  code/__DEFINES/dcs/signals.dm
  code/datums/components/squeak.dm
Labels: Removal

#13069 Ports TG #51879 - Makes rads glow, buffs rad goggles
  code/__DEFINES/layers_planes.dm
  code/datums/components/radioactive.dm
  code/datums/radiation_wave.dm
  code/modules/clothing/glasses/engine_goggles.dm
Labels: Feature

#13068 sterilized gauze, ointment and suture stacksizes
  code/game/objects/items/stacks/medical.dm
Labels: Balance/Rebalance, Tweak

#13066 speech verbs now copy through dna copying
  code/datums/dna.dm
Labels: Tweak

#13079 parry counterattack text now actually shows up
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/living_active_parry.dm
Labels: Fix

#13078 Made traitor reroll reroll to MI13 only.
  code/modules/uplink/uplink_items/uplink_bundles.dm
Labels: Tweak

#13081 Ports ethereals from TG
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/names.dm
  code/__HELPERS/text.dm
  code/_globalvars/lists/names.dm
  code/_onclick/hud/alert.dm
  code/datums/components/mood.dm
  code/datums/mood_events/needs_events.dm
  code/game/machinery/rechargestation.dm
  code/game/objects/items/trash.dm
  code/modules/admin/topic.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/food/snacks_vend.dm
  code/modules/language/language_holder.dm
  code/modules/language/voltaic.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/lighting.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/surgery/organs/stomach.dm
  code/modules/surgery/organs/tongue.dm
  code/modules/vending/snack.dm
  config/game_options.txt
  icons/misc/language.dmi
  icons/obj/food/food.dmi
  icons/obj/janitor.dmi
  sound/weapons/etherealhit.ogg
  sound/weapons/etherealmiss.ogg
  strings/names/ethereal.txt
  tgstation.dme
Labels: Config Update, Feature, Sound, Sprites

#13082 Removed (an)aphrodisiacs.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/pool.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/modules/admin/chat_commands.dm
  code/modules/cargo/packs/misc.dm
  code/modules/client/preferences.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/vending/kinkmate.dm
  modular_citadel/code/datums/status_effects/chems.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Map Edit, Removal

#13084 Made IC issue wording less salt-assuming
  code/modules/admin/verbs/adminhelp.dm
Labels: Tweak

#13085 KC-G Phase 2.1 - Parry Tweaks
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/machine_vending.dm
Labels: Balance/Rebalance

#13060 wizard timestop parrying katana
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/mob/living/emote.dm
Labels: Feature

#13054 Improves zombies, the gimped threat
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/zombie/items.dm
Labels: Balance/Rebalance, Feature

#13053 makes cargo's Dirty Magazines 3x cheaper
  code/modules/cargo/packs/misc.dm
Labels: Balance/Rebalance

#13051 juice spilled
  strings/traumas.json
Labels: Feature

#13040 funny chair loses block chance and gains active block/parry
  code/game/objects/structures/beds_chairs/chair.dm
Labels: Balance/Rebalance

#13047 replaces box whiteship tbaton with truncheon
  _maps/shuttles/whiteship_box.dmm
Labels: Map Edit, Removal, Tweak

#13076 adds swarming components to rats so they're a bit less cancer to visualize
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
Labels: Tweak

#11699 probably stops borgs from clicking fast enough to circumvent low health module failures
  code/modules/mob/living/silicon/robot/inventory.dm
Labels: Awaiting further discussion/approval, Fix

#13022 increases space levels to 4
  code/modules/mapping/map_config.dm
Labels: Tweak

#13050 removes a spammy and bad brain damage line about rp server
  strings/traumas.json
Labels: Removal

#12933 regarding malf ais, apcs, space, and engineering cyborg grippers
  code/game/area/areas.dm
  code/modules/power/apc.dm
Labels: Balance/Rebalance

#13075 My balls are raw. Meatballs, that is.
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
Labels: Tweak

#13002 explosions now only hard knockdown for 1-4 seconds instead of 4-16+, instead doing stamina damage. on people affected.
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance/Rebalance

#13034 turns off fix/feature delta bot
  tools/WebhookProcessor/github_webhook_processor.php
Labels: Tools

#13097 Patented Zero Salt PR That Adds One New Hair Style That Is Just Pompadourless Volaju Because
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  icons/mob/human_face.dmi
Labels: Feature, Sprites

#13093 Tracer's a human, not a changeling.
  code/game/objects/items/implants/implant_misc.dm
Labels: Tweak

#13094 PDA Uplinks Can Now Siphon Pens
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#13111 quickly fixes alteranate volaju to be more alternate and gives the quartermaster a blue sechud icon
  icons/mob/hud.dmi
  icons/mob/human_face.dmi
Labels: Sprites

#13103 funny timestop katana is less funny and more gameplay oriented
  code/game/objects/items/weaponry.dm
Labels: Balance/Rebalance

#13120 Fixes missing icon and handtele being fast
  code/game/objects/items/teleportation.dm
  icons/obj/machines/research.dmi
Labels: Sprites

#13098 Mafia Component
  _maps/map_files/Mafia/mafia_ayylmao.dmm
  _maps/map_files/Mafia/mafia_ball.dmm
  _maps/map_files/Mafia/mafia_gothic.dmm
  _maps/map_files/Mafia/mafia_lavaland.dmm
  _maps/map_files/Mafia/mafia_reebe.dmm
  _maps/map_files/Mafia/mafia_snow.dmm
  _maps/map_files/Mafia/mafia_spiderclan.dmm
  _maps/map_files/Mafia/mafia_syndie.dmm
  _maps/map_files/generic/CentCom.dmm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mafia/_defines.dm
  code/modules/mafia/controller.dm
  code/modules/mafia/map_pieces.dm
  code/modules/mafia/outfits.dm
  code/modules/mafia/roles.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/procedural_mapping/mapGenerator.dm
  icons/obj/mafia.dmi
  tgstation.dme
  tgui/packages/tgui/assets/bg-neutral.svg
  tgui/packages/tgui/index.js
  tgui/packages/tgui/interfaces/MafiaPanel.js
  tgui/packages/tgui/public/tgui.bundle.css
  tgui/packages/tgui/public/tgui.bundle.js
  tgui/packages/tgui/styles/themes/neutral.scss
Labels: Feature, Map Edit, Sprites, UI

#13095 custom name/desc ring and necklace
  code/modules/clothing/gloves/ring.dm
  code/modules/clothing/under/accessories.dm
  code/modules/paperwork/pen.dm
  icons/obj/clothing/accessories.dmi
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/code/modules/client/loadout/gloves.dm
Labels: Feature, Sprites

#13090 Added Burek to Space
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pies_sweets.dm
  icons/obj/food/piecake.dmi
Labels: Sprites

#13089 Demodularization + making certain sprite overlays less hilariously jank
  code/modules/arousal/genitals.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#13106 ce hardsuit no longer requires a jumpsuit to actually be fully radproof
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Balance/Rebalance

#13107 The warcrime gun belongs in the armory
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/goodies.dm
Labels: Balance/Rebalance

#13070 lowers price of 2 borderline useless uplink items
  code/modules/uplink/uplink_items/uplink_stealthdevices.dm
Labels: Fix, Tweak

#13071 Adds doors to the west of box medbay
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Tweak

#13011 adds a cybernetic eyepatch to the syndicate uplink
  code/__DEFINES/traits.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/wall/mineral_walls.dm
  code/game/turfs/simulated/walls.dm
  code/modules/antagonists/blob/blob/blobs/shield.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/projectile.dm
  code/modules/uplink/uplink_items/uplink_clothing.dm
  icons/mob/clothing/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Fix, Sprites

#12808 you can now use any typepath as an emoji :/obj/item/clothing/mask/joy:
  code/modules/emoji/emoji_parse.dm
Labels: Feature, Test Merge Candidate

#13126 fixes the random fucking medbay tables that some dipshit left in the hallway on box
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#13114 "it'll be fine Sables, nothing bad will happen if we remove the /mob blacklist from radiation"
  code/modules/antagonists/revenant/revenant.dm
Labels: In Game Exploit, Priority: High

#13096 Ports Opossums from Desert Rose
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
  code/modules/mob/living/simple_animal/friendly/possum.dm
  icons/mob/animal.dmi
  tgstation.dme
Labels: Feature, Map Edit, Sprites

#13134 Removes fermisleepers
  code/game/machinery/Sleeper.dm
  tgui/packages/tgui/interfaces/Sleeper.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Removal, UI

#13137 listed_turf is now O(n) average case instead of O(n^2)
  code/modules/mob/mob.dm
Labels: In Game Exploit, Priority: CRITICAL

#13152 we also left out the code that let abductors actually BUY THINGS
  code/modules/antagonists/abductor/machinery/console.dm
Labels: Fix

#13150 150 runtimes from warden shotguns being shitcode
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
Labels: Priority: High

#13160 Fixes missing icons for anomaly cores
  icons/obj/assemblies/new_assemblies.dmi
Labels: Sprites

#13112 what the fuck is an energy gun
  _maps/map_files/CogStation/CogStation.dmm
Labels: Fix, Map Edit, Priority: High, Salt

#13145 makes sleepers use the proper state
  code/game/machinery/Sleeper.dm
Labels: Fix

#13133 clockwork chairs now keep spinning because it's no longer that laggy to maintain it since it's a processing system instead of while(TRUE) now
  code/game/objects/structures/beds_chairs/chair.dm
Labels: Tweak

#13131 gives ethereals underwear
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
Labels: Tweak

#13105 ports binder bras from rp
  code/modules/mob/dead/new_player/sprite_accessories/undershirt.dm
  icons/mob/clothing/underwear.dmi
Labels: Sprites

#13154 Rewrites, remakes, replaces, and improves several tips, also adds a couple more
  strings/sillytips.txt
  strings/tips.txt
Labels: Feature, Removal

#13157 chaplain nullrod nerf
  code/game/objects/items/dualsaber.dm
Labels: Balance/Rebalance

#13177 [FUCK] Cogscarabs can no longer do very scary stuff
  code/modules/antagonists/clockcult/clock_items/construct_chassis.dm
Labels: FUCK, Fix

#12739 [READY] DRAKEBORGS & PLUSHIES
  code/game/objects/items/plushes.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/cyborg/Drakeborg-licensing.txt
  icons/mob/cyborg/drakemech.dmi
  icons/obj/license.txt
  icons/obj/plushes.dmi
  modular_citadel/icons/mob/widerobot.dmi
Labels: Code Improvement, Feature, Needs Review, Sprites

#13092 active blocking now also considers a stamina damaging projectile's stamina damage to be .. damage
  code/modules/mob/living/living_active_block.dm
Labels: Tweak

#13037 turns 304 lines of snowflake code into 24 lines
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Refactor, Tweak

#13109 adds more heatpipes to snaxi sm
  _maps/map_files/Snaxi/Snaxi.dmm
Labels: Map Edit

#13067 readds mosins to cargo, sort of
  code/game/objects/effects/spawners/bundle.dm
  code/game/objects/items/storage/toolbox.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/security.dm
Labels: Feature

#13176 Increases Kindle cast time and moves a bit of code
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_scripts.dm
Labels: Balance/Rebalance, Tweak

#13175 space diner now spawns thanks whoever coded this
  code/datums/ruins/space.dm
  config/spaceRuinBlacklist.txt
Labels: Config Update, Fix

#13167 nerfs plasma cutters
  code/modules/projectiles/projectile/special/plasma.dm
Labels: Balance/Rebalance

#13168 Ports "Fixes tesla lagging the server to shit." from /tg/
  code/__DEFINES/_flags/_flags.dm
Labels: Balance/Rebalance

#13164 You Can No Longer Remove The Inferno Part Of Disco Inferno (tgstation/tgstation#52823)
  _maps/shuttles/emergency_discoinferno.dmm
  code/game/turfs/simulated/floor/mineral_floor.dm
Labels: Feature, Map Edit

#13159 you can now beat eachother to death with a certain dildo.
  code/modules/arousal/toys/dildos.dm
Labels: Feature

#13153 Updates the contributor policy to reflect the new policy in place
  .github/CONTRIBUTING.md
Labels: Github

#13148 vehicle rider headshots
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/sealed.dm
Labels: Balance/Rebalance

#13144 you *theoretically* should be able to throw items over plant dna manips (but it's not working), adds a side window to the bluespace beaker to see reagents through
  code/modules/hydroponics/gene_modder.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Feature, Sprites

#13147 i despise cargocode - tweaks, buffs, etc.
  code/modules/cargo/exports/gear.dm
  code/modules/cargo/exports/organs_robotics.dm
  code/modules/cargo/exports/parts.dm
  code/modules/cargo/exports/weapons.dm
Labels: Balance/Rebalance

#13141 Gives ashwalkers night vision eyeballs
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
Labels: Feature

#13130 skeleton traits are now not horrendously overpowered
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
Labels: Tweak

#13129 Allows ghosts to see the contents of closets
  code/__DEFINES/logging.dm
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Tweak

#13124 Icon fixes and some mutation tweaks for botany. Please don't make me do this again, I will codersprite your plants into the ground.
  code/modules/hydroponics/grown/cannabis.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/hydroponics/grown/garlic.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/grown/tea_coffee.dm
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/growing_vegetables.dmi
Labels: Fix, Removal, Sprites

#13110 cease your shitcode: cum edition
  code/__DEFINES/pool.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/diseases/advance/symptoms/species.dm
  code/datums/dna.dm
  code/modules/arousal/organs/womb.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/dead/new_player/sprite_accessories/Citadel_Snowflake.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/alienpeople.dm
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/frills.dm
  code/modules/mob/dead/new_player/sprite_accessories/horns.dm
  code/modules/mob/dead/new_player/sprite_accessories/legs_and_taurs.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/dead/new_player/sprite_accessories/spines.dm
  code/modules/mob/dead/new_player/sprite_accessories/synthliz.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Refactor

#13087 glaive needs wield for parry, deswords reflect energy projectiles on block AND reflect any projectile on perfect parry
  code/game/objects/items/dualsaber.dm
  code/game/objects/items/weaponry.dm
  code/modules/mining/equipment/kinetic_crusher.dm
Labels: Balance/Rebalance, Feature

#13179 kills an ugly if-chain in inventory code (probably)
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
Labels: Code Improvement

#13180 ports multiz glass floors (tgstation/tgstation#50831)
  _maps/RandomRuins/IceRuins/icemoon_surface_mining_site.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
  _maps/map_files/debug/multiz.dmm
  _maps/multiz_debug.json
  _maps/snaxi.json
  code/__DEFINES/is_helpers.dm
  code/controllers/subsystem/mapping.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/openspace/openspace.dm
  code/game/turfs/openspace/transparent.dm
  code/game/turfs/simulated/floor/plating.dm
  icons/turf/floors/glass.dmi
  icons/turf/floors/reinf_glass.dmi
  tgstation.dme
Labels: Feature, Map Edit, Sprites

#13185 slaughter demons to MOB_SIZE_LARGE
  code/modules/antagonists/slaughter/slaughter.dm
Labels: Balance/Rebalance

#13186 a few snaxi improvements; chiefly labelling the telepads better.
  _maps/map_files/Snaxi/Snaxi.dmm
  icons/obj/decals.dmi
Labels: Map Edit, Sprites

#13190 adds art to ghost cafe
  _maps/map_files/generic/CentCom.dmm
Labels: Feature, Map Edit

#13108 .357 DumDum Rounds (they're adminspawn only don't worry)
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
Labels: Feature

#13195 makes glass floors actually deconstructable
  code/game/turfs/openspace/transparent.dm
Labels: Fix

#13189 Revert "[TESTMERGE ONLY] FUCK"
  code/__DEFINES/pool.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/diseases/advance/symptoms/species.dm
  code/datums/dna.dm
  code/modules/arousal/organs/womb.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/dead/new_player/sprite_accessories/Citadel_Snowflake.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/alienpeople.dm
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/frills.dm
  code/modules/mob/dead/new_player/sprite_accessories/horns.dm
  code/modules/mob/dead/new_player/sprite_accessories/legs_and_taurs.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/dead/new_player/sprite_accessories/spines.dm
  code/modules/mob/dead/new_player/sprite_accessories/synthliz.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Revert

#13194 Updates the clockcult help link to link to our wiki.
  code/game/gamemodes/clock_cult/clock_cult.dm
Labels: Tweak

#13202 Makes Ethereal hair their mutcolor instead of white
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
Labels: Fix

#13207 [s] ports does the html admin thing in a better way probably
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Administration

#13206 [s] xss
  code/modules/research/nanites/nanite_programs/suppression.dm
Labels: Priority: CRITICAL

#13210 >pirate announce metabreaks >in the year of our Lord 2020
  code/modules/events/pirates.dm
Labels: Balance/Rebalance

#13214 [s] Min and max are two very distinct procs...
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Fix

#13199 [READY] tested code
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  code/modules/projectiles/guns/ballistic.dm
Labels: Do Not Merge, Needs Review

#13183 Shuttle hotfix so now you can make huge shuttle things
  code/controllers/configuration/entries/game_options.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
Labels: Config Update, Fix, Tweak

#13211 Updates tips
  strings/tips.txt
Labels: Feature

#13212 Ports reftracking from TG.
  byond-extools.dll
  code/__DEFINES/qdel.dm
  code/__DEFINES/vv.dm
  code/_compile_options.dm
  code/controllers/subsystem/garbage.dm
  code/datums/datumvars.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/admin/view_variables/view_variables.dm
  tgstation.dme
Labels: Administration

#13223 fix lizard snouts
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
Labels: Fix
