Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-03, with the labels that each got.

#11279 tgstation 45232 - lava rivers can no longer be plasma'd for basalt
  code/game/turfs/simulated/lava.dm
  code/game/turfs/simulated/river.dm
Labels: Code Improvement, Fix

#11268 ongoing vampire ability balance/rework attempt
  code/modules/antagonists/bloodsucker/powers/cloak.dm
  code/modules/antagonists/bloodsucker/powers/lunge.dm
  code/modules/antagonists/bloodsucker/powers/mesmerize.dm
  tgstation.dme
Labels: Balance/Rebalance, Tweak

#11287 Allow moaning while in soft crit
  code/modules/mob/living/carbon/emote.dm
Labels: FUCK, Good First PR, MEME PR, Priority: CRITICAL, Tweak

#11302 fixes compact defibs starting with a 1k instead of 10k cell
  code/game/objects/items/defib.dm
Labels: Fix

#11291 Makes the mining base more natural-looking
  _maps/RandomRuins/LavaRuins/miningbase.dmm
Labels: Fix, Map Edit

#11281 Just another round-end sound.
  code/controllers/subsystem/ticker.dm
  sound/roundend/seeyoulaterokay.ogg
Labels: Sound

#11283 Makes most winter coats and hoods have their own desc
  code/modules/clothing/suits/miscellaneous.dm
Labels: Feature

#11271 Pushing stuff now checks for Process_Spacemove on the automatic step
  code/modules/mob/living/living.dm
Labels: Tweak

#11041 Bloodsucker external blood gain rebalancing
  code/datums/mood_events/generic_negative_events.dm
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
Labels: Balance/Rebalance, Needs Review

#11299 fix flypeople nutrition
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
Labels: Fix

#11250 Rising bass nerfs and fixes
  code/datums/martial/rising_bass.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  icons/mob/actions/actions_items.dmi
Labels: Balance/Rebalance, Fix, Sprites

#11203 Three new posters!
  code/game/objects/effects/contraband.dm
  icons/obj/contraband.dmi
Labels: Feature, Sprites

#11289 Cotton/Durathreads now stack to 80
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Tweak

#11320 Stops ninjas employed by syndies from receiving friendly flavor objectives.
  code/modules/antagonists/ninja/ninja.dm
Labels: Fix

#11308 Removes lag
  code/game/machinery/telecomms/machines/allinone.dm
  code/game/machinery/telecomms/machines/broadcaster.dm
  code/game/machinery/telecomms/machines/bus.dm
  code/game/machinery/telecomms/machines/processor.dm
  code/game/machinery/telecomms/telecomunications.dm
Labels: Removal, Test Merge Candidate

#11321 fixes storage closing while dragging, aka "this one line fix that i procrastinated giving a fuck about for about 9 months now"
  code/datums/components/storage/storage.dm
Labels: Fix

#11314 Kat Furniture! New sofas, chess pieces, nine new posters and shower curtain functionality!
  code/game/objects/effects/contraband.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/beds_chairs/pew.dm
  code/game/objects/structures/beds_chairs/sofa.dm
  code/game/objects/structures/chess.dm
  code/game/objects/structures/watercloset.dm
  icons/obj/chess.dmi
  icons/obj/contraband.dmi
  icons/obj/sofa.dmi
  tgstation.dme
Labels: Feature, Fix, Sprites

#11303 what the fuck you mean music line too long??
  code/game/objects/structures/musician.dm
Labels: Test Merge Candidate, Tweak

#11277 En garde! (nah just sword pointing)
  code/__DEFINES/components.dm
  code/datums/elements/sword_point.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/cult/cult_items.dm
  modular_citadel/code/_onclick/item_attack.dm
  tgstation.dme
Labels: Tweak

#11310 Fixing mob holders inventory slot flags (ergo they are not glasses)
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
Labels: Fix

#11327 Fixes reagent containers transfer cycling
  code/modules/reagents/reagent_containers.dm
Labels: Fix

#11318 fix nose booping
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Fix

#11130 Enables space ruin generation in the station z-level. Adds new ruins for the sake of station ruins.
  _maps/RandomRuins/SpaceRuins/spacehermit.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid1.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid10.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid2.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid3.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid4.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid5.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid6.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid7.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid8.dmm
  _maps/RandomRuins/SpaceRuinsStation/roid9.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/mapping.dm
  code/datums/ruins/space.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/game/area/Space_Station_13_areas.dm
  code/modules/projectiles/guns/magic/wand.dm
  config/game_options.txt
  config/stationRuinBlacklist.txt
  icons/obj/guns/magic.dmi
Labels: Config Update, Map Edit, Sprites, Work In Progress

#11181 changes sausage girth from circumference -> diameter
  code/__DEFINES/citadel_defines.dm
  code/__HELPERS/mobs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/arousal/organs/ovipositor.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
Labels: Fix

#11218 no more ai illegal upgrades, version 2 because I forgot I made it in web browser last time
  code/modules/research/designs/electronics_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance

#11333 Updates to kilostation
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Balance/Rebalance, Map Edit, Tweak

#11325 Removed some bad flavor objectives.
  strings/flavor_objectives/ninja_helping.txt
  strings/flavor_objectives/traitor.txt
Labels: Removal

#11328 Removed unused techweb var - Cargo selling of Techwebs nodes
  code/modules/research/techweb/_techweb_node.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Removal

#11064 3 new arm tool set implants
  code/game/objects/items/kitchen.dm
  code/game/objects/items/shields.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/organs/augments_arms.dm
Labels: Feature

#11330 Allows blobbernauts to drag objects (but not mobs) again.
  code/modules/antagonists/blob/blob/blobs/blob_mobs.dm
Labels: Balance/Rebalance

#11324 Makes medical hardsuits have built in huds
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Feature

#11323 Porting a couple material datums code updates and fixes.
  code/__DEFINES/materials.dm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/materials.dm
  code/datums/components/material_container.dm
  code/datums/materials/_material.dm
  code/game/atoms.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/machinery/toylathe.dm
  code/game/objects/items/apc_frame.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/table_frames.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/antagonists/bloodsucker/objects/bloodsucker_coffin.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/cargo/exports/materials.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/integrated_electronics/core/printer.dm
  code/modules/integrated_electronics/core/saved_circuits.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/mint.dm
  code/modules/mining/ores_coins.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/designs.dm
Labels: Fix

#11319 Fixes and improves RCL sprite update procs.
  code/game/objects/items/RCL.dm
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/tools.dmi
Labels: Sprites

#11316 Makes cargo passive point generation 125 a minute and not 2 or so every tick.
  code/controllers/subsystem/shuttle.dm
Labels: Fix

#11306 Removes makeshift switchblades
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/weaponry.dm
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Removal, Sprites

#11297 some dozens lines about some update_overlays issues and cryopods/MMIs.
  code/game/machinery/cell_charger.dm
  code/game/machinery/cloning.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  icons/obj/pda.dmi
Labels: Sprites

#11222 Ashwalkers now can make a well, got their livestock back and more!
  _maps/map_files/Mining/Lavaland.dmm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/watercloset.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/reagents/reagent_containers/glass.dm
  icons/obj/janitor.dmi
  icons/obj/lavaland/ash_flora.dmi
  icons/obj/watercloset.dmi
Labels: Feature, Map Edit, Sprites

#11355 fix quintuple sec mix_sound def
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
Labels: Fix

#11334 Made power sink objective more feasible
  code/game/gamemodes/objective_sabotage.dm
Labels: Balance/Rebalance, Fix

#11298 Ports TG's Syndicate Contractors
  code/__DEFINES/antagonists.dm
  code/__HELPERS/areas.dm
  code/__HELPERS/game.dm
  code/__HELPERS/roundend.dm
  code/__HELPERS/text.dm
  code/_globalvars/lists/poll_ignore.dm
  code/datums/browser.dm
  code/datums/mind.dm
  code/game/area/areas/ruins/space.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/antagonists/_common/antag_team.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/antagonists/traitor/syndicate_contract.dm
  code/modules/cargo/supplypod.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/events/grid_check.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/modular_computers/computers/item/tablet.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/ninja/suit/n_suit_verbs/energy_net_nets.dm
  code/modules/uplink/uplink_items/uplink_bundles.dm
  html/changelogs/AutoChangeLog-pr-11270.yml
  icons/mob/head.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/contractor_tablet.dmi
  icons/obj/items_and_weapons.dmi
  sound/effects/confirmdropoff.ogg
  sound/effects/contractorbatonhit.ogg
  sound/effects/contractstartup.ogg
  sound/effects/podwoosh.ogg
  sound/machines/uplinkerror.ogg
  sound/machines/uplinkpurchase.ogg
  sound/weapons/contractorbatonextend.ogg
  tgstation.dme
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/interfaces/synd_contract.ract
Labels: Balance/Rebalance, Feature, Fix, Refactor, Sound, Sprites, Tweak, UI

#11336 Makes MKUltra's explosion no longer spread prefbreak gas
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Removal

#11367 Corrects arrow crafting
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
Labels: Fix

#11358 Box bar lightswitch/pipe fixes now with mapmerge
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit

#11340 Porting movespeed modifiers code updates.
  code/__DEFINES/movespeed_modification.dm
  code/datums/martial/cqc.dm
  code/datums/martial/psychotic_brawl.dm
  code/datums/martial/sleeping_carp.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_mobility.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
Labels: Fix, Tweak

#11338 Fixes Chocolate Jelly Donuts
  code/modules/food_and_drinks/food/snacks_pastry.dm
Labels: Fix, Good First PR

#11359 Corrects snowcones
  code/modules/food_and_drinks/food/snacks_frozen.dm
  icons/obj/food/snowcones.dmi
Labels: Sprites

#11361 Fixes bartender drink slide spill A
  code/modules/reagents/reagent_containers.dm
Labels: Fix

#11339 TEG fix so fract doesn't yell at me
  _maps/RandomRuins/StationRuins/Box/Engine/engine_teg.dmm
Labels: Map Edit, Tweak

#11193 Makes two new legion drops
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
Labels: Feature

#11356 Nerfs ninja stungloves to match new batons
  code/modules/ninja/suit/gloves.dm
  code/modules/ninja/suit/ninjaDrainAct.dm
Labels: Balance/Rebalance

#10770 Removes an unused file and another outdated one.
  code/__HELPERS/type2type_vr.dm
  code/__HELPERS/unused.dm
  code/modules/ninja/suit/mask.dm
  code/modules/vore/eating/belly_obj.dm
  code/modules/vore/eating/vorepanel.dm
  tgstation.dme
Labels: Removal

#11363 Culls irrelevant targeting information on Drink Fling.
  code/modules/reagents/reagent_containers.dm
Labels: Tweak

#11360 Stunbaton disarm mode also works on disarm intent now
  code/game/objects/items/stunbaton.dm
Labels: Tweak

#11368 Eigenstasium no longer encourages certain personalities
  modular_citadel/code/modules/reagents/chemistry/reagents/eigentstasium.dm
Labels: Tweak

#11383 Gives storyteller weights defaults properly (whoops)
  code/controllers/subsystem/vote.dm
Labels: Fix

#11369 Porting the musician and curator beacons.
  code/datums/traits/good.dm
  code/game/objects/items/devices/instruments.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/religion.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/vending/wardrobes.dm
Labels: Feature, Tweak

#11357 Patches some awful integrated circuit examiner runtime errors.
  code/__DEFINES/misc.dm
  code/modules/integrated_electronics/subtypes/input.dm
Labels: Fix

#11365 Makes monkey probability of gorillize from radiation exponential.
  code/__DEFINES/radiation.dm
  code/modules/mob/living/carbon/monkey/life.dm
Labels: Tweak

#11288 [ready] Craftable Prescription & Sunglasses HUDs
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/modules/clothing/glasses/hud.dm
  icons/obj/clothing/glasses.dmi
Labels: Fix, Needs Review, Sprites

#11317 Ports Skyrat's synths (Plus limb rendering overhaul and more)
  code/__DEFINES/mobs.dm
  code/__HELPERS/mobs.dm
  code/datums/dna.dm
  code/game/machinery/limbgrower.dm
  code/modules/antagonists/bloodsucker/powers/veil.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/ipc_synths.dm
  code/modules/mob/dead/new_player/sprite_accessories/legs_and_taurs.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/dead/new_player/sprite_accessories/synthliz.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  config/game_options.txt
  modular_citadel/icons/mob/mam_taur.dmi
  modular_citadel/icons/mob/mutant_bodyparts.dmi
  modular_citadel/icons/mob/synthliz_antennas.dmi
  modular_citadel/icons/mob/synthliz_body_markings.dmi
  modular_citadel/icons/mob/synthliz_snouts.dmi
  modular_citadel/icons/mob/synthliz_tails.dmi
  tgstation.dme
Labels: Config Update, Work In Progress

#11377 Some contractor adjustments & fixes
  code/__HELPERS/game.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/antagonists/traitor/syndicate_contract.dm
  code/modules/modular_computers/file_system/programs/antagonist/contract_uplink.dm
  code/modules/uplink/uplink_items/uplink_bundles.dm
  icons/mob/inhands/weapons/melee_righthand.dmi
Labels: Balance/Rebalance, Fix, Sprites

#11393 Webedit fixing bloodsucker mesmerize
  code/modules/antagonists/bloodsucker/powers/mesmerize.dm
Labels: Fix

#11382 tauric contractor space suits
  code/modules/clothing/spacesuits/syndi.dm
  icons/mob/head_muzzled.dmi
  icons/mob/suit_digi.dmi
  icons/mob/taur_canine.dmi
  icons/mob/taur_naga.dmi
Labels: Feature, Sprites

#11403 [s] Ports "Fixes gibber part update"
  code/modules/food_and_drinks/kitchen_machinery/gibber.dm
Labels: Fix

#11397 syndicate contractor helmets are no longer secretly lead
  code/modules/clothing/spacesuits/syndi.dm
Labels: Balance/Rebalance

#11395 Shuttle timer display seconds fix
  code/modules/shuttle/shuttle.dm
Labels: Fix

#11392 syndicate elite hardsuit helmet doesnt hide masks anymore
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Fix

#11388 Food Ports / Butter Bear / Food Craft Speed
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/cargo/packs/organic.dm
  code/modules/food_and_drinks/food/snacks_burgers.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_seafood.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  icons/mob/animal.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
Labels: Feature, Sprites, Tweak

#11398 fixes hands free actions (like !!!adrenal implants!!!) not being available during stuns
  code/datums/action.dm
Labels: Fix

#11399 normalising wagging tail names for a very specific bug fix
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/mutant_bodyparts.dmi
  modular_citadel/icons/mob/mam_tails.dmi
Labels: Fix, Sprites

#11349 Pixel shifting for ERP
  code/modules/keybindings/bindings_mob.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: FUCK, Feature, Good First Issue, Good First PR

#11417 One liner fixing dynamic voting resulting in the unstartable gamemode.
  code/controllers/subsystem/vote.dm
Labels: Fix, Priority: High

#11401 Gives pipe and ashen bow inhand sprites
  code/modules/projectiles/guns/ballistic/bow.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
Labels: Sprites

#11419 [s] Sanitizes ParseSong tempo.
  code/game/objects/structures/musician.dm
Labels: In Game Exploit, Priority: High

#11411 Webedit touching the MOVESPEED_ID_DAMAGE_SLOWDOWN_FLYING speed modifier: Citadel Edition.
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#10702 Hey, do you remember that wizard round where everyone tried arming up the nuclear bomb and we all went DELTA RED DELTA RED DELTA RED DELTA ?
  code/game/machinery/computer/communications.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/shuttle/emergency.dm
Labels: Kneejerk Change, Tweak

#11335 Made flavor texts into an element datum, appliable to every atom.
  code/__DEFINES/components.dm
  code/__HELPERS/_cit_helpers.dm
  code/datums/dna.dm
  code/datums/elements/flavor_text.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  modular_citadel/code/modules/client/preferences.dm
  tgstation.dme
Labels: Refactor

#11385 Box theatre starboard vent/scrubber fix
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#11420 removes limbo courtesy of bhijn
  code/modules/admin/IsBanned.dm
Labels: Removal

#11421 Fixes the "blind while not unconscious bug", alternatively, "if in doubt, assume something is coded in the worst possible way and is held together by duct tape and prayers"
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Fix

#11432 legion swarming now only applies to legions, not all of everything else that is a supertype and subtype of /hivelordbrood
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
Labels: Balance/Rebalance

#11410 Ports tg#44633: Fixes blood beam oneshotting mech pilots.
  code/game/mecha/mecha_defense.dm
Labels: Fix

#11409 Particle Defender no longer just the HoS taser but a shotgun/Stimulants protect against the tased effect.
  code/__DEFINES/traits.dm
  code/datums/status_effects/debuffs.dm
  code/modules/projectiles/projectile/energy/stun.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
Labels: Balance/Rebalance

#11414 Fixes mob spawners errors with posibrains.
  code/modules/mob/living/brain/posibrain.dm
Labels: Fix

#11424 Some fakedeath fixes requested by kev also ports a fix from tg to regen coma
  code/datums/diseases/advance/symptoms/heal.dm
  code/modules/research/nanites/nanite_programs/suppression.dm
Labels: Code Improvement

#11408 Refactors Martial Arts code, human_defense, and ports New Sleeping Carp
  code/datums/martial/_martial.dm
  code/datums/martial/plasma_fist.dm
  code/datums/martial/psychotic_brawl.dm
  code/datums/martial/rising_bass.dm
  code/datums/martial/sleeping_carp.dm
  code/game/objects/items/granters.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/uplink/uplink_items/uplink_stealth.dm
  tgstation.dme
Labels: Feature, Refactor

#11373 miner powercreep starring 150 damage pointblank shotgun
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  icons/obj/guns/projectile.dmi
Labels: Balance/Rebalance, Feature, Sprites

#11307 gets rid of fly species requirement from hulk
  code/datums/mutations/hulk.dm
Labels: Balance/Rebalance, Fix, Removal

#11440 fixes master
  code/__DEFINES/components.dm
  code/datums/dna.dm
  code/datums/mutations/actions.dm
Labels: Priority: CRITICAL

#11406 Ports station minimaps from Yogstation thank you monster860 you are an epic gamer
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/minimaps.dm
  code/game/area/areas.dm
  code/modules/client/verbs/minimap.dm
  code/modules/mapping/minimaps.dm
  html/blank.png
  tgstation.dme
Labels: Config Update, Feature

#11429 Dynamic tweaks/fixes
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/vote.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  code/modules/antagonists/swarmer/swarmer_event.dm
  code/modules/events/portal_storm.dm
  code/modules/events/wormholes.dm
Labels: Balance/Rebalance, Feature, Fix, Removal, Tweak

#11425 fixes synthflesh/rezadone dehusk threshold check
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix

#11422 Changes up some lava land ruins spawns
  code/datums/ruins/lavaland.dm
Labels: Balance/Rebalance, Tweak

#11416 Makes Bluespace and Urianium reagents be able to be turned into sheets
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature

#11431 Missing contractor tablet icon state fix
  code/modules/modular_computers/computers/item/tablet.dm
Labels: Fix

#11451 More dynamic fixes
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Fix

#11448 Makes the autotransfer subsystem slightly more modulable.
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/autotransfer.dm
  code/datums/elements/ghost_role_eligibility.dm
  code/modules/mob/dead/observer/observer.dm
  config/config.txt
Labels: Config Update, Fix

#11447 Porting datum components system updates.
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/dcs/helpers.dm
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/dcs.dm
  code/datums/components/README.md
  code/datums/components/_component.dm
  code/datums/components/fantasy/_fantasy.dm
  code/datums/components/nanites.dm
  code/datums/components/orbiter.dm
  code/datums/components/radioactive.dm
  code/datums/components/remote_materials.dm
  code/datums/components/stationloving.dm
  code/datums/components/thermite.dm
  code/datums/components/wet_floor.dm
  code/datums/datum.dm
  code/datums/elements/_element.dm
  code/datums/elements/mob_holder.dm
  code/datums/materials/basemats.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/toylathe.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/structures/windoor_assembly.dm
  code/modules/assembly/infrared.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/mapping/mapping_helpers/_mapping_helpers.dm
  code/modules/mining/machine_silo.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/research/nanites/nanite_cloud_controller.dm
  tgstation.dme
Labels: Code Improvement

#11437 Ports Blob Buffs
  code/__DEFINES/antagonists.dm
  code/modules/antagonists/blob/blob/blobs/shield.dm
  code/modules/antagonists/blob/blob/powers.dm
Labels: Balance/Rebalance, Fix

#11436 Kilostation adjustments
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Map Edit, Tweak

#11453 I'm pretty sure this was causing people to bleed out from light hits
  code/_onclick/item_attack.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#11452 make the CMO hypokit not literally worse than normal ones
  code/game/objects/items/storage/firstaid.dm
Labels: Tweak

#11450 ports ([READY] Allows bandannas to be worn as neckerchiefs. #40125) from TG code
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/neck/_neck.dm
Labels: Feature, Needs Review

#11446 Revert "Stunbaton disarm mode also works on disarm intent now"
  code/game/objects/items/stunbaton.dm
Labels: Revert

#11461 Fixes bloodsucker heart theft objective not completing properly
  code/modules/antagonists/bloodsucker/bloodsucker_objectives.dm
Labels: Fix

#11464 Made server votes not subject to the cooldown
  code/controllers/subsystem/vote.dm
Labels: Fix

#11460 Fixes mice biting wires while in backpacks
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Fix

#11466 fixes to quirk blacklisting
  code/controllers/subsystem/processing/quirks.dm
Labels: Fix

#11456 Box station captains office now has a weird dog
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit

#11467 Adds a blacklist to contractor dropoff areas
  code/game/gamemodes/objective.dm
Labels: Tweak

#11458 Buffs borg hypos - Anti-radiation addition
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Feature, Tweak

#11455 Nerfs paper work - Again
  code/modules/cargo/packs/misc.dm
Labels: Code Improvement, Tweak

#11290 Traitor classes: a new paradigm.
  code/__DEFINES/antagonists.dm
  code/datums/components/uplink.dm
  code/datums/mind.dm
  code/modules/antagonists/traitor/IAA/internal_affairs.dm
  code/modules/antagonists/traitor/classes/ai.dm
  code/modules/antagonists/traitor/classes/assassin.dm
  code/modules/antagonists/traitor/classes/freeform.dm
  code/modules/antagonists/traitor/classes/hijack.dm
  code/modules/antagonists/traitor/classes/human.dm
  code/modules/antagonists/traitor/classes/martyr.dm
  code/modules/antagonists/traitor/classes/subterfuge.dm
  code/modules/antagonists/traitor/classes/traitor_class.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/uplink/uplink_items.dm
  tgstation.dme
Labels: Feature

#11479 Fixing some GetElement runtimes.
  code/__HELPERS/game.dm
  code/datums/elements/ghost_role_eligibility.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  tgstation.dme
Labels: Fix, Priority: High

#11477 Nerfs beam rifles and fixes the reflection bugs
  code/modules/projectiles/guns/misc/beam_rifle.dm
Labels: Balance/Rebalance

#11475 fixes the swapping of buttons in robotics console lockdown
  code/game/machinery/computer/robot.dm
Labels: Fix

#11474 halves the firebeath mutation's cooldown to 1 minute from 2 minutes
  code/datums/mutations/actions.dm
Labels: Balance/Rebalance

#11462 Fixing some bug reports.
  code/controllers/subsystem/jukeboxes.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/stacks/wrap.dm
  code/modules/admin/admin.dm
  code/modules/modular_computers/hardware/battery_module.dm
Labels: Fix

#11465 duffel bags of holding
  code/game/objects/items/storage/backpack.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/back.dmi
  icons/obj/storage.dmi
Labels: Feature, Sprites

#11488 Fixed missing pipe by box vault
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#11496 "pickpocketing fixes for thieving gloves" or "I hate byond logic."
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#11483 mining borg nerfs - "they should be outclassed lategame"
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Removal

#11484 Fixing a couple issues with recyclers.
  code/game/machinery/recycler.dm
Labels: Fix

#11498 Replaced and added missing Diagnostic HUDSunglasses sprites
  code/modules/clothing/glasses/hud.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Fix, Sprites

#11500 Electrostaff Sprite Fix
  code/game/objects/items/twohanded.dm
  icons/mob/back.dmi
  icons/mob/inhands/weapons/staves_lefthand.dmi
  icons/mob/inhands/weapons/staves_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Fix, Sprites

#11503 Removes stun bullet .45/Kitchen Gun a lot more desirable for heavy duty cleaning!
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/projectiles/ammunition/ballistic/smg.dm
  code/modules/projectiles/boxes_magazines/external/smg.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
Labels: Balance/Rebalance, Removal

#11504 Fixes being unable to remove turret guns
  code/game/machinery/porta_turret/portable_turret.dm
Labels: Fix

#11493 Blacklists two custom item flasks in "get drink" proc
  code/__HELPERS/unsorted.dm
Labels: Fix

#11495 Ash walker camp tweak because Ghommie asked me to.
  _maps/map_files/Mining/Lavaland.dmm
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Map Edit

#11501 Ports "Makes iron sheets build the normal metal table again"
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Tweak

#11505 fixes ais being unable to undeploy from shells while stunned
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Fix

#11506 Big Box Brig Boogaloo (kevinzs requests and stuffs)
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#11494 Adds craftable HUDpatches, similar to the HoS'
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/glasses/hud.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Sprites

#11519 mentor fixes and improvements
  modular_citadel/code/modules/mentor/dementor.dm
  modular_citadel/code/modules/mentor/mentor_verbs.dm
  modular_citadel/code/modules/mentor/mentorpm.dm
  tgstation.dme
Labels: Feature, Fix

#11516 arrow craft nitpicking (alt title: "why are subtypes like this")
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/projectiles/ammunition/caseless/arrow.dm
  code/modules/projectiles/projectile/reusable/arrow.dm
Labels: Tweak

#11511 Let's just start with the shuttles.
  _maps/shuttles/arrival_cog.dmm
  _maps/shuttles/emergency_cog.dmm
  _maps/shuttles/labour_cog.dmm
  _maps/shuttles/whiteship_cog.dmm
  code/datums/shuttles.dm
Labels: Code Improvement, Feature, Map Edit

#11517 space hermit jankitude
  _maps/RandomRuins/SpaceRuins/spacehermit.dmm
Labels: Balance/Rebalance, Fix, Map Edit

#11520 stops validhunting geneticists from knowing exactly who is an is a vampire (and allows vampires genes)
  code/__DEFINES/traits.dm
  code/game/machinery/computer/dna_console.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/dna_injector.dm
  code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
Labels: Balance/Rebalance

#11518 Energy Gun Sprite cleanup and Animations
  icons/obj/guns/energy.dmi
Labels: Sprites

#11533 Corrects Edaggers being unable to enbed
  code/modules/paperwork/pen.dm
Labels: Fix

#11351 tasers are now as fast as disablers and 7 --> 14 tile range but do not have impact damage
  code/datums/status_effects/debuffs.dm
  code/modules/projectiles/projectile/energy/stun.dm
Labels: Balance/Rebalance

#11539 Rewrote waffle traitor flavor text
  code/modules/antagonists/traitor/classes/freeform.dm
Labels: Tweak

#11534 fermenting barrels now no longer get hit when taking liquids out
  code/modules/hydroponics/fermenting_barrel.dm
Labels: Code Improvement

#11507 Plastitanium Rapier: Sleepy Edition
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/storage/belt.dm
  code/modules/uplink/uplink_items/uplink_dangerous.dm
  icons/mob/belt.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items_and_weapons.dmi
Labels: Balance/Rebalance, Feature, Sprites

#11491 Make mass hallucination more admemeable
  code/modules/events/mass_hallucination.dm
Labels: Feature

#11352 Nerfs HoS taser and warden stun pump action blaster
  code/modules/projectiles/projectile/energy/stun.dm
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
Labels: Balance/Rebalance

#11532 fixes a box oopsies
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#11553 Hypereutactic blade properly slows you down again, adds set_slowdown() and hooks vv_edit_var for it
  code/game/objects/items.dm
  code/game/objects/items/twohanded.dm
Labels: Code Improvement, Fix

#11528 fixes beam rifles and some micro optimizations to projectiles and readds the chameleon gun for debugging
  code/game/objects/effects/temporary_visuals/projectiles/projectile_effects.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/projectiles/guns/misc/chameleon.dm
  code/modules/projectiles/projectile.dm
  tgstation.dme
Labels: Fix

#11541 removes xray from the gene pool (webedit edition)
  code/datums/mutations/combined.dm
Labels: Balance/Rebalance, Removal
