Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-09, with the labels that each got.

#13313 Makes plastitanium rapier not silently poison for pacifists.
  code/game/objects/items/melee/misc.dm
Labels: Balance/Rebalance

#13316 pref for hiding your ckey from roundend report
  code/__HELPERS/roundend.dm
  code/datums/mind.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/login.dm
Labels: Feature

#13310 Makes fusion analyze not assume we're still on fusion v5
  code/__HELPERS/type2type.dm
  code/game/objects/items/devices/scanners.dm
Labels: Fix

#13308 Adds a character saving unit test
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/character_saving.dm
Labels: Code Improvement

#13305 Removes growth pills and genital autosurgeons from the maint loot table. Shoves them in the kinkmates.
  code/_globalvars/lists/maintenance_loot.dm
  code/modules/vending/kinkmate.dm
Labels: Removal, Tweak

#13330 Banishing a few blemishes.
  code/__DEFINES/dcs/signals.dm
  code/datums/components/chasm.dm
  code/datums/diseases/advance/symptoms/fire.dm
  code/game/objects/items/crayons.dm
  code/modules/mining/equipment/wormhole_jaunter.dm
  code/modules/paperwork/photocopier.dm
Labels: Fix

#13325 Revert "removes two unused sprites"
  icons/mob/32x64.dmi
  icons/mob/cyborg/drakemech.dmi
Labels: Removal, Revert, Sprites

#13322 makes handle_speech in ipc accent actually return the speech args so ipcs can talk
  code/datums/accents.dm
Labels: Fix

#13338 Makes the character save test more verbose when failing.
  code/modules/unit_tests/character_saving.dm
Labels: Tweak

#13331 moves engineering projectors to the "tool designs" protolathe category
  code/modules/research/designs/misc_designs.dm
Labels: Tweak

#13333 adds anchored state/anchoring tip to supermatter shard examine text
  code/modules/power/supermatter/supermatter.dm
Labels: Tweak

#13335 Adds shivering/sweating notifications (in devman terms: readds the old temperature notifications)
  code/_onclick/hud/alert.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/screen_alert.dmi
Labels: Feature, Sprites

#13337 Compresses owo.ogg
  sound/voice/medbot/owo.ogg
Labels: Sound, Tweak

#13304 Revert "Buffs defib users by making them stop pulling automatically"
  code/game/objects/items/defib.dm
Labels: Revert

#13321 Makes ghost dojo hilbert hotel's numbers less trivially deducible.
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
Labels: Tweak

#13341 Nerfs random brain trauma a good deal.
  code/modules/events/brain_trauma.dm
Labels: Balance/Rebalance

#13339 Completely decouples events from dynamic.
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  code/modules/antagonists/disease/disease_event.dm
  code/modules/antagonists/revenant/revenant_spawn_event.dm
  code/modules/antagonists/swarmer/swarmer_event.dm
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/carp_migration.dm
  code/modules/events/communications_blackout.dm
  code/modules/events/dust.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/heart_attack.dm
  code/modules/events/ion_storm.dm
  code/modules/events/major_dust.dm
  code/modules/events/meteor_wave.dm
  code/modules/events/nightmare.dm
  code/modules/events/pirates.dm
  code/modules/events/portal_storm.dm
  code/modules/events/processor_overload.dm
  code/modules/events/radiation_storm.dm
  code/modules/events/spider_infestation.dm
  code/modules/events/vent_clog.dm
  code/modules/events/wormholes.dm
  tgstation.dme
Labels: Removal

#13289 heretics touchup
  code/datums/status_effects/debuffs.dm
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
  code/modules/antagonists/eldritch_cult/eldritch_effects.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/eldritch_cult/knowledge/ash_lore.dm
  code/modules/antagonists/eldritch_cult/knowledge/flesh_lore.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
  icons/effects/mouse_pointers/mute_target.dmi
  icons/mob/actions/actions_ecult.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/eldritch.dmi
Labels: Sprites

#13348 Thermomachine boards (Freezer/Heater) now tell you how to change their pipe layer
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Tweak

#13244 Blacksmithing 2: Anarcho-Primitivist Assistants (travis don't fail on me now)
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/datums/materials/basemats.dm
  code/datums/skills/_skill_holder.dm
  code/datums/skills/blacksmithing.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/belt.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/cargo/packs/misc.dm
  code/modules/mining/equipment/mineral_scanner.dm
  code/modules/smithing/anvil.dm
  code/modules/smithing/finished_items.dm
  code/modules/smithing/furnace.dm
  code/modules/smithing/smithed_items.dm
  icons/obj/clothing/belts.dmi
  icons/obj/smith.dmi
  tgstation.dme
Labels: Feature, Sprites

#13279 alternate to 13728 - 60% rngblock, activeblock covers sides, effectiveness against projectiles upped
  code/game/objects/items/dualsaber.dm
Labels: Balance/Rebalance

#13311 Makes pool actually check for reagents
  code/modules/pool/pool_controller.dm
Labels: Fix

#13073 you can no longer attack people with surgical tools if you are in help intent
  code/modules/surgery/tools.dm
Labels: Tweak

#13136 the station charter rename now disallows any name with characters above a single byte in length unless an admin edits it to allow unicode
  code/game/objects/items/charter.dm
Labels: Administration

#13246 anomaly manufacturing port from tg. supermatter anomaly generation nerfed to 20% rather than removed
  code/__DEFINES/research/anomalies.dm
  code/controllers/subsystem/research.dm
  code/game/machinery/_machinery.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/modules/cargo/packs/science.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/research/anomaly/explosive_compressor.dm
  code/modules/research/anomaly/raw_anomaly.dm
  tgstation.dme
Labels: Feature

#13287 Reverts load delays because it's still a problem and by god am I just done at this point
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/guns/ballistic.dm
Labels: Revert

#13332 makes magweapons emp-immune
  code/modules/projectiles/guns/ballistic/magweapon.dm
Labels: Balance/Rebalance

#12452 Miner Loot Shuffle MK III
  _maps/shuttles/emergency_arena.dmm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/lavaland/necropolis_tendril.dm
  code/modules/library/lib_items.dm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/legionnaire.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/pandora.dm
  code/modules/projectiles/ammunition/special/magic.dm
  code/modules/projectiles/guns/magic/spell_book.dm
  code/modules/projectiles/projectile/magic/spellcard.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/bottle.dm
  icons/obj/library.dmi
  icons/obj/mining.dmi
  tgstation.dme
Labels: Map Edit, Sound, Sprites, Stale, UI

#13358 Fixes a typo in anvil.dm
  code/modules/smithing/anvil.dm
Labels: Grammar and Formatting

#13334 Revert Drakeborgs
  code/game/objects/items/plushes.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/cyborg/Drakeborg-licensing.txt
  icons/mob/cyborg/drakemech.dmi
  icons/obj/license.txt
  icons/obj/plushes.dmi
  modular_citadel/icons/mob/widerobot.dmi
Labels: Awaiting further discussion/approval, Revert, Sprites

#13359 Turf visuals fix plus corrected names of a couple things.
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/atoms.dm
  code/datums/components/fantasy/prefixes.dm
  code/datums/elements/decal.dm
  code/game/objects/effects/decals/decal.dm
  code/modules/cargo/packs/goodies.dm
  code/modules/clothing/under/costume.dm
Labels: Fix, Grammar and Formatting

#13360 Silicon death sounds or "Cease shooting the malfunctioning metal doorknob at the tone"
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/silicon.dm
  sound/voice/borg_deathsound.ogg
  sound/voice/scream/android_scream.ogg
Labels: Sound

#13344 Makes heat conduction work for the first time ever
  byond-extools.dll
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor/reinf_floor.dm
  code/game/turfs/simulated/wall/mineral_walls.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
Labels: Fix

#13378 Makes superconducting turfs not get stuck at incredibly low temperatures.
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
Labels: Balance/Rebalance

#13385 Minesweeper no longer blows up your ears when you select "Play on the same board"
  code/game/machinery/computer/arcade/minesweeper.dm
Labels: Fix

#13381 fix pill button on chemical press
  code/modules/plumbing/plumbers/pill_press.dm
Labels: Fix

#13377 Adds some unit tests for reactions.
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/unit_tests/reactions.dm
Labels: Code Improvement

#13374 Slimepeople diet preference changes
  code/__DEFINES/food.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/food/snacks_frozen.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/food/snacks_pizza.dm
  code/modules/food_and_drinks/food/snacks_salad.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/food_and_drinks/food/snacks_vend.dm
  code/modules/hydroponics/grown/ambrosia.dm
  code/modules/hydroponics/grown/cannabis.dm
  code/modules/hydroponics/grown/citrus.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Feature, Tweak

#13373 Fixed toggleable polychromic hoods/helmets not polychroming with their suit
  code/datums/elements/polychromic.dm
  code/modules/clothing/suits/toggles.dm
Labels: Fix

#13370 [s] Lets not have certain irreplacable things get qdel()d by one simple trick
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
Labels: Balance/Rebalance

#13369 the PR I really didn't want to make - poplocks revolvers to 15 people
  code/modules/uplink/uplink_items/uplink_dangerous.dm
Labels: Balance/Rebalance, Salt

#13368 Cogstation Fixes and Improvements
  _maps/map_files/CogStation/CogStation.dmm
  code/game/machinery/mass_driver.dm
Labels: Code Improvement, Fix, Map Edit, Tweak

#13363 Signalizes ling/bloodsucker life code.
  code/__DEFINES/dcs/signals.dm
  code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/life.dm
Labels: Refactor

#13389 Donator Item - Halo
  icons/mob/clothing/custom_w.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#13396 fixes travis
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Tweak

#13365 Hey wait isn't there numbers between 11 and 15
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Fix

#13362 Fixes organ fluid production.
  code/modules/arousal/arousal.dm
  code/modules/arousal/genitals.dm
Labels: Fix

#13387 New Brain Damage Line
  strings/traumas.json
Labels: Feature

#13388 Adds peculiar plushies, which are made by failing to make plushmium
  code/datums/mood_events/generic_negative_events.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/plushes.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Feature, Fix

#13255 you can choose limbs to be prosthetic/amputated
  code/__DEFINES/loadout.dm
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/ticker.dm
  code/datums/traits/negative.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/dummy.dm
  icons/mob/augmentation/cosmetic_prosthetic/bishop.dmi
  icons/mob/augmentation/cosmetic_prosthetic/cybersolutions.dmi
  icons/mob/augmentation/cosmetic_prosthetic/grayson.dmi
  icons/mob/augmentation/cosmetic_prosthetic/hephaestus.dmi
  icons/mob/augmentation/cosmetic_prosthetic/nanotrasen.dmi
  icons/mob/augmentation/cosmetic_prosthetic/talon.dmi
  icons/mob/augmentation/cosmetic_prosthetic/ward.dmi
  icons/mob/augmentation/cosmetic_prosthetic/xion.dmi
Labels: Feature, Sprites

#13404 Hopefully fixes icon overlay issue for the halo
  icons/obj/custom.dmi
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#13401 Porting new chess sprites
  icons/obj/chess.dmi
Labels: Feature, Sprites

#13394 Some bodypart-related fixes
  code/game/objects/items/stacks/medical.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#13399 fixes linter issues, removes acid degrading armor
  code/controllers/subsystem/persistence.dm
  code/datums/mutations/_mutations.dm
  code/game/objects/items/devices/portable_chem_mixer.dm
  code/game/objects/obj_defense.dm
  code/modules/antagonists/bloodsucker/powers/brawn.dm
  code/modules/antagonists/bloodsucker/powers/feed.dm
  code/modules/paperwork/ticketmachine.dm
  code/modules/recycling/disposal/bin.dm
Labels: Removal

#13403 fixes joystick users getting kicked for hacking. again.
  code/__DEFINES/admin/keybindings.dm
Labels: Priority: High

#13382 hulks no longer break their hand from punching a wall
  code/game/turfs/simulated/walls.dm
Labels: Balance/Rebalance

#13364 projectile process invoke async because people keep breaking shit and trying to enforce do not sleep on it is a moot point because people keep breaking shit
  code/modules/projectiles/projectile.dm
Labels: Priority: CRITICAL

#13410 added wrong state for halo and skirt, fixed with this
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
Labels: Sprites

#13408 Get in the damn robot, Skylar
  code/modules/clothing/under/miscellaneous.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#13402 copying prefs always regenerates icons now (attempt to stop preview icons being outright wrong)
  code/modules/client/preferences.dm
Labels: Tweak

#13393 [Ready] Donator Item - Custom Skirt
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Needs Review, Sprites

#13430 Removes removeNullsFromList, cause it doesn't work.
  code/__HELPERS/_lists.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/events/brand_intelligence.dm
Labels: Fix, Removal

#13426 Gives IPCs hair.
  code/modules/mob/living/carbon/human/species_types/ipc.dm
Labels: Feature

#13433 Makes holosigns uncontaminable
  code/game/objects/structures/holosign.dm
Labels: Tweak

#13286 heterochromia: you can select individual eye colours
  code/__DEFINES/DNA.dm
  code/datums/dna.dm
  code/game/objects/items/implants/implant_hijack.dm
  code/game/objects/structures/mirror.dm
  code/modules/admin/create_mob.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/fugitive/fugitive_outfits.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/organs/eyes.dm
  icons/mob/human_face.dmi
Labels: Feature, Sprites

#13397 Micro Powered Fans!
  code/game/machinery/poweredfans/fan_assembly.dm
  code/game/machinery/poweredfans/poweredfans.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  icons/obj/poweredfans.dmi
  tgstation.dme
Labels: Feature, Sprites

#13411 Eris Chair Port and Bed Sprite Improvements
  icons/obj/bedsheets.dmi
  icons/obj/chairs.dmi
  icons/obj/objects.dmi
Labels: Sprites, Tweak

#13412 Removed the supermatter sabotage objective; reworked non-murder MI13 objective picking.
  code/game/gamemodes/objective_sabotage.dm
  code/modules/antagonists/traitor/classes/subterfuge.dm
Labels: Balance/Rebalance, Removal

#13413 Properly standardizes fuid production rate.
  code/__DEFINES/citadel_defines.dm
  code/modules/arousal/genitals.dm
Labels: Balance/Rebalance

#13414 Fixed an erroneous comment that may cause issues.
  code/modules/mob/living/life.dm
Labels: Grammar and Formatting

#13415 Sprite Improvements! Jetpacks, TEG, Antimatter.
  icons/obj/machines/antimatter.dmi
  icons/obj/power.dmi
  icons/obj/tank.dmi
Labels: Sprites

#13419 Adds engineering hazard jumpsuits
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#13420 Light replacer can print at Engineering
  code/modules/research/designs/misc_designs.dm
Labels: Feature

#13421 alters the TEG's logistic power generation
  code/modules/power/generator.dm
Labels: Tweak

#13424 Makes cryo pods no longer replace already-won objectives.
  code/game/machinery/cryopod.dm
Labels: Tweak

#13427 More animated drinks
  icons/obj/drinks.dmi
Labels: Sprites, Tweak

#13432 Tweaks a thing
  code/modules/research/designs/tool_designs.dm
Labels: Tweak

#13437 turrets will now break instead of magically poofing out of existence
  code/game/machinery/_machinery.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/machinery/porta_turret/portable_turret_construct.dm
Labels: Fix

#13439 Fixes a 5+ year old bug with ghost poly's hex value that potentially causes runtimes and crashes.
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Fix

#13462 fixes a typo causing your right eye colour to save as the left eye colour
  code/modules/client/preferences_savefile.dm
Labels: Fix

#13416 Unique slimeperson screams and laughter, and adds new customizable speech verbs
  code/_globalvars/lists/flavor_misc.dm
  code/modules/mob/living/emote.dm
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/sound/voice/scream_jelly_f1.ogg
  modular_citadel/sound/voice/scream_jelly_f2.ogg
  modular_citadel/sound/voice/scream_jelly_m1.ogg
  modular_citadel/sound/voice/scream_jelly_m2.ogg
  sound/voice/jelly/manlaugh1.ogg
  sound/voice/jelly/manlaugh2.ogg
  sound/voice/jelly/nyaha.ogg
  sound/voice/jelly/nyahaha1.ogg
  sound/voice/jelly/nyahaha2.ogg
  sound/voice/jelly/nyahehe.ogg
  sound/voice/jelly/womanlaugh.ogg
Labels: Sound
