Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-07, with the labels that each got.

#12654 readds bohbombing
  code/datums/components/storage/concrete/bag_of_holding.dm
Labels: Fix

#12659 removes sexchem jumpsuit ripping
  modular_citadel/code/datums/status_effects/chems.dm
Labels: Removal

#12647 attempts to port Wizard Gamemode now ends when all wizards and wizard apprentices are dead #47514
  code/game/gamemodes/wizard/wizard.dm
Labels: Tweak

#12620 Gives Omega Station genpop.
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Map Edit

#12656 Fixing two handed items and etcetera.
  code/datums/components/twohanded.dm
  code/game/objects/items/RCL.dm
  code/game/objects/items/dualsaber.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/toys.dm
Labels: Fix

#12407 Much better looking lava land ruins!
  _maps/RandomRuins/AnywhereRuins/fountain_hall.dmm
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_alien_nest.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_biodome_winter.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_envy.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_gluttony.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_greed.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pride.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_sloth.dmm
Labels: Map Edit

#12631 Nerfing shaft miners' paycheck.
  code/modules/jobs/job_types/shaft_miner.dm
Labels: Balance/Rebalance

#12632 Ups melee stam cost multiplier from 0.8 back to 1, made stam cost for throwing mobs scale with mob_size
  code/__DEFINES/combat.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Balance/Rebalance

#12630 You can't (un)equip garments on/from obscured inventory slots anymore.
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/mob/living/simple_animal/friendly/drone/inventory.dm
  code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
  code/modules/mob/mob.dm
Labels: Feature

#12661 Fix broken UI icons
  code/modules/asset_cache/asset_list_items.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/research/rdconsole.dm
  code/modules/vending/_vending.dm
  tgui-next/packages/tgui/interfaces/Vending.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Fix, Tweak, UI

#12657 Witch hunter hat tweak.
  code/game/objects/items/holy_weapons.dm
Labels: Tweak

#12670 PLEASE SANITIZE PREFERENCES PLEASE ALWAYS SANITIZE PREFERENCES NEVER DONT SANITIZE PREFERENCES EVERYONE HAS A NULL SPEECH VERB
  code/modules/client/preferences_savefile.dm
Labels: Priority: High

#12666 More blood fixes
  code/modules/reagents/reagent_containers/blood_pack.dm
Labels: Fix

#12674 Actually fixing a feature.
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix

#12671 Fix Pilltype button (for real this time).also fix technode icon missing.
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/research/rdconsole.dm
Labels: Fix

#12665 retextures titanium walls (tg#50454)
  icons/obj/doors/airlocks/shuttle/overlays.dmi
  icons/obj/doors/airlocks/shuttle/shuttle.dmi
  icons/obj/smooth_structures/shuttle_window.dmi
  icons/obj/stack_objects.dmi
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
  icons/turf/walls/shuttle_wall.dmi
Labels: Sprites, Tweak

#12668 Hardsuit strip menu helmet toggle
  code/modules/mob/living/carbon/human/human.dm
Labels: Feature

#12683 refactors how blood dna color is stored so we don't have 1.7 million colors in a list
  code/game/atoms.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Priority: High, Refactor

#12672 add crushed sodacan and some digitigrade uniform sprite.
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/medical.dm
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/janitor.dmi
Labels: Feature, Sprites

#12685 Silences the skill panel check_rights() call.
  code/datums/skills/_check_skills.dm
Labels: Fix

#12658 slightly tweaks the cooking oil damage formula
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Tweak

#12677 Fixes items' skills list keys missing associated traits and improves modulability a little.
  code/__DEFINES/skills/defines.dm
  code/_onclick/item_attack.dm
  code/datums/skills/_skill.dm
  code/datums/skills/_skill_holder.dm
  code/game/objects/items.dm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/mining/ores_coins.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/power/lighting.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Fix

#12660 Reverts improv small arms, makes guncrafting easier and faster
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/tools/saw.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tools.dm
  tgstation.dme
Labels: Removal, Revert

#12593 adds verb to auto bunker override on linked servers
  code/controllers/configuration/entries/comms.dm
  code/datums/world_topic.dm
  code/modules/client/client_defines.dm
  code/modules/client/verbs/autobunker.dm
  tgstation.dme
Labels: Config Update, Feature

#12652 cybernetic implant shields will now automatically extend and be used to block if the user has no item to block with
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items/shields.dm
  code/modules/mob/living/living_active_block.dm
  code/modules/mob/living/living_active_parry.dm
  code/modules/surgery/organs/augments_arms.dm
Labels: Balance/Rebalance, Feature

#12650 adds a keybind to toggle active blocking instead of only press-hold
  code/modules/keybindings/keybind/combat.dm
Labels: Tweak

#12651 lowers shield blocking stamcost/second 3.5 to 2.5
  code/game/objects/items/shields.dm
Labels: Balance/Rebalance

#12699 Shifts South Dir of Silver LWraps Right 1px
  icons/mob/clothing/feet_digi.dmi
Labels: Sprites, Tweak

#12688 [READY] Fixes Small Strides Formula
  code/datums/dna.dm
  code/modules/client/preferences.dm
Labels: Fix, Needs Review, Tweak

#12698 Fixes Bee Balm
  code/modules/hydroponics/grown/flowers.dm
  icons/obj/hydroponics/growing_flowers.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Fix, Sprites

#12684 Food ports, tweaks, and fixes.
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  icons/obj/food/burgerbread.dmi
  icons/obj/food/food.dmi
Labels: Feature, Fix, Sprites, Tweak

#12697 Updates Cog's chemistry lab.
  _maps/map_files/CogStation/CogStation.dmm
Labels: Map Edit

#12702 [s] Fixes the 'Kill once' objective
  code/game/gamemodes/objective.dm
Labels: Fix

#12694 mowing down experimental cloner copypasta.
  _maps/RandomRuins/SpaceRuins/cloning_facility.dmm
  code/__DEFINES/machines.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  code/game/machinery/exp_cloner.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
  tgstation.dme
Labels: Map Edit

#12648 bluespace tray + bluespace jar
  code/game/objects/items/pet_carrier.dm
  code/game/objects/items/storage/bags.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/techweb/nodes/bluespace_nodes.dm
  icons/obj/food/containers.dmi
  icons/obj/pet_carrier.dmi
Labels: Feature, Sprites

#12700 Post This Ratvar, OR how I regained my contributor role in one simple step, OR how I buffed clock cult unknowingly.
  code/game/objects/effects/contraband.dm
  icons/obj/contraband.dmi
Labels: Feature, Sprites

#12710 Fixes hair falling out of hoodies
  code/modules/clothing/suits/toggles.dm
Labels: Fix

#12712 Hey, what if you could actually make the donuts?
  code/modules/hydroponics/grown/peas.dm
Labels: Fix

#12707 Resprited brains into a new slime core sprite for jelly people.
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  icons/obj/surgery.dmi
Labels: Sprites

#12708 Adds a pool to PubbyStation.
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#12732 removes a stray pixel from the muzzled clearmasks
  icons/mob/clothing/mask_muzzled.dmi
Labels: Fix, Removal, Sprites

#12720 port examines and eye contact
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/mind.dm
  code/datums/traits/negative.dm
  code/game/atoms.dm
  code/game/machinery/computer/arcade/battle.dm
  code/game/objects/items/cards_ids.dm
  code/modules/client/client_defines.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/paper.dm
Labels: Feature

#12717 Wedding crate
  code/modules/cargo/packs/costumes_toys.dm
Labels: Feature

#12716 Adds more emojis
  code/modules/asset_cache/asset_list_items.dm
  code/modules/emoji/emoji_parse.dm
  icons/emoji_32.dmi
Labels: Sprites

#12725 Robocog.
  _maps/map_files/CogStation/CogStation.dmm
Labels: Map Edit

#12711 [s] Updates goonchat [ready]
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/chat.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/html/browserOutput.html
  code/modules/goonchat/browserassets/js/browserOutput.js
  code/modules/mob/living/say.dm
  config/in_character_filter.txt
Labels: Config Update, Needs Review

#12726 lambda now has a center gateway and (should) works
  _maps/map_files/LambdaStation/lambda.dmm
Labels: Map Edit

#12713 Popping the north monastery tunnel on Pubby
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Removal

#12714 Fixes / Buffs sentinels compromise to heal augmented bodyparts aswell.
  code/modules/antagonists/clockcult/clock_helpers/slab_abilities.dm
Labels: Balance/Rebalance

#12715 Drinkable and Sell-able Telecrystals
  code/game/objects/items/stacks/telecrystal.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature, Tweak

#12722 lowers wisdom cow's spawnrate to standard and makes it 66% less spammy
  code/modules/events/wisdomcow.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Tweak

#12624 policy configuration & support hooks for clone memory disorder
  code/__DEFINES/configuration.dm
  code/controllers/configuration/config_entry.dm
  code/controllers/configuration/entries/policy.dm
  code/game/machinery/cloning.dm
  code/game/objects/items/defib.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/surgery/advanced/revival.dm
  config/config.txt
  config/policy.txt
  tgstation.dme
Labels: Administration, Config Update

#12693 Trashbag Whitelist Update
  code/game/objects/items/storage/bags.dm
Labels: Balance/Rebalance, Tweak

#12743 Updates on some of the legals
  sound/ambience/license.txt
  sound/effects/license.txt
Labels: Sound

#12752 vore no longer breaks preferences
  code/modules/vore/eating/bellymodes.dm
  code/modules/vore/eating/living.dm
Labels: Fix

#12746 chemical reactions now have priority - "the first grenade helped with the revenant and the second blew up the evacuation shuttle"
  code/__DEFINES/chemistry/reactions.dm
  code/__HELPERS/cmp.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  tgstation.dme
Labels: Feature

#12737 hey can we not have circuit fusion bombs
  code/modules/integrated_electronics/subtypes/reagents.dm
Labels: Fix

#12706 adds security/medical records to character setup
  code/datums/datacore.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Feature

#12736 hey let's not have 25% micro borgs going around killing people
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Fix

#12747 refactors circuit screens a bit, no more messages coming out of the floor
  code/modules/integrated_electronics/subtypes/output.dm
Labels: Refactor

#12764 [s] ports a patch that stops coins crashing the server
  code/game/objects/items/cards_ids.dm
  code/modules/mining/mint.dm
Labels: Fix

#12770 FUCK
  code/modules/mob/living/carbon/life.dm
Labels: Priority: High

#12760 Fix Paramedic Jumpsuit
  code/modules/clothing/under/jobs/medical.dm
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
Labels: Fix, Sprites

#12738 the travelling trader midround event
  code/game/objects/items/kitchen.dm
  code/game/objects/items/pet_carrier.dm
  code/game/objects/items/stacks/tape.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/events/travelling_trader.dm
  code/modules/mining/money_bag.dm
  code/modules/mob/living/simple_animal/friendly/bumbles.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/reagents/reagent_dispenser.dm
  tgstation.dme
Labels: Feature, Fix

#12782 [s] coin related patch
  code/game/objects/items/cards_ids.dm
Labels: Fix

#12774 Fixes a zeolite runtime
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
Labels: Fix

#12783 Fixes seeing real name in OOC Notes
  code/datums/elements/flavor_text.dm
Labels: Fix

#12791 funniest shit i've ever seen
  code/__DEFINES/admin.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/living/simple_animal/pickle.dm
  code/modules/mob/transform_procs.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/energy/misc.dm
  code/modules/projectiles/projectile/magic.dm
  icons/mob/32x64.dmi
  tgstation.dme
Labels: Feature, Sprites

#12755 Adds new icon for Bluespace Jar
  icons/obj/pet_carrier.dmi
Labels: Sprites

#12798 [s] Ports lots of vunerability fix
  code/controllers/configuration/config_entry.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/title.dm
  code/datums/components/material_container.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/objs.dm
  code/game/turfs/closed.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/client/client_procs.dm
  code/modules/lighting/lighting_area.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/mint.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/living.dm
  code/modules/movespeed/_movespeed_modifier.dm
  code/modules/paperwork/folders.dm
  code/modules/power/cell.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/recycling/conveyor2.dm
  code/modules/shuttle/arrivals.dm
Labels: Administration, Fix

#12799 fixes a tiny pickle edge case
  code/modules/mob/living/simple_animal/pickle.dm
  code/modules/mob/transform_procs.dm
  icons/mob/32x64.dmi
Labels: Fix, Sprites

#12775 wrestling rotation fix
  code/datums/martial/wrestling.dm
Labels: Fix

#12776 snail shell backpack
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/back.dmi
  icons/obj/storage.dmi
Labels: Feature, Sprites

#12779 Circle Game, Updated
  code/game/objects/items/weaponry.dm
Labels: Feature, PRB: Reset

#12759 set hierophant friendly fire check to on by default
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Tweak

#12758 Adds another light to pubby next to the kitchen
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#12750 replaces plushies in the loadout menu with a choice box
  code/game/objects/items/miscellaneous.dm
  modular_citadel/code/modules/client/loadout/backpack.dm
Labels: Feature

#12733 Slime Extractification
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature

#12763 hopefully fixes records possibly
  code/game/machinery/computer/security.dm
Labels: Fix

#12762 drops martial art minpops down to twenty pop
  code/modules/uplink/uplink_items/uplink_stealth.dm
Labels: Tweak

#12761 A pool and lighting fixes for Delta Station.
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Map Edit

#12812 Makes pen uplink work again
  code/datums/components/uplink.dm
Labels: Fix

#12803 removes tango dancing
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: In Game Exploit, Removal

#12814 fixes gateways switching to active power use when thy should not be using power at all
  code/modules/awaymissions/gateway.dm
Labels: Priority: High

#12810 service borg fix/tweak
  code/game/objects/items/RSF.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix, Tweak

#12830 Fixes genewebs being impossibly impassable
  code/game/objects/effects/spiders.dm
Labels: Fix

#12646 [READY] Alt-click cigarette pack functionality added to pill bottles.
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomZLevels/away_mission/research.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/arrival_delta.dmm
  _maps/shuttles/arrival_omega.dmm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/RSF.dm
  code/game/objects/items/dice.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/vending/games.dm
  modular_citadel/code/modules/client/loadout/hands.dm
Labels: Do Not Merge, Feature, Map Edit, Needs Review

#12728 "I didn't see the map vote" - Adds a stat vote panel for plurality and approval voting as an alternative to the regular popups.
  code/controllers/subsystem/vote.dm
  code/modules/mob/mob.dm
Labels: Feature

#12766 adds a couple of emojis to 32x32
  icons/emoji_32.dmi
Labels: Sprites

#12786 makes survivalists pseudoantags again and limits summon guns/magic to one use
  code/game/gamemodes/objective.dm
  code/modules/antagonists/survivalist/survivalist.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Tweak

#12823 gravity now immediately updates on entering/exiting areas with different gravity and space meaning no more slow for 4 seconds while in a hardsuit and then fast with jetpack
  code/game/area/areas.dm
  code/game/turfs/space/space.dm
Labels: Fix

#12727 bandaids around turnstiles being bad code until it can have its movement checks refactored
  code/game/machinery/turnstile.dm
Labels: Refactor

#12749 Adds monophobia quirk.
  code/datums/traits/negative.dm
Labels: Feature

#12795 Makes extradimensional oranges weirder. [/TG/ PORT]
  code/modules/hydroponics/grown/citrus.dm
Labels: Feature

#12800 Fixes swarmers not being able to eat any items at all
  code/modules/antagonists/swarmer/swarmer.dm
Labels: Fix

#12804 Decal Painter ui fix
  code/game/objects/items/airlock_painter.dm
Labels: Fix

#12826 Makes damp rags no longer instantly apply chemicals
  code/modules/reagents/reagent_containers/rags.dm
Labels: Balance/Rebalance

#12805 This is stupid
  code/game/objects/items/devices/geiger_counter.dm
Labels: Tweak

#12807 lowers stray cargo pod weight from 2x normal to 1/2 normal
  code/modules/events/stray_cargo.dm
Labels: Tweak

#12811 removes the 2 best weapons in the game from traitor uplink's 10tc surgery bag
  code/game/objects/items/storage/backpack.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
Labels: Balance/Rebalance, Removal

#12829 the fried component
  code/__DEFINES/admin.dm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/unsorted.dm
  code/datums/components/edible.dm
  code/datums/components/fried.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/food/snacks_bread.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  tgstation.dme
Labels: Feature

#12787 Ports Medicated Sutures and Advanced Regenerative Mesh from TG
  code/game/objects/items/stacks/cash.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/tape.dm
  code/game/objects/items/stacks/wrap.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/paperwork/paper.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/vending/megaseed.dm
  icons/obj/hydroponics/growing_vegetables.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  icons/obj/stack_objects.dmi
Labels: Feature, Fix, Sprites

#12843 uhhhhhhh ok nothing to see here let's fix spell packets this time again
  code/modules/spells/spell_types/wizard.dm
Labels: Priority: High

#12824 makes brainwashing disk role restricted and debuffs its price
  code/modules/uplink/uplink_items/uplink_devices.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
Labels: Balance/Rebalance

#12852 This shit creeped me out so there's a good chance it creeps other people out
  strings/abductee_objectives.txt
Labels: Removal

#12851 maid fetish content pr
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/misc.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/kinkmate.dm
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/head.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  modular_citadel/code/modules/client/loadout/gloves.dm
  modular_citadel/code/modules/client/loadout/head.dm
Labels: Feature, Sprites

#12847 Chat queue optimization
  code/controllers/subsystem/chat.dm
Labels: Tweak

#12835 might fix necropolis chests turning up completely empty
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Fix

#12855 Unfucks the monophobia traits (Aswell as traits in general) with this one simple trick
  code/datums/traits/negative.dm
Labels: Fix

#12854 tipes
  code/__DEFINES/integrated_electronics.dm
Labels: Grammar and Formatting

#12856 ports tg radiation suits and also makes syndiekrav gloves actually visually distinct
  code/datums/martial/krav_maga.dm
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/head_muzzled.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/mob/clothing/taur_canine.dmi
  icons/mob/clothing/taur_hooved.dmi
  icons/mob/clothing/taur_naga.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#12860 Allows Photos to be Burned
  code/modules/photography/photos/photo.dm
Labels: Feature

#12866 Fixes Snaxi DMM Typos
  _maps/map_files/Snaxi/Snaxi.dmm
Labels: Fix, Map Edit

#12867 Expands OmegaStation's medical wing.
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Map Edit

#12869 the very much needed zombie buffs
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/zombie/items.dm
Labels: Tweak

#12809 Gripper brained. The medborg can do chemistry now, oh no.
  code/game/machinery/iv_drip.dm
  code/game/objects/items/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/obj/device.dmi
Labels: Sprites

#12828 Ports several food sprites/foods from Baystation/Citadel RP
  code/game/objects/items/storage/fancy.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  icons/obj/food/soupsalad.dmi
Labels: Feature, Sprites, Tweak

#12868 regarding manifest injections
  code/datums/datacore.dm
Labels: Priority: High

#12864 regarding changelings
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/absorb.dm
  code/modules/antagonists/changeling/powers/revive.dm
Labels: Priority: High

#12844 fixes traitor jobban link
  code/modules/admin/topic.dm
Labels: Priority: High

#12848 species customization now allows 16 million colors instead of 4 thousand
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
Labels: Tweak

#12846 it would be real lovely if the server didn't nuke 40 people's characters because the configuration couldn't be loaded because i really hate dll memes
  code/modules/client/preferences_savefile.dm
Labels: Priority: High

#12821 Increases projectile speed across the board by around 40-45%
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance

#12873 FUCK - rewrites sanitize_hexcolor to support converting from RGB to RRGGBB
  code/__HELPERS/mobs.dm
  code/__HELPERS/sanitize_values.dm
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
Labels: Priority: High

#12857 adds deep beepsky lore to the game in the form of hats
  code/datums/beepsky_fashion.dm
  code/datums/dog_fashion.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  icons/mob/secbot_accessories.dmi
  tgstation.dme
Labels: Feature, Sprites

#12878 maybe you should be able to see wound descriptions
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix

#12879 beepsky replaces THREAT_LEVEL with the actual threat
  code/modules/mob/living/simple_animal/bot/secbot.dm
Labels: Fix

#12909 [FUCK] Fixes organ decay
  code/__DEFINES/_flags/item_flags.dm
Labels: Fix

#12877 What if Meta Arrivals Weren't An Eye Sore?
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit, Tweak

#12872 Adds depth to the lick wounds mechanic.
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/wounds/cuts.dm
  code/game/objects/items/plushes.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  icons/obj/plushes.dmi
  sound/voice/catpeople/distressed.ogg
  sound/voice/catpeople/license.txt
  sound/voice/catpeople/puking.ogg
Labels: Feature, Good First PR, Sound, Sprites, Tweak

#12914 forensic scanners no longer pick up color in blood dna
  code/modules/detectivework/scanner.dm
Labels: Fix

#12881 since it's a little hard to fix the actual issue let's just make the projectile safety check that's causing stuff to freeze when something goes wrong more lenient so things don't freeze and people don't think anything is wrong
  code/modules/projectiles/projectile.dm
Labels: Priority: High

#12871 ports some tg changes to make clients properly garbage collect
  code/modules/client/client_procs.dm
Labels: MANUALLY CHECK TRAVIS - IGNORE BUILD STATUS

#12893 pickles don't die until their contents is released
  code/modules/mob/living/simple_animal/pickle.dm
Labels: Fix

#12863 clown mobss are now allied to each other and clownops are now allied to clown mobs
  code/game/gamemodes/clown_ops/clown_ops.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
Labels: Feature

#12895 Training Bokkens - "funny wood sticks for parrying and beating the shit out of people"
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/weaponry.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mining/equipment/marker_beacons.dm
  code/modules/mob/living/living_active_parry.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/lighting.dmi
Labels: Feature, Fix, Sprites

#12896 makes some small tweaks to pet carriers / bluespace jars
  code/game/objects/items/pet_carrier.dm
Labels: Fix

#12903 removes zoomba/roomba borg sprites
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robots.dmi
Labels: Removal, Sprites

#12917 FIXES. STUNBATONS. FOR. THE LAST. TIME - WINGET IS A SLEEP() AND NO ONE REALIZED THAT MAKING BATONS MAKE PEOPLE -GLORF WOULD MAKE THEM BREAK UNDER LAG
  code/modules/mob/living/carbon/human/say.dm
Labels: Priority: CRITICAL

#12817 boosts stimpak cost back up to 5 from 3
  code/modules/uplink/uplink_items/uplink_devices.dm
Labels: Balance/Rebalance

#12876 tidies up species files
  code/__DEFINES/is_helpers.dm
  code/modules/clothing/clothing.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/angel.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/carbon/human/species_types/xeno.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/emote.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  tgstation.dme
Labels: Tweak

#12899 literally adds 3 pixels across the board for paper masks
  icons/mob/clothing/mask.dmi
Labels: Sprites

#12901 Adds spaceman's trumpet seeds to the exotic seeds crate
  code/modules/cargo/packs/organic.dm
Labels: Tweak

#12916 Metastation atmos and toxins map update
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit

#12918 Minor paramed edit
  code/datums/traits/negative.dm
Labels: Tweak

#12920 Ports the Black Box theft objective from TG
  code/game/gamemodes/objective_items.dm
  code/game/machinery/telecomms/machines/message_server.dm
  icons/obj/stationobjs.dmi
Labels: Feature, Sprites

#12921 Adds tags to applicable clothing, stating the defenses and resistances said clothes have.
  code/modules/clothing/clothing.dm
Labels: Feature

#12923 Adds more toilets, among other things to Snow Taxi.
  _maps/map_files/Snaxi/Snaxi.dmm
Labels: Map Edit

#12927 ZOMBIES. ACT LIKE ONE.
  code/modules/zombie/organs.dm
Labels: Tweak

#12934 Miscellaneous fixes to Kilo Station and a Fan for the Listening Outpost
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Fix, Map Edit, Tweak
