Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-11, with the labels that each got.

#13567 slime puddles look better and cant be abused by lings
  code/__DEFINES/traits.dm
  code/datums/components/squeak.dm
  code/datums/mutations/_mutations.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/movespeed/modifiers/innate.dm
  icons/mob/mob.dmi
Labels: Sprites, Tweak

#13648 Fixes a bunch of fallout from the tgui PR
  code/game/machinery/announcement_system.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/dna_scanner.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/implants/implant_hijack.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/events/pirates.dm
  code/modules/mining/laborcamp/laborstacker.dm
  code/modules/power/apc.dm
  code/modules/spells/spell_types/lichdom.dm
  tgui/packages/tgui/interfaces/RoboticsControlConsole.js
  tgui/public/tgui.bundle.js
Labels: Fix, UI

#13647 adds a /obj/effect/landmark/barthpot to boxstation so jacqueline actaully spawns on boxstation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#13629 kills wallnomalies
  code/modules/events/anomaly.dm
Labels: Removal

#13633 Fixes the Layer 3 Outlet Injector mapping asset being on the wrong layer
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
Labels: Fix

#13632 corrects the time for the memory loss message to show when being revived to 300 seconds instead of 30
  code/game/objects/items/defib.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/surgery/advanced/revival.dm
Labels: Fix

#13623 removes batform from roundstart halloween vampire
  code/__DEFINES/species.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
Labels: Priority: High, Removal

#13521 [READY] Rebalances zeolites and their reaction
  code/modules/reagents/chemistry/machinery/chem_heater.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Balance/Rebalance, Needs Review

#13604 Makes welder code better*
  code/game/objects/items/tools/weldingtool.dm
Labels: Balance/Rebalance, Code Improvement

#13602 Adds a new "minor antag" roundstart to dynamic
  code/__DEFINES/dynamic.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_minor.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  tgstation.dme
Labels: Feature

#13618 new jungle gateway map
  _maps/RandomZLevels/away_mission/jungleresort.dmm
  code/modules/awaymissions/mission_code/jungleresort.dm
  config/awaymissionconfig.txt
  tgstation.dme
Labels: Config Update, Feature, Map Edit

#13630 character size scaling
  code/controllers/configuration/entries/game_options.dm
  code/datums/dna.dm
  code/modules/client/preferences.dm
  config/game_options.txt
Labels: Config Update, Feature

#13635 bone gauntlets bandaid nerf
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance

#13637 TGS DMAPI Updater deletes old files
  .github/workflows/update_tgs_dmapi.yml
Labels: Github

#13639 More guns can be suppressed
  code/modules/projectiles/guns/ballistic/pistol.dm
  icons/obj/guns/projectile.dmi
Labels: Sprites, Tweak

#13641 Nerfs combat knife damage
  code/game/objects/items/kitchen.dm
Labels: Balance/Rebalance

#13659 admins loading gateways will no longer crash the server
  code/controllers/subsystem/mapping.dm
Labels: Fix

#13658 Changes to void volt and the clock power_drain() proc
  code/modules/antagonists/clockcult/clock_helpers/clock_powerdrain.dm
  code/modules/antagonists/clockcult/clock_scripture.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_scripts.dm
Labels: Balance/Rebalance, Fix

#13657 Fixes transmission sigil power drain
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
Labels: Fix

#13656 More time for admins to cancel events
  code/modules/events/_event.dm
Labels: Administration

#13655 fixes held items proccing crossed when passing someone
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#13654 Christmas Tree / Jacqueen Gift Blacklist
  code/game/objects/items/gift.dm
  code/modules/holiday/halloween/jacqueen.dm
Labels: Fix

#13653 A few fixes to kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Map Edit, Tweak

#13664 Donator - Exo Frame
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#13669 Makes cult sacrifice not permakill people anymore.
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/controllers/subsystem/traumas.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/storage/book.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/holiday/halloween/halloween.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/transform_procs.dm
Labels: Tweak

#13682 Trying to figure out what's up with CogStation...
  _maps/map_files/CogStation/CogStation.dmm
Labels: Map Edit

#13683 Attempts to turn gift static blacklist into a global list
  code/game/objects/items/gift.dm
Labels: Code Improvement

#13678 Comments out spacemandmm should not sleeps
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/living/life.dm
Labels: Code Improvement

#13644 [READY] Hybrid bodyparts - wound surgery edition
  code/datums/wounds/_wounds.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/surgery/bone_mending.dm
  code/modules/surgery/burn_dressing.dm
  code/modules/surgery/mechanic_steps.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/repair_puncture.dm
  code/modules/surgery/surgery_step.dm
Labels: Balance/Rebalance, Needs Review

#13671 Just some more clock rite code-wise support
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
  code/modules/antagonists/clockcult/clock_helpers/clock_rites.dm
Labels: Code Improvement

#13673 Makes construct mind saving reference the mind, fixing some issues
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/mob/living/simple_animal/constructs.dm
Labels: Fix

#13674 The borg VTEC ability no longer persists after the upgrade is removed
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Fix

#13675 Fixes sleeper UI Interactiveness
  code/game/machinery/Sleeper.dm
Labels: Fix

#13676 Very minor fix to clockie borg slab ui
  code/modules/antagonists/clockcult/clock_items/clockwork_slab.dm
Labels: Fix

#13681 Fixes a bunch of supplypod related stuff
  code/__DEFINES/is_helpers.dm
  code/datums/components/pellet_cloud.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  code/modules/antagonists/traitor/syndicate_contract.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/cargo/supplypod.dm
  code/modules/events/stray_cargo.dm
Labels: Fix

#13680 Fixes a hallucination runtime
  code/modules/flufftext/Hallucination.dm
Labels: Fix

#13688 Oops - Repeatable Surgery Edition
  code/modules/surgery/surgery_step.dm
Labels: Fix

#13672 chief sub
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
Labels: Grammar and Formatting

#13662 re-allows angel species on magic mirrors
  code/game/objects/structures/mirror.dm
Labels: Feature, MANUALLY CHECK TRAVIS - IGNORE BUILD STATUS

#13679 [TESTMERGE ONLY] System Corruption for robotic species
  code/__DEFINES/DNA.dm
  code/__DEFINES/combat.dm
  code/__DEFINES/radiation.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/computer/Operating.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/mob/living/carbon/alien/damage_procs.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/handle_corruption.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/damage_procs.dm
  code/modules/mob/living/silicon/pai/pai_defense.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
  code/modules/surgery/organs/augments_internal.dm
  code/modules/surgery/purge_corruption.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/OperatingComputer.js
  tgui/packages/tgui/interfaces/Sleeper.js
  tgui/public/tgui.bundle.js
Labels: Feature, UI

#13694 Local Assistant man can now bash rock again!*
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/mining_common_kilo.dmm
  _maps/shuttles/mining_common_meta.dmm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/mining/mine_items.dm
Labels: Feature, Map Edit

#13582 adds advanced colouring mode: allows you to individually colour mutant parts
  code/__DEFINES/citadel_defines.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/frills.dm
  code/modules/mob/dead/new_player/sprite_accessories/ipc_synths.dm
  code/modules/mob/dead/new_player/sprite_accessories/legs_and_taurs.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/dead/new_player/sprite_accessories/spines.dm
  code/modules/mob/dead/new_player/sprite_accessories/synthliz.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  icons/mob/human_parts_greyscale.dmi
  icons/mob/mutant_bodyparts.dmi
Labels: Feature, Fix, Sprites

#13686 Ports tgui whitescreen fixes
  .vscode/extensions.json
  .vscode/settings.json
  code/modules/tgui/tgui_window.dm
  tgui/.yarn/sdks/eslint/bin/eslint.js
  tgui/.yarn/sdks/eslint/package.json
  tgui/.yarn/sdks/integrations.yml
  tgui/global.d.ts
  tgui/packages/tgui-panel/styles/main.scss
  tgui/packages/tgui/assets.js
  tgui/packages/tgui/backend.js
  tgui/packages/tgui/debug/middleware.js
  tgui/packages/tgui/package.json
  tgui/packages/tgui/styles/components/FatalError.scss
  tgui/packages/tgui/styles/main.scss
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  tgui/public/tgui.html
  tgui/yarn.lock
Labels: Fix, UI

#13685 Ports: Admins can now see chronological order of events in logging tabs.
  code/__DEFINES/_flags/_flags.dm
  code/modules/admin/verbs/individual_logging.dm
  code/modules/client/verbs/looc.dm
  code/modules/mob/mob_helpers.dm
Labels: Fix, Refactor, UI

#13689 Fixes APC recharge power use
  code/modules/power/apc.dm
Labels: Fix

#13697 Makes spontaneous brain trauma require min 5 players.
  code/modules/events/brain_trauma.dm
Labels: Balance/Rebalance

#13703 Makes dynamic no longer show "none" in the vote.
  code/controllers/configuration/configuration.dm
Labels: Fix

#13702 Makes gear harness no longer cover chest/groin.
  code/modules/clothing/under/miscellaneous.dm
Labels: Tweak

#13707 Makes synthetics inherently immune to alcohol
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/traits/neutral.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Balance/Rebalance, Tweak

#13705 Buffs rad collectors
  code/modules/power/singularity/collector.dm
Labels: Balance/Rebalance

#13698 ports rebindable communication hotkeys from tg
  code/controllers/subsystem/input.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/keybindings/keybind/__defines.dm
  code/modules/keybindings/keybind/_keybind.dm
  code/modules/keybindings/keybind/communication.dm
  code/modules/keybindings/keybind/mob.dm
  code/modules/keybindings/keybind/movement.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/say.dm
  tgstation.dme
Labels: Feature

#13715 Trims sneaky opposum who snuck into boxstations' science
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Tweak

#13687 https://github.com/tgstation/tgstation/pull/54991 - tail intertwining
  code/modules/mob/living/living.dm
Labels: Feature

#13714 fixes admin rank copy not transferring over exclude/can_edit_rights
  code/modules/admin/permissionedit.dm
Labels: Priority: High
