Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-12, with the labels that each got.

#13721 moar crimmas
  code/modules/holiday/holidays.dm
Labels: Tweak

#13719 Ports construction bags and makes it easier to get material bags. (READY)
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  icons/obj/tools.dmi
Labels: Balance/Rebalance, Feature, Sprites

#13717 Mining and Monastery Shuttle Fixes
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01.dmm
  _maps/shuttles/mining_common_kilo.dmm
  _maps/shuttles/mining_common_meta.dmm
  code/modules/mining/mine_items.dm
  code/modules/shuttle/monastery.dm
Labels: Fix, Map Edit

#13720 podpeople have green blood but done correctly
  code/__DEFINES/misc.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
Labels: Tweak

#13733 Tailcoilies fix
  code/modules/mob/living/living.dm
Labels: Fix

#13711 Medibots now only treat those they can actually treat
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: Tweak

#13736 Makes the experimental organ replacement surgery work on robots
  code/modules/antagonists/abductor/equipment/abduction_surgery.dm
Labels: Tweak

#13741 [s] Objective fixes : screaming lizard edition
  code/game/machinery/cryopod.dm
Labels: FUCK, Fix, Priority: CRITICAL

#13740 the biggest nitpick in the entire universe
  modular_citadel/icons/mob/mam_snouts.dmi
Labels: Fix

#13704 Makes emotes show up in the "local" filter with TGUI
  code/datums/emotes.dm
  code/modules/mob/say_vr.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
Labels: Fix, UI

#13738 Updates the heretics gamemode with a bunch of changes from /tg/
  code/__DEFINES/antagonists.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/status_effects/debuffs.dm
  code/modules/antagonists/eldritch_cult/eldritch_book.dm
  code/modules/antagonists/eldritch_cult/eldritch_effects.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/eldritch_cult/knowledge/ash_lore.dm
  code/modules/antagonists/eldritch_cult/knowledge/flesh_lore.dm
  icons/mob/actions/actions_ecult.dmi
Labels: Balance/Rebalance, Sprites

#13745 Adds more sanity to construct soul returning
  code/modules/mob/living/simple_animal/constructs.dm
Labels: Fix

#13739 custom eyes and tongues now properly carry across cloning
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#13747 Porting to the /tg/ sprite changes, and functionality, of large reagent containers
  code/modules/cargo/packs/materials.dm
  code/modules/reagents/reagent_dispenser.dm
  icons/obj/objects.dmi
Labels: Feature, Sprites, Tweak

#13617 loadout 2: electric boogaloo
  code/__DEFINES/loadout.dm
  code/controllers/subsystem/job.dm
  code/datums/elements/polychromic.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/_loadout.dm
  modular_citadel/code/modules/client/loadout/neck.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature, Work In Progress

#13737 Flash the screen on climax
  code/modules/arousal/arousal.dm
Labels: MEME PR, Salt

#13750 Fixes Delta's cargo conveyor problem.
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Map Edit

#13743 thunderdome entertainment monitors fix + stuff
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/camera/motion.dm
  code/game/machinery/computer/camera.dm
  code/modules/admin/secrets.dm
  code/modules/holiday/holidays.dm
  icons/obj/status_display.dmi
Labels: Feature, Fix, Map Edit, Sprites

#13713 all gas masks (but welding + glass) can be alt clicked to show/hide identity
  code/modules/clothing/masks/gasmask.dm
Labels: Feature

#13762 removes noteleport from luxury shuttle
  code/game/area/areas/shuttles.dm
Labels: Removal, Tweak

#13777 NO, you are allowed ONE roll of an overpowered item for christmas, NOT INFINITE
  _maps/templates/hilbertshotel.dmm
  code/modules/events/holiday/xmas.dm
Labels: Map Edit, Removal

#13766 New fancy dark gygax sprites
  icons/mecha/mecha.dmi
Labels: Sprites, Tweak

#13771 Better donuts boxes
  code/game/objects/items/storage/fancy.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  icons/obj/food/containers.dmi
  icons/obj/food/donut.dmi
Labels: Sprites, Tweak

#13765 Fancier jukebox sprites
  icons/obj/stationobjs.dmi
Labels: Sprites, Tweak

#13752 tweaks stamcrit to be removed when under 100 stamina damage, rather than at 140
  code/__DEFINES/combat.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Balance/Rebalance

#13751 standardizes text formatting to rp server's |one character| instead of ||two|| because why did i even do the latter
  code/game/say.dm
Labels: Tweak

#13753 [testmerge this first]shoving yourself up now costs 50% more
  code/__DEFINES/combat/stamina_combat.dm
Labels: Balance/Rebalance

#13699 nanite updates: permanent nanites, hostile lockdown, anti-virus, resistance tweaking
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/components/nanites.dm
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/nanite_chamber.dm
  code/modules/research/nanites/nanite_chamber_computer.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
  code/modules/research/techweb/nodes/nanites_nodes.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
Labels: Feature, Tweak

#13764 mechs leave no wrecks when sold on cargo shuttle
  code/modules/cargo/exports.dm
Labels: Tweak

#13769 Adds goose bar sign
  code/game/objects/structures/barsigns.dm
  icons/obj/barsigns.dmi
Labels: Feature, Sprites

#13767 Pretty meat icons update
  icons/obj/food/food.dmi
Labels: Sprites, Tweak

#13758 replaces custom holoform verb with an action, lets holoform AIs emote
  code/__HELPERS/custom_holoforms.dm
  code/datums/emotes.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/custom_holoform.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  icons/mob/actions/actions_silicon.dmi
Labels: Config Update, Sprites, Work In Progress

#13757 changes the age gate to use date of birth
  code/modules/mob/dead/new_player/new_player.dm
Labels: Feature

#13746 Reworks Northwest Box Station Maint and adds a bridge between Atmos and the Turbine
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit

#13784 Port of "Effects can no longer trigger landmines"
  code/game/objects/effects/mines.dm
Labels: Fix

#13725 makes keybind system automatically generate anti-collision keybinds where necessary to avoid unintentional macro fires
  code/controllers/subsystem/input.dm
  code/modules/keybindings/keybind/communication.dm
  code/modules/keybindings/setup.dm
Labels: Fix

#13791 [s]Update saved_circuits.dm
  code/modules/integrated_electronics/core/saved_circuits.dm
Labels: In Game Exploit

#13763 RPED drops lowest tier parts
  code/datums/components/storage/concrete/rped.dm
Labels: Tweak

#13808 Polycircuit sanity checking
  code/game/objects/items/devices/polycircuit.dm
Labels: Fix, Tweak

#13790 Mapping touchups
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
Labels: Map Edit, Tweak

#13804 [s] sanitizes circuits get pin data
  code/modules/integrated_electronics/core/helpers.dm
Labels: Fix

#13806 adds logging to shell execution
  code/__HELPERS/shell.dm
Labels: Priority: CRITICAL

#13803 Prevents traitor AI from doomsdaying while carded
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
Labels: Balance/Rebalance

#13796 Scarp Changes and Bundle
  code/datums/martial/sleeping_carp.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/mob/living/carbon/human/physiology.dm
  code/modules/uplink/uplink_items/uplink_bundles.dm
Labels: Balance/Rebalance, Feature

#13813 nerfs loudmode headsets from 160% to 120% fontsize
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
Labels: Tweak, UI

#13756 gives citadel main its own tgui db id to avoid issues but this time i actually don't webedit so i can recompile tgui
  tgui/packages/common/storage.js
  tgui/public/tgui-common.chunk.js
Labels: UI

#13799 fixes space ninjas being able to hardstun with their gloves
  code/modules/ninja/suit/ninjaDrainAct.dm
Labels: Fix

#13776 Makes Traitor AIs have 'kill once' objectives instead of 'assassinate'
  code/modules/antagonists/traitor/classes/ai.dm
Labels: Tweak

#13811 Prevents borg hypos from injecting if it would OD the target while on help intent
  code/modules/reagents/reagent_containers/borghypo.dm
  tgstation.dme
Labels: Tweak

#13809 Makes gear harness cover nothing
  code/modules/clothing/under/miscellaneous.dm
Labels: Tweak

#13801 Makes limb grower better
  code/game/machinery/limbgrower.dm
  code/modules/research/designs/limbgrower_designs.dm
Labels: Fix, Refactor

#13774 Clown Car The Honkening
  code/modules/uplink/uplink_items/uplink_roles.dm
  code/modules/vehicles/cars/clowncar.dm
Labels: Balance/Rebalance

#13755 ports colormates from rp/vorestation
  code/__HELPERS/icons.dm
  code/__HELPERS/matrices.dm
  code/game/machinery/colormate.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/designs/machine_desings/machine_designs_all_misc.dm
  code/modules/research/techweb/nodes/engineering_nodes.dm
  icons/obj/vending.dmi
  tgstation.dme
Labels: Feature, Sprites

#13785 Makes grab bag ONLY make station antags; triples alien dynamic threat.
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/dynamic.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/vote.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_minor.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  code/modules/antagonists/xeno/xeno.dm
  code/modules/events/nightmare.dm
  config/dynamic_config.txt
Labels: Balance/Rebalance, Config Update, Tweak

#13814 Fixes twin sword sheaths icon/item state from being blank sprites
  code/game/objects/items/storage/belt.dm
Labels: Fix

#13824 LF
  README.md
  SQL/tgstation_schema.sql
  TGS3.json
  _maps/boxstation.json
  _maps/runtimestation.json
  bot/nudge.py
  code/datums/components/README.md
  config/antag_rep.txt
  config/comms.txt
  html/changelog.css
  sound/voice/catpeople/license.txt
  strings/names/adjectives.txt
  strings/names/ai.txt
  strings/names/carp.txt
  strings/names/clown.txt
  strings/names/death_commando.txt
  strings/names/first.txt
  strings/names/first_female.txt
  strings/names/first_male.txt
  strings/names/golem.txt
  strings/names/last.txt
  strings/names/lizard_female.txt
  strings/names/lizard_male.txt
  strings/names/mime.txt
  strings/names/ninjaname.txt
  strings/names/ninjatitle.txt
  strings/names/plasmaman.txt
  strings/names/posibrain.txt
  strings/names/verbs.txt
  strings/names/wizardfirst.txt
  strings/names/wizardsecond.txt
  tools/CreditsTool/remappings.txt
  tools/Runtime Condenser/Main.cpp
  tools/UnstandardnessTestForDM/readme.txt
  tools/WebhookProcessor/secret.php
  tools/travis/travis_config.txt
Labels: Config Update, Map Edit, SQL, Sound, Tools

#13819 survival dagger light fix + butchery buff
  code/game/objects/items/kitchen.dm
  icons/obj/kitchen.dmi
Labels: Balance/Rebalance, Fix, Sprites

#13823 Maybe less christmas
  code/modules/holiday/holidays.dm
Labels: Tweak

#13829 Bandaid fix for input controller lockup due to sleeping
  code/controllers/subsystem/input.dm
  code/game/objects/items/puzzle_pieces.dm
  code/modules/keybindings/setup.dm
Labels: Priority: High

#13773 Zeolites tweaks
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Tweak

#13815 Removes slime blood to jelly conversion
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Balance/Rebalance, Removal

#13825 Windoors stay open longer
  code/game/machinery/doors/windowdoor.dm
Labels: Tweak

#13828 fix: you can only entwine tails with people who have a tail
  code/modules/mob/living/living.dm
Labels: Fix

#13822 Fixes a thing in stunhands used on clockies
  code/modules/antagonists/cult/blood_magic.dm
Labels: Fix

#13820 [TESTMERGE ONLY] Temporarily disables Reebe
  code/game/gamemodes/clock_cult/clock_cult.dm
Labels: Testmerge only

#13772 adds a respawn/return to lobby system, tweaks cryo to preserve everything instead of just ""important items""
  code/__DEFINES/role_preferences.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/configuration/entries/respawns.dm
  code/controllers/subsystem/ticker.dm
  code/datums/world_topic.dm
  code/game/machinery/cryopod.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/respawn.dm
  code/modules/mob/living/death.dm
  code/modules/mob/mob.dm
  config/config.txt
  config/respawns.txt
  tgstation.dme
Labels: Config Update

#13833 bone chitin gloves no longer more murderous than an armblade
  code/modules/antagonists/changeling/powers/mutations.dm
Labels: Balance/Rebalance

#13835 Pugilists can now parry most things with their bare hands
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/living_active_parry.dm
  code/modules/mob/living/living_blocking_parrying.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_mobility.dm
  code/modules/mob/living/living_signals.dm
  tgstation.dme
Labels: Feature

#13844 Fixes mint machine
  code/modules/mining/mint.dm
Labels: Fix

#13837 sprinting now defaults to toggle rather than hold (because 90% of our players probably never check the keybinding preferences and from personal experience, holding down shift to move is awful)
  code/modules/keybindings/keybind/movement.dm
Labels: Tweak

#13852 !always_can_respawn_as
  code/modules/jobs/job_types/_job.dm
Labels: FUCK, Priority: High

#13845 fixes dullahans being hardcoded to ignore config unless it's halloween
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
Labels: Fix

#13830 fixes apids(bees) not rendering
  code/modules/surgery/bodyparts/_bodyparts.dm
Labels: Fix

#13836 refactors statpanel a bit to send topics to client instead of item which bypasses problematic /Topic overrides entirely
  code/game/atoms.dm
  code/modules/client/client_procs.dm
  html/statbrowser.html
Labels: Refactor

#13866 fixes a bug with hijack implants
  code/modules/power/apc.dm
Labels: In Game Exploit, Priority: High

#13850 Fixes self-refueling welders
  code/game/objects/items/tools/weldingtool.dm
Labels: Fix

#13865 cell/proc/give() no longer lets you give negative charge
  code/modules/power/cell.dm
Labels: Fix

#13870 Did you know? Magrifle ammo being free lights is LIKELY A BUG.
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets/ferromagnetic.dm
Labels: Fix

#13857 fixes contractor pods this time for real (and 25% tested instead of 0%)
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/cargo/supplypod.dm
Labels: Priority: High

#13846 Ling & Bloodsucker healing now affects IPCs / Synths
  code/datums/status_effects/buffs.dm
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
Labels: Balance/Rebalance

#13881 A Pubby Christmas
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#13873 Nyctophobia quirk now triggers in 0.2 seconds instead of instantly
  code/datums/traits/negative.dm
Labels: Tweak

#13901 woops i accidentally gave every single goddamn person pugilist parry
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Priority: CRITICAL

#13838 removes deathgasping on death if already faking death as it's real easy to spot changelings in stasis otherwise
  code/modules/mob/living/carbon/death.dm
Labels: Fix, Removal

#13897 Fixess Energy Bola to be catchable
  code/game/objects/items/handcuffs.dm
Labels: Fix

#13893 Nerfs meth and morphine to only remove damage slowdown rather than all slowdown (read this carefully, as this affects lings)
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Tweak

#13894 reduces coldslowdown to tempdiff / 35 instead of tempdiff / 20
  code/__DEFINES/atmospherics.dm
Labels: Tweak

#13896 cydonia helmet fix & taur(naga&canine)Ert hardsuit
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/head_muzzled.dmi
  icons/mob/clothing/taur_canine.dmi
  icons/mob/clothing/taur_naga.dmi
Labels: Feature, Fix, Sprites, Tweak

#13898 Makes regen coma properly work at 25% when sleeping; makes coma more precedent
  code/datums/diseases/advance/symptoms/heal.dm
Labels: Balance/Rebalance, Fix

#13887 Fix for Necrotizing Fasciitis
  code/datums/diseases/advance/symptoms/flesh_eating.dm
Labels: Fix

#13883 Set Pose from RP server is now a thing (in reality this just modifies existing temporary flavor text to be better but no one here understands enough code so I'll spare the explanation)
  code/datums/elements/flavor_text.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Feature, Tweak

#13882 adds subtler emote that wraps around adjacent tables
  code/modules/mob/say_vr.dm
Labels: Feature

#13880 antag rep configs are now actually possible to set for jobs with more than one word in the title
  code/modules/jobs/job_types/_job.dm
Labels: Priority: High

#13869 removes slime layering and stops puddle tackling
  code/datums/components/tackle.dm
  code/modules/mob/living/carbon/human/innate_abilities/blobform.dm
Labels: Removal, Tweak

#13904 Adds some more instant summons safety
  code/modules/spells/spell_types/summonitem.dm
Labels: Tweak

#13906 fixes the admin panel (tickets, sdq2l)
  html/statbrowser.html
Labels: Priority: CRITICAL

#13900 Ports cute birbs from RP
  code/modules/cargo/packs/livestock.dm
  code/modules/mob/living/simple_animal/parrot.dm
  icons/mob/animal.dmi
Labels: Feature, Sprites

#13855 Paramed office on box + Surgery remodel
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  icons/obj/closet.dmi
Labels: Code Improvement, Feature, Map Edit, Sprites, Tweak

#13884 ":n hey miners don't forget the dock silver" the PR - also includes a box whiteship tinyfan fix
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/whiteship_box.dmm
Labels: Feature, Fix, Map Edit

#13903 Lings no longer deathgasp twice when entering regen stasis
  code/modules/antagonists/changeling/powers/fakedeath.dm
Labels: Fix

#13913 Local Martial Artist forgets one line of code (fixes Scarp Parrying)
  code/datums/martial/sleeping_carp.dm
Labels: Fix

#13892 rebalances changeling combat mutations
  code/modules/antagonists/changeling/powers/mutations.dm
Labels: Balance/Rebalance

#13902 slimes can now have digitigrade/avian legs
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  icons/mob/human_parts_greyscale.dmi
Labels: Feature, Sprites

#13917 *squeak
  code/modules/mob/living/carbon/human/emote.dm
Labels: Feature

#13915 Fixes new bird sprites defaulting to basic parrot when sitting
  code/modules/cargo/packs/livestock.dm
  code/modules/mob/living/simple_animal/parrot.dm
  icons/mob/animal.dmi
Labels: Fix, Sprites

#13914 Some area designation fixes for CogStation.
  _maps/map_files/CogStation/CogStation.dmm
  code/game/area/Space_Station_13_areas.dm
Labels: Map Edit

#13916 reverts the removal of the holoform verb because kevin likes it
  code/__HELPERS/custom_holoforms.dm
  code/modules/mob/living/silicon/custom_holoform.dm
Labels: Feature, Revert

#13911 salicyclic acid
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Grammar and Formatting

#13905 gives codex cicatrix inhands
  code/modules/antagonists/eldritch_cult/eldritch_book.dm
  icons/mob/inhands/misc/books_lefthand.dmi
  icons/mob/inhands/misc/books_righthand.dmi
  icons/obj/eldritch.dmi
Labels: Sprites

#13927 FUCK OFF WHY IS VORE SHITCODE CAUSING CHERNOBYL AGAIN I HATE VORE CODE
  code/modules/vore/eating/belly_obj.dm
Labels: Priority: CRITICAL

#13926 Revert kevinzs' shame
  code/modules/arousal/arousal.dm
Labels: Removal, Revert

#13867 Makes zeolites far, far easier to make
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Balance/Rebalance

#13885 Makes space heaters worth using
  code/game/machinery/spaceheater.dm
Labels: Test Merge Candidate, Tweak
