Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-10, with the labels that each got.

#13391 Lambda Mk.II
  _maps/lambdastation.json
  _maps/map_files/LambdaStation/dorms.dmm
  _maps/map_files/LambdaStation/lambda.dmm
Labels: Feature, Fix, Map Edit, Tweak

#13372 please stop using explosive holoparasites to make instant kill toolboxes
  code/datums/components/killerqueen.dm
Labels: Priority: High

#13454 fixes botany harvest causing attack hand to runtime
  code/modules/hydroponics/hydroponics.dm
Labels: Fix, Priority: High

#13417 fixes mecha trackers
  code/game/mecha/mecha_defense.dm
Labels: In Game Exploit, Priority: High

#13448 Fixes a spelling error in an armor value that caused runtimes.
  code/modules/clothing/spacesuits/miscellaneous.dm
Labels: Fix

#13317 Ports tgstation/tgstation#52549
  code/modules/client/preferences_savefile.dm
Labels: Code Improvement

#13398 wound config values, wound bonus for how damaged a limb is
  code/__DEFINES/wounds.dm
  code/controllers/configuration/entries/game_options.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  config/wounds.txt
Labels: Config Update, Tweak

#13429 Fixed a dumb typo that may or may not be causing atmos jank.
  code/controllers/subsystem/air.dm
Labels: Fix

#13431 Gives Cargo Technicians the choice of longer trousers.
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/uniform.dm
  tgstation.dme
Labels: Feature, Sprites

#13443 Gabbys new wooden floor tile types
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
Labels: Feature, Grammar and Formatting, Sprites

#13446 Makes dynamic less probabilistic, keeping the desired threat level more aggressively
  code/__DEFINES/maths.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  code/game/gamemodes/dynamic/readme.md
Labels: Balance/Rebalance

#13450 Plz work, new heavy suits
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites, Tweak

#13455 Added policy config for sentient pyro slimes (no actual policy yet)
  code/__DEFINES/configuration.dm
  code/game/objects/effects/anomalies.dm
Labels: Feature

#13463 adds luminescent and stargazer sprites as selectable body sprites for slimes
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Feature

#13466 Cleans up and fixes SDGF code a bit, consistent naked clones, transfer_ckey resets view range
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/mob.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
Labels: Balance/Rebalance, Config Update, Fix, Tweak

#13467 Fixes vore prefs (I was looking in the wrong place the whole time)
  code/__DEFINES/_flags/_flags.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/unit_tests/character_saving.dm
  code/modules/vore/eating/living.dm
Labels: Fix

#13423 Gives drones back their e button (port)
  code/modules/keybindings/keybind/robot.dm
Labels: Fix

#13441 Makes fever use the proper thresholds and shivering have thresholds at all.
  code/datums/diseases/advance/symptoms/shivering.dm
Labels: Fix

#13477 Adds craftable railings
  code/__HELPERS/unsorted.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/stairs.dm
  tgstation.dme
Labels: Feature

#13486 Altcloaks from the Frontier
  code/modules/clothing/suits/cloaks.dm
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/cloaks.dmi
  modular_citadel/code/modules/client/loadout/neck.dm
Labels: Feature, Sprites

#13314 No more chemspam: Ports portions of ArcaneMusic's botany rework from TG.
  code/__DEFINES/botany.dm
  code/modules/hydroponics/grown/ambrosia.dm
  code/modules/hydroponics/grown/banana.dm
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/cannabis.dm
  code/modules/hydroponics/grown/cereals.dm
  code/modules/hydroponics/grown/chili.dm
  code/modules/hydroponics/grown/cocoa_vanilla.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/hydroponics/grown/cotton.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/grown/kudzu.dm
  code/modules/hydroponics/grown/melon.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/mushrooms.dm
  code/modules/hydroponics/grown/nettle.dm
  code/modules/hydroponics/grown/onion.dm
  code/modules/hydroponics/grown/peas.dm
  code/modules/hydroponics/grown/root.dm
  code/modules/hydroponics/grown/tea_coffee.dm
  code/modules/hydroponics/grown/tomato.dm
  code/modules/hydroponics/hydroitemdefines.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/hydroponics_chemreact.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/hydroponics/seeds.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
  code/modules/plumbing/plumbers/autohydro.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/research/designs/biogenerator_designs.dm
  strings/tips.txt
  tgstation.dme
Labels: Feature, Removal, Tweak

#13471 adds "clicks" as a speech verb in the character creator
  code/_globalvars/lists/flavor_misc.dm
Labels: Feature

#13475 Ports a few RP clothings and adds the detective clothing vendor
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/clothing/under/jobs/rnd.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/suits.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/vending.dmi
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature, Map Edit, Sprites

#12439 makes ipcs more like robots (a partial port from skyrat)
  code/__DEFINES/DNA.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/traits.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/mob/dead/new_player/sprite_accessories/alienpeople.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/horns.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/power/cable.dm
  code/modules/power/cell.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/coronary_bypass.dm
  code/modules/surgery/dental_implant.dm
  code/modules/surgery/embalming.dm
  code/modules/surgery/emergency_cardioversion_recovery.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/healing.dm
  code/modules/surgery/lipoplasty.dm
  code/modules/surgery/lobectomy.dm
  code/modules/surgery/mechanic_steps.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/stomach.dm
  code/modules/surgery/plastic_surgery.dm
  code/modules/surgery/robot_brain_surgery.dm
  code/modules/surgery/robot_healing.dm
  icons/obj/surgery.dmi
  tgstation.dme
Labels: Sprites, Stale

#13502 Fixes ghost funny + keeps SDGF view fix.
  code/modules/mob/mob.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
Labels: Fix

#13488 No harmful parry countering for pacifists.
  code/modules/mob/living/living_active_parry.dm
Labels: Fix

#13485 [s] Fixes a tiny Neovgre edge case
  code/game/mecha/combat/neovgre.dm
Labels: Fix

#13484 Fixes plushlings
  code/game/objects/items/plushes.dm
Labels: Fix

#13482 Tweaks heretic sacrifice husking
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
Labels: Tweak

#13489 standardizes minimum brightness of mutant parts
  code/__DEFINES/citadel_defines.dm
  code/game/objects/structures/mirror.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak

#13493 adds limb id support for gendered body parts
  code/_globalvars/lists/flavor_misc.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
Labels: Fix

#13494 Makes the slimeperson swap-body UI stay open when you switch bodies
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Tweak

#13495 fixes the door bolts on the snow cabin
  _maps/RandomZLevels/away_mission/SnowCabin.dmm
Labels: Fix, Map Edit

#13508 bodypart fixes - robotic bodypart & digitigrade edition
  code/datums/wounds/_scars.dm
  code/datums/wounds/_wounds.dm
  code/modules/client/preferences.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/dismemberment.dm
  code/modules/vending/_vending.dm
Labels: Fix

#13474 ports "Makes changelog compile only fire if CHANGELOG_ENABLER secret is present" from tg
  .github/workflows/compile_changelogs.yml
Labels: Github

#13481 A bunch of blacksmithing fixes / tweaks
  code/datums/skills/_skill.dm
  code/datums/skills/blacksmithing.dm
  code/modules/smithing/anvil.dm
  code/modules/smithing/smithed_items.dm
Labels: Fix, Tweak

#13483 Fixes Revenants reviving
  code/modules/antagonists/revenant/revenant.dm
Labels: Fix

#13487 Fixes borg KA upgrade installation
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Fix

#13499 Makes toilet loot not exist to cause bad GC bugs.
  code/game/objects/structures/watercloset.dm
Labels: Fix

#13461 adds arcade carpets
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/modules/cargo/packs/misc.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  icons/obj/tiles.dmi
  icons/turf/floors.dmi
Labels: Feature, Sprites

#13518 Plant Sprite Fixes II: The Mycus must grow! (And the grass should die)
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/hydroponics/grown/mushrooms.dm
  icons/obj/hydroponics/growing_mushrooms.dmi
Labels: Fix, Sprites

#13507 Ports the better statpannel design, fixes missing icons, and fixes statvoting [ready]
  code/__HELPERS/icons.dm
  code/controllers/subsystem/dcs.dm
  code/controllers/subsystem/economy.dm
  code/controllers/subsystem/events.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/statpanel.dm
  code/controllers/subsystem/vote.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_investigate.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/adminmenu.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/admin/verbs/cinematic.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/dice.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/admin/verbs/playsound.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/verbs/shuttlepanel.dm
  code/modules/admin/verbs/tripAI.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/verbs/ooc.dm
  html/statbrowser.html
Labels: Do Not Merge, Needs Review

#13512 cant believe nobody realized the issue - fixes cryo announcements
  code/game/machinery/announcement_system.dm
Labels: Fix

#13252 qol: looking at loadout equips your loadout items on you instead of job items
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
Labels: Tweak

#13511 additional revolver sprites
  code/modules/projectiles/guns/ballistic/revolver.dm
  icons/obj/guns/projectile.dmi
Labels: Sprites

#13513 adds selectable eye types to customization
  code/__DEFINES/citadel_defines.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair_face.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/organs/eyes.dm
  icons/mob/eyes.dmi
  icons/mob/hair.dmi
  icons/mob/human_face.dmi
  icons/mob/human_parts.dmi
  icons/mob/human_parts_greyscale.dmi
  icons/mob/lips.dmi
Labels: Feature, Sprites

#13514 Jacq fixes2020edition
  code/modules/holiday/halloween/bartholomew.dm
  code/modules/holiday/halloween/jacqueen.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
Labels: Fix, UI

#13516 fixes rounding error in growthstages
  code/modules/hydroponics/hydroponics.dm
Labels: Fix

#13519 licking people is now an epic radial
  code/modules/vore/eating/living.dm
Labels: Feature

#13523 fixes arcade carpet
  code/game/objects/items/stacks/tiles/tile_types.dm
Labels: Fix

#13509 Slight adjustment to the "Skelter" ruin.
  _maps/RandomRuins/SpaceRuins/skelter.dmm
  code/modules/ruins/spaceruin_code/skelter.dm
  tgstation.dme
Labels: Map Edit

#13504 buffs stands in general, adds gravitokinetic stand type from tg, fixes broken protector shield
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/guardian/types/assassin.dm
  code/modules/mob/living/simple_animal/guardian/types/charger.dm
  code/modules/mob/living/simple_animal/guardian/types/explosive.dm
  code/modules/mob/living/simple_animal/guardian/types/gravitokinetic.dm
  code/modules/mob/living/simple_animal/guardian/types/protector.dm
  code/modules/mob/living/simple_animal/guardian/types/support.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature, Fix

#13503 survival daggers, luxpod capsule resprite, glaive sprite tweaks soon (tm)
  code/game/objects/items/kitchen.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/machine_vending.dm
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
  icons/obj/kitchen.dmi
  icons/obj/mining.dmi
Labels: Feature, Sprites, Tweak

#13501 Made holofirelocks work.
  code/game/objects/structures/holosign.dm
Labels: Fix

#13500 Updates Lambda station
  _maps/map_files/LambdaStation/dorms.dmm
  _maps/map_files/LambdaStation/lambda.dmm
Labels: Feature, Map Edit, Tweak

#13498 Lingblood rework (Loudness is now an average, rather than a sum)
  code/__DEFINES/antagonists.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Labels: Tweak

#13496 allows players in deadchat to see explosions
  code/datums/explosion.dm
  code/game/objects/empulse.dm
Labels: Feature

#13526 Adds a line that actually saves vore prefs to the vore pref saving
  code/modules/vore/eating/vorepanel.dm
Labels: Fix, Priority: High

#13536 fixes cyborg sprint
  code/modules/keybindings/keybind/movement.dm
Labels: Priority: High

#13517 "are you sure we should remove mobs from the immunity typecache" v2: electric boogaloo
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#13490 kind of easy to tell if you have a fake virus if it's ticking at 20 times the speed of a normal virus right
  code/datums/status_effects/debuffs.dm
Labels: Fix

#13453 microoptimization to get rad contents
  code/__HELPERS/radiation.dm
Labels: Test Merge Candidate

#13480 [OH GOD TESTMERGE THIS FIRST] another microoptimization to GetAllContents() because microoptimizations are fun
  code/__HELPERS/unsorted.dm
Labels: Test Merge Candidate

#13539 cleans up the eye customization pr
  code/modules/mob/living/carbon/human/species.dm
Labels: Removal

#13444 reworks family heirlooms, adds heirlooms that can be based off your species
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/objects.dm
  code/datums/traits/negative.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/power/cell.dm
  icons/obj/device.dmi
Labels: Sprites, Tweak

#13405 warp implant is now infinite use and now actually reverts your position to 10 seconds before in time rather than use a snowflake chemical to teleport you 5 seconds later
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implant_misc.dm
  code/modules/uplink/uplink_items/uplink_implants.dm
Labels: Revert, Tweak

#13472 the pr that lets slimes turn into useless puddles
  code/__DEFINES/traits.dm
  code/datums/components/squeak.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living_mobility.dm
  code/modules/movespeed/modifiers/innate.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/parts.dm
  html/changelog.html
  icons/mob/actions/actions_slime.dmi
  icons/mob/mob.dmi
Labels: Feature, Sprites

#13531 Oops! Regenerate_bodyparts-edition
  code/modules/surgery/bodyparts/dismemberment.dm
Labels: Fix

#13014 [REVIEW PLEASE] Minimum Megas/Tendrils For Lavaland But Cleaner I Swear
  code/controllers/subsystem/minimum_spawns.dm
  code/datums/ruins/lavaland.dm
  code/modules/mapping/ruins.dm
  tgstation.dme
Labels: Feature

#13497 Refactors some defines for easier Species Development
  code/__DEFINES/colors.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/species.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/diseases/transformation.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/abductor.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/angel.dm
  code/modules/mob/living/carbon/human/species_types/anthromorph.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/carbon/human/species_types/xeno.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  tgstation.dme
Labels: Code Improvement, Refactor

#13525 fixes the hilbert's jukebox(?)
  _maps/templates/hilbertshotel.dmm
Labels: Fix, Map Edit

#13527 Fully Upgraded Advanced RTG Machine Preset
  code/modules/power/rtg.dm
Labels: Feature

#13533 Face hugger jambalaya. Should be ready.
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  icons/obj/food/soupsalad.dmi
Labels: Feature, Sprites

#13535 [READY] Energy Sabers - an elegant esword skin for a more civilized age
  code/_onclick/hud/radial.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/objs.dm
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/defibrillators.dmi
  icons/obj/items_and_weapons.dmi
Labels: Feature, Needs Review, Sprites, Tweak

#13540 Service+Plumbing QoL Pass 1: Beakers, Belts, Plungers and Pipes
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/plumbing/plumbers/autohydro.dm
  code/modules/research/designs/biogenerator_designs.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
  icons/mob/clothing/belt.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/clothing/belts.dmi
Labels: Feature, Sprites, Tweak

#13544 Fixes a bunch of portal-related runtimes
  code/game/machinery/wishgranter.dm
  code/game/mecha/equipment/tools/other_tools.dm
  code/modules/events/wormholes.dm
  code/modules/projectiles/guns/energy/special.dm
Labels: Fix

#13015 Combat v4: Redesigning Stamina, Sprint, Combat mode
  code/__DEFINES/_flags/item_flags.dm
  code/__DEFINES/combat.dm
  code/__DEFINES/combat/stamina_combat.dm
  code/__DEFINES/configuration.dm
  code/__DEFINES/skills/defines.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/mobs.dm
  code/_onclick/hud/screen_objects/stamina.dm
  code/_onclick/item_attack.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration/entries/stamina_combat.dm
  code/datums/martial/sleeping_carp.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/game/objects/items.dm
  code/game/objects/items/electrostaff.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/mop.dm
  code/game/objects/items/powerfist.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/tanks/jetpack.dm
  code/game/objects/items/tools/screwdriver.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_active_block.dm
  code/modules/mob/living/living_active_parry.dm
  code/modules/mob/living/living_blocking_parrying.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_mobility.dm
  code/modules/mob/living/living_sprint.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/stamina_buffer.dm
  code/modules/movespeed/_movespeed_modifier.dm
  code/modules/movespeed/modifiers/items.dm
  code/modules/movespeed/modifiers/mobs.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  modular_citadel/code/modules/mob/living/carbon/damage_procs.dm
  modular_citadel/code/modules/mob/living/damage_procs.dm
  modular_citadel/code/modules/mob/living/living.dm
  modular_citadel/icons/ui/screen_gen.dmi
  tgstation.dme
Labels: Config Update

#13510 a more sane json-based map override system for jobs (todo port to rp so rp can have map rotation)
  _maps/map_files/PubbyStation/job_changes.dm
  _maps/pubbystation.json
  code/__DEFINES/maps.dm
  code/controllers/subsystem/job.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/map_changes/map_changes.dm
  code/modules/mapping/map_config.dm
  tgstation.dme
Labels: Map Edit, Test Merge Candidate

#13542 removes gibbing (blobattack) sound from *blorble so it always plays the far nicer attackblob sound instead
  code/modules/mob/living/emote.dm
Labels: Removal

#13193 buffsi ntegrated circuit medium screens
  code/modules/integrated_electronics/subtypes/output.dm
Labels: MANUALLY CHECK TRAVIS - IGNORE BUILD STATUS, Tweak

#13530 THROWING A CLOWN INTO THE SUPERMATTER ENGINE NOW RANDOMLY ADJUSTS ENERGY AND DAMAGE
  code/modules/power/supermatter/supermatter.dm
Labels: Feature

#13522 Fixes the intermittent master controller lockups
  code/controllers/subsystem/input.dm
  code/controllers/subsystem/npcpool.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/hostile/wizard.dm
  code/modules/mob/living/simple_animal/parrot.dm
Labels: FUCK, Fix, Test Merge Candidate

#13349 Updates git, travis, and build tests
  .editorconfig
  .gitattributes
  .github/workflows/autobuild_tgui.yml
  .github/workflows/round_id_linker.yml
  .gitignore
  .gitlab-ci.yml
  .gitmodules
  .travis.yml
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  code/game/atoms_movable.dm
  code/game/turfs/space/space.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/anchored_mobs.dm
  code/modules/unit_tests/bespoke_id.dm
  code/modules/unit_tests/binary_insert.dm
  code/modules/unit_tests/chain_pull_through_space.dm
  code/modules/unit_tests/component_tests.dm
  code/modules/unit_tests/machine_disassembly.dm
  code/modules/unit_tests/medical_wounds.dm
  code/modules/unit_tests/metabolizing.dm
  code/modules/unit_tests/outfit_sanity.dm
  code/modules/unit_tests/plantgrowth_tests.dm
  code/modules/unit_tests/quick_swap_sanity.dm
  code/modules/unit_tests/resist.dm
  code/modules/unit_tests/say.dm
  code/modules/unit_tests/spawn_humans.dm
  code/modules/unit_tests/subsystem_init.dm
  code/modules/unit_tests/surgeries.dm
  code/modules/unit_tests/unit_test.dm
  tools/travis/check_filedirs.sh
  tools/travis/check_grep.sh
  tools/travis/install_dreamchecker.sh
  tools/travis/install_spaceman_dmm.sh
  tools/travis/run_server.sh
Labels: Code Improvement, Github, Map Edit, Tools

#13553 fixes eye sprites up
  code/modules/client/preferences_savefile.dm
  icons/mob/eyes.dmi
  icons/mob/human_parts.dmi
Labels: Fix, Sprites

#13473 Ports Arachnids (Spider People) from WaspStation
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/names.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/names.dm
  code/controllers/subsystem/traumas.dm
  code/datums/mutations/actions.dm
  code/game/objects/effects/arachnid_web.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/language/arachnid.dm
  code/modules/language/language_holder.dm
  code/modules/mob/dead/new_player/sprite_accessories/arachnid.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/arachnid.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/tongue.dm
  config/game_options.txt
  icons/misc/language.dmi
  icons/mob/arachnid_legs.dmi
  icons/mob/arachnid_mandibles.dmi
  icons/mob/arachnid_parts.dmi
  icons/mob/arachnid_spinneret.dmi
  strings/names/spider_first.txt
  strings/names/spider_last.txt
  tgstation.dme
Labels: Config Update, Feature, Sprites

#13528 Robotic limbs 2 : Threshhold Boogaloo
  code/__DEFINES/mobs.dm
  code/datums/components/caltrop.dm
  code/datums/diseases/advance/symptoms/itching.dm
  code/datums/wounds/_scars.dm
  code/datums/wounds/_wounds.dm
  code/game/machinery/aug_manipulator.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/storage/book.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/antagonists/abductor/equipment/glands/heal.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/sprite_accessories/alienpeople.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/frills.dm
  code/modules/mob/dead/new_player/sprite_accessories/horns.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/mob_helpers.dm
  code/modules/power/cable.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/medspray.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/dismemberment.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/robot_bodyparts.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/helpers.dm
  code/modules/surgery/limb_augmentation.dm
  code/modules/surgery/prosthetic_replacement.dm
  code/modules/surgery/robot_brain_surgery.dm
  code/modules/surgery/robot_healing.dm
  code/modules/vending/_vending.dm
Labels: Balance/Rebalance, Code Improvement, Config Update, Refactor, Sprites, Tweak, UI

#13543 ports tg legion reworks, colossus now enrages against sand golems, and some minor sprite stuff with him too
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  icons/mob/lavaland/64x64megafauna.dmi
  icons/mob/lavaland/96x96megafauna.dmi
  icons/mob/lavaland/lavaland_monsters.dmi
  icons/mob/lavaland/legion.dmi
Labels: Balance/Rebalance, Feature, Sprites, Test Merge Candidate

#13547 security fashion power crêpe but it's a sheath for your anime sword
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/stunbaton.dm
  code/modules/vending/security.dm
  icons/mob/clothing/belt.dmi
  icons/obj/clothing/belts.dmi
Labels: Feature, Sprites

#13346 Makes dwarf text not check every replacement every time.
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
Labels: Refactor

#13529 Makes planetary atmos no longer superconduct
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
Labels: Tweak

#13566 makes legion stop dropping empty chests or something
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
Labels: Fix

#13563 cloning correctly copies blood colour, body sprite type and your eye type
  code/datums/dna.dm
  tgstation.dme
Labels: Tweak

#13549 Fixes cloning computer UI not updating when pressing certain buttons - also adds extra check for names to update a message
  code/game/machinery/computer/cloning.dm
Labels: Fix

#13554 High Luminosity Eye Fix
  code/modules/surgery/organs/eyes.dm
Labels: Fix

#13552 Fixes a race condition in the surgery unit test that causes it to fail at random
  code/modules/unit_tests/surgeries.dm
Labels: Fix

#13555 fixes movespeed configurations
  code/controllers/configuration/config_entry.dm
  code/controllers/configuration/entries/game_options.dm
Labels: Config Update, Priority: High

#13573 Removes the surgery unit test so travis stops randomly failing.
  code/modules/unit_tests/_unit_tests.dm
Labels: Fix, Removal

#13575 Fixes subtle hotkey, adds subtler anti-ghost hotkey
  code/modules/keybindings/keybind/mob.dm
  code/modules/mob/say_vr.dm
Labels: Feature, Fix

#13577 Made fermichem displays work correctly.
  code/modules/reagents/chemistry/machinery/chem_heater.dm
  tgui/packages/tgui/interfaces/ChemDispenser.js
  tgui/packages/tgui/interfaces/ChemHeater.js
  tgui/packages/tgui/interfaces/common/BeakerContents.js
  tgui/public/tgui.bundle.js
Labels: Fix, UI

#13571 Porting putnams ventcrawling PR and Fix
  code/modules/mob/inventory.dm
  code/modules/mob/living/ventcrawling.dm
Labels: Fix

#13570 Makes get_damaged_bodyparts use proper arguments
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/research/nanites/nanite_programs/healing.dm
Labels: Fix

#13557 Fixes people's slots getting switched around every time a savefile update happens because the update process is getting interrupted by the anti spam check that we put in when people crashed the server with autoclickers
  code/modules/client/preferences_savefile.dm
Labels: Priority: High

#13589 autosurgeons from the travelling trader have uses set to 1 instead of INFINITY
  code/modules/events/travelling_trader.dm
Labels: Tweak

#13585 Fixed species-specific drinks not giving a mood boost if right species
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Fix

#13587 the snow taxi is no longer the slow taxi
  _maps/shuttles/snow_taxi.dmm
Labels: Map Edit, Tweak

#13596 Donator - Vest and Shirt
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#13606 fix statpanel deleting whole admin tab
  html/statbrowser.html
Labels: Fix

#13588 Adding hiss, purr and meow emotes
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/sound/voice/hiss.ogg
  modular_citadel/sound/voice/meow1.ogg
  modular_citadel/sound/voice/purr.ogg
Labels: Feature, Sound

#13608 Ports a Python hook fix from /tg/.
  tools/hooks/python.sh
Labels: Fix, Tools

#13598 Fixes hijack UI
  code/modules/power/apc.dm
  tgui/packages/tgui/interfaces/Apc.js
  tgui/public/tgui.bundle.js
Labels: UI

#13599 Fixes matrix color randomization in /proc/randomize_human
  code/modules/admin/create_mob.dm
Labels: Fix

#13586 Re-codersprites the brass claw
  icons/mob/inhands/antag/clockwork_lefthand.dmi
  icons/mob/inhands/antag/clockwork_righthand.dmi
  icons/obj/clockwork_objects.dmi
Labels: Removal, Sprites

#13611 Giving science a space loop on every map
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#13593 Stringified the vote #defines for easier config stuff
  code/__DEFINES/vote.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/ticker.dm
  config/config.txt
Labels: Code Improvement, Config Update

#13592 Adds ranked choice ballots to stat voting
  code/controllers/subsystem/statpanel.dm
Labels: Feature

#13569 Adds automatic TGS DMAPI updates
  .github/workflows/update_tgs_dmapi.yml
Labels: Github

#13601 antagonistic items will no longer fail to be placed on you
  code/game/gamemodes/gangs/gang.dm
  code/game/gamemodes/objective.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
  code/modules/antagonists/overthrow/overthrow.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/mob/living/carbon/inventory.dm
Labels: Tweak

#13603 controversial shotgun buff (very scary)
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Balance/Rebalance, Tweak

#13605 Adds corporate uniforms to the clothing vender
  code/modules/vending/clothesmate.dm
Labels: Feature

#13607 polychromic maid outfit
  code/modules/clothing/under/jobs/civilian/civilian.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature, Sprites

#13612 Space Hermit map buff
  _maps/RandomRuins/SpaceRuins/spacehermit.dmm
Labels: Feature, Map Edit

#13616 Quick clown/mime masks designs fix.
  code/modules/clothing/masks/gasmask.dm
Labels: Fix

#13625 Reverts this circuit frame removal
  code/controllers/subsystem/processing/circuit.dm
  code/modules/integrated_electronics/core/assemblies.dm
Labels: Revert

#13627 Here I fix a few issues.
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomZLevels/away_mission/research.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/arrival_delta.dmm
  _maps/shuttles/arrival_omega.dmm
  code/datums/accents.dm
  code/datums/action.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/RSF.dm
  code/game/objects/items/dice.dm
  code/modules/keybindings/keybind/human.dm
  code/modules/keybindings/keybind/living.dm
  code/modules/keybindings/keybind/robot.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/vending/games.dm
  modular_citadel/code/modules/client/loadout/hands.dm
Labels: Fix, Map Edit

#13626 [SALT] MAKES MEGAFAUNA ITEMS LAVAPROOF (LIKE THE LAVA STAFF)
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
Labels: Balance/Rebalance

#13628 Adjusting Boxstation's Southeast Maint (three new rooms)
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit

#13636 gas masks for engi loadouts
  modular_citadel/code/modules/client/loadout/mask.dm
Labels: Tweak

#13645 [s] removes the ability to an entire canister
  code/modules/integrated_electronics/subtypes/atmospherics.dm
Labels: Removal
