Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-04, with the labels that each got.

#11669 Ports "Fixes vault and high security door material exploit and tweaks high security door cost"
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/door_assembly_types.dm
Labels: Fix, Tweak

#11681 TGUI Next in the Medbay
  code/game/machinery/Sleeper.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  tgui-next/packages/tgui/interfaces/ChemDispenser.js
  tgui-next/packages/tgui/interfaces/ChemHeater.js
  tgui-next/packages/tgui/interfaces/ChemMaster.js
  tgui-next/packages/tgui/interfaces/Sleeper.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Code Improvement, Feature, UI

#11682 Sabotage objective tweaks
  code/game/gamemodes/objective_sabotage.dm
Labels: Removal, Tweak

#11683 holodeck WRESTLING
  _maps/map_files/generic/CentCom.dmm
  code/datums/martial/wrestling.dm
  code/game/area/areas/holodeck.dm
Labels: Feature, Map Edit

#11692 small improvement with color selections on character appearance menu
  code/modules/client/preferences.dm
Labels: Fix

#11693 Corrects OPS crate
  code/modules/cargo/packs/emergency.dm
Labels: Grammar and Formatting

#11698 The banishment of the floating disembodied phallus.
  code/__DEFINES/citadel_defines.dm
  code/__HELPERS/mobs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/arousal/genitals.dm
  modular_citadel/code/modules/arousal/genitals_sprite_accessories.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
Labels: Fix

#11700 adds new cosmetic and craftable paper masks.
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature, Sprites

#11604 Even More fixes to Lambda
  _maps/map_files/LambdaStation/lambda.dmm
Labels: Feature, Map Edit, Tweak

#11701 Massive megafauna buff.
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Tweak

#11708 makes sergal markings better
  modular_citadel/icons/mob/mam_markings.dmi
  modular_citadel/icons/mob/mam_snouts.dmi
Labels: Tweak

#11717 Chem Dispensers and Heaters now show pH again
  tgui-next/packages/tgui/interfaces/ChemDispenser.js
  tgui-next/packages/tgui/interfaces/ChemHeater.js
  tgui-next/packages/tgui/interfaces/common/BeakerContents.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Fix, UI

#11707 Punches land with the same consistency across races, punches cheaper, king hits are nastier
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#11715 Further dynamic tweaks: "you can instamerge this time" edition
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
Labels: Balance/Rebalance, Fix, Tweak

#11713 fixes shadow emission
  code/modules/hydroponics/plant_genes.dm
Labels: Fix

#11702 Changes making cablecuffs to using cable in your hand, instead of a menu.
  code/game/objects/items/handcuffs.dm
  code/modules/power/cable.dm
Labels: Code Improvement, Tweak

#11721 Swaps a few pumps and pipes in Atmos on Meta Station for quality of life
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit, Tweak

#11329 Made laser carbines and magrifles bulkier.
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/magweapon.dm
  code/modules/projectiles/guns/energy/laser.dm
  icons/mob/back.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
Labels: Balance/Rebalance, Sprites

#11433 Spellcasting element
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/dcs/signals.dm
  code/datums/action.dm
  code/datums/elements/spellcasting.dm
  code/datums/mutations/actions.dm
  code/game/objects/items/implants/implant_spell.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
  code/modules/antagonists/santa/santa.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/awaymissions/mission_code/Academy.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/events/wizard/aid.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/simple_animal/friendly/gondola.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/statue.dm
  code/modules/mob/living/simple_animal/hostile/wizard.dm
  code/modules/mob/mob.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/aimed.dm
  code/modules/spells/spell_types/area_teleport.dm
  code/modules/spells/spell_types/barnyard.dm
  code/modules/spells/spell_types/bloodcrawl.dm
  code/modules/spells/spell_types/charge.dm
  code/modules/spells/spell_types/conjure.dm
  code/modules/spells/spell_types/construct_spells.dm
  code/modules/spells/spell_types/devil.dm
  code/modules/spells/spell_types/devil_boons.dm
  code/modules/spells/spell_types/ethereal_jaunt.dm
  code/modules/spells/spell_types/forcewall.dm
  code/modules/spells/spell_types/infinite_guns.dm
  code/modules/spells/spell_types/knock.dm
  code/modules/spells/spell_types/lichdom.dm
  code/modules/spells/spell_types/lightning.dm
  code/modules/spells/spell_types/mime.dm
  code/modules/spells/spell_types/mind_transfer.dm
  code/modules/spells/spell_types/rod_form.dm
  code/modules/spells/spell_types/santa.dm
  code/modules/spells/spell_types/shadow_walk.dm
  code/modules/spells/spell_types/shapeshift.dm
  code/modules/spells/spell_types/spacetime_distortion.dm
  code/modules/spells/spell_types/summonitem.dm
  code/modules/spells/spell_types/taeclowndo.dm
  code/modules/spells/spell_types/telepathy.dm
  code/modules/spells/spell_types/the_traps.dm
  code/modules/spells/spell_types/touch_attacks.dm
  code/modules/spells/spell_types/turf_teleport.dm
  code/modules/spells/spell_types/voice_of_god.dm
  code/modules/spells/spell_types/wizard.dm
  tgstation.dme
Labels: Refactor

#11706 Minesweeper armageddon improvements
  code/game/machinery/computer/arcade/minesweeper.dm
  code/modules/research/designs/machine_desings/machine_designs_all_misc.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Fix

#11712 Porting the mutation conflict system, and resizing quantum realm fix.
  code/datums/mutations/_mutations.dm
  code/datums/mutations/body.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature

#11720 Corrects missing slash in a bullet
  modular_citadel/code/modules/projectiles/guns/ballistic/handguns.dm
Labels: Code Improvement

#11711 Buffs skateboards
  code/__DEFINES/traits.dm
  code/__HELPERS/mobs.dm
  code/datums/mutations/body.dm
  code/game/objects/items/weaponry.dm
  code/modules/vehicles/scooter.dm
  code/modules/vehicles/vehicle_actions.dm
  code/modules/vending/games.dm
  icons/mob/actions/actions_vehicle.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/vehicles.dmi
  sound/vehicles/skateboard_ollie.ogg
  sound/vehicles/skateboard_roll.ogg
Labels: Feature, Removal, Sound, Sprites, Tweak

#11703 Removes public mining from the game
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/shuttles/mining_common_meta.dmm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/mining/mine_items.dm
Labels: Awaiting further discussion/approval, Balance/Rebalance, Map Edit, Removal

#11575 Coggers.
  _maps/cogstation.dm
  _maps/cogstation.json
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/CogStation/FOLDER.txt
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/modules/paperwork/paper_premade.dm
Labels: Feature, Map Edit, Tweak

#11664 Stuff about power
  code/_globalvars/misc.dm
  code/modules/power/apc.dm
Labels: Balance/Rebalance, Tweak

#11476 Completely overhauls how blocking, shields, reflecting, and anything in between is handled. Has some small gameplay effects.
  code/__DEFINES/combat.dm
  code/__DEFINES/dcs/signals.dm
  code/__HELPERS/cmp.dm
  code/_onclick/item_attack.dm
  code/datums/components/wearertargeting.dm
  code/datums/martial/sleeping_carp.dm
  code/game/objects/items.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/grenades/grenade.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/shields.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/assembly/flash.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/color.dm
  code/modules/holodeck/items.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_block.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living_block.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/silicon_defense.dm
  code/modules/mob/living/simple_animal/guardian/types/charger.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/legionnaire.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/projectile.dm
  code/modules/research/xenobiology/crossbreeding/_clothing.dm
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
  tgstation.dme
Labels: FUCK, Refactor

#11722 goodbye separated chemicals
  code/modules/hydroponics/grown/berries.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/tobacco.dm
  code/modules/hydroponics/plant_genes.dm
Labels: Removal, Tweak

#11813 Fixing master.
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Priority: High

#11818 Update spacemandmm to 1.4
  SpacemanDMM.toml
  code/__HELPERS/unsorted.dm
  code/controllers/hooks.dm
  code/controllers/subsystem/processing/weather.dm
  code/datums/components/radioactive.dm
  code/datums/components/wet_floor.dm
  code/datums/datum.dm
  code/datums/wires/_wires.dm
  code/game/data_huds.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/requests_console.dm
  code/game/objects/items/RCL.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/antagonists/abductor/machinery/experiment.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/integrated_electronics/subtypes/smart.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
  code/modules/modular_computers/computers/item/processor.dm
  code/modules/modular_computers/hardware/battery_module.dm
  code/modules/paperwork/contract.dm
  code/modules/projectiles/guns/misc/chameleon.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/plastic_surgery.dm
  code/modules/vending/_vending.dm
  code/modules/vore/eating/belly_obj.dm
  code/modules/vore/trycatch.dm
  dependencies.sh
  modular_citadel/code/modules/arousal/genitals.dm
  modular_citadel/code/modules/reagents/objects/items.dm
Labels: Good First PR

#10891 [Ready]Better crate options
  code/game/objects/items/bodybag.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/crates_lockers/closets/bodybag.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/bodybag.dmi
Labels: Feature, Needs Review, Sprites

#11823 Bringing contamination back
  code/__DEFINES/radiation.dm
  code/datums/radiation_wave.dm
Labels: Fix

#10732 Eldritch Affairs
  code/_onclick/hud/alert.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
  code/modules/antagonists/clockcult/clock_items/clockwork_slab.dm
  code/modules/antagonists/clockcult/clock_scripture.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_scripts.dm
  code/modules/antagonists/clockcult/clockcult.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/ritual.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/power/singularity/narsie.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
Labels: Feature

#11824 Fixes occasional tunnel hole in the space hermit ruin.
  _maps/RandomRuins/SpaceRuins/spacehermit.dmm
  code/game/turfs/simulated/minerals.dm
  icons/turf/mining.dmi
  icons/turf/smoothrocks.dmi
Labels: Fix, Map Edit, Sprites

#11825 Little Holodeck refactor.
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/mapping.dm
  code/game/area/areas/holodeck.dm
  code/modules/holodeck/area_copy.dm
  code/modules/holodeck/computer.dm
Labels: Refactor

#11836 Made a few for loops typed again.
  code/modules/holodeck/area_copy.dm
Labels: Fix

#11837 Item color removal port fixes.
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  icons/mob/clothing/uniform_digi.dmi
Labels: FUCK, Fix, Sprites

#10986 wall walking boots for traitors
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/uplink/uplink_items/uplink_clothing.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/feet_digi.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/module.dmi
Labels: Feature, Sprites, Stale

#11275 Reenables the swarmers event.
  code/datums/helper_datums/teleport.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/antagonists/swarmer/swarmer_event.dm
Labels: Feature

#11834 adds rudimentary linux iptables support for fail2topic (and makes fail2topic disabled by default while i'm at it)
  code/controllers/subsystem/fail2topic.dm
  config/config.txt
Labels: Config Update

#11840 Actually fixed wizard garbs.
  code/datums/elements/spellcasting.dm
Labels: Priority: High

#11838 makes circuit theft admin only
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/controllers/subsystem/processing/circuit.dm
  code/modules/cargo/packs/science.dm
Labels: Map Edit, Removal

#11831 Fixing some sprite accessories offsets, shifted the icon states 2 px down.
  modular_citadel/code/modules/arousal/genitals_sprite_accessories.dm
  modular_citadel/icons/obj/genitals/taur_penis_onmob.dmi
Labels: Fix

#11830 Fixes the phantom thief component, again
  code/datums/components/phantomthief.dm
  code/modules/clothing/glasses/phantomthief.dm
Labels: Fix

#11829 Fixing a whacky miniature cell duping issue.
  code/modules/power/lighting.dm
Labels: Fix

#11828 Fixes toilet cistern loot spawning on the floor.
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/structures/watercloset.dm
Labels: Fix

#11826 Body size preferences! Oh no!
  code/__DEFINES/movespeed_modification.dm
  code/__HELPERS/mobs.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  config/game_options.txt
Labels: Config Update, Refactor

#11655 Gives a cooldown to the crusher's vortex talisman trophy.
  code/modules/mining/equipment/kinetic_crusher.dm
Labels: Balance/Rebalance

#11618 Adds garlic, and tweaks bloodsuckers a bunch.
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/human.dm
  code/_onclick/item_attack.dm
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/game/gamemodes/bloodsucker/bloodsucker.dm
  code/game/machinery/cloning.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/antagonists/bloodsucker/bloodsucker_integration.dm
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
  code/modules/antagonists/bloodsucker/bloodsucker_powers.dm
  code/modules/antagonists/bloodsucker/bloodsucker_sunlight.dm
  code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
  code/modules/antagonists/bloodsucker/items/bloodsucker_organs.dm
  code/modules/antagonists/bloodsucker/objects/bloodsucker_crypt.dm
  code/modules/antagonists/bloodsucker/powers/cloak.dm
  code/modules/antagonists/bloodsucker/powers/feed.dm
  code/modules/antagonists/bloodsucker/powers/fortitude.dm
  code/modules/food_and_drinks/food/snacks_bread.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/hydroponics/grown/garlic.dm
  code/modules/hydroponics/grown/onion.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/language/vampiric.dm
  code/modules/mining/equipment/regenerative_core.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/mob_movement.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  modular_citadel/code/modules/reagents/objects/clothes.dm
  tgstation.dme
Labels: Balance/Rebalance, Code Improvement, Feature, Fix, Sprites, Tweak

#11855 ToS compliance
  _maps/RandomRuins/SpaceRuins/bus.dmm
  code/__DEFINES/inventory.dm
  code/__HELPERS/game.dm
  code/datums/diseases/wizarditis.dm
  code/datums/materials/basemats.dm
  code/datums/mutations/speech.dm
  code/game/machinery/doors/checkForMultipleDoors.dm
  code/game/objects/items/manuals.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/signs/signs_plaques.dm
  code/modules/admin/secrets.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pizza.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_spaghetti.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
  html/archivedchangelog.html
  icons/obj/food/food.dmi
  strings/insult.json
  strings/ion_laws.json
  strings/names/death_commando.txt
  strings/traumas.json
Labels: Map Edit, Sprites, Tweak

#11799 Replacing potential slurs and misinterpretable words with tolerable vocables.
  code/__DEFINES/inventory.dm
  code/__HELPERS/game.dm
  code/datums/diseases/wizarditis.dm
  code/datums/materials/basemats.dm
  code/datums/mutations/speech.dm
  code/game/machinery/doors/checkForMultipleDoors.dm
  code/game/objects/items/manuals.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/signs/signs_plaques.dm
  code/modules/admin/secrets.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pizza.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_spaghetti.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
  icons/obj/food/food.dmi
Labels: Priority: High

#11858 ok for REAL
  config/mentors.txt
Labels: Config Update

#11879 fixes magboots
  code/modules/clothing/shoes/magboots.dm
Labels: Fix

#11851 Contractor kits are now poplocked to 30.
  code/modules/uplink/uplink_items/uplink_bundles.dm
Labels: Balance/Rebalance

#11839 you can no longer knock out xenomorphs by punching them in the face i guess
  code/modules/mob/living/carbon/alien/status_procs.dm
Labels: Fix

#11844 Its no longer possible to craft multiple things at a time
  code/datums/components/crafting/craft.dm
Labels: Fix

#11886 [Fix] YouTool Vending
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Fix

#11877 Fixes a bunch of gripes people had with lambda.
  _maps/map_files/LambdaStation/lambda.dmm
Labels: Fix, Map Edit

#11849 Removes pixel offsets from box dorms lockers/dressers etcetera.
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Removal, Tweak

#11852 Custom skin tone preferences.
  code/__DEFINES/DNA.dm
  code/__HELPERS/mobs.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/dna.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/game/objects/structures/mirror.dm
  code/modules/admin/create_mob.dm
  code/modules/antagonists/bloodsucker/powers/veil.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/angel.dm
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/helpers.dm
  config/game_options.txt
  icons/mob/human_parts_greyscale.dmi
  modular_citadel/code/modules/arousal/genitals.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/arousal/organs/testicles.dm
  modular_citadel/code/modules/arousal/organs/vagina.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
Labels: Config Update, Feature, Sprites

#11857 Race drinks!
  code/__DEFINES/food.dm
  code/__DEFINES/is_helpers.dm
  code/datums/mood_events/drink_events.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#11880 Allows xenohybrids to scream like xeno would
  modular_citadel/code/modules/mob/cit_emotes.dm
Labels: Feature, Removal

#11870 Catnip is no longer a mime plant
  code/modules/hydroponics/grown/tea_coffee.dm
Labels: Fix

#11730 Minor snowflakes clothing variations refactor. Removal of copypasted states.
  code/__DEFINES/inventory.dm
  code/game/objects/items.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/religion.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/clothing/under/jobs/civilian/curator.dm
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/clothing/under/jobs/rnd.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/shorts.dm
  code/modules/clothing/under/skirt_dress.dm
  code/modules/clothing/under/suits.dm
  code/modules/clothing/under/sweaters.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/clothing/trek.dm
  modular_citadel/icons/mob/citadel/uniforms.dmi
  modular_citadel/icons/mob/clothing/turtlenecks.dmi
  modular_citadel/icons/obj/clothing/turtlenecks.dmi
Labels: Sprites

#11863 Honey Palm can be distill into mead
  code/modules/hydroponics/grown/flowers.dm
Labels: Feature

#11893 Once upon a time, a based guardian anchored its name to others' minds.
  code/modules/mob/living/simple_animal/guardian/guardian.dm
Labels: Fix

#11882 Makes objectives clean theirselves up properly
  code/game/gamemodes/objective.dm
Labels: Fix

#11900 reverts #11880
  modular_citadel/code/modules/mob/cit_emotes.dm
Labels: Removal, Revert

#11866 Shuffles around and buffs resisting embedded objects
  modular_citadel/code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#11885 ports "Makes visible(based on sight) messages always appear to mobs in range of 1 despite in darkness"
  code/modules/mob/mob.dm
Labels: Tweak

#11883 Makes dynamic voting not the default
  config/game_options.txt
Labels: Config Update

#11887 storage boxes now have clickdrag passthrough
  code/_onclick/hud/screen_objects/storage.dm
Labels: Tweak

#11899 Fixing some more mistakes I did to clothing.
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#11860 Adds more shields and tweaks a few!
  code/game/objects/items/shields.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/inhands/equipment/shields_lefthand.dmi
  icons/mob/inhands/equipment/shields_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/shields.dmi
Labels: Balance/Rebalance, Feature, Sprites

#11902 Revert "Makes so turning in place updates riders when riding someone's back"
  code/datums/components/riding.dm
Labels: Fix, Revert

#11903 fix for my relatively minuscule backend refactor for holodeck.
  code/__DEFINES/subsystems.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/mapping.dm
  code/controllers/subsystem/holodeck.dm
  code/game/area/areas/holodeck.dm
  code/modules/holodeck/area_copy.dm
  code/modules/holodeck/computer.dm
  tgstation.dme
Labels: Refactor

#11895 fixes piggyback merging
  code/datums/components/riding.dm
Labels: Fix

#11906 Fixing Forensic scanners not reading blood DNA.
  code/game/atoms.dm
Labels: Fix

#11846 Optimizing vore + commenting out simplemob vore (sorry)
  code/__DEFINES/citadel_defines.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/voreconstants.dm
  code/game/objects/items/devices/dogborg_sleeper.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/holodeck/holo_effect.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/dragon_vore.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/simple_animal_vr.dm
  code/modules/mob/living/simple_animal/simplemob_vore_values.dm
  code/modules/vore/eating/belly_obj.dm
  code/modules/vore/eating/bellymodes.dm
  code/modules/vore/eating/living.dm
  code/modules/vore/eating/vorepanel.dm
  modular_citadel/code/modules/mob/living/silicon/robot/dogborg_equipment.dm
Labels: Refactor, Removal

#11894 Adds not-so-great TMP-era trek utility uniform, also fixes loadout restriction descs
  code/modules/clothing/under/trek.dm
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature, Grammar and Formatting, Merge Conflict, Sprites

#11897 Snitches now get stitches
  code/game/gamemodes/gangs/gang.dm
Labels: Balance/Rebalance

#11865 Shuffles resist embed higher up on the resist chain
  code/modules/mob/living/living.dm
Labels: Tweak

#11868 Ports TG Tackling and uses it to rework bloodsucker lunge
  _maps/RandomRuins/LavaRuins/lavaland_surface_alien_nest.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/advancedlab.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomZLevels/Academy.dmm
  _maps/RandomZLevels/spacebattle.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/_onclick/click.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/datums/components/tackle.dm
  code/datums/elements/squish.dm
  code/datums/mutations/body.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/antagonists/bloodsucker/powers/fortitude.dm
  code/modules/antagonists/bloodsucker/powers/lunge.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/awaymissions/corpse.dm
  code/modules/cargo/exports/gear.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/security.dm
  code/modules/clothing/gloves/tacklers.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/outfits/vr.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/ruins/lavaland_ruin_code.dm
  code/modules/uplink/uplink_items/uplink_clothing.dm
  code/modules/vending/security.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
  tgstation.dme
Labels: Balance/Rebalance, Code Improvement, Map Edit, Sprites

#11854 Something about configs and integers.
  code/__HELPERS/sanitize_values.dm
  code/controllers/configuration/entries/game_options.dm
  code/modules/client/preferences_savefile.dm
Labels: Config Update

#11967 Replaces, a ^ in supermatter calculations with **
  code/modules/power/supermatter/supermatter.dm
Labels: FUCK, Priority: High

#11942 Cube world, aka - More dehydrated cubes! Modular Cubes and more!
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/cargo/packs/organic.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/kitchen_machinery/monkeyrecycler.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/mining/machine_vending.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/research/designs/biogenerator_designs.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  code/modules/research/xenobiology/crossbreeding/industrial.dm
  code/modules/research/xenobiology/crossbreeding/reproductive.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/vending/dinnerware.dm
Labels: Merge Conflict

#11832 adds extra functionality to storage whitelists
  code/datums/components/storage/storage.dm
Labels: Feature

#11848 Removing SS_TICKER from the lighting subsystem
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/processing/flightpacks.dm
Labels: Currently Testmerged, Test Merge Candidate, Tweak

#12016 fixes global proccall
  code/modules/admin/callproc/callproc.dm
Labels: Priority: High

#11847 A peeve with random bodies.
  code/__HELPERS/mobs.dm
  code/datums/dna.dm
  code/modules/antagonists/bloodsucker/powers/veil.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
Labels: Fix

#11918 nerf to biogenerator upgrades, removal of flour and glass bottles designs.
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/research/designs/biogenerator_designs.dm
  icons/obj/drinks.dmi
Labels: Sprites

#11947 Ports /vg/ atmos map for boxstation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Test Merge Candidate

#11989 Nerfs confusion
  code/modules/mob/mob_movement.dm
Labels: Test Merge Candidate

#12006 Kilo station improvements
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/cargo_kilo.dmm
  _maps/shuttles/emergency_kilo.dmm
  _maps/shuttles/ferry_kilo.dmm
  _maps/shuttles/labour_kilo.dmm
  _maps/shuttles/mining_kilo.dmm
Labels: Awaiting further discussion/approval

#12000 Fuck Ranged Security Knockdowns: The Taser Nerf PR That Will Get Me Killed By A Witchhunt
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/ammunition/energy/stun.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/projectile/special/ion.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
  modular_citadel/icons/obj/guns/pumpactionblaster.dmi
Labels: Awaiting further discussion/approval

#12063 Disables hardmode citadel combat
  code/modules/mob/living/carbon/damage_procs.dm
  modular_citadel/code/modules/mob/living/carbon/damage_procs.dm
Labels: Priority: High
