Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-01, with the labels that each got.

#10361 Ghost Cafe patrons now spawn with chameleon kits
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Feature

#10356 Adds space to sprint and toggle sprint as preferences
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/keybindings/bindings_human.dm
Labels: Feature

#10330 More nanites from /tg/station
  code/controllers/subsystem/processing/nanites.dm
  code/datums/components/nanites.dm
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/nanites/program_disks.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Good First PR

#10383 megafauna (including player transformed ones !!) are no longer deaf
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Fix

#10370 blood drunk buff probably shouldnt cripple you
  code/datums/status_effects/buffs.dm
Labels: Fix

#10372 forcefield projectors on toolbelts, cool and good sprites for atmos holofan/forcefield proj
  code/game/objects/items/devices/forcefieldprojector.dm
  code/game/objects/items/holosign_creator.dm
  code/game/objects/items/storage/belt.dm
  icons/obj/device.dmi
Labels: Sprites, Tweak

#10369 crusher trophy drop chance increase
  code/modules/mob/living/simple_animal/hostile/mining_mobs/mining_mobs.dm
Labels: Tweak

#10379 shotgun pointblanking people actually throws them
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/toy.dm
Labels: Feature

#10368 ORM lasers actually affect point return
  code/modules/mining/machine_redemption.dm
Labels: Balance/Rebalance

#10374 [s] Fixes Dragon's Tooth Sword 50% armor penetration by making it 35%
  code/game/objects/items/melee/energy.dm
Labels: Fix

#10366 beaker buff - alt title fuck hypovials and fuck making them free and better alternatives to beakers
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/hypovial.dm
Labels: Balance/Rebalance

#10371 call of duty loot boxes
  code/modules/cargo/packs/misc.dm
Labels: Feature

#10390 [s] removes fun
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: FUCK

#10388 Adds the "View Crew Manifest" verb to Robots
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: Feature

#10270 randomized recipes fallback fix.
  code/modules/reagents/chemistry/recipes/special.dm
Labels: Fix

#10238 Brings in some mapping code updates.
  _maps/RandomZLevels/Cabin.dmm
  _maps/RandomZLevels/VR/snowdin_VR.dmm
  _maps/RandomZLevels/caves.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RandomZLevels/spacebattle.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/Mining/Lavaland.dmm
  code/__DEFINES/maps.dm
  code/__HELPERS/_logging.dm
  code/__HELPERS/level_traits.dm
  code/_globalvars/logging.dm
  code/controllers/subsystem/air.dm
  code/game/atoms.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/stunbaton.dm
  code/game/turfs/baseturf_skipover.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/simulated/floor/plating.dm
  code/game/turfs/simulated/floor/plating/asteroid.dm
  code/game/turfs/turf.dm
  code/game/world.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/holodeck/computer.dm
  code/modules/mapping/map_template.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mapping/preloader.dm
  code/modules/mapping/reader.dm
  code/modules/recycling/conveyor2.dm
Labels: Code Improvement, Fix, Grammar and Formatting, Map Edit, Tweak

#10189 Storytellers for Dynamic
  code/__DEFINES/dynamic.dm
  code/__DEFINES/vote.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_events.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  code/modules/admin/admin.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  tgstation.dme
Labels: Feature

#10255 Hopefully fixes the broken Christmas clothes that no one knows how they broke?
  icons/obj/clothing/suits.dmi
Labels: Fix, Sprites

#10403 Add a way to make opaque plastic flaps
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Feature

#10419 HELP I CANT POWERGAME NANITES IF I CANT MAKE NANITE MACHINES (please testmerge these things more)
  code/game/objects/items/stacks/stack.dm
Labels: Priority: High

#10432 Fixes a few cans not having crushed sprites
  icons/obj/janitor.dmi
Labels: Fix, Sprites

#10191 Custom Holoforms for pAIs and AIs oh and adds certain cyborg pai holograms. also mild pai nerf.
  code/__DEFINES/misc.dm
  code/__HELPERS/custom_holoforms.dm
  code/__HELPERS/icons.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/job.dm
  code/datums/emotes.dm
  code/game/machinery/hologram.dm
  code/game/objects/buckling.dm
  code/game/objects/items/devices/paicard.dm
  code/modules/client/preferences.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/custom_holoform.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/pai_defense.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/living/silicon/pai/say.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/mob/living/silicon/pai/update_icon.dm
  code/modules/mob/living/update_icons.dm
  code/modules/mob/mob.dm
  icons/effects/effects.dmi
  modular_citadel/code/modules/mob/cit_emotes.dm
  tgstation.dme
Labels: Config Update, Feature, Sprites

#10399 Knocks down cargo passive gen 750 -> 500
  code/controllers/subsystem/shuttle.dm
Labels: Balance/Rebalance

#10412 matchbox runtime fix
  code/datums/components/storage/concrete/_concrete.dm
Labels: Fix

#10413 Reduces engraving light power
  code/modules/library/soapstone.dm
Labels: Tweak

#10378 A simple fix and a simple test.
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#10429 Corrects MASON Rig's missing flags
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Tweak

#10380 powerfists throw people faster but also leak their gas into the air
  code/game/objects/items/powerfist.dm
Labels: Balance/Rebalance, Feature, Tweak

#10278 Fixes Fermi plushie reaction. Removes carbonation of caramel
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/reagents/chemistry/recipes/others.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Fix

#10256 Adds an alcohol intolerance trait (NOT light drinker)
  code/__DEFINES/traits.dm
  code/controllers/subsystem/processing/quirks.dm
  code/datums/traits/neutral.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Feature

#10428 Made dev bombs kill through bomb armor again
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance/Rebalance

#10396 reverts that one TEG nerf that forced it to require an arbitrary burnmix
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/power/generator.dm
Labels: Revert

#10430 VIBE CHECK
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/touch_attacks.dm
Labels: Balance/Rebalance

#10435 biogenerator can print flour sacks and enzyme now, also some boxes idk
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/research/designs/biogenerator_designs.dm
Labels: Feature

#10433 nerfs pogscarabs
  code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
Labels: Balance/Rebalance

#10317 Corrects issues with box map
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#10224 Makes trait blacklisting remove random positives instead of removing every quirk (new and improved)
  code/controllers/subsystem/processing/quirks.dm
Labels: Tweak

#10446 Revert "Makes mob/Stat on a 1 second timer rather than fast-as-possible to tone down highpop lag"
  code/modules/mob/mob.dm
Labels: Revert

#10350 Ghost cafe quality-of-life, plus making ghost role eligibility an element
  _maps/map_files/generic/CentCom.dmm
  code/__HELPERS/game.dm
  code/_globalvars/misc.dm
  code/datums/action.dm
  code/datums/elements/_element.dm
  code/datums/elements/ghost_role_eligibility.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items/holy_weapons.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/antagonists/blob/blob/powers.dm
  code/modules/client/client_defines.dm
  code/modules/events/holiday/xmas.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  tgstation.dme
Labels: Feature, Map Edit, Refactor

#10427 beaker tweaks: setting transfer values verb on altclick, value tweaks
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/hypovial.dm
Labels: Tweak

#10437 Fixes roundstart mushpeople being unable to MUSH PUUUUUUUUUUUUNCH!!
  code/__DEFINES/components.dm
  code/datums/mind.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
Labels: Fix

#10401 Add three more Supermatter Engine variation for Box
  _maps/RandomRuins/StationRuins/Box/Engine/engine_sm_1x3.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_sm_3x.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_sm_5x5.dmm
  code/datums/ruins/station.dm
Labels: Feature, Map Edit

#10384 cargo tweaks, new shit, why do digitigrade sprites exist
  code/datums/components/storage/concrete/pockets.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/storage/toolbox.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/emergency.dm
  code/modules/cargo/packs/livestock.dm
  code/modules/cargo/packs/medical.dm
  code/modules/cargo/packs/misc.dm
  code/modules/cargo/packs/organic.dm
  code/modules/cargo/packs/science.dm
  code/modules/cargo/packs/security.dm
  code/modules/cargo/packs/service.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/boxing.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/research/stock_parts.dm
  code/modules/vending/security.dm
  icons/mob/feet.dmi
  icons/mob/feet_digi.dmi
  icons/mob/head.dmi
  icons/mob/inhands/equipment/toolbox_lefthand.dmi
  icons/mob/inhands/equipment/toolbox_righthand.dmi
  icons/mob/mask.dmi
  icons/mob/mask_muzzled.dmi
  icons/mob/suit.dmi
  icons/mob/suit_digi.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_digi.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/storage.dmi
Labels: Feature, Fix, Sprites, Tweak

#9878 Unmodularize several machinery and structures
  code/game/machinery/Sleeper.dm
  code/game/machinery/firealarm.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/tables_racks.dm
  modular_citadel/code/game/machinery/Sleeper.dm
  modular_citadel/code/game/machinery/displaycases.dm
  modular_citadel/code/game/objects/structures/beds_chairs/chair.dm
  modular_citadel/code/game/objects/structures/tables_racks.dm
  tgstation.dme
Labels: Tweak

#10047 Turns dog/cat petting into an element datum.
  code/datums/elements/wuv.dm
  code/datums/mood_events/generic_positive_events.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  tgstation.dme
Labels: Code Improvement, Refactor

#10439 doppler logs
  code/game/machinery/doppler_array.dm
Labels: Feature

#10420 Increase radiation plasma usage in radiation collector
  code/modules/power/singularity/collector.dm
Labels: Tweak

#10305 Various Mining borg changes. And some extras.
  _maps/templates/shelter_1.dmm
  _maps/templates/shelter_2.dmm
  _maps/templates/shelter_3.dmm
  code/game/machinery/rechargestation.dm
  code/game/objects/items/robot/robot_items.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/storage/bags.dm
  code/game/turfs/simulated/minerals.dm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/mining/point_bank.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/ammunition/energy/plasma.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/projectile/special/plasma.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/device.dmi
  modular_citadel/icons/mob/widerobot.dmi
  tgstation.dme
  tgui/src/interfaces/point_bank.ract
Labels: Config Update, Map Edit, Sound, Sprites, UI

#10474 [s] Fixes traitors
  code/datums/mind.dm
  code/modules/antagonists/traitor/datum_traitor.dm
Labels: Administration, Fix

#10452 Fixes lattice's examine.
  code/game/objects/structures/lattice.dm
Labels: Fix

#10285 [s] Fixes singularity pulls duping rods out of engine floors.
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/game/turfs/simulated/floor/reinf_floor.dm
Labels: Fix

#10467 stops lightspeed spessmen in boxes
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
Labels: Fix

#10457 Add a playback device and make the Voice Analyzer actually care about languages.
  code/modules/assembly/playback.dm
  code/modules/assembly/voice.dm
  code/modules/vending/assist.dm
  tgstation.dme
Labels: Feature, Fix

#10459 Adds cold-blooded neutral quirk
  code/datums/traits/neutral.dm
Labels: Feature

#10472 Dermal Button nanite icon fix
  icons/mob/actions/actions_items.dmi
Labels: Fix, Sprites

#10447 [READY] Bloodsucker tweaks
  code/datums/status_effects/debuffs.dm
  code/game/gamemodes/bloodsucker/bloodsucker.dm
  code/game/machinery/cloning.dm
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
  code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
  code/modules/antagonists/bloodsucker/datum_vassal.dm
  code/modules/antagonists/bloodsucker/items/bloodsucker_organs.dm
  code/modules/antagonists/bloodsucker/items/bloodsucker_stake.dm
  code/modules/antagonists/bloodsucker/objects/bloodsucker_crypt.dm
  code/modules/antagonists/bloodsucker/powers/bs_cloak.dm
  code/modules/antagonists/bloodsucker/powers/bs_masquerade.dm
  code/modules/antagonists/bloodsucker/powers/bs_mesmerize.dm
  code/modules/antagonists/bloodsucker/powers/bs_trespass.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/mining/equipment/regenerative_core.dm
Labels: Needs Review

#10442 Halfs the nutriments in sugar
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Tweak

#10440 Allows users to vote their least favorite game modes in secret/extended vote
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  config/game_options.txt
Labels: Config Update, Feature, Fix

#10483 Fix limb damage
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#10473 [s] adds a basic sanity check to server_hop
  code/datums/world_topic.dm
  code/game/world.dm
Labels: Fix

#10469 Ports fail2topic from Aurora
  code/__DEFINES/subsystems.dm
  code/__HELPERS/_logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/fail2topic.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/fail2topic.dm
  code/game/world.dm
  code/modules/tgs/v3210/commands.dm
  config/config.txt
  tgstation.dme
Labels: Config Update

#10463 Allowed random engines to be weighted
  code/controllers/configuration/entries/game_options.dm
  code/datums/ruins/station.dm
  code/game/objects/effects/landmarks.dm
  config/game_options.txt
Labels: Config Update

#10503 [S] Fix a pipe problem for the 5x5 SM
  _maps/RandomRuins/StationRuins/Box/Engine/engine_sm_5x5.dmm
Labels: Fix, Map Edit

#10488 Red Dead Redemption 2 but it's a crappy 2D space man game
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/mob/dead/new_player/sprite_accessories/undershirt.dm
  code/modules/vending/clothesmate.dm
  icons/mob/feet.dmi
  icons/mob/head.dmi
  icons/mob/underwear.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/shoes.dm
Labels: Sprites

#10498 reduces table cooldown to 0.4
  code/game/objects/structures/tables_racks.dm
Labels: Salt, Tweak

#10485 replaces old "zulie" sprites with new ones
  icons/mob/custom_w.dmi
Labels: Sprites, Tweak

#10486 moves observe to ghost tab instead of sticking it in the ooc tab
  code/modules/mob/dead/observer/observer.dm
Labels: Tweak

#10482 modular citadel file destruction but only slightly
  code/datums/wires/autoylathe.dm
  code/game/machinery/toylathe.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/designs/autoylathe_designs.dm
  code/modules/vending/kinkmate.dm
  code/modules/vending/medical.dm
  code/modules/vending/sovietvend.dm
  code/modules/vending/wardrobes.dm
  modular_citadel/code/datums/components/material_container.dm
  modular_citadel/code/game/machinery/vending.dm
  modular_citadel/code/game/objects/items/circuitboards/machine_circuitboards.dm
  tgstation.dme
Labels: Code Improvement

#10489 Fixes and improvements for chameleon clothes
  code/modules/clothing/chameleon.dm
Labels: Fix, Tweak

#10465 More ghost dojo tweaks
  _maps/map_files/generic/CentCom.dmm
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Feature, Fix, Map Edit, Removal, Tweak

#10523 you can finally put armor plating on your standard explorer suit hood again
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/machine_vending.dm
Labels: Fix

#10511 Fixes health analyzers
  code/game/objects/items/devices/scanners.dm
Labels: Fix

#10495 allow guests to use looc
  code/modules/client/verbs/looc.dm
Labels: Feature

#10505 better electropack ui
  code/controllers/subsystem/pai.dm
  code/game/objects/items/devices/radio/electropack.dm
  modular_citadel/code/game/objects/items/devices/radio/shockcollar.dm
Labels: Tweak

#10497 Cleans up uplink_items into each folder
  code/modules/uplink/uplink_items.dm
  code/modules/uplink/uplink_items/uplink_ammo.dm
  code/modules/uplink/uplink_items/uplink_badass.dm
  code/modules/uplink/uplink_items/uplink_bundles.dm
  code/modules/uplink/uplink_items/uplink_clothing.dm
  code/modules/uplink/uplink_items/uplink_dangerous.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
  code/modules/uplink/uplink_items/uplink_explosives.dm
  code/modules/uplink/uplink_items/uplink_implants.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
  code/modules/uplink/uplink_items/uplink_stealth.dm
  code/modules/uplink/uplink_items/uplink_stealthdevices.dm
  code/modules/uplink/uplink_items/uplink_support.dm
  tgstation.dme
Labels: Code Improvement

#10247 ATMOS Firelocks and more
  code/game/objects/items/holosign_creator.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/holosign.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Tweak

#10528 fixes vampires
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
Labels: Priority: High

#10509 Fixes reagent containers examine.
  code/modules/reagents/reagent_containers.dm
Labels: Fix

#10516 Allows calling procs in SDQL update queries without storing the return anywhere
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Administration

#10518 ports the explosion rework thingamajig
  code/__DEFINES/combat.dm
  code/game/objects/effects/effect_system/effects_other.dm
  code/game/objects/items/devices/doorCharge.dm
  code/game/objects/items/grenades/plastic.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Balance/Rebalance, Code Improvement

#10522 printable syndicate sleepers - this is blackmajors fault im not gonna lie
  code/game/machinery/Sleeper.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/designs/machine_desings/machine_designs_medical.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#10521 Fixes roundstart borg spawns, plus a little bit extra.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_citadel/icons/mob/widerobot.dmi
Labels: Map Edit

#10532 A few reagents related fixes.
  code/game/objects/items/extinguisher.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Fix

#10480 Added second flavor text, not copied anywhere.
  code/__HELPERS/_cit_helpers.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/say_vr.dm
Labels: Feature

#10504 Bees
  code/modules/mob/living/simple_animal/friendly/bumbles.dm
  icons/mob/animal.dmi
  icons/mob/bees.dmi
  icons/mob/pets.dmi
Labels: Feature, Sprites

#10416 Massive RCD Port & Updates
  code/__DEFINES/construction.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/firealarm.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/RCD.dm
  code/game/turfs/simulated/floor.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/power/apc.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/effects/effects_rcd.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites, Tweak

#10492 Plastic snow
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature

#10546 Prevent Playback Devices from triggering Voice Analyzer
  code/modules/assembly/playback.dm
  code/modules/assembly/voice.dm
Labels: Fix

#10404 Puts an end to the Christmas Menace
  code/modules/vending/autodrobe.dm
  code/modules/vending/clothesmate.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Tweak

#10556 CI to check for wrong line ending
  .travis.yml
  tgstation.dme
  tools/travis/check_line_endings.py
Labels: Tools, Tweak

#10493 Makes the post-secret gamemode vote score-based instead of schulze-based
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
Labels: Config Update, Tweak

#10539 ports hShark snout from hyper-station-13
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  modular_citadel/icons/mob/mam_snouts.dmi
Labels: Feature, Good First PR, Sprites

#10478 Makes the gorilla shuttle emag only
  code/datums/shuttles.dm
Labels: Tweak

#10287 Minor captains closet cleanup.
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Removal

#10549 durathread winter coats from hyper
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/crafting/recipes/recipes_clothing.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/suit_digi.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#10558 Slimepeople can no longer just chill on vitality matrixes
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
Labels: Fix

#10538 Fixes to chemistry
  code/game/objects/items/devices/scanners.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers.dm
Labels: Fix

#10454 fixes clothing directional sprites(i swear not all of them are my fault)
  code/modules/clothing/under/miscellaneous.dm
  icons/obj/clothing/uniforms.dmi
Labels: Fix, Sprites

#10531 Hydroponics can now make sci points
  code/controllers/subsystem/research.dm
  strings/tips.txt
Labels: Code Improvement, Feature

#10560 [s] makes master compile.
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/suit_digi.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_digi.dmi
Labels: Priority: High, Sprites

#10530 deletes modular items but this time i don't get cucked
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items.dm
  code/game/objects/items/balls.dm
  code/game/objects/items/boombox.dm
  code/game/objects/items/devices/radio/electropack.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/grenades/grenade.dm
  code/game/objects/items/stunbaton.dm
  code/game/world.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  modular_citadel/code/game/objects/effects/spawner/spawners.dm
  modular_citadel/code/game/objects/items.dm
  modular_citadel/code/game/objects/items/devices/radio/encryptionkey.dm
  modular_citadel/code/game/objects/items/devices/radio/headset.dm
  modular_citadel/code/game/objects/items/devices/radio/shockcollar.dm
  modular_citadel/code/game/objects/items/stunsword.dm
  modular_citadel/code/init.dm
  tgstation.dme
Labels: Code Improvement

#10535 staff assistant jumpsuit gang
  code/modules/clothing/under/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  goon/icons/mob/worn_js_rank.dmi
  goon/icons/obj/item_js_rank.dmi
  modular_citadel/code/modules/client/loadout/_service.dm
Labels: Feature

#10557 remove trait genes without disks
  code/modules/hydroponics/gene_modder.dm
Labels: Fix

#10415 Small controller/backend updates from /tg/
  code/__DEFINES/callbacks.dm
  code/__DEFINES/qdel.dm
  code/__HELPERS/unsorted.dm
  code/controllers/master.dm
  code/controllers/subsystem/server_maint.dm
  code/controllers/subsystem/timer.dm
  code/datums/callback.dm
Labels: Test Merge Candidate

#10563 Makes fragile suit less likely to brake from toys
  code/modules/clothing/spacesuits/miscellaneous.dm
Labels: Fix

#10567 [s] more efficient supply reagents export.
  code/modules/cargo/exports.dm
  code/modules/shuttle/supply.dm
Labels: Fix, Priority: High

#10417 Nightshift improvements: public area settings/levels, nightshift auth requirement change, config changes, etc etc
  code/__DEFINES/misc.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/nightshift.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/modules/power/apc.dm
  config/game_options.txt
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/interfaces/apc.ract
Labels: Config Update, Feature, UI

#10456 Removes arousal damage and replaces it with simpler systems
  code/__DEFINES/citadel_defines.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/_cit_helpers.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/datums/datumvars.dm
  code/datums/mind.dm
  code/datums/traits/neutral.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/organs/vocal_cords.dm
  modular_citadel/code/datums/status_effects/chems.dm
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/arousal/genitals.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/arousal/organs/testicles.dm
  modular_citadel/code/modules/arousal/organs/vagina.dm
  modular_citadel/code/modules/arousal/toys/dildos.dm
  modular_citadel/code/modules/client/preferences.dm
  modular_citadel/code/modules/integrated_electronics/subtypes/manipulation.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
  modular_citadel/code/modules/reagents/reagents/cit_reagents.dm
  tgstation.dme
Labels: Feature, Removal, Tweak

#10347 [experimental] Buffs the stamina buffer by making it recharge for free.
  code/modules/mob/living/carbon/life.dm
  modular_citadel/code/_onclick/hud/stamina.dm
Labels: Balance/Rebalance, Test Merge Candidate

#10565 Revert "shotgun pointblanking people actually throws them"
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/toy.dm
Labels: Revert

#10582 Made temp flavor "more" pop up with actual temp flavor
  code/modules/mob/mob.dm
  code/modules/mob/say_vr.dm
Labels: Fix

#10584 Hotfix for CI line endings
  tools/travis/check_line_endings.py
Labels: Code Improvement, Tools

#10375 Add a Radiation Hardsuit
  code/modules/cargo/packs/engineering.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#10569 Ports the Nanite Remote, Nanite Mood Programs + Rebalance, and the Research Generating Nanites
  code/__DEFINES/components.dm
  code/datums/components/nanites.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/modules/research/designs/electronics_designs.dm
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/research/nanites/nanite_programs/suppression.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
  code/modules/research/nanites/nanite_remote.dm
  code/modules/research/nanites/program_disks.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/device.dmi
  tgui/assets/tgui.js
  tgui/src/interfaces/nanite_comm_remote.ract
Labels: Balance/Rebalance, Feature, Sprites, UI

#10570 Power cable + atmos pipe auto mapping helpers
  code/modules/atmospherics/machinery/pipes/simple.dm
  code/modules/mapping/mapping_helpers/_mapping_helpers.dm
  code/modules/mapping/mapping_helpers/baseturf.dm
  code/modules/mapping/mapping_helpers/network_builder/_network_builder.dm
  code/modules/mapping/mapping_helpers/network_builder/atmos_pipe.dm
  code/modules/mapping/mapping_helpers/network_builder/power_cables.dm
  code/modules/power/cable.dm
  icons/effects/mapping_helpers.dmi
  tgstation.dme
Labels: Code Improvement, Sprites

#10591 Removes blood duplication via virus mix
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Removal

#10579 Fix Cyborgs spawns on all maps
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#10599 Fixed gibtonite instantly exploding on pick mining
  code/game/turfs/simulated/minerals.dm
Labels: Fix

#10481 Updates Science Uniform and Accessories
  icons/mob/feet.dmi
  icons/mob/feet_digi.dmi
  icons/mob/suit.dmi
  icons/mob/suit_digi.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_digi.dmi
Labels: Removal, Sprites

#10586 Nerfs RLDs because they hard counter nightmares and night ops.
  code/game/objects/items/RCD.dm
Labels: Balance/Rebalance

#10580 Craft logging
  code/__HELPERS/_logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/general.dm
  code/game/objects/items/stacks/stack.dm
  code/game/world.dm
  code/modules/crafting/craft.dm
  config/config.txt
Labels: Administration, Config Update

#10600 Fixes sprinkles on jelly donuts + lack of berry juice
  code/modules/food_and_drinks/food/snacks_pastry.dm
  icons/obj/food/donut.dmi
Labels: Fix, Sprites

#10501 Adds a couple relief valves
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/objects/items/RPD.dm
  code/modules/atmospherics/machinery/components/binary_devices/relief_valve.dm
  code/modules/atmospherics/machinery/components/unary_devices/relief_valve.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  icons/obj/atmospherics/components/relief_valve.dmi
  icons/obj/atmospherics/pipes/pipe_item.dmi
  tgstation.dme
  tgui/assets/tgui.js
  tgui/src/interfaces/atmos_relief.ract
Labels: Feature, Map Edit, Sprites, Tweak, UI

#10578 Port TG's Mining changes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/shuttles/mining_common_meta.dmm
  code/datums/shuttles.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/mining/mine_items.dm
Labels: Feature, Map Edit

#10571 Riot foam dart design cost consistency.
  code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
Labels: Fix

#10568 Add passive vents
  code/game/objects/items/RPD.dm
  code/modules/atmospherics/machinery/components/unary_devices/passive_vent.dm
  icons/obj/atmospherics/components/unary_devices.dmi
  icons/obj/atmospherics/pipes/pipe_item.dmi
  tgstation.dme
Labels: Feature, Sprites

#10601 Adds 16777216 dorms to the ghost dojo
  _maps/map_files/generic/CentCom.dmm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
Labels: Feature, Map Edit

#10547 Makes ghost dojo mobs dust if they're dead and ghostless
  code/datums/elements/dusts_on_catatonia.dm
  code/game/objects/structures/ghost_role_spawners.dm
  tgstation.dme
Labels: Tweak

#10594 Removes shrink rays from abductor console.
  code/modules/antagonists/abductor/machinery/console.dm
Labels: Removal

#10307 stunglasses
  code/datums/action.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/crafting/recipes/recipes_clothing.dm
Labels: Feature

#10520 you like examining things? - port of tgstation 40920
  code/datums/status_effects/debuffs.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/teleporter.dm
  code/game/machinery/dna_scanner.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/harvester.dm
  code/game/machinery/hologram.dm
  code/game/machinery/launch_pad.dm
  code/game/machinery/limbgrower.dm
  code/game/machinery/recharger.dm
  code/game/machinery/rechargestation.dm
  code/game/machinery/recycler.dm
  code/game/machinery/spaceheater.dm
  code/game/machinery/teleporter.dm
  code/game/mecha/mech_bay.dm
  code/game/mecha/mech_fabricator.dm
  code/game/objects/items/devices/laserpointer.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/gibber.dm
  code/modules/food_and_drinks/kitchen_machinery/monkeyrecycler.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seed_extractor.dm
  code/modules/power/port_gen.dm
  code/modules/power/rtg.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/tesla/coil.dm
  code/modules/power/turbine.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_heater.dm
  code/modules/research/experimentor.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/nanites/nanite_chamber.dm
Labels: Code Improvement, Tweak

#10587 Adds bloodsucker antagonist bans
  code/modules/admin/topic.dm
Labels: Administration

#10097 Made traitor kevlar/armor padding accessories examine-proof.
  code/__DEFINES/inventory.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/accessories.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/uplink/uplink_items/uplink_clothing.dm
Labels: Tweak

#10614 Made suicide a config flag
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/game_options.dm
  code/modules/client/verbs/suicide.dm
  config/game_options.txt
Labels: Config Update

#10597 Ghost role eligibility activation in player panel
  code/datums/elements/ghost_role_eligibility.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  modular_citadel/code/modules/admin/admin.dm
  modular_citadel/code/modules/admin/topic.dm
  tgstation.dme
Labels: Administration, Code Improvement

#10346 Nerfs limb stamcrit by doubling the base limb stam regen rate and making disabled limbs double the regen rate further
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Balance/Rebalance, Feature, Test Merge Candidate

#10615 Fixes the nanite sprites deleting the game sprites
  icons/obj/device.dmi
Labels: Fix, Sprites

#10621 .357 AP printable from illegal ballistics
  code/modules/research/techweb/all_nodes.dm
  modular_citadel/code/modules/projectiles/boxes_magazines/external/pistol.dm
Labels: Feature

#10617 Grenades can now actually have their timers adjusted
  code/game/objects/items/grenades/grenade.dm
Labels: Fix

#10635 removes det scanner from adv bio
  code/modules/research/techweb/all_nodes.dm
Labels: Removal

#10608 PDA blocking
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Feature

#10588 Reduces Forcefield Projector Range to Two Tiles
  code/game/objects/items/devices/forcefieldprojector.dm
Labels: Tweak

#10468 ghosting no longer makes it so you don't count for abductors
  code/modules/antagonists/abductor/machinery/experiment.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob_defines.dm
Labels: Feature

#10619 conveyor updates
  code/modules/cargo/packs/engineering.dm
  code/modules/recycling/conveyor2.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_construction.dm
Labels: Feature, Tweak

#10640 Map Fixes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, Map Edit

#10606 Update the Passive Vents that I added
  code/modules/atmospherics/machinery/components/unary_devices/passive_vent.dm
Labels: Refactor

#10622 Ghost Cafe Cleanup
  _maps/map_files/generic/CentCom.dmm
Labels: Feature, Map Edit, Removal, Tweak

#10450 (is this really a good idea) hitscan emitters
  code/game/objects/effects/temporary_visuals/projectiles/impact.dm
  code/game/objects/effects/temporary_visuals/projectiles/muzzle.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Balance/Rebalance

#10645 Modularize the mining base
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01.dmm
  _maps/map_files/Mining/Lavaland.dmm
  code/datums/ruins/station.dm
  code/game/objects/effects/landmarks.dm
  icons/rooms/Lavaland/Mining.dmi
Labels: Feature, Map Edit, Sprites

#10410 Humans and anthromorphs can now use lizard tails.
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
Labels: Tweak
