Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-02, with the labels that each got.

#10793 Masks are now PROPERLY hidden my headgear that hides masks (Spacesuits, Hardsuits, Rad Hoods, Etc.)
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Fix

#10786 made the centcomm suit syndies order be a variant with no sensors
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/clothing/under/miscellaneous.dm
Labels: Tweak

#10777 Gangs can now only tag with GANG spraycans, rather than lathed spraycans
  code/game/objects/items/crayons.dm
Labels: Balance/Rebalance

#10776 heck suit resistances - goliath resistance and also acid-proof
  code/modules/mining/equipment/explorer_gear.dm
Labels: Tweak

#10559 custom reagent pie smite
  code/__DEFINES/admin.dm
  code/__HELPERS/reagents.dm
  code/datums/datumvars.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Feature

#10781 RPD icon reorder, less building pixelhunting
  code/game/objects/items/RPD.dm
Labels: Feature, Tweak

#10821 FIXES FANCY SWITCHBLADES
  code/game/objects/items/weaponry.dm
Labels: Fix

#10830 [s] fixes a glitch with the PKA
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Fix

#10803 fixes the whitespace that gets created when you have highlighting strings on
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: Fix

#10808 [READY] Ports chem dispenser macro recording
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/interfaces/chem_dispenser.ract
Labels: Feature, Needs Review, Removal, UI

#10811 [READY]Ports TG updates to crafting and componentizes it
  code/__DEFINES/components.dm
  code/_onclick/hud/generic_dextrous.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/components/crafting/craft.dm
  code/datums/components/crafting/glassware.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/datums/components/crafting/recipes/recipes_robot.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/crafting/recipes.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/login.dm
  tgstation.dme
Labels: Needs Review, UI

#10800 fixes kevinz error with preferences.dm
  modular_citadel/code/modules/client/preferences.dm
Labels: Fix

#10352 Changes to the way SM handles power related to integrity and max integrity damage
  code/game/objects/items/miscellaneous.dm
  code/modules/cargo/packs/engine.dm
  code/modules/power/supermatter/supermatter.dm
  icons/obj/supermatter.dmi
Labels: Sprites, Tweak

#10805 guns/ammo/projectiles now properly clean up while being deleted
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/projectile.dm
Labels: Salt, Test Merge Candidate

#10731 Energy crossbow changed from RNG to static effects
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/energy/ebow.dm
Labels: Balance/Rebalance, Feature, Removal

#10744 Moar engines!
  _maps/RandomRuins/StationRuins/Box/Engine/budget.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/empty.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_am.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_teg.dmm
  code/datums/ruins/station.dm
  config/game_options.txt
Labels: Config Update, Feature, Map Edit

#10841 Fixes being able to pull after wearing boxing gloves
  code/datums/martial/boxing.dm
Labels: Fix

#10816 pH strip feedback fix/tweak
  modular_citadel/code/modules/reagents/objects/items.dm
Labels: Fix, Good First PR

#10817 Updates Virus Symptom Stats to Match TG
  code/datums/diseases/advance/symptoms/choking.dm
  code/datums/diseases/advance/symptoms/fire.dm
  code/datums/diseases/advance/symptoms/flesh_eating.dm
  code/datums/diseases/advance/symptoms/hallucigen.dm
  code/datums/diseases/advance/symptoms/narcolepsy.dm
  code/datums/diseases/advance/symptoms/shivering.dm
  code/datums/diseases/advance/symptoms/viral.dm
  code/datums/diseases/advance/symptoms/vomit.dm
Labels: Balance/Rebalance, Good First PR

#10796 Status Display Fix: It's About Time
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/machinery/status_display.dm
Labels: Fix, Map Edit

#10831 Fixing chaplain armaments beacon edge case.
  code/game/objects/items/holy_weapons.dm
Labels: Fix

#10833 Playback device spam peeve.
  code/modules/assembly/playback.dm
Labels: Tweak

#10819 clown ops infiltrator consistency.
  _maps/shuttles/infiltrator_basic.dmm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/storage/boxes.dm
  icons/obj/storage.dmi
Labels: Map Edit, Sprites, Tweak

#10820 clown ops uplink consistency.
  code/modules/uplink/uplink_items/uplink_clothing.dm
  code/modules/uplink/uplink_items/uplink_dangerous.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
  code/modules/uplink/uplink_items/uplink_implants.dm
  code/modules/uplink/uplink_items/uplink_stealth.dm
  code/modules/uplink/uplink_items/uplink_stealthdevices.dm
Labels: Tweak

#10834 Craftable Crates!
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Feature

#10784 polychromic winter coats
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/suit_digi.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/code/modules/client/loadout/suit.dm
Labels: Feature, Sprites

#10850 Fixes maploaded APC terminals direction.
  code/modules/power/apc.dm
Labels: Fix

#10810 Adds ring jewelry
  code/game/objects/items/storage/fancy.dm
  code/modules/cargo/packs/misc.dm
  code/modules/clothing/gloves/ring.dm
  icons/obj/ring.dmi
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/code/modules/client/loadout/gloves.dm
  tgstation.dme
Labels: Feature, Sprites

#10829 Fixed and brutalized clown op slippery weapons a little.
  code/__DEFINES/mobs.dm
  code/datums/components/slippery.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/objects/items/grenades/grenade.dm
  code/game/turfs/open.dm
  code/game/turfs/space/space.dm
  code/modules/mob/living/carbon/carbon_movement.dm
Labels: Balance/Rebalance, Fix

#10838 Minor Loadout/Outfit Changes
  code/modules/clothing/under/jobs/medsci.dm
  modular_citadel/code/modules/client/loadout/_medical.dm
  modular_citadel/code/modules/client/loadout/head.dm
Labels: Tweak

#10837 Tweaking Chef Vendor, Blood Crate, and Cake Recipe
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/vending/drinnerware.dm
Labels: Tweak

#10799 makes the golden ""plastitanium"" toolbox actually plastitanium
  code/game/objects/items/storage/toolbox.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
Labels: Fix

#10705 Cleanup/Partial revert of RGB blood ""rework""
  code/__DEFINES/components.dm
  code/_globalvars/lists/mobs.dm
  code/game/atoms.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/effects/decals/cleanable/aliens.dm
  code/game/objects/effects/decals/cleanable/gibs.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/twohanded.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/detectivework/detective_work.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/helpers.dm
  code/modules/surgery/organs/heart.dm
  modular_citadel/code/modules/reagents/reagents/cit_reagents.dm
Labels: Balance/Rebalance, Revert

#10836 adding stuff to techfabs - RCD carts, combifans
  code/game/objects/items/holosign_creator.dm
  code/game/objects/structures/holosign.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_construction.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/effects/effects.dmi
Labels: Feature, Sprites

#10866 Fixes genital skintone mismatching
  modular_citadel/code/modules/arousal/genitals.dm
Labels: Fix

#10876 Fixes slipping.
  code/datums/components/slippery.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
Labels: Fix, Priority: High

#10884 [s] fixing bad nasty endless dna console loop.
  code/game/machinery/computer/dna_console.dm
Labels: Priority: CRITICAL

#10801 changes to rising bass
  code/datums/martial/rising_bass.dm
  icons/mob/actions/actions_items.dmi
Labels: Balance/Rebalance, Sprites

#10852 Comments out meteor defense tech node
  code/modules/research/techweb/all_nodes.dm
Labels: Removal

#10887 Fixes pitch black characters
  code/__HELPERS/sanitize_values.dm
Labels: Priority: High

#10854 Makes a proc for meteor string gen
  code/modules/events/meteor_wave.dm
  code/modules/flufftext/Hallucination.dm
Labels: Feature

#10860 Makes quick item usage (click-dragging unequipped item) require combat mode
  code/game/objects/items.dm
Labels: Tweak

#10862 seed extractor examine tweak/fix
  code/modules/hydroponics/seed_extractor.dm
Labels: Tweak

#10847 Fixes Space Ninja "Nothing" Objective.
  code/modules/antagonists/ninja/ninja.dm
Labels: Fix

#10872 Makes shield no longer block energy projectiles and be destroyed when damaged too much.
  code/game/objects/items/shields.dm
Labels: Balance/Rebalance

#10865 Demodularizes and nerfs magnetic rifles/pistols with power cell requirements.
  code/game/machinery/recharger.dm
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/caseless/ferromagnetic.dm
  code/modules/projectiles/ammunition/caseless/foam.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/magweapon.dm
  code/modules/projectiles/boxes_magazines/external/toy.dm
  code/modules/projectiles/boxes_magazines/internal/toy.dm
  code/modules/projectiles/guns/ballistic/magweapon.dm
  code/modules/projectiles/guns/ballistic/toy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/ferromagnetic.dm
  code/modules/projectiles/projectile/reusable/foam_dart.dm
  code/modules/research/designs/autoylathe_designs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/ammo.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/guns/toy.dmi
  icons/obj/projectiles.dmi
  modular_citadel/code/modules/projectiles/guns/ballistic/magweapon.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/magweapon_energy.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/rifles.dm
  modular_citadel/icons/obj/guns/cit_guns.dmi
  tgstation.dme
Labels: Balance/Rebalance, Sprites

#10873 Updated relief valve UI to tgui-next
  tgui-next/packages/tgui/interfaces/AtmosRelief.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Tweak, UI

#10867 Further buff and fix to the clown ops' tearstache grenade.
  code/__DEFINES/traits.dm
  code/_onclick/hud/screen_objects.dm
  code/game/gamemodes/clown_ops/clown_weapons.dm
  code/game/objects/items/grenades/chem_grenade.dm
  code/game/objects/items/tanks/tanks.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/uplink/uplink_items/uplink_explosives.dm
Labels: Balance/Rebalance, Fix

#10840 Save panic bunker between rounds
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/persistence.dm
  code/modules/admin/chat_commands.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client_procs.dm
  config/config.txt
Labels: Administration, Config Update

#10874 Fixes the petting element.
  code/datums/elements/wuv.dm
Labels: Fix

#10893 [READY]TGUI Next Crafting
  code/datums/components/crafting/craft.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Feature, Needs Review, Removal, UI

#10739 Add a Dwarf Language
  code/modules/language/dwarven.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
  code/modules/surgery/organs/tongue.dm
  icons/misc/language.dmi
  tgstation.dme
Labels: Feature, Sprites

#10875 Adds bunny ear style for humans and anthromorphs
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  modular_citadel/icons/mob/mam_ears.dmi
Labels: Sprites

#10869 can we talk about how admin attack logs being viewable in game is not a good thing, alternatively "i want a word with whoever coded mech logging"
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/mining_tools.dm
  code/game/mecha/equipment/tools/other_tools.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/mecha/mecha_defense.dm
  code/game/mecha/mecha_topic.dm
  code/game/mecha/working/ripley.dm
Labels: Fix

#10812 Stunbaton Balance Adjustments 2.0 (Unfucked Edition)
  code/game/objects/items/stunbaton.dm
Labels: Balance/Rebalance

#10583 Consent logging
  code/__HELPERS/_logging.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/vore/eating/living.dm
  modular_citadel/code/modules/arousal/arousal.dm
Labels: Administration

#10832 Mining Update : Real update
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01.dmm
Labels: Map Edit

#10791 [READY] Further tweaks to bloodsuckers
  code/datums/mood_events/generic_negative_events.dm
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
  code/modules/antagonists/bloodsucker/bloodsucker_powers.dm
  code/modules/antagonists/bloodsucker/bloodsucker_sunlight.dm
  code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
  code/modules/antagonists/bloodsucker/datum_vassal.dm
  code/modules/antagonists/bloodsucker/objects/bloodsucker_coffin.dm
  code/modules/antagonists/bloodsucker/objects/bloodsucker_crypt.dm
  code/modules/antagonists/bloodsucker/powers/bs_brawn.dm
  code/modules/antagonists/bloodsucker/powers/bs_feed.dm
  code/modules/antagonists/bloodsucker/powers/bs_fortitude.dm
  code/modules/antagonists/bloodsucker/powers/bs_gohome.dm
  code/modules/antagonists/bloodsucker/powers/bs_haste.dm
  code/modules/antagonists/bloodsucker/powers/bs_lunge.dm
  code/modules/antagonists/bloodsucker/powers/bs_mesmerize.dm
  code/modules/antagonists/bloodsucker/powers/bs_trespass.dm
  code/modules/mob/living/carbon/alien/special/facehugger.dm
Labels: Balance/Rebalance, Feature, Needs Review, Tweak

#10788 crushing magboots for tators
  code/modules/clothing/shoes/magboots.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
Labels: Feature

#10747 shoving someone into a wall on the second shove now also disarms their weapon
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance

#10855 The Syndicats are run by aliens - Fixes Alien cargo crate to be correction emag
  code/modules/cargo/packs/science.dm
Labels: Feature

#10894 Buffs carps again
  code/modules/mob/living/simple_animal/hostile/carp.dm
Labels: Feature

#10915 jackboot magpistols are a thing again
  code/datums/components/storage/concrete/pockets.dm
Labels: Balance/Rebalance

#10903 fuck organ decay - tgstation#47770
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Feature

#10898 Disposing of a problem on Delta.
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix, Map Edit, Tweak

#10931 Fixing admin ranks configs loading.
  code/modules/admin/admin_ranks.dm
Labels: FUCK, Priority: High

#10907 Fixes no-grav lavaland labor/mining shuttle areas.
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01.dmm
Labels: Fix, Map Edit

#10905 consoleless interfaces default, standard RCD ammo added to industrial engi
  code/modules/research/designs/autolathe_desings/autolathe_designs_construction.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tools.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/machinery/departmental_circuit_imprinter.dm
  code/modules/research/machinery/departmental_protolathe.dm
  code/modules/research/machinery/techfab.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Tweak

#10900 Ports atmos priority reaction mix from TG
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Fix

#10899 Almost all venders now can be restocked
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/cargo/packs/vending.dm
  code/modules/vending/assist.dm
  code/modules/vending/cartridge.dm
  code/modules/vending/drinnerware.dm
  code/modules/vending/engivend.dm
  code/modules/vending/kinkmate.dm
  code/modules/vending/megaseed.dm
  code/modules/vending/nutrimax.dm
  code/modules/vending/security.dm
  code/modules/vending/sovietvend.dm
  code/modules/vending/sustenance.dm
  code/modules/vending/youtool.dm
  icons/obj/citvending.dmi
  icons/obj/vending.dmi
  icons/obj/vending_restock.dmi
  modular_citadel/icons/vending_restock.dmi
Labels: Feature, Sprites

#10885 Removing a couple troublesome NSFW useless and unused preferences.
  code/__HELPERS/mobs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/testicles.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
Labels: Fix

#10902 Fixes some mounted defibrillator issue.
  code/game/machinery/defibrillator_mount.dm
Labels: Fix

#10883 Allows ghosts to read newscasters and books
  code/__DEFINES/interaction_flags.dm
  code/game/atoms.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/newscaster.dm
  code/game/turfs/turf.dm
  code/modules/library/lib_items.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob_helpers.dm
Labels: Tweak

#10700 Anomalous honking crystal pet peeve & co.
  code/__DEFINES/traits.dm
  code/modules/antagonists/nukeop/clownop.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
Labels: Tweak

#10881 Refactoring mob holders into an element.
  code/__DEFINES/components.dm
  code/_onclick/click.dm
  code/datums/elements/mob_holder.dm
  code/datums/elements/wuv.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/inhand_holder.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/sloth.dm
  code/modules/mob/mob.dm
  tgstation.dme
Labels: Refactor

#10906 husking is stupid - 5u rezadone/100u synthflesh heals husking, husking takes more burn
  code/__DEFINES/reagents.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance, Feature

#10868 Holofans visual tweak.
  code/game/objects/structures/holosign.dm
Labels: Tweak

#10870 Fixed wheelchair-goers appearing as shoeless
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Fix

#10901 Corrects Box'es caps office + some other tweaks
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#10917 Removes the hypospray verb for toggling spray/inject mode and makes it into an Alt click proc.
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Removal, Tweak

#10623 Better antag objectives: for real this time
  code/__DEFINES/dynamic.dm
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/vote.dm
  code/__HELPERS/roundend.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/dynamic.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/processing/quirks.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/datums/mind.dm
  code/datums/traits/_quirk.dm
  code/datums/traits/negative.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/objective_sabotage.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/book.dm
  code/modules/admin/antag_panel.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/_common/antag_team.dm
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/collector/collector.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/disease/disease_datum.dm
  code/modules/antagonists/ninja/ninja.dm
  code/modules/antagonists/survivalist/survivalist.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/antagonists/valentines/valentine.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/spells/spell_types/rightandwrong.dm
  config/dynamic_config.txt
  interface/stylesheet.dm
  strings/flavor_objectives/ninja_helping.txt
  strings/flavor_objectives/ninja_syndie.txt
  strings/flavor_objectives/traitor.txt
  strings/flavor_objectives/traitor/assistant.txt
  strings/flavor_objectives/traitor/engineering.txt
  strings/flavor_objectives/traitor/medical.txt
  strings/flavor_objectives/traitor/science.txt
  strings/flavor_objectives/wizard.txt
  tgstation.dme
Labels: Config Update, Feature

#10922 renames the lawyer cartridge to something more accurate to its function
  code/game/objects/items/devices/PDA/cart.dm
Labels: Tweak

#10929 Double-esword and hypereuplastic blade toys are now blunt.
  code/game/objects/items/toys.dm
Labels: Fix

#10798 Formal security wear are now armor vests (HAS SOME BALANCE CONCERNS)
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/cargo/packs/security.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/vending/wardrobes.dm
  modular_citadel/code/modules/client/loadout/_security.dm
Labels: Map Edit, Removal, Tweak

#10787 thief's gloves
  code/modules/clothing/gloves/_gloves.dm
  code/modules/clothing/gloves/boxing.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mob/living/living.dm
  code/modules/uplink/uplink_items/uplink_clothing.dm
  icons/obj/clothing/gloves.dmi
Labels: Feature, Sprites

#10921 Lavaland's Herald speech fix.
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
Labels: Fix

#10924 Fixing whitelisted/donor loadouts
  modular_citadel/code/modules/custom_loadout/read_from_file.dm
Labels: Fix

#10950 beam rifle sanity update
  code/modules/projectiles/guns/misc/beam_rifle.dm
Labels: Fix, Priority: High

#10951 fail2topic runtime fix
  code/controllers/subsystem/fail2topic.dm
Labels: Fix

#10957 Fixes a spurious dynamic runtime if nobody votes
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Fix

#10774 nuke explosion is 512 dev which is actually less laggy than heavy + light
  code/controllers/subsystem/ticker.dm
Labels: Tweak

#10892 Small guncode refactor but it works
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/projectiles/ammunition/energy/plasma.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/special.dm
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
Labels: Feature, Fix, Refactor

#10935 Returns the Van Dyke mustache to its former glory
  icons/mob/human_face.dmi
Labels: Good First PR, Removal, Sprites

#10966 Fix mining base having holes to space
  _maps/map_files/Mining/Lavaland.dmm
Labels: Fix, Map Edit

#10960 lavaland plant disk techdisk actually works
  code/modules/research/designs/misc_designs.dm
Labels: Fix

#10974 Fixed antag quirk blacklisting
  code/modules/antagonists/_common/antag_datum.dm
Labels: Fix

#10762 One last attempt at balancing tasers (and some adv egun stuff)
  code/__DEFINES/flags.dm
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/living.dm
  code/modules/projectiles/ammunition/energy/stun.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/projectiles/projectile/energy/stun.dm
Labels: Balance/Rebalance, Feature

#10942 Added a config for map voting types
  code/__DEFINES/vote.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  config/config.txt
Labels: Config Update, Feature

#10959 TGUI Next autobuilding
  .github/workflows/autobuild_tgui.yml
  dependencies.sh
  tgui-next/README.md
  tgui-next/bin/tgui
  tools/hooks/install.sh
  tools/travis/build_tgui.sh
  tools/travis/install_build_tools.sh
Labels: Github, Tools, UI

#10918 Add dwarves as a round-start race
  config/game_options.txt
Labels: Config Update

#10930 Put the meteor timer to 3-5 minutes
  code/modules/events/meteor_wave.dm
Labels: Tweak

#10972 Removes bone armor and dagger from crafting menu
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Removal, Tweak

#10936 Cyborging someone will now be able to force-remove gang lead status, much like how it can force-deantag headrevs and bloodsuckers
  code/modules/mob/living/silicon/login.dm
Labels: Balance/Rebalance

#10277 ENDS THE PLUSHIE DRAMA
  code/controllers/configuration/entries/plushies.dm
  code/game/objects/items/dehy_carp.dm
  code/game/objects/items/plushes.dm
  config/config.txt
  config/plushies/defines.txt
  config/plushies/plushie_config.txt
  config/plushies/sprites.dmi
  icons/obj/plushes.dmi
  modular_citadel/code/modules/custom_loadout/custom_items.dm
  tgstation.dme
Labels: Config Update, Refactor, Sprites

#10937 Updates the debug outfit
  code/__HELPERS/unsorted.dm
  code/datums/components/uplink.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/debug_items.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/projectiles/guns/magic/wand.dm
  code/modules/research/stock_parts.dm
  code/modules/uplink/uplink_devices.dm
  icons/obj/device.dmi
  tgstation.dme
Labels: Administration, Sprites

#10981 Nerfing Stimulants
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#10984 Makes heads of staff no longer come to work as a gang leader
  code/game/gamemodes/gangs/gangs.dm
Labels: Balance/Rebalance

#10926 Buffs the Pirate Ship to be bomb resistant
  _maps/shuttles/pirate_default.dmm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/objects/effects/spawners/structure.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/wall/mineral_walls.dm
  code/game/turfs/simulated/wall/reinf_walls.dm
  code/modules/events/pirates.dm
Labels: Feature, Map Edit, Tweak

#10976 fixing another issue with the hear component signal.
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/living/say.dm
Labels: Fix

#10948 Prevents certain unpurchasable discounts.
  code/modules/uplink/uplink_items.dm
Labels: Fix

#10971 Adds more Alien disco
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/structures/beds_chairs/chair.dm
  icons/obj/abductor.dmi
Labels: Feature, Sprites

#10988 Reverts 10486 (Observe verb in the Ghost tab)
  code/modules/mob/dead/observer/observer.dm
Labels: Revert, Tweak

#10967 Fixes AI unanchoring not properly removing the no teleport trait.
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#11000 makes RCDs not cost a single sheet of glass and metal
  code/modules/research/designs/tool_designs.dm
Labels: Balance/Rebalance

#11001 Pandemic Fixes
  code/__HELPERS/text.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
Labels: Fix

#10982 something about suit_digi.dmi
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/suit_digi.dmi
Labels: Sprites

#10989 CallMaterialName reagent fix
  code/modules/research/rdconsole.dm
Labels: Fix

#10961 Fixes an issue with the nearsighted prescription glasses taking over worn eyewear
  code/datums/traits/negative.dm
Labels: Fix

#10996 Separates gulag and public mining, removes sec vendor from gulag
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01.dmm
Labels: Feature, Map Edit, Removal, Tweak

#11003 Fixes energy lens not being in gun contents
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#10861 Ports /vg/station drink sliding
  code/__DEFINES/maths.dm
  code/__HELPERS/vector.dm
  code/datums/action.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/reagents/reagent_containers.dm
  tgstation.dme
Labels: Feature

#11032 Fixes cryotubes not transferring reagents for minutes at a time (because at tier 4 it takes 80 * 20 = 1600 deciseconds (!!!) to .. transfer regeants??)
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
Labels: Fix

#11007 Mining Shuttle Fix
  _maps/RandomRuins/StationRuins/Box/Engine/engine_singulo.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/engine_tesla.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/modules/mining/mine_items.dm
Labels: Map Edit

#10992 buckshot buff - 60 to 75 on all pellet pointblank
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Balance/Rebalance

#11018 EMPs now function as intended and mute pAIs for 3 minutes, not 60 minutes.
  code/modules/mob/living/silicon/pai/pai_defense.dm
Labels: Fix

#11020 Movement animations for the pupdozer
  modular_citadel/icons/mob/widerobot.dmi
Labels: Good First PR, Sprites

#11043 fixes apc icons
  code/modules/power/apc.dm
Labels: Fix

#10994 Mom said its my time to scribe Nar'Sie (Alternatively: Nar'Sie runes no longer take half the time (or even less) to scribe on runed floor)
  code/modules/antagonists/cult/ritual.dm
Labels: Balance/Rebalance

#11029 Made the fallback if config is incorrect for map voting plurality (default)
  code/controllers/subsystem/ticker.dm
Labels: Tweak

#10987 Something about missing privates sprites and bad code.
  code/__DEFINES/citadel_defines.dm
  code/__HELPERS/_cit_helpers.dm
  code/__HELPERS/global_lists.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/arousal/genitals.dm
  modular_citadel/code/modules/arousal/genitals_sprite_accessories.dm
  modular_citadel/code/modules/arousal/organs/breasts.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/arousal/organs/testicles.dm
  modular_citadel/code/modules/arousal/organs/vagina.dm
  modular_citadel/icons/obj/genitals/breasts.dmi
  modular_citadel/icons/obj/genitals/breasts_onmob.dmi
  modular_citadel/icons/obj/genitals/penis.dmi
  modular_citadel/icons/obj/genitals/penis_onmob.dmi
  modular_citadel/icons/obj/genitals/taur_penis_onmob.dmi
  modular_citadel/icons/obj/genitals/testicles.dmi
  modular_citadel/icons/obj/genitals/vagina.dmi
  modular_citadel/icons/obj/genitals/vagina_onmob.dmi
Labels: Sprites

#11005 Moves the hypospray mode change to CTRL click
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Tweak

#11012 Introduces the Ratvarian mixed drink, the CogChamp!
  code/modules/cargo/bounties/reagent.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#10943 Fixing an oversight with genital/Remove() and cleaning the code a little.
  modular_citadel/code/modules/arousal/arousal.dm
  modular_citadel/code/modules/arousal/genitals.dm
  modular_citadel/code/modules/arousal/organs/penis.dm
Labels: Fix

#11030 Update to markings_notmammals.dmi
  modular_citadel/icons/mob/markings_notmammals.dmi
Labels: Good First PR

#11024 Fixes brig cell timers, alternatively "WHO DECIDED TO USE NUMBER OF SECONDS FROM 2000 INSTEAD OF FROM THE CURRENT DAY"
  code/game/machinery/doors/brigdoors.dm
Labels: Fix

#11026 Makes ninja and wizards no longer spawn with suit sensors
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/under/color.dm
  code/modules/ninja/outfit.dm
Labels: Balance/Rebalance

#10755 small refactor to melee_attack_chain
  code/_onclick/item_attack.dm
  code/game/objects/items/RPD.dm
  code/game/objects/items/teleportation.dm
  code/modules/antagonists/clockcult/clock_items/replica_fabricator.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/mining/equipment/resonator.dm
  code/modules/research/stock_parts.dm
Labels: Refactor

#10955 refactors and changes up gravity gun projectiles a bit
  code/modules/projectiles/ammunition/energy/gravity.dm
  code/modules/projectiles/projectile/special/gravity.dm
Labels: Feature, Refactor

#11027 Captain's Locker De-bloat, plus the Captain's Wardrobe (NOW WITH NO MERGE CONFLICTS)!
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/vending/wardrobes.dm
  icons/obj/vending.dmi
  icons/obj/vending_restock.dmi
Labels: Feature, Map Edit, Sprites

#10969 allows you to wirecutters the manifests off crates without opening them
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Feature

#10973 Station Locked firing pins
  code/modules/projectiles/pins.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#11021 Porting tgs DMAPI and script updates, getrev updates and OoM errors handling.
  code/__DEFINES/tgs.config.dm
  code/__DEFINES/tgs.dm
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/server_maint.dm
  code/controllers/subsystem/ticker.dm
  code/datums/helper_datums/getrev.dm
  code/game/world.dm
  code/modules/error_handler/error_handler.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/core/default_event_handler.dm
  code/modules/tgs/core/tgs_version.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v4/commands.dm
  config/config.txt
  tools/tgs4_scripts/PostCompile.bat
  tools/tgs4_scripts/PostCompile.ps1
Labels: Config Update, Tools

#11038 STOP_PROCESSING now also removes from currentrun
  code/__DEFINES/MC.dm
  code/controllers/subsystem/processing/weather.dm
  code/datums/weather/weather.dm
  tgstation.dme
Labels: Fix, Removal

#11022 ports auto profiler subsystem from tg
  code/__DEFINES/profile.dm
  code/__DEFINES/subsystems.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/profiler.dm
  code/game/world.dm
  code/modules/admin/verbs/debug.dm
  config/config.txt
  tgstation.dme
Labels: Config Update, Feature

#10997 Sprites, Tweaks, and Snacks, QoL
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/structures/crates_lockers/crates/bins.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_egg.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/vending/snack.dm
  icons/obj/drinks.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  icons/obj/janitor.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites, Tweak

#11035 fixes ctf claymores not spawning and buffs them to be armor pierce + less stamina
  code/modules/awaymissions/capture_the_flag.dm
Labels: Fix

#11044 TGUI Next Uplinks
  code/datums/components/uplink.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  tgui-next/packages/tgui/interfaces/Uplink.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Feature, UI

#11079 Makes valentine related antag datums convertable by bloodsuckers
  code/game/gamemodes/bloodsucker/bloodsucker.dm
Labels: Tweak

#11081 Makes the valentines chocolates no longer rule 9 bait
  code/modules/food_and_drinks/food/snacks_other.dm
Labels: Fix

#11056 Bullets no longer do equal blood volume deletion to unmitigated damage; replicates #9682
  code/modules/projectiles/projectile.dm
Labels: Removal
