Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-06, with the labels that each got.

#12232 Makes seed points take into acount more varables so that you can get more points!
  code/controllers/subsystem/research.dm
Labels: Awaiting further discussion/approval

#12478 IGNORE THIS, EMPTY PR
  modular_citadel/README.md
Labels: Feature, Removal, Work In Progress

#12491 Fixing IC printers material containers for real.
  code/datums/components/material_container.dm
Labels: Fix

#12483 Fixes offstation-AI silicon access
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#12493 [s] xenobio golems can no longer be used to exploit eldritch affairs mechanics
  code/datums/mind.dm
Labels: Fix

#12496 Porting "Speeds up /datum/light_source/proc/update_corners() by 16% or so"
  code/__DEFINES/lighting.dm
  code/__HELPERS/game.dm
  code/modules/lighting/lighting_source.dm
Labels: Code Improvement

#12481 Fixing two issues.
  code/game/objects/structures/watercloset.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Fix

#12479 ports tgs regal rats
  code/_globalvars/lists/maintenance_loot.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/mobs.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
  config/game_options.txt
  icons/mob/actions/actions_animal.dmi
  icons/obj/food/food.dmi
  tgstation.dme
Labels: Config Update, Feature, Sprites

#12471 poplocks hijack/glorious death
  code/modules/antagonists/traitor/classes/hijack.dm
  code/modules/antagonists/traitor/classes/martyr.dm
  code/modules/antagonists/traitor/classes/traitor_class.dm
  code/modules/antagonists/traitor/datum_traitor.dm
Labels: Priority: High

#12494 more simplemobs including slimes fit in pet carriers
  code/modules/mob/living/simple_animal/friendly/cockroach.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/mob/living/simple_animal/friendly/sloth.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
Labels: Feature

#12499 Initial OmegaStation Security overhaul.
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Map Edit

#12386 [Ready] Improvised Weapons Update: Part 2
  code/__DEFINES/construction.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/antagonists/bloodsucker/items/bloodsucker_stake.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm
  icons/mob/clothing/back.dmi
  icons/obj/ammo.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/gun_parts.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/tools.dmi
Labels: Needs Review, Sprites

#12507 Clicking on atmospherics objects as a ghost will allow you to scan their air much like with an analyzer.
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/tanks/tanks.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
Labels: Feature

#12489 Disks are now smaller
  code/__DEFINES/storage/volumetrics.dm
Labels: Balance/Rebalance, Salt

#12513 [s] Fixes a major HTML injection vulnerability
  code/datums/elements/flavor_text.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix

#12506 Adds polychrome uniforms to loadout / kinkmate
  code/modules/vending/kinkmate.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Tweak

#12503 Fixing old beserker hardsuits having the wrong helmet type
  code/modules/clothing/spacesuits/miscellaneous.dm
Labels: Fix

#12498 changes the inefficient attack message prefix and threshold.
  code/__DEFINES/combat.dm
  code/_onclick/item_attack.dm
Labels: Tweak

#12514 the abstract idea of shadows can no longer be radioactive
  code/modules/lighting/emissive_blocker.dm
Labels: Fix

#12510 Finally, A use for peas!
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_salad.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_donut.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_seafood.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  icons/obj/food/donut.dmi
  icons/obj/food/food.dmi
  icons/obj/food/soupsalad.dmi
Labels: Feature, Sprites

#12505 Adds more LGBTQIA+ related holidays
  code/__DEFINES/time.dm
  code/modules/holiday/holidays.dm
Labels: Feature, Fix

#12515 Zoombas
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/mob/robots.dmi
Labels: Sprites

#12502 Port - Lets you tape knives to cleanbots. You know, if you really want to. #47590/tgstation/Ryll-Ryll
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
Labels: Feature

#12516 Fixes VV not allowing proper access to datums in associative lists. Upgrades SDQL2 printout for the 3rd? 4th? 5th? time
  code/__DEFINES/is_helpers.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/view_variables/debug_variables.dm
Labels: Feature, Fix

#12523 fix food carts
  code/modules/food_and_drinks/kitchen_machinery/food_cart.dm
Labels: Fix

#12509 slimes can change their body color using alter form
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Feature

#12518 refactors projectile ricochet and fixes a runtime with projectile motion
  code/__DEFINES/_flags/_flags.dm
  code/__DEFINES/combat.dm
  code/__DEFINES/projectiles.dm
  code/_globalvars/bitfields.dm
  code/game/atoms.dm
  code/game/turfs/simulated/wall/mineral_walls.dm
  code/game/turfs/simulated/walls.dm
  code/modules/antagonists/blob/blob/blobs/shield.dm
  code/modules/projectiles/projectile.dm
  tgstation.dme
Labels: Fix, Refactor

#12522 Gets rid of a useless file
  config/plushies/defines.txt
  config/plushies/plushie_config.txt
Labels: Config Update

#12520 Lobotomy can no longer give magic resilience traumas
  code/modules/surgery/advanced/lobotomy.dm
Labels: Balance/Rebalance

#12521 Tackle "crit fail" now only gives a lobotomy class leg paralysis instead of magic/unremovable
  code/datums/brain_damage/severe.dm
  code/datums/components/tackle.dm
Labels: Balance/Rebalance

#12543 [s] Gin fix
  code/modules/research/designs/autobotter_designs.dm
Labels: Fix

#12532 Porting sutures and meshes from /TG/
  _maps/RandomRuins/LavaRuins/lavaland_surface_biodome_winter.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomZLevels/away_mission/wildwest.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/infiltrator_basic.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/holiday/halloween/bartholomew.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Feature, Good First PR, Map Edit

#12535 Updating ID Icons
  code/game/objects/items/cards_ids.dm
  icons/obj/card.dmi
Labels: Feature, Sprites

#12539 a couple little snaxi fixes
  _maps/map_files/Snaxi/Snaxi.dmm
Labels: Fix, Map Edit

#12538 some cog touchups
  _maps/map_files/CogStation/CogStation.dmm
Labels: Map Edit, Tweak

#12531 Takes icebox out back and old yellers it.
  _maps/icebox.json
  _maps/iceboxstation.dm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Below.dmm
  config/maps.txt
Labels: Config Update, Map Edit

#12544 Shuttles from beestation
  code/__DEFINES/shuttles.dm
  code/controllers/configuration/entries/game_options.dm
  code/game/area/areas/shuttles.dm
  code/game/atoms.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/shuttle/custom_shuttle.dm
  code/game/machinery/shuttle/shuttle_engine.dm
  code/game/machinery/shuttle/shuttle_heater.dm
  code/game/machinery/status_display.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/designs/electronics_designs.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/nodes/bluespace_nodes.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/custom_shuttle.dm
  code/modules/shuttle/navigation_computer.dm
  code/modules/shuttle/shuttle.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_actions.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_console.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_eye.dm
  code/modules/shuttle/shuttle_creation/shuttle_creator_overlay.dm
  code/modules/shuttle/shuttle_creation/shuttle_upgrades.dm
  icons/mob/actions/actions_shuttle.dmi
  icons/obj/tools.dmi
  tgstation.dme
Labels: Config Update, Feature, Good First PR, Sprites

#12537 ports tipping medbots from tg
  code/__DEFINES/robots.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  sound/voice/medbot/close.ogg
  sound/voice/medbot/dont_like.ogg
  sound/voice/medbot/forgive.ogg
  sound/voice/medbot/fuck_you.ogg
  sound/voice/medbot/hey_wait.ogg
  sound/voice/medbot/i_require_asst.ogg
  sound/voice/medbot/i_trusted_you.ogg
  sound/voice/medbot/im_different.ogg
  sound/voice/medbot/is_this_the_end.ogg
  sound/voice/medbot/nooo.ogg
  sound/voice/medbot/oh_fuck.ogg
  sound/voice/medbot/pain_is_real.ogg
  sound/voice/medbot/please_dont.ogg
  sound/voice/medbot/please_im_scared.ogg
  sound/voice/medbot/please_put_me_back.ogg
  sound/voice/medbot/reported.ogg
  sound/voice/medbot/shindemashou.ogg
  sound/voice/medbot/thank_you.ogg
  sound/voice/medbot/turn_off.ogg
  sound/voice/medbot/why.ogg
  sound/voice/medbot/youre_good.ogg
Labels: Feature, PRB: Reset, Sound

#12482 More insectoid insects (I accidentally ruined the first version of this, so I'm trying again.)
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
Labels: Feature

#12554 fixes an oversight that bricks atmos under specific conditions.
  code/controllers/subsystem/air.dm
Labels: Fix

#12555 Square Root Circuit fix
  code/modules/integrated_electronics/subtypes/arithmetic.dm
Labels: Fix

#12548 ports several tg events including fugitives
  _maps/shuttles/hunter_bounty.dmm
  _maps/shuttles/hunter_russian.dmm
  _maps/shuttles/hunter_space_cop.dmm
  code/__DEFINES/antagonists.dm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/status_effects.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/poll_ignore.dm
  code/datums/hud.dm
  code/datums/shuttles.dm
  code/datums/status_effects/debuffs.dm
  code/game/area/areas/shuttles.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/structures/fugitive_role_spawners.dm
  code/game/objects/structures/traps.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/fugitive/fugitive.dm
  code/modules/antagonists/fugitive/fugitive_outfits.dm
  code/modules/antagonists/fugitive/fugitive_ship.dm
  code/modules/antagonists/fugitive/hunter.dm
  code/modules/cargo/packs/misc.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/head/beanie.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/hailer.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/events/brain_trauma.dm
  code/modules/events/fake_virus.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/events/stray_cargo.dm
  code/modules/events/wisdomcow.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/contraband.dmi
  icons/obj/device.dmi
  icons/obj/machines/research.dmi
  icons/obj/objects.dmi
  strings/wisdoms.txt
  tgstation.dme
Labels: Feature, Map Edit, Sprites

#12560 Runtime Fixes
  code/modules/research/techweb/nodes/bluespace_nodes.dm
Labels: Fix

#12553 fixes dd.log
  code/game/world.dm
Labels: MANUALLY CHECK TRAVIS - IGNORE BUILD STATUS, Priority: High

#12563 fixes master (shuttles not loading)
  code/game/atoms.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/shuttle/shuttle_engine.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/research/designs/comp_board_designs/comp_board_designs_sec.dm
  code/modules/shuttle/shuttle.dm
  code/modules/shuttle/shuttle_creation/shuttle_upgrades.dm
Labels: Priority: High

#12487 Adds ||italics|| __underline__ ++bold++ support because why the fuck not
  code/datums/chatmessage.dm
  code/game/say.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/say.dm
  code/modules/mob/say_vr.dm
Labels: Feature

#12564 fixes sutures and mesh being invisible hey speedmerge this
  icons/obj/stack_objects.dmi
Labels: Priority: High, Sprites

#12542 Removes lewd events from the vent clog event
  code/modules/events/vent_clog.dm
Labels: Removal

#12566 Fixing some runtimes issues and warnings bout rnd.
  code/modules/research/designs/comp_board_designs/comp_board_designs_all_misc.dm
  code/modules/research/designs/electronics_designs.dm
  code/modules/research/designs/machine_desings/machine_designs_all_misc.dm
  icons/obj/module.dmi
  icons/turf/shuttle.dmi
Labels: Sprites

#12558 Drastically buffs punch hit chance
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance, MANUALLY CHECK TRAVIS - IGNORE BUILD STATUS

#12556 Ports the reworked snowcabin and beach away missions
  _maps/RandomZLevels/away_mission/Cabin.dmm
  _maps/RandomZLevels/away_mission/SnowCabin.dmm
  _maps/RandomZLevels/away_mission/TheBeach.dmm
  _maps/RandomZLevels/away_mission/moonoutpost19.dmm
  _maps/RandomZLevels/away_mission/undergroundoutpost45.dmm
  code/game/turfs/closed.dm
  code/modules/antagonists/abductor/ice_abductor.dm
  code/modules/awaymissions/mission_code/Cabin.dm
  code/modules/vehicles/atv.dm
  config/awaymissionconfig.txt
  icons/effects/freeze.dmi
  tgstation.dme
Labels: Config Update, MANUALLY CHECK TRAVIS - IGNORE BUILD STATUS, Map Edit, Sprites

#12488 Porting Cargo small-order support, cargo goodies packs, beating vendors for loot/squish.
  code/__DEFINES/cargo.dm
  code/datums/components/omen.dm
  code/datums/elements/embed.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/modules/cargo/console.dm
  code/modules/cargo/coupon.dm
  code/modules/cargo/order.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/cargo/packs/goodies.dm
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/medical.dm
  code/modules/cargo/packs/misc.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/damage_procs.dm
  code/modules/power/power.dm
  code/modules/shuttle/supply.dm
  code/modules/vending/_vending.dm
  code/modules/vending/medical_wall.dm
  icons/obj/closet.dmi
  tgstation.dme
  tgui-next/packages/tgui/interfaces/Cargo.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Feature, Sprites, Tweak, UI

#12561 Ports IV bags from TG
  code/game/machinery/iv_drip.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/reagents/reagent_containers/chem_pack.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/nodes/biotech_nodes.dm
  icons/obj/bloodpack.dmi
  icons/obj/reagentfillings.dmi
  tgstation.dme
Labels: Feature, Sprites

#12583 fixes one of the icon states for the diagnostic hud eyepatch
  icons/mob/clothing/eyes.dmi
Labels: Fix, Sprites

#12579 port tg#51713 (no more infinite singulo lattices on da ice)
  code/game/turfs/simulated/floor.dm
Labels: Fix

#12572 Disables the stray syndicate crate event
  code/modules/events/stray_cargo.dm
Labels: Removal

#12577 removes snore spam
  code/datums/status_effects/debuffs.dm
Labels: Removal

#12565 two small fixes
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Fix

#12574 Buying a 'random uplink item' can no longer force objective / class changes
  code/modules/uplink/uplink_items/uplink_bundles.dm
Labels: Balance/Rebalance

#12568 fix analyze function on chem master
  code/modules/reagents/chemistry/machinery/chem_master.dm
  tgui-next/packages/tgui/interfaces/Bepis.js
  tgui-next/packages/tgui/interfaces/Canvas.js
  tgui-next/packages/tgui/interfaces/ChemMaster.js
  tgui-next/packages/tgui/interfaces/GravityGenerator.js
  tgui-next/packages/tgui/interfaces/HypnoChair.js
  tgui-next/packages/tgui/interfaces/LanguageMenu.js
  tgui-next/packages/tgui/interfaces/Launchpad.js
  tgui-next/packages/tgui/interfaces/NaniteRemote.js
  tgui-next/packages/tgui/interfaces/NtosConfiguration.js
  tgui-next/packages/tgui/interfaces/OperatingComputer.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/yarn.lock
Labels: Fix, UI

#12570 Adds Kepi and Orvilike Kepi
  code/modules/clothing/head/misc.dm
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/clothing/trek.dm
Labels: Feature, Sprites

#12571 Adds the medical-spec gygax
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_parts.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/mecha/medical/medigax.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/nodes/mecha_nodes.dm
  icons/mecha/mech_construct.dmi
  icons/mecha/mech_construction.dmi
  icons/mecha/mecha.dmi
  tgstation.dme
Labels: Feature, Sprites

#12580 ghosts now appear at round-end (tg#51572
  code/__HELPERS/mobs.dm
  code/__HELPERS/roundend.dm
Labels: Feature

#12575 Wataur Bottle
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/vending/cola.dm
  icons/obj/drinks.dmi
  icons/obj/reagentfillings.dmi
Labels: Feature, Sprites, Work In Progress

#12582 SMESes should now work with self-charging cells (tg#51240)
  code/modules/power/smes.dm
Labels: Fix

#12584 Kicks away mission loot in the teeth
  _maps/RandomZLevels/away_mission/Academy.dmm
  _maps/RandomZLevels/away_mission/caves.dmm
  _maps/RandomZLevels/away_mission/challenge.dmm
  _maps/RandomZLevels/away_mission/research.dmm
  _maps/RandomZLevels/away_mission/snowdin.dmm
  _maps/RandomZLevels/away_mission/spacebattle.dmm
  _maps/RandomZLevels/away_mission/wildwest.dmm
  code/modules/awaymissions/mission_code/snowdin.dm
  code/modules/awaymissions/mission_code/spacebattle.dm
  config/awaymissionconfig.txt
  tgstation.dme
Labels: Balance/Rebalance, Config Update, Map Edit

#12581 prevents shunted AIs from doomsdaying (tg#51284)
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/power/apc.dm
Labels: Fix

#12597 adds .json to valid log types for log browsing
  code/__HELPERS/files.dm
Labels: Priority: High

#12599 Add proper deletion to mentor SQL queries
  modular_citadel/code/modules/mentor/mentor_memo.dm
Labels: Fix

#12588 organs now decay while dead again
  code/modules/mob/living/carbon/life.dm
Labels: Fix

#12600 Fixing the snore-pocalypse, and another not so critical issue.
  code/__DEFINES/dcs/signals.dm
  code/datums/components/spawner.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/status_effect.dm
  code/game/objects/obj_defense.dm
  code/modules/flufftext/Dreaming.dm
Labels: Fix, Priority: High

#12606 fixes soap not cleaning blood
  code/game/objects/items/clown_items.dm
Labels: Fix

#12592 felinids nya when tabled
  code/game/objects/structures/tables_racks.dm
Labels: Feature

#12610 Lying down now respects the direction you're facing
  code/modules/mob/living/living_mobility.dm
Labels: Tweak

#12627 [S] You can save the whales, you can save the toads
  tgui-next/packages/tgui/components/NumberInput.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Fix, UI

#12619 slimes blood colour is their body colour
  code/game/atoms.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature

#12615 Solving several issues.
  code/datums/looping_sounds/_looping_sound.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/window.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/spiders.dm
  code/modules/integrated_electronics/subtypes/weaponized.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/research/techweb/_techweb.dm
  icons/mob/robots.dmi
Labels: Feature, Fix, Grammar and Formatting, Sprites

#12591 Snow Snaxi update
  _maps/map_files/Snaxi/Snaxi.dmm
Labels: Map Edit, Removal, Tweak

#12607 cog fixes round 2
  _maps/map_files/CogStation/CogStation.dmm
  _maps/shuttles/whiteship_cog.dmm
  code/datums/shuttles.dm
  code/modules/mob/living/simple_animal/friendly/panda.dm
Labels: Fix, Map Edit

#12601 piggyback carrying people is no longer comically slow
  code/__DEFINES/mobs/slowdowns.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#12603 Some edits to pouches, and something that can hold sheets.
  code/game/objects/items/storage/bags.dm
  code/modules/vending/engivend.dm
  code/modules/vending/security.dm
  icons/obj/items_and_weapons.dmi
Labels: Feature, Sprites

#12611 Fuck abuse of mechanics, fermi chem edition.
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Balance/Rebalance

#12637 fixes slime blood colour
  code/game/atoms.dm
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Fix

#12644 simple mob blood is no longer white
  code/game/atoms.dm
Labels: Fix

#12640 fixes independent bindings not registering keyups
  code/modules/keybindings/bindings_client.dm
Labels: Fix, Priority: High

#12626 prevents duplicate chatboxes from typing indicators by inserting 28 macros into the basic macro sets that just trigger a nonsensical verb that does nothing
  code/controllers/subsystem/input.dm
Labels: Fix

#12623 i would appreciate it if outgoing mentorpms didn't sear my eyes out of my head
  modular_citadel/code/modules/mentor/mentorpm.dm
Labels: Tweak

#12595 *squish
  modular_citadel/code/modules/mob/cit_emotes.dm
  sound/voice/slime_squish.ogg
Labels: Sound

#12605 adds line numbers to config errors
  code/controllers/configuration/configuration.dm
Labels: Feature

#12622 big batch of spelling/grammar corrections
  code/datums/components/crafting/glassware/lens_crafting.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/game/gamemodes/objective_items.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/structures/watercloset.dm
  code/game/turfs/simulated/floor/fancy_floor.dm
  code/modules/antagonists/bloodsucker/powers/veil.dm
  code/modules/cargo/bounties/science.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/exports/tools.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/food/snacks_frozen.dm
  code/modules/hydroponics/grown/tea_coffee.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
  strings/tips.txt
Labels: Grammar and Formatting

#12416 TGUI-next Check Skills menu.
  code/__DEFINES/skills/defines.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/cmp.dm
  code/datums/mind.dm
  code/datums/skills/_check_skills.dm
  code/datums/skills/_skill.dm
  code/datums/skills/_skill_holder.dm
  code/datums/skills/_skill_modifier.dm
  code/datums/skills/engineering.dm
  code/datums/skills/medical.dm
  code/datums/skills/modifiers/job.dm
  code/datums/skills/modifiers/mood.dm
  code/datums/skills/modifiers/organs.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/asset_cache/asset_list_items.dm
  tgui-next/packages/tgui/interfaces/SkillPanel.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: UI

#12390 Porting brain trauma updates: Curse of madness, cloning traumas, random brain trauma event.
  code/__DEFINES/misc.dm
  code/__DEFINES/mobs.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/events.dm
  code/datums/brain_damage/magic.dm
  code/datums/brain_damage/severe.dm
  code/datums/mutations/actions.dm
  code/game/gamemodes/clown_ops/bananium_bomb.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/events/_event.dm
  code/modules/events/anomaly.dm
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  code/modules/events/brain_trauma.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/camerafailure.dm
  code/modules/events/carp_migration.dm
  code/modules/events/dust.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/ghost_role.dm
  code/modules/events/heart_attack.dm
  code/modules/events/immovable_rod.dm
  code/modules/events/pirates.dm
  code/modules/events/processor_overload.dm
  code/modules/events/spacevine.dm
  code/modules/events/spider_infestation.dm
  code/modules/events/wizard/madness.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/brain/brain.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/curse.dm
  code/modules/spells/spell_types/mime.dm
  code/modules/spells/spell_types/santa.dm
  code/modules/spells/spell_types/shadow_walk.dm
  code/modules/spells/spell_types/taeclowndo.dm
  code/modules/spells/spell_types/telepathy.dm
  code/modules/spells/spell_types/voice_of_god.dm
  code/modules/spells/spell_types/wizard.dm
  code/modules/vending/_vending.dm
  tgstation.dme
Labels: Config Update

#12645 More and more fixes.
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/materials.dm
  code/datums/status_effects/debuffs.dm
  code/game/atoms.dm
  code/game/mecha/mecha_topic.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/watercloset.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mining/ores_coins.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/say.dm
  icons/obj/module.dmi
  modular_citadel/icons/mob/mutant_bodyparts.dmi
Labels: Fix, Sprites

#12587 Peachening 2 Even with Master Boogaloo
  icons/obj/hydroponics/harvest.dmi
Labels: Sprites

#12598 speech options on char customization, small skeleton changes
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
Labels: Feature

#12629 https://github.com/tgstation/tgstation/pull/51886 by Fikou
  code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tools.dm
  code/modules/research/techweb/nodes/tools_nodes.dm
  code/modules/vending/assist.dm
  code/modules/vending/engivend.dm
  code/modules/vending/youtool.dm
Labels: Feature
