Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2020-05, with the labels that each got.

#12077 Stops organs from turning against owners in cold environments and freezers.
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
  code/modules/surgery/organs/appendix.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/organ_internal.dm
Labels: Fix, Priority: High

#11874 General taur visuals refactor and other things.
  code/__DEFINES/inventory.dm
  code/__DEFINES/layers_planes.dm
  code/__DEFINES/misc.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/pants.dm
  code/modules/clothing/under/shorts.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/alienpeople.dm
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/caps.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/frills.dm
  code/modules/mob/dead/new_player/sprite_accessories/horns.dm
  code/modules/mob/dead/new_player/sprite_accessories/ipc_synths.dm
  code/modules/mob/dead/new_player/sprite_accessories/legs_and_taurs.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/dead/new_player/sprite_accessories/spines.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  icons/mob/clothing/alpha_masks.dmi
  icons/mob/clothing/taur_hooved.dmi
  icons/mob/clothing/uniform.dmi
  modular_citadel/icons/mob/mam_taur.dmi
Labels: Refactor, Removal, Sprites

#12135 fixes sdql2 global proccalls
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Priority: High

#12139 Fixes VSC debugger
  code/game/world.dm
Labels: Priority: High

#12166 Fixes cakehat
  code/modules/clothing/head/misc_special.dm
Labels: Priority: CRITICAL

#11867 alternate buff to stimpak buff pr #11737
  code/modules/uplink/uplink_items/uplink_devices.dm
Labels: Balance/Rebalance

#11873 fixes dummies having some default features on changing them to the same species
  code/modules/mob/living/carbon/human/dummy.dm
Labels: Fix

#11955 shotgun shell clips
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/ammo.dmi
Labels: Awaiting further discussion/approval

#12161 Fixes the maploader
  code/modules/mapping/reader.dm
  code/modules/procedural_mapping/mapGenerators/repair.dm
Labels: Test Merge Candidate

#12193 fixes xenomorphs not being in combat mode
  code/__DEFINES/combat.dm
  code/modules/mob/living/living_combat.dm
  code/modules/mob/living/living_sprint.dm
Labels: FUCK

#12183 [s]All EMP pulses now log to file
  code/game/objects/empulse.dm
Labels: Priority: High

#11975 Cargo Rework - MK *why did I ever lison to people that were just powergamers?*
  code/modules/cargo/exports.dm
  code/modules/cargo/exports/gear.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/cargo/exports/organs_robotics.dm
  code/modules/cargo/exports/tools.dm
Labels: Awaiting further discussion/approval

#12211 Finally, peas.
  code/modules/hydroponics/grown/peas.dm
  code/modules/vending/megaseed.dm
  icons/obj/hydroponics/growing_vegetables.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
  tgstation.dme
Labels: Good First PR

#12147 Some fixes, some addtions some harm - Ice box changes
  _maps/RandomRuins/IceRuins/icemoon_surface_engioutpost.dmm
  _maps/RandomRuins/IceRuins/icemoon_underground_abandoned_village.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
Labels: Merge Conflict

#12264 [s] cryogenics logging
  code/__DEFINES/logging.dm
  code/game/machinery/cryopod.dm
  code/modules/admin/admin_investigate.dm
Labels: Priority: High

#12316 fixed coordinate converters in Integrated Electronics converters.dm
  code/modules/integrated_electronics/subtypes/converters.dm
Labels: Good First PR

#12333 Removing that one keg.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/shuttles/emergency_gorilla.dmm
  code/modules/reagents/reagent_dispenser.dm
Labels: FUCK

#12370 MouseDrop_T
  code/modules/mapping/mapping_helpers/network_builder/_network_builder.dm
Labels: Priority: High

#12197 A little airlock electronics tgui Fix, courtesy of YakumoChen
  tgui-next/packages/tgui/interfaces/AirlockElectronics.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Merge Conflict

#12226 Improvised Weapons Update: Part 1
  code/__DEFINES/construction.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/tools/saw.dm
  code/modules/holiday/halloween/bartholomew.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tools.dm
  icons/obj/ammo.dmi
  icons/obj/guns/gun_parts.dmi
  icons/obj/guns/projectile.dmi
  tgstation.dme
Labels: Blocked

#12145 Telecomms TGUI
  code/game/machinery/requests_console.dm
  code/game/machinery/telecomms/computers/logbrowser.dm
  code/game/machinery/telecomms/computers/message.dm
  code/game/machinery/telecomms/computers/telemonitor.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/machines/bus.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/machinery/telecomms/machines/server.dm
  code/game/machinery/telecomms/telecomunications.dm
  tgui-next/packages/tgui/interfaces/TelecommsInteraction.js
  tgui-next/packages/tgui/interfaces/TelecommsLogBrowser.js
  tgui-next/packages/tgui/interfaces/TelecommsMonitor.js
  tgui-next/packages/tgui/interfaces/TelecommsPDALog.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Merge Conflict
