Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-03, with the labels that each got.

#14333 departmental-ish turtlenecks
  code/modules/clothing/under/suits.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Sprites

#14334 Cannot modify null.real_name
  code/modules/mob/transform_procs.dm
Labels: Fix

#14331 Fixes gearpainter del operation
  code/game/machinery/colormate.dm
Labels: Fix

#14327 fixes pacifist zombies
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
Labels: Fix

#14322 Adds a pAI policy config
  code/__DEFINES/configuration.dm
  code/game/objects/items/devices/paicard.dm
  config/policy.txt
Labels: Config Update

#14320 Removes auto-matchmaking from valentine's event
  code/modules/events/holiday/vday.dm
Labels: Removal

#14307 Adds a new event: supermatter surge
  code/modules/events/supermatter_surge.dm
  tgstation.dme
Labels: Feature

#14295 Removes open-air fusion completely.
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Removal

#14342 Fixes #14341
  code/modules/client/verbs/aooc.dm
Labels: Fix

#14290 Legions pass their type to the mob they infect
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
Labels: Fix

#14324 Changes to ash drake transformation
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/spells/spell_types/shapeshift.dm
Labels: Balance/Rebalance, Feature

#14344 [FIX] More pacifism bug squashing
  code/game/objects/items/flamethrower.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Fix

#14362 [s] Massively reduced max-size minesweeper
  code/game/machinery/computer/arcade/minesweeper.dm
Labels: Tweak

#14356 Removes Superconuctivity from Reinforced Plasma Glass
  code/game/objects/structures/window.dm
Labels: Removal

#14354 Makes ash storm volume quieter
  code/datums/looping_sounds/weather.dm
Labels: Tweak

#14352 exiting a bluespace jar through any means, hardstuns you for 5 seconds
  code/game/objects/items/pet_carrier.dm
Labels: Tweak

#14353 MWS-01 Changes
  code/game/objects/items/storage/secure.dm
  code/modules/projectiles/boxes_magazines/external/rechargable.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  sound/weapons/MWSfire.ogg
Labels: Balance/Rebalance, Feature, Grammar and Formatting, Sound, Tweak

#14357 the one where i haphazardly replace a sprite - replaces cat tail sprite with EikoBiko's
  icons/mob/mutant_bodyparts.dmi
Labels: Sprites

#14359 funny trauma announce
  code/modules/events/brain_trauma.dm
Labels: Feature

#14360 pipe shotgun reskins
  code/modules/projectiles/guns/ballistic/revolver.dm
  icons/obj/guns/projectile.dmi
Labels: Feature, Sprites

#14361 Makes hyper-nob, nitryl easier to make
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Balance/Rebalance

#14351 Uncaps TEG output
  code/modules/power/generator.dm
Labels: Balance/Rebalance

#14358 femur breaker actually breaks legs any%
  code/game/objects/structures/femur_breaker.dm
Labels: Feature

#14375 Allows repeated mode adjust to be >100 total
  code/controllers/configuration/configuration.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
Labels: Tweak

#14379 Fixes being able to go over the defined limit of roundstart prosthetics
  code/modules/client/preferences.dm
Labels: Fix

#14383 Removes one paramedic slot
  code/modules/jobs/job_types/paramedic.dm
Labels: Removal

#14380 Fixes all the augmentation sprites so they actually are properly labelled and segmented
  icons/mob/augmentation/augments.dmi
  icons/mob/augmentation/augments_mining.dmi
  icons/mob/augmentation/augments_security.dmi
  icons/mob/augmentation/cosmetic_prosthetic/bishop.dmi
  icons/mob/augmentation/cosmetic_prosthetic/cybersolutions.dmi
  icons/mob/augmentation/cosmetic_prosthetic/grayson.dmi
  icons/mob/augmentation/cosmetic_prosthetic/hephaestus.dmi
  icons/mob/augmentation/cosmetic_prosthetic/nanotrasen.dmi
  icons/mob/augmentation/cosmetic_prosthetic/talon.dmi
  icons/mob/augmentation/cosmetic_prosthetic/ward.dmi
  icons/mob/augmentation/cosmetic_prosthetic/xion.dmi
Labels: Fix, Sprites

#14371 Material container fixes
  code/datums/components/material_container.dm
  code/datums/components/remote_materials.dm
  code/game/mecha/mech_fabricator.dm
  code/modules/mining/machine_silo.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/machinery/circuit_imprinter.dm
  code/modules/research/rdmachines.dm
  icons/obj/machines/research.dmi
  icons/obj/robotics.dmi
Labels: Fix, Sprites

#14306 Adds a supernova event, with tweaks to allow this
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/processing/weather.dm
  code/controllers/subsystem/sun.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/game/gamemodes/bloodsucker/bloodsucker.dm
  code/modules/antagonists/bloodsucker/bloodsucker_sunlight.dm
  code/modules/events/supernova.dm
  code/modules/power/solar.dm
  code/modules/power/tracker.dm
  tgstation.dme
Labels: Feature, Refactor

#14376 Adds recent-chaos weighting for secret
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/persistence/recent_votes_etc.dm
  code/game/gamemodes/bloodsucker/bloodsucker.dm
  code/game/gamemodes/brother/traitor_bro.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/changeling/traitor_chan.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/clown_ops/clown_ops.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil agent/devil_agent.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/eldritch_cult/eldritch_cult.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/monkey/monkey.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/overthrow/overthrow.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/double_agents.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
  config/game_options.txt
Labels: Config Update, Feature

#14392 Readability/Grammar alteration
  code/game/objects/items/defib.dm
Labels: Grammar and Formatting

#14412 let's not have sentience potions able to sentience the paper wizard :)
  code/modules/mob/living/simple_animal/hostile/bosses/boss.dm
Labels: Balance/Rebalance

#14403 fixes the BRPED desc that has been quirky! for years
  code/modules/research/stock_parts.dm
Labels: Grammar and Formatting

#14423 makes the chaos thing actually work (whoops)
  code/controllers/subsystem/persistence/recent_votes_etc.dm
Labels: Fix

#14410 new hair/sprite fix
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  icons/mob/clothing/mask.dmi
  icons/mob/hair.dmi
Labels: Feature, Fix, Sprites

#14402 limb growers for pubby and delta
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#14310 [READY] robo-limb surgery tiers
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
  code/modules/smithing/smithed_items.dm
  code/modules/surgery/healing.dm
  code/modules/surgery/robot_healing.dm
Labels: Feature

#14419 Fixes cosmetic augments missing their feet
  icons/mob/augmentation/cosmetic_prosthetic/bishop.dmi
  icons/mob/augmentation/cosmetic_prosthetic/cybersolutions.dmi
  icons/mob/augmentation/cosmetic_prosthetic/grayson.dmi
  icons/mob/augmentation/cosmetic_prosthetic/hephaestus.dmi
  icons/mob/augmentation/cosmetic_prosthetic/nanotrasen.dmi
  icons/mob/augmentation/cosmetic_prosthetic/talon.dmi
  icons/mob/augmentation/cosmetic_prosthetic/ward.dmi
  icons/mob/augmentation/cosmetic_prosthetic/xion.dmi
Labels: Fix, Sprites

#14411 adds a cute new plushie
  html/changelog.html
  html/changelogs/.all_changelog.yml
  icons/obj/plushes.dmi
Labels: Feature, Sprites

#14397 Fixes general interactions with telecomms.
  code/game/machinery/telecomms/machine_interactions.dm
Labels: Fix

#14437 Tweaks supernova to not be inconsequential as often
  code/modules/events/supernova.dm
Labels: Balance/Rebalance

#14398 post-hardsync1.5
  code/_globalvars/lists/flavor_misc.dm
  code/game/atoms_movable.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/_computer.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/tanks/tank_types.dm
  code/game/objects/objs.dm
  code/game/objects/structures/artstuff.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/update_icons.dm
  icons/mob/AI.dmi
Labels: Fix, Sprites

#14433 Fixes a spelling mistake.
  code/datums/traits/negative.dm
Labels: Fix

#14421 Removes the illegal tech node from a few common items that are found through space/gateway/lavaland exploration.
  code/modules/uplink/uplink_items/uplink_clothing.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
  code/modules/uplink/uplink_items/uplink_stealthdevices.dm
Labels: Balance/Rebalance, Removal

#14439 Nerfs hyper-nob/nitryl's point values
  code/__DEFINES/reactions.dm
  code/modules/cargo/exports/large_objects.dm
Labels: Balance/Rebalance

#14438 Adds Shrine Maiden outfit for donator
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#14141 Clockwork cult rite additions and other edits
  _maps/map_files/generic/City_of_Cogs.dmm
  code/__DEFINES/is_helpers.dm
  code/_onclick/hud/clockwork_marauder.dm
  code/datums/skills/modifiers/job.dm
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
  code/modules/antagonists/clockcult/clock_helpers/clock_rites.dm
  code/modules/antagonists/clockcult/clock_helpers/fabrication_helpers.dm
  code/modules/antagonists/clockcult/clock_items/clock_augments.dm
  code/modules/antagonists/clockcult/clock_mobs/_eminence.dm
  code/modules/antagonists/clockcult/clock_mobs/clockwork_guardian.dm
  code/modules/antagonists/clockcult/clock_mobs/clockwork_marauder.dm
  code/modules/antagonists/clockcult/clock_scripture.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_applications.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_judgement.dm
  code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
  code/modules/antagonists/clockcult/clock_structures/ratvar_the_clockwork_justicar.dm
  code/modules/antagonists/clockcult/clock_structures/reflector.dm
  code/modules/antagonists/clockcult/clockcult.dm
  code/modules/antagonists/cult/cult_comms.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/living_defense.dm
  code/modules/power/singularity/narsie.dm
  icons/mob/actions/actions_clockcult.dmi
  icons/mob/clockwork_mobs.dmi
  icons/mob/inhands/antag/clockwork_righthand.dmi
  sound/magic/clockwork/ratvar_announce.ogg
  sound/magic/clockwork/ratvar_announce1.ogg
  sound/magic/clockwork/ratvar_announce2.ogg
  sound/magic/clockwork/ratvarfire.ogg
  sound/weapons/neovgre_laser.ogg
  tgstation.dme
Labels: Feature, Fix, Map Edit, Sound, Sprites

#14347 the speech panel pr
  code/_globalvars/lists/flavor_misc.dm
  code/datums/traits/good.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/language/arachnid.dm
  code/modules/language/draconic.dm
  code/modules/language/dwarven.dm
  code/modules/language/language.dm
  code/modules/language/monkey.dm
  code/modules/language/mushroom.dm
  code/modules/language/slime.dm
  code/modules/language/sylvan.dm
  code/modules/language/voltaic.dm
Labels: Feature

#14406 a PR about empty hypospray kits, vial printing, along with a thing about quantum electromag
  code/game/objects/items/storage/firstaid.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/_techweb_node.dm
  code/modules/research/techweb/nodes/biotech_nodes.dm
  code/modules/research/techweb/nodes/bluespace_nodes.dm
  code/modules/research/techweb/nodes/misc_nodes.dm
Labels: Feature

#14448 Literally just adds targets to give because i forgot to do that
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#14456 Added a "no antags please" pref
  code/__DEFINES/role_preferences.dm
  code/game/gamemodes/game_mode.dm
  code/modules/client/preferences.dm
Labels: Feature

#14442 Adds the skirt variant of the "Tactitool Turtleneck" to the loadout
  code/modules/clothing/under/syndicate.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature

#14444 Locks Bluespace Jars to be admin-only
  code/game/objects/items/pet_carrier.dm
  code/modules/events/travelling_trader.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/techweb/nodes/bluespace_nodes.dm
Labels: Removal

#14462 adds a missing icon state for bluespace beaker filling
  icons/obj/reagentfillings.dmi
Labels: Fix, Sprites

#14470 no more bluespace bodybag of shotgun shells in pocket
  code/game/objects/structures/crates_lockers/closets.dm
Labels: In Game Exploit

#14471 fixes being able to reach into closed bodybags (couldn't webedit 2 files in one PR without being not lazy)
  code/game/objects/items/bodybag.dm
Labels: In Game Exploit

#14400 Map addition & cleanups
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_envy.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_sloth.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_survivalpod.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/advancedlab.dmm
  _maps/RandomRuins/SpaceRuins/bigape.dmm
  _maps/RandomRuins/SpaceRuins/bigderelict1.dmm
  _maps/RandomRuins/SpaceRuins/cloning_facility.dmm
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/derelict6.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomRuins/SpaceRuins/shuttlerelic.dmm
  _maps/RandomRuins/SpaceRuins/skelter.dmm
  _maps/RandomRuins/SpaceRuins/spacediner.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomRuins/SpaceRuins/whiteshipdock.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/budget.dmm
  _maps/RandomRuins/StationRuins/Box/Engine/empty.dmm
  _maps/RandomZLevels/VR/snowdin_VR.dmm
  _maps/RandomZLevels/VR/syndicate_trainer.dmm
  _maps/RandomZLevels/away_mission/Academy.dmm
  _maps/RandomZLevels/away_mission/caves.dmm
  _maps/RandomZLevels/away_mission/challenge.dmm
  _maps/RandomZLevels/away_mission/moonoutpost19.dmm
  _maps/RandomZLevels/away_mission/research.dmm
  _maps/RandomZLevels/away_mission/snowdin.dmm
  _maps/RandomZLevels/away_mission/undergroundoutpost45.dmm
  _maps/RandomZLevels/away_mission/wildwest.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/LambdaStation/dorms.dmm
  _maps/map_files/Mafia/mafia_lavaland.dmm
  _maps/map_files/Mafia/mafia_reebe.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/debug/multiz.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/SpaceDock.dmm
  _maps/shuttles/arrival_kilo.dmm
  _maps/shuttles/emergency_birdboat.dmm
  _maps/shuttles/emergency_delta.dmm
  _maps/shuttles/escape_pod_default.dmm
  _maps/shuttles/labour_cog.dmm
  _maps/shuttles/mining_kilo.dmm
Labels: Feature, Map Edit

#14465 Fixes post absorb revive
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/revive.dm
Labels: Fix

#14457 Fixes the bug that allows anybody(other than heads) to auto-call holopads and adds secure holopads.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/machinery/hologram.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Fix, Map Edit

#14458 Buffs the Warden's Particle defender to something that isn't pure dumpster trash
  modular_citadel/code/modules/projectiles/guns/pumpenergy.dm
Labels: Balance/Rebalance

#14461 removes pacifism from ghost cafe
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Removal

#14464 Enables the in character filter for server configuration
  code/__DEFINES/say.dm
  code/controllers/configuration/configuration.dm
  code/modules/mob/living/say.dm
Labels: Administration, Config Update

#14436 Buffed supermatter surge to make it up to 50x as strong as before.
  code/modules/events/supermatter_surge.dm
Labels: Balance/Rebalance

#14469 fixes puddles breaking
  code/modules/mob/living/carbon/human/innate_abilities/blobform.dm
Labels: Fix

#14468 move documentation domain to cit
  .github/workflows/generate_documentation.yml
Labels: Github

#14323 Hierophant staff no longer deals 30 damage
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Balance/Rebalance

#14489 Fixes NIRM
  code/game/objects/structures/crates_lockers/crates/secure.dm
  code/modules/cargo/order.dm
  code/modules/modular_computers/file_system/programs/budgetordering.dm
  code/modules/shuttle/supply.dm
Labels: Fix

#14447 Fixes laptop and tweaks stacks
  code/controllers/subsystem/ticker.dm
  code/datums/shuttles.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/tanks/jetpack.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/cargo/supplypod.dm
  code/modules/modular_computers/computers/item/laptop.dm
  code/modules/modular_computers/file_system/programs/jobmanagement.dm
Labels: Fix

#14491 noguns now takes precedence over trigger guard
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: Fix

#14475 Black Market: The return
  code/__DEFINES/blackmarket.dm
  code/controllers/subsystem/blackmarket.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/modules/cargo/blackmarket/blackmarket_item.dm
  code/modules/cargo/blackmarket/blackmarket_items/clothing.dm
  code/modules/cargo/blackmarket/blackmarket_items/consumables.dm
  code/modules/cargo/blackmarket/blackmarket_items/misc.dm
  code/modules/cargo/blackmarket/blackmarket_items/tools.dm
  code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
  code/modules/cargo/blackmarket/blackmarket_market.dm
  code/modules/cargo/blackmarket/blackmarket_telepad.dm
  code/modules/cargo/blackmarket/blackmarket_uplink.dm
  code/modules/cargo/packs/misc.dm
  code/modules/reagents/reagent_containers/bottle.dm
  icons/obj/blackmarket.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/BlackMarketUplink.js
Labels: Feature, Fix, Sprites, UI

#14473 Bark Box Remastered Edition
  _maps/RandomRuins/SpaceRuins/advancedlab.dmm
  code/game/objects/items/balls.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/fluff.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/cargo/packs/vending.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/vending/barkbox.dm
  icons/mob/clothing/neck.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/head_fluff.dmi
  icons/mob/inhands/fluff_lefthand.dmi
  icons/mob/inhands/fluff_righthand.dmi
  icons/mob/mouthfluff.dmi
  icons/obj/barkbox_fluff.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  icons/obj/vending.dmi
  icons/obj/vending_restock.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/icons/mob/inhands/balls_left.dmi
  modular_citadel/icons/mob/inhands/balls_right.dmi
  modular_citadel/icons/mob/mouthball.dmi
  modular_citadel/icons/obj/balls.dmi
  tgstation.dme
Labels: Balance/Rebalance, Feature, Grammar and Formatting, Map Edit, Removal, Sprites

#14484 biodegrade works on legcuffs
  code/modules/antagonists/changeling/powers/biodegrade.dm
Labels: Feature

#14481 Nightmares' light eater can now destroy messes that emit light
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
Labels: Fix

#14430 Adjusts Thermals in Genetics; Moves X-ray implant to illegal tech.
  code/datums/mutations/body.dm
  code/datums/mutations/combined.dm
  code/datums/mutations/sight.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
  code/modules/research/techweb/nodes/syndicate_nodes.dm
Labels: Balance/Rebalance

#14498 medsuture/medmesh recipe buff
  code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Balance/Rebalance

#14472 makes the global antag disable pref more clear. forces savefile update to default all players to having the **disable** *disabled* (i love double negatives).
  code/__DEFINES/role_preferences.dm
  code/game/gamemodes/game_mode.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Priority: CRITICAL

#14483 makes strained muscles slightly less absurd by adding a proper chemical slowdown
  code/modules/antagonists/changeling/powers/strained_muscles.dm
Labels: Balance/Rebalance

#14499 Time to stuff the fix-feature bot back into its locker
  tools/WebhookProcessor/github_webhook_processor.php
Labels: Tools

#14497 .38 lever-action rifles but not actually implemented
  code/modules/cargo/packs/service.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/projectile.dmi
Labels: Feature, Sprites

#14507 Added "Diamond Ingots" for Blacksmithing
  code/datums/materials/basemats.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/smithing/smithed_items.dm
Labels: Balance/Rebalance

#14505 the loadout now recognises collars as polychromic items
  modular_citadel/code/modules/client/loadout/neck.dm
Labels: Fix

#14480 Adds suit sensor damage, clothing damage changes
  code/__DEFINES/_flags/obj_flags.dm
  code/__DEFINES/misc.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/jobs/Plasmaman/civilian_service.dm
  code/modules/clothing/under/jobs/Plasmaman/security.dm
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  strings/tips.txt
Labels: Balance/Rebalance, Fix

#14517 slimes can be delimbed
  code/modules/surgery/bodyparts/_bodyparts.dm
Labels: Fix

#14518 Shields: Changes, additional flags, bug fixes, sprites
  code/__DEFINES/_flags/shields.dm
  code/_globalvars/bitfields.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/shields.dm
  code/modules/antagonists/clockcult/clock_items/clock_weapons/ratvarian_shield.dm
  code/modules/assembly/flash.dm
  code/modules/cargo/bounties/security.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/research/designs/weapon_designs.dm
  icons/mob/inhands/equipment/shields_lefthand.dmi
  icons/mob/inhands/equipment/shields_righthand.dmi
  icons/obj/shields.dmi
Labels: Feature, Fix, Sprites

#14515 Lets try again, Plasma Ingots (Fucked up the first time)
  code/datums/materials/basemats.dm
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: Balance/Rebalance

#14513 Makes threat a subsystem instead of dynamic-attached
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/roundend.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/activity.dm
  code/controllers/subsystem/persistence/recent_votes_etc.dm
  code/datums/explosion.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_storytellers.dm
  code/game/machinery/cryopod.dm
  code/modules/mob/living/death.dm
  code/modules/spells/spell_types/lichdom.dm
  tgstation.dme
Labels: Feature

#14512 Gives the Blackmarket Uplink a description
  code/modules/cargo/blackmarket/blackmarket_uplink.dm
Labels: Feature

#14511 Removes Ichor Crates from chest rolls
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Balance/Rebalance, Removal

#14509 Adjusts blackmarket uplink
  code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
Labels: Balance/Rebalance

#14506 fixes character previews but does it using defines (thanks zero)
  code/__DEFINES/loadout.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
Labels: Fix

#14504 i hate kitsune players so here i am porting triple kitsune tails from VORE fuck you
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  modular_citadel/icons/mob/mam_tails.dmi
Labels: Feature

#14501 Adds small walk hud icons
  code/_onclick/hud/screen_objects.dm
  modular_citadel/icons/ui/screen_clockwork.dmi
  modular_citadel/icons/ui/screen_midnight.dmi
  modular_citadel/icons/ui/screen_operative.dmi
  modular_citadel/icons/ui/screen_plasmafire.dmi
  modular_citadel/icons/ui/screen_slimecore.dmi
Labels: Sprites

#14434 Adds radial skin menu to joy mask, pensive, angry, flushed
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/mask_muzzled.dmi
  icons/obj/clothing/masks.dmi
Labels: Feature, Sprites

#14486 patches out a radioactive microlaser tech, makes radioactive microlasers not knock out rad-immune creatures
  code/game/objects/items/devices/traitordevices.dm
Labels: Balance/Rebalance, Fix

#14522 calling upon the Rusted Hills no longer pokes at bluespace
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/knowledge/flesh_lore.dm
Labels: Fix

#14274 lets ghost cafe residents disguise themselves as any mob or object
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Feature

#14440 Made slaughter demon have higher weight if there's more blood
  code/modules/antagonists/slaughter/slaughterevent.dm
Labels: Feature

#14519 Black Market - Some tweaks, additions and comments
  code/modules/cargo/blackmarket/blackmarket_item.dm
  code/modules/cargo/blackmarket/blackmarket_items/clothing.dm
  code/modules/cargo/blackmarket/blackmarket_items/consumables.dm
  code/modules/cargo/blackmarket/blackmarket_items/misc.dm
  code/modules/cargo/blackmarket/blackmarket_items/tools.dm
  code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
Labels: Feature

#14533 fixes automatic hydroponics system design spitting out the machine rather than board
  code/modules/research/designs/machine_desings/machine_designs_service.dm
Labels: Fix

#14528 Fixed being unable to fix suit sensors if damaged at all unless destroyed completely
  code/modules/clothing/under/_under.dm
Labels: Fix

#14431 Ports Ancient bundle from TG
  code/game/objects/items/storage/uplink_kits.dm
Labels: Feature
