Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-12, with the labels that each got.

#15335 Synth / IPC kinda-buffs - Chemwarfare Edition
  code/__DEFINES/reagents.dm
  code/__HELPERS/reagents.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/impure_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  modular_citadel/code/modules/reagents/objects/items.dm
  tgui/packages/tgui/interfaces/ChemMaster.js
Labels: Fix, Balance/Rebalance, UI

#15403 Pubby Holopad
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#15407 Fixes fireman carry dropping the carried target if passing over a prone individual
  code/__DEFINES/traits.dm
  code/datums/components/riding.dm
  code/modules/mob/living/living_movement.dm
Labels: Fix

#15406 Box Perma Fixes
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#15400 LaTeX-in-paper
  tgui/packages/tgui/fonts/KaTeX/KaTeX_AMS-Regular.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Caligraphic-Bold.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Caligraphic-Regular.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Fraktur-Bold.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Fraktur-Regular.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Main-Bold.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Main-BoldItalic.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Main-Italic.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Main-Regular.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Math-BoldItalic.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Math-Italic.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_SansSerif-Bold.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Script-Regular.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Size1-Regular.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Size2-Regular.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Size3-Regular.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Size4-Regular.woff2
  tgui/packages/tgui/fonts/KaTeX/KaTeX_Typewriter-Regular.woff2
  tgui/packages/tgui/interfaces/PaperSheet.js
  tgui/packages/tgui/package.json
  tgui/packages/tgui/styles/atomic/KaTeX.scss
  tgui/packages/tgui/styles/atomic/TexMath.scss
  tgui/packages/tgui/styles/main.scss
  tgui/yarn.lock
Labels: Feature, UI

#15417 Fixes Linters
  code/game/objects/items/stunbaton.dm
  code/modules/holiday/halloween/jacqueen.dm
  code/modules/research/xenobiology/crossbreeding/_misc.dm
  strings/flavor_objectives/traitor/assistant.txt
  strings/flavor_objectives/traitor/engineering.txt
  strings/flavor_objectives/traitor/medical.txt
Labels: Fix, Priority: High

#15405 Fix a few issues related to ball map weather
  _maps/festivestation.json
  _maps/spookystation.json
  code/__DEFINES/maps.dm
  code/datums/weather/weather_types/ice_storm.dm
  modular_citadel/code/modules/eventmaps/Spookystation/JTGSZwork.dm
Labels: Fix, Map Edit

#15410 Itty Bitty Pubby Fixie TAKE TWO
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#15338 Adds Clock Cult to the midround pool.
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Feature, Test Merge Candidate, Testmerge Approved

#15344 being fat no longer makes you slower when floating
  code/modules/movespeed/modifiers/mobs.dm
Labels: Fix

#15424 Centralizes dogborg speech even inside something
  code/datums/chatmessage.dm
Labels: Fix

#15422 Removes a redundant variable declaration
  code/modules/surgery/organs/lungs.dm
Labels: Removal

#15416 Hey what if cold blooded people didn't get a permanent too-hot alert if their body is the same temperature as the air around them
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#15415 The pool's safe temperatures are now within a somewhat reasonable range.
  code/modules/pool/pool_controller.dm
Labels: Balance/Rebalance

#15421 Fixes even more linter stuff
  code/game/objects/items/tanks/watertank.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/mining/fulton.dm
  code/modules/paperwork/pen.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Fix

#15426 Fixes science per-minute output
  code/controllers/subsystem/research.dm
  code/modules/research/techweb/_techweb.dm
Labels: Fix

#15429 Returns the grace time for admins to cancel events to 30 seconds
  code/modules/events/_event.dm
Labels: Fix

#15432 Fixes assemblies
  code/game/objects/items.dm
  code/modules/assembly/assembly.dm
  code/modules/assembly/holder.dm
Labels: Fix

#15402 finally change pin removal from crafting to tools
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/projectiles/gun.dm
Labels: Fix

#15433 fixes debug chemical synthesizers
  code/modules/reagents/chemistry/machinery/chem_synthesizer.dm
  tgui/packages/tgui/interfaces/ChemDebugSynthesizer.js
Labels: UI

#15420 Fixes excited group process delay heuristic
  code/controllers/subsystem/air.dm
Labels: Fix

#15401 Ports tgui stripping (finally)
  code/__DEFINES/logging.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/strippable.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/mobs.dm
  code/datums/elements/mob_holder.dm
  code/datums/elements/strippable.dm
  code/game/objects/items.dm
  code/game/objects/structures/displaycase.dm
  code/modules/admin/outfit_editor.dm
  code/modules/antagonists/clockcult/clock_items/clockwork_armor.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/alien/larva/larva.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_stripping.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_stripping.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/mob.dm
  code/modules/vending/_vending.dm
  icons/UI_Icons/inventory/back.png
  icons/UI_Icons/inventory/belt.png
  icons/UI_Icons/inventory/collar.png
  icons/UI_Icons/inventory/ears.png
  icons/UI_Icons/inventory/glasses.png
  icons/UI_Icons/inventory/gloves.png
  icons/UI_Icons/inventory/hand_l.png
  icons/UI_Icons/inventory/hand_r.png
  icons/UI_Icons/inventory/head.png
  icons/UI_Icons/inventory/id.png
  icons/UI_Icons/inventory/mask.png
  icons/UI_Icons/inventory/neck.png
  icons/UI_Icons/inventory/pocket.png
  icons/UI_Icons/inventory/shoes.png
  icons/UI_Icons/inventory/suit.png
  icons/UI_Icons/inventory/suit_storage.png
  icons/UI_Icons/inventory/uniform.png
  tgstation.dme
  tgui/packages/tgfont/icons/air-tank-slash.svg
  tgui/packages/tgui/interfaces/StripMenu.tsx
  tgui/packages/tgui/styles/atomic/centered-image.scss
  tgui/packages/tgui/styles/main.scss
Labels: Sprites, UI, Test Merge Candidate
