Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-01, with the labels that each got.

#13909 Twitch Plays: Clown Car
  code/__DEFINES/dcs/signals.dm
  code/datums/components/orbiter.dm
  code/datums/components/riding.dm
  code/datums/components/twitch_plays.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/vehicles/cars/clowncar.dm
  tgstation.dme
Labels: Feature

#13924 Allows mass sticking money into your id
  code/game/objects/items/credit_holochip.dm
  code/game/objects/items/stacks/cash.dm
  code/modules/mining/ores_coins.dm
Labels: Tweak

#13930 Touchups for sec box
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Tweak

#13859 unlockable loadout items
  code/__DEFINES/loadout.dm
  code/_globalvars/lists/loadout_categories.dm
  code/game/objects/items/mop.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/mining/point_bank.dm
  icons/mob/clothing/neck.dmi
  icons/obj/bedsheets.dmi
  modular_citadel/code/modules/client/loadout/unlockable.dm
  tgstation.dme
Labels: Currently Testmerged, Sprites, Work In Progress

#13950 MetaStation Paramedical + Surgery Revamp
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#13946 [Port] Fixes log collisions
  code/__HELPERS/_logging.dm
  code/modules/mob/mob_helpers.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
Labels: Administration

#13945 Makes IPC cells & power cords printable
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
Labels: Feature

#13943 utility uniform typos and making the capdrobe not suck
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/clothing/under/jobs/rnd.dm
  code/modules/vending/wardrobes.dm
Labels: Fix, Grammar and Formatting, Tweak

#13941 Portable Chem Mixer now added to the Biological Technology tech node.
  code/modules/research/techweb/nodes/biotech_nodes.dm
Labels: Fix

#13940 Paramedic EVA suit now purchasable from Cargo
  code/modules/cargo/packs/medical.dm
Labels: Feature

#13938 anthromorphic synth species
  code/__DEFINES/species.dm
  code/modules/mob/living/carbon/human/species_types/anthromorph.dm
Labels: Feature

#13936 Fixes loadout specific polychromic hoodies not having their hoods polychromable
  code/controllers/subsystem/job.dm
  code/datums/elements/polychromic.dm
Labels: Fix

#13934 Ports bluespace navigation gigabeacon from TG
  code/modules/research/designs/machine_desings/machine_designs_engi.dm
  code/modules/research/techweb/nodes/bluespace_nodes.dm
  code/modules/shuttle/navigation_computer.dm
  code/modules/shuttle/spaceship_navigation_beacon.dm
  tgstation.dme
Labels: Feature

#13932 Ports xenomorph plasma usage in power description from bee
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/alien/humanoid/caste/praetorian.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
Labels: Tweak

#13947 Chemmaster output buff
  code/modules/reagents/chemistry/machinery/chem_master.dm
  tgui/packages/tgui/interfaces/ChemMaster.js
  tgui/public/tgui.bundle.js
Labels: Tweak, UI

#13951 Max groin cannon size increased before being punished for erecting a massive mayo-blaster to -max roundstart config- inches instead of 20
  code/modules/arousal/organs/penis.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
Labels: Tweak

#13955 Nightmare Lights Damage Buff
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
Labels: Fix, Tweak

#13948 Bokken and Bokken Accessories: Bonkvengeance
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/weaponry.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/smith.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites, Tweak

#13954 Cog and firelocks.
  _maps/map_files/CogStation/CogStation.dmm
  code/game/area/Space_Station_13_areas.dm
Labels: Feature, Fix, Map Edit, Tweak

#13959 Bokken Fixes: You can make them now. Nyoops.
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/weaponry.dm
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/smith.dmi
Labels: Fix, Sprites, Tweak

#13856 Actually made gear harness properly adjustable
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/miscellaneous.dm
Labels: Fix

#13968 Ding for prayers
  code/modules/admin/verbs/pray.dm
  sound/effects/ding.ogg
Labels: Sound, Tweak

#13972 Fixing maint areas in boxstation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Tweak

#13970 Meta Surgery Fixies
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#13961 Fuck it, I'll just fix a whole bunch of stuff on cogstation
  _maps/map_files/CogStation/CogStation.dmm
Labels: Map Edit, Tweak

#13957 [s] logging patch 36735734
  code/modules/paperwork/pen.dm
Labels: Priority: High

#13834 ports the traitor assistant POGBOX that scales damage with tc from /TG/
  code/game/objects/items/storage/toolbox.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
  icons/obj/storage.dmi
Labels: Feature, Sprites

#13978 removes c4 mob gibbing
  code/game/objects/items/grenades/plastic.dm
Labels: Balance/Rebalance, Removal

#13984 fixes removing toner from photocopiers (this is an untested fix but it probably works because it compiled)
  tgui/packages/tgui/interfaces/Photocopier.js
  tgui/public/tgui.bundle.js
Labels: UI

#13981 Porting the ability to wear the caution sign (plus a random metastation fix)
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomZLevels/away_mission/Academy.dmm
  _maps/RandomZLevels/away_mission/SnowCabin.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/LambdaStation/dorms.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/janicart.dm
  code/modules/cargo/packs/service.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Map Edit, Sprites

#13983 Adds some flavor stuff for the xenohybrid species tongue as well as wings. No longer includes language.
  code/_globalvars/lists/flavor_misc.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/species_types/xeno.dm
Labels: Feature

#13980 Makes gas sensors fireproof
  code/game/machinery/computer/atmos_control.dm
Labels: Feature

#13988 [s] we love private orders
  code/modules/cargo/console.dm
Labels: Fix

#13931 Ports disposable sentry gun for station engineers as a traitor item from TG
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/objects/items/devices/traitordevices.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
Labels: Feature

#13997 The garbage collector doesn't waste time anymore
  code/controllers/subsystem/garbage.dm
Labels: Tweak

#14001 Only one chair per tile, thanks metastation 2
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit, Tweak

#13996 Port of: Prevents the morph from become an AI eye
  code/modules/antagonists/morph/morph.dm
Labels: Tweak

#13976 i have done nothing but teleport bread for three days
  code/datums/helper_datums/teleport.dm
  code/modules/food_and_drinks/food/snacks_bread.dm
  code/modules/mob/living/simple_animal/hostile/bread.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/mob/animal.dmi
  icons/obj/food/burgerbread.dmi
  tgstation.dme
Labels: Feature, Sprites

#13967 Small blob tweaks + fix
  code/modules/antagonists/blob/blob/blobs/resource.dm
  code/modules/antagonists/blob/blob/powers.dm
Labels: Balance/Rebalance, Fix

#14005 Stops mob loot from failing to Initialize
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix, Priority: CRITICAL

#14002 removes glitter persistence
  code/game/objects/effects/decals/cleanable/misc.dm
Labels: Removal

#14016 disabling adminhelp noises no longer disables looc
  code/modules/client/verbs/looc.dm
Labels: Fix

#14010 Fixes some missing upgraded cybernetic organs in the exofab and also makes prosthetic limbs printable at them.
  code/modules/research/designs/medical_designs.dm
Labels: Feature, Fix

#14008 Removes double punctuation in the tumor bread description.
  code/modules/food_and_drinks/food/snacks_bread.dm
Labels: Removal

#14007 Fixes heretic special role adding / removal
  code/game/gamemodes/eldritch_cult/eldritch_cult.dm
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
Labels: Fix

#14006 Attempting to complete a borg AI shell without a cell installed no longer causes issues
  code/game/objects/items/robot/robot_parts.dm
Labels: Fix

#13995 (Somewhat) fixes clickdelay when attacking objects.
  code/game/objects/obj_defense.dm
Labels: Fix, Priority: High

#13965 Good Night Disky
  code/datums/elements/bed_tucking.dm
  code/game/objects/items/devices/paicard.dm
  code/game/objects/items/plushes.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  tgstation.dme
Labels: Feature

#14017 fixes stabilized oil extracts making infinite explosions
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Priority: High

#14014 Bokken Fixes 2: Missing sprites and stuff
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/belt.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/obj/smith.dmi
Labels: Fix, Sprites

#13993 Makes cursed heart more tolerable
  code/datums/action.dm
  code/modules/surgery/organs/heart.dm
Labels: Tweak

#13973 completely removes penis/breast enlargement effects due to it being completely unmaintained and to be frank awful
  code/__DEFINES/status_effects.dm
  code/modules/arousal/organs/breasts.dm
  code/modules/arousal/organs/penis.dm
  modular_citadel/code/datums/status_effects/chems.dm
Labels: Removal

#14026 Skidaddle skidoodle, your 12+ inch dick no longer looks like a noodley elephant trunk
  code/modules/arousal/organs/penis.dm
Labels: Fix

#14019 species with NOTRANSSTING cannot have envy's knife used on them
  code/modules/ruins/objects_and_mobs/sin_ruins.dm
Labels: Fix

#14036 You will no longer unbuckle fireman-carried/piggybacked people when touching someone on help or grab intent
  code/game/objects/buckling.dm
Labels: Tweak

#14038 an unatomic PR designed for maximizing maintainer suffering
  _maps/shuttles/emergency_nature.dmm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/mob/living/carbon/human/species_types/arachnid.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/xeno.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/vending/wardrobes.dm
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
Labels: Balance/Rebalance, Feature, Map Edit, Sprites

#14033 Adds Color Mates to every station (except Snaxi)
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/dorms.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
Labels: Feature, Map Edit

#14015 Tweaks some Synth damage stuff
  code/datums/status_effects/buffs.dm
  code/game/turfs/simulated/floor/misc_floor.dm
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
  code/modules/antagonists/clockcult/clock_helpers/slab_abilities.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/silicon/pai/pai_defense.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/surgery/limb_augmentation.dm
Labels: Balance/Rebalance

#14009 Ports a bunch of wings from cit RP and fulpstation [Ready]
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  icons/mob/wings.dmi
Labels: Feature, Fix, Needs Review, Sprites

#14025 More Synth tweaks
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/surgery/emergency_reboot.dm
  code/modules/surgery/remove_embedded_object.dm
  tgstation.dme
Labels: Balance/Rebalance, Feature, Tweak

#14032 two toggled self-buffing spells that have no relation to any anime or video game in particular
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/buffs.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/antagonists/wizard/wizard.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/spells/spell_types/togglebuff.dm
  icons/obj/library.dmi
  icons/obj/magic.dmi
  sound/magic/powerdown.ogg
  sound/magic/powerup.ogg
  tgstation.dme
Labels: Balance/Rebalance, Feature, Sound, Sprites

#14035 Comments out hololocks
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/nodes/misc_nodes.dm
Labels: Tweak

#14034 Fixes some edge cases regarding system corruption
  code/modules/mob/living/carbon/handle_corruption.dm
Labels: Fix

#14021 Fixes combat mode being permanently disabled under specific circumstances
  code/datums/status_effects/status_effect.dm
Labels: Fix

#13975 resprites paramedic softsuit to not violate r*d cr*ss copyright and resprites the paramedic closet
  code/modules/clothing/spacesuits/miscellaneous.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/head_muzzled.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/obj/closet.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#14039 on the precipice of stickiness - sticky tape roundstart tech
  code/modules/research/techweb/nodes/misc_nodes.dm
Labels: Feature

#14062 i don't wanna talk about it
  code/modules/spells/spell_types/togglebuff.dm
Labels: Fix

#14042 adds klonk sound effect for literal horsecock dildo
  code/modules/arousal/toys/dildos.dm
Labels: Feature

#14064 s] nothing to see here move on
  config/respawns.txt
Labels: Config Update, Priority: High

#14060 removes shrink ray again because "wait, whose idea was to readd this?" (turns out it was shoehorned back in by lettern during the tgui port)
  code/modules/antagonists/abductor/equipment/orderable_gear.dm
Labels: Removal

#14057 removes stealthmin orbit block
  code/__HELPERS/unsorted.dm
Labels: Removal

#14054 Returns the Maintenance Shotgun to it's original recipe. Removes the Maintenance Rifle, and associated items.
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/holiday/halloween/bartholomew.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm
Labels: Feature, Removal

#14048 Hey this Tip Of The Round is wrong.
  strings/tips.txt
Labels: Tweak

#14044 Belt slot prayer beads
  code/game/objects/items/holy_weapons.dm
Labels: Good First PR, Tweak

#14040 fixes pda logs
  tgui/packages/tgui/interfaces/TelecommsPDALog.js
  tgui/public/tgui.bundle.js
  tgui/yarn.lock
Labels: Fix, UI

#14061 something something gauze things
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix, Tweak

#14070 Makes Buzz Fuzz go on a diet
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Balance/Rebalance

#14043 licking people washes pie off their face
  code/modules/vore/eating/living.dm
Labels: Feature

#14055 Purges the cock and titty straining when both genitals are growing
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
Labels: Tweak

#14029 Ports TG code for wormhole projector and gravity gun.
  code/modules/projectiles/guns/energy/special.dm
Labels: Tweak

#14030 Replaces majority judgment with usual judgement
  code/__DEFINES/vote.dm
  code/controllers/subsystem/vote.dm
Labels: Tweak

#14037 Nanogel for robotic limbs
  code/game/objects/items/stacks/medical.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/vending/medical.dm
  code/modules/vending/medical_wall.dm
  code/modules/vending/robotics.dm
  icons/obj/stack_objects.dmi
Labels: Feature, Sprites

#13963 Mostly ports tgstation #54644; New roboticist labcoat sprites
  code/modules/clothing/suits/labcoat.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#14091 [s] UM
  code/modules/projectiles/projectile/reusable/foam_dart.dm
Labels: In Game Exploit, Priority: High

#14082 s
  code/modules/awaymissions/mission_code/Academy.dm
Labels: Balance/Rebalance, Feature, Fix, Tweak

#14089 Minor minning station QoL
  _maps/RandomRuins/StationRuins/Lavaland/Mining_Station/Mining_Station_Public_01.dmm
Labels: Map Edit, Tweak

#13610 Makes the atmos subsystem pause correctly
  code/controllers/subsystem/air.dm
Labels: Fix

#14094 Gives /datum/reagent/consumable/ethanol/species_drink a name
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Feature

#14097 i'm not sure why cargo's bird crate has every bird spawn with a headset but let's not have that
  code/modules/mob/living/simple_animal/parrot.dm
Labels: Removal

#14110 Removes oversized genitalia analysis from medical scanners
  code/game/objects/items/devices/scanners.dm
Labels: Removal

#14109 Fixes the space tackling meme
  code/datums/components/tackle.dm
Labels: Fix

#14107 Mining borgs get a point ID again.
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature

#14100 twinsheath additions
  code/game/objects/items/storage/belt.dm
  code/modules/smithing/finished_items.dm
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/smith.dmi
Labels: Sprites, Tweak

#14095 Fixes deleted hypereutatic blade sprites
  icons/mob/inhands/64x64_lefthand.dmi
  icons/mob/inhands/64x64_righthand.dmi
Labels: Sprites

#14092 Adds Timid wo/man costumes
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/mob/dead/new_player/sprite_accessories/socks.dm
  code/modules/vending/autodrobe.dm
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/feet_digi.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/mask_muzzled.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/mob/clothing/underwear.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Grammar and Formatting, Sprites

#14076 pulling cotton (or durathread) while standing on a pile of cotton (or durathread) picks all of them
  code/modules/hydroponics/grown/cotton.dm
Labels: Tweak

#13969 Tweaks blood bag consumption
  code/modules/reagents/reagent_containers/blood_pack.dm
Labels: Fix, Tweak

#14103 [READY]Give hotkey, but citadel
  code/_onclick/hud/alert.dm
  code/_onclick/right_click.dm
  code/modules/keybindings/keybind/carbon.dm
  code/modules/mob/living/carbon/inventory.dm
Labels: Feature, Needs Review

#14130 you can now shove yourself up on any intent
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak

#14126 Port "Humanizing a monkey no longer yeets any buried smuggler's satchels from the tile onto their person."
  code/modules/mob/transform_procs.dm
Labels: Fix

#14123 Port "Let Me Tell You A Story"
  code/modules/mob/living/carbon/alien/alien.dm
Labels: Fix

#14125 Port of "Puts encryption keys in hand when removed"
  code/game/objects/items/devices/radio/headset.dm
Labels: Tweak

#14121 Port of "Makes the microwave cleanable by the damp rag"
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
Labels: Feature

#14129 Porting a cursed name about drinking
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
Labels: Fix

#14128 Port of "Update some oldcode"
  code/__HELPERS/_lists.dm
  code/__HELPERS/names.dm
  code/__HELPERS/type2type.dm
Labels: Fix

#14124 Port of "AI can now look up and down zlevels"
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
Labels: Feature

#13876 Refactors ventcrawling
  code/__DEFINES/dcs/signals.dm
  code/datums/diseases/transformation.dm
  code/datums/elements/ventcrawling.dm
  code/game/objects/structures/plasticflaps.dm
  code/modules/antagonists/abductor/equipment/glands/ventcrawl.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/simple_animal/friendly/bumbles.dm
  code/modules/mob/living/simple_animal/friendly/butterfly.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/cockroach.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
  code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/possum.dm
  code/modules/mob/living/simple_animal/friendly/snake.dm
  code/modules/mob/living/simple_animal/hostile/banana_spider.dm
  code/modules/mob/living/simple_animal/hostile/bread.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
  code/modules/mob/living/simple_animal/hostile/killertomato.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/mob/living/simple_animal/hostile/mushroom.dm
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/frog.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/living/ventcrawling.dm
  code/modules/recycling/disposal/bin.dm
  tgstation.dme
Labels: Refactor

#14135 Fixes the Ventcrawling element not detaching properly
  code/datums/elements/ventcrawling.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
Labels: Fix

#14059 removes headsets and flashes from more legion corpses
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
Labels: Removal

#14105 Heretic sacrifice target logging + a fix
  code/__DEFINES/antagonists.dm
  code/game/gamemodes/objective.dm
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/antagonists/eldritch_cult/eldritch_knowledge.dm
Labels: Administration, Fix, Tweak

#14114 itt: i dont test my code again - free golem ship GPSes start disabled
  _maps/RandomRuins/AnywhereRuins/golem_ship.dmm
  code/datums/components/gps.dm
  code/game/objects/items/devices/gps.dm
Labels: Balance/Rebalance, Map Edit, PRB: Reset

#14116 adminhelps and pms only sanitize text once, stopping ' becoming &39;! or whatever
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Administration

#14117 lets blobs use the 'me' verb
  code/modules/antagonists/blob/blob/overmind.dm
Labels: Feature

#14137 Dropper can no longer drop things at it's location without having them
  code/modules/integrated_electronics/core/integrated_circuit.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: Fix

#14136 Ports a fix for infinite floor tiles from tg caused by a bug that was fixed a long time ago on tg code.
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  sound/effects/whistlereset.ogg
Labels: Fix, Sound

#14134 [READY]Give Improved
  code/_onclick/right_click.dm
  code/game/objects/items.dm
  code/game/objects/items/stunbaton.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Feature, Needs Review

#14133 department budget cards but not in lockers
  code/game/objects/items/cards_ids.dm
  icons/obj/card.dmi
Labels: Sprites, Tweak

#14131 Mass air alarm fixings for (basically) every station
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, PRB: Reset, Tweak

#14127 tgstation#56348 - contractor TC buff
  code/modules/antagonists/traitor/equipment/contractor.dm
Labels: Balance/Rebalance, PRB: Reset

#14111 [READY]Gives the revenant TK
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/controllers/subsystem/throwing.dm
  code/datums/components/storage/storage.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/eightball.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/pneumaticCannon.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/tanks/tanks.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/antagonists/revenant/revenant.dm
  code/modules/assembly/flash.dm
  code/modules/paperwork/paper.dm
Labels: Feature, Needs Review

#14102 [READY] somatoray buff - mutation locks + revolution ray
  code/modules/hydroponics/hydroponics.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special/floral.dm
  code/modules/research/designs/weapon_designs.dm
  icons/obj/guns/energy.dmi
  icons/obj/projectiles.dmi
Labels: Feature, Needs Review, Sprites

#14118 About ratvarian borgs and spells sometimes not working (+ a few other small things)
  code/modules/antagonists/clockcult/clock_helpers/clock_rites.dm
  code/modules/antagonists/clockcult/clock_items/clockwork_slab.dm
Labels: Balance/Rebalance, Fix

#14139 small refactor to pinpointers, allow pinpointers with custom targets
  code/game/objects/items/pinpointer.dm
Labels: Refactor

#14112 ~~hugboxes~~ fixes the bug (that was probably my fault) that makes 1 dev explosions ALWAYS delete brain
  code/datums/explosion.dm
  code/game/atoms.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/death.dm
  code/modules/mob/living/death.dm
Labels: Fix

#14086 officially adds the functionality to insert holdable mobs into colormate
  code/game/machinery/colormate.dm
Labels: Feature

#14142 adds aesthetic sterile masks (and the paper mask) to the loadout panel
  code/modules/clothing/masks/miscellaneous.dm
  modular_citadel/code/modules/client/loadout/mask.dm
Labels: Feature

#14147 fixes miner bedsheet
  code/modules/mining/machine_redemption.dm
  code/modules/mining/point_bank.dm
Labels: Fix

#14146 RP ports featuring accessories, small code fixes, shibari ropes, stockings, and celebrating 2021's animal or whatever
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/under/accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/socks.dm
  code/modules/mob/dead/new_player/sprite_accessories/undershirt.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/kinkmate.dm
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/neck.dmi
  icons/mob/clothing/underwear.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/neck.dmi
  modular_citadel/code/modules/client/loadout/neck.dm
Labels: Feature, Sprites

#14145 ports some hairstyles from rp because god knows we need some good hairs that aren't Short Hair 3 and Wisp
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  icons/mob/hair.dmi
Labels: Sprites

#14067 Box Chapel Redecoration [updated]
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Fix, Map Edit

#14151 Final, final, final cloak PR, now conflict free
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/cloaks.dmi
Labels: PRB: Reset, Sprites, Tweak

#14157 Gee kevin, why does atmos get /two/ air alarms?
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Removal

#14148 gives the advanced extinguisher a sprite that doesn't look like total dogshit even by codersprite standards
  code/game/objects/items/extinguisher.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Sprites

#14150 a zero pr that didn't need a followup pr to fix bugs doesn't exist | adds the multicolor berets to loadout
  code/modules/clothing/under/accessories.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/accessories.dmi
  modular_citadel/code/modules/client/loadout/head.dm
Labels: Sprites

#14156 hair ports part two | now featuring skrell hair
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  icons/mob/hair.dmi
Labels: Feature, Sprites

#14149 adds 'clucks', 'caws' and 'gekkers' to the speech verb list
  code/_globalvars/lists/flavor_misc.dm
Labels: Feature

#14031 Fixes fermichem EMPs being massive.
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Balance/Rebalance

#14165 no more instakill gun circuits (ext_cooldown 1-->4)
  code/modules/integrated_electronics/subtypes/weaponized.dm
Labels: Balance/Rebalance
