Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-08, with the labels that each got.

#14817 [READY] tempgun rebalance (it's not a nerf don't worry)
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/special/temperature.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
  sound/weapons/frost.ogg
Labels: Awaiting further discussion/approval, Balance/Rebalance, Sound, Sprites

#14977 Fixes brainless sprite being an error sprite
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#14979 line ending fuckery
  _maps/RandomRuins/LavaRuins/lavaland_surface_bathhouse.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_engioutpost.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hotsprings.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_library.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_lust.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_mining_site.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_wrath.dmm
Labels: Map Edit

#14982 makes organs decay again
  code/modules/surgery/organs/organ_internal.dm
Labels: Fix

#14975 Fixes certain skirty uniforms not having the FEMALE_UNIFORM_TOP fitted flag
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/miscellaneous.dm
Labels: Fix

#14984 Halves probability on supernova rads
  code/modules/events/supernova.dm
Labels: Balance/Rebalance

#14978 Adds military gas mask for donator
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#14988 Old Gateway animation return
  code/modules/awaymissions/gateway.dm
  icons/obj/machines/gateway.dmi
Labels: Fix, Sprites

#14981 Makes rod of asclepius usable for revival surgery
  code/modules/surgery/advanced/revival.dm
Labels: Balance/Rebalance

#14989 lets felinids, humans and moths have markings
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
Labels: Feature

#14996 Automatically fails pull requests with broken line endings
  tools/ci/check_grep.sh
Labels: Tools

#14961 Makes supermatter properties auxgm-based
  code/__DEFINES/atmospherics.dm
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/auxgm.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Refactor

#14995 Update linux scripts and dependencies for new auxmos version
  dependencies.sh
  tools/build/build.sh
  tools/tgs4_scripts/PreCompile.sh
Labels: Tools

#15001 Fixes circular reference in genitals on Destroy()
  code/modules/arousal/genitals.dm
Labels: Fix

#14992 Changelings now use a radial menu to select DNAs (tg port)
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/humanform.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/antagonists/changeling/powers/transform.dm
  icons/mob/radial.dmi
Labels: Sprites

#15005 Blacklists incapacitated mobs from being sentience event candidates
  code/modules/events/sentience.dm
Labels: Fix

#14991 Polyvitiligo now actually does something instead of making you a crayon eater.
  code/datums/brain_damage/severe.dm
  code/datums/diseases/advance/symptoms/skin.dm
Labels: Fix

#15017 lets you select 4 prosthetic limbs instead of only 2
  code/__DEFINES/loadout.dm
Labels: Feature

#15008 [Ready] Shark Tails, dodododododo
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  modular_citadel/icons/mob/mam_tails.dmi
Labels: Sprites

#15009 Ship happens on OmegaStation.
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Map Edit

#15019 [Ready] Blank Bottles
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/nodes/export_nodes.dm
  code/modules/vending/boozeomat.dm
  icons/obj/drinks.dmi
  icons/obj/reagentfillings.dmi
Labels: Feature, Sprites

#15006 Pubby Additions + Touchups
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit

#15022 Adds some showers to the beach
  _maps/RandomZLevels/away_mission/TheBeach.dmm
Labels: Feature, Map Edit

#15026 undoes a small amount of Trillby™ Spelling™
  code/datums/components/crafting/glassware/lens_crafting.dm
Labels: Grammar and Formatting

#15007 Old Gateway animation return: now includes less icons
  code/modules/awaymissions/gateway.dm
  icons/obj/machines/gateway.dmi
Labels: Sprites

#15031 undoes more Trillby™ Spelling™
  code/datums/components/crafting/glassware/glassware.dm
Labels: Grammar and Formatting

#15023 Brings back the MK ultra gas, remove MK ultra explosion, but makes the gas less horny and prefbreaky
  modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Balance/Rebalance

#15050 fixes the chainsaw sprite
  icons/mob/inhands/weapons/chainsaw_lefthand.dmi
  icons/mob/inhands/weapons/chainsaw_righthand.dmi
Labels: Fix, Sprites

#15048 Fixes updates for rechargers & energy guns, ports "recharge feedback" from TG
  code/game/machinery/recharger.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  icons/obj/stationobjs.dmi
Labels: Feature, Fix, Sprites

#15045 Fixes waddling ruining character size and forcing character scale to 1
  code/datums/components/waddling.dm
Labels: Fix
