Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-09, with the labels that each got.

#15059 fixes losing your additional language upon changing species
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Fix

#15072 Fixes a runtime in ghost update_icon
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#15067 makes the arm/leg markings for synthetic lizards appear as an option again
  code/modules/mob/dead/new_player/sprite_accessories/synthliz.dm
Labels: Fix

#15068 [Fix] Un-Spaces the Sunken Library.
  _maps/RandomRuins/LavaRuins/lavaland_surface_library.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_mining_site.dmm
Labels: Fix, Map Edit

#15049 Fixes Entering an already occupied VR Sleeper
  code/modules/VR/vr_sleeper.dm
Labels: Fix

#15075 Fixes the "unreadied player gamemode votes don't count" not working
  code/controllers/subsystem/vote.dm
Labels: Fix

#15081 FIX Dead Gremlins no longer give AA
  code/modules/mob/living/simple_animal/gremlin/gremlin.dm
Labels: Fix

#15076 you can just about
  strings/tips.txt
Labels: Grammar and Formatting

#15077 woopsies, pubby xenobio jank
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#15080 PORT Adds new outfits for command and centcom staff!
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/obj/clothing/suits.dmi
  tgstation.dme
Labels: Sprites

#15083 FIX Ghosts can no longer highlight your inventory
  code/game/objects/items.dm
Labels: Fix

#15089 Mask of Madness no longer wallhacks
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
Labels: Fix

#15064 tg hammers port uwu
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Sprites

#15069 tgifies the cyborg tools
  icons/obj/items_cyborg.dmi
Labels: Sprites

#15058 the unatomized hypospray/medbay tools/emergency kits resprite
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/clown_ops/clown_ops.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/clothing/outfits/vr.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/station_goals/dna_vault.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/obj/chemical.dmi
  icons/obj/storage.dmi
  icons/obj/surgery.dmi
  icons/obj/syringe.dmi
Labels: Fix, Sprites

#15039 Ports Colorist Quirk and Hair Gradients Preferences
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/traits/neutral.dm
  code/game/objects/items/dyekit.dm
  code/modules/cargo/packs/goodies.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/vending/games.dm
  icons/mob/hair_gradients.dmi
  icons/obj/dyespray.dmi
  tgstation.dme
Labels: Feature, Sprites

#15056 [TESTMERGE] Brings Reebe back to the Clockcult mode
  code/game/gamemodes/clock_cult/clock_cult.dm
Labels: Feature, Test Merge Candidate, Testmerge Approved

#15065 ports tg hazard vest
  icons/mob/clothing/suit.dmi
Labels: Sprites

#15108 ok let's NOT default everyone to having sparkledog hair
  code/modules/client/preferences_savefile.dm
Labels: Priority: High

#15110 arachnid legs now show up properly
  icons/mob/arachnid_parts.dmi
Labels: Fix, Sprites

#15103 Does some nice stuff on cyborg grippers
  code/_onclick/cyborg.dm
  code/game/objects/items.dm
  code/game/objects/items/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/inventory.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature, Fix, Refactor

#15088 how did no one notice ephedrine (see: every painkiller speedup buff which uses the same system) was broken until i abused it and got to be the beta tester?
  code/modules/movespeed/_movespeed_modifier.dm
Labels: Priority: High, Salt

#15063 ports various tg armor resprites and some such
  code/__DEFINES/dcs/signals.dm
  code/datums/components/armor_plate.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/mining/equipment/explorer_gear.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/head_muzzled.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/mob/clothing/taur_canine.dmi
  icons/mob/clothing/taur_hooved.dmi
  icons/mob/clothing/taur_naga.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#15121 fixes cwc tgui theme
  tgui/packages/tgui/index.js
Labels: Fix, UI

#15122 possibly fixes arc blasting loud sfx
  code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
Labels: Fix

#15124 adrenals are actually useful plus fixes all speedups
  code/modules/movespeed/_movespeed_modifier.dm
  code/modules/movespeed/modifiers/reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix, Balance/Rebalance

#15123 Fixes a runtime with Hitby
  code/modules/mob/living/living_defense.dm
Labels: Fix

#15113 Stops the SM from blowing things up
  code/modules/power/supermatter/supermatter.dm
Labels: Balance/Rebalance

#15062 bread is no longer equipped on the head; instead you actually hold it in your mouth
  code/modules/food_and_drinks/food/snacks_bread.dm
Labels: Fix

#15136 Revert "Reworks supermatter gas output to be less cascade-y, more risky"
  code/__DEFINES/maths.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Revert

#15120 Mafia updates
  code/__DEFINES/traits.dm
  code/modules/client/verbs/suicide.dm
  code/modules/mafia/_defines.dm
  code/modules/mafia/controller.dm
  code/modules/mafia/map_pieces.dm
  code/modules/mafia/outfits.dm
  code/modules/mafia/roles.dm
Labels: Code Improvement

#15099 tablets gaming - an NT IRN "buff"
  code/modules/modular_computers/file_system/programs/budgetordering.dm
Labels: Balance/Rebalance

#15071 Remove arbitrary bomb research cap + tweak formula a little
  code/game/machinery/doppler_array.dm
Labels: Balance/Rebalance

#15140 It's soft, plush, and very nice to get shoved agaisnt --> against
  code/game/turfs/simulated/floor/misc_floor.dm
Labels: Grammar and Formatting

#15141 very effective agaisnt flesh --> against
  code/modules/uplink/uplink_items/uplink_ammo.dm
Labels: Grammar and Formatting

#15128 fixes pubbystation having a diagonal air pump (????)
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#15155 [s] Fixes a major issue regarding techweb hidden nodes
  code/modules/research/techweb/_techweb.dm
Labels: In Game Exploit, Fix, Priority: High

#15152 blacklists morphine from dart guns, also haloperidol
  code/__DEFINES/reagents.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
Labels: Balance/Rebalance

#15119 Fixes Slaughter Demon, gives it an action button, and a slight buff
  code/modules/antagonists/slaughter/slaughter.dm
  icons/mob/actions/actions_minor_antag.dmi
Labels: Fix, Sprites, Balance/Rebalance

#15134 more brain trauma lines for genuinely no reason other than they're funny
  strings/traumas.json
Labels: Feature

#15137 Allows clock cultists to convert carded AIs by placing their card onto a conversion sigil
  code/modules/antagonists/clockcult/clock_effects/clock_sigils.dm
Labels: Balance/Rebalance

#15139 The cat surgeon event now prefers using "safe" turfs as spawn location
  code/modules/events/cat_surgeon.dm
Labels: Fix

#15143 fixes box perma not being connected to power; some small touch ups other than that also
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#15144 bone satchel onmob sprites
  code/game/objects/items/storage/backpack.dm
  icons/mob/clothing/back.dmi
  icons/obj/mining.dmi
  icons/obj/storage.dmi
Labels: Fix, Sprites

#15147 Adds a config entry for monstermos (disabled for now)
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/air.dm
  config/entries/dynamic.txt
  config/entries/general.txt
Labels: Config Update

#15154 [Fix] Fixes Space Heater behavior
  code/game/machinery/spaceheater.dm
  code/modules/power/cell.dm
Labels: Fix

#15162 prisoners cannot latejoin anymore
  code/modules/jobs/job_types/prisoner.dm
Labels: Fix

#15160 removes passkey from access circuits as it's not used anymore
  code/modules/integrated_electronics/subtypes/access.dm
Labels: Fix

#15157 Storage nanite designs are no longer inaccessible
  code/modules/research/techweb/nodes/bepis_nodes.dm
Labels: Fix

#15156 fixes madness mask sprites
  icons/mob/clothing/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Fix, Sprites

#15163 saltpr adding more suit slot clothing
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/code/modules/client/loadout/suit.dm
Labels: Feature, Sprites

#15167 Xenobio regenerative extract nerfing - Hold still for 5 seconds to use on others, 1 second for self, adds stackable disgust when used
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
Labels: Balance/Rebalance

#15168 Pubby and Beach Away Fixes
  _maps/RandomZLevels/away_mission/TheBeach.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#15169 adds a new mild trauma
  code/datums/brain_damage/mild.dm
Labels: Feature

#15171 Hey raspy why can plastic golems ventcrawl even with equipment?
  code/modules/mob/living/carbon/human/species_types/golems.dm
Labels: Fix

#15178 all medipens get inhands
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/obj/syringe.dmi
Labels: Sprites

#15176 fixes dogborg sleepers not working
  code/game/objects/items/devices/dogborg_sleeper.dm
Labels: Fix

#15094 removes building (fortnite) windows
  code/game/objects/items/stacks/sheets/glass.dm
Labels: Balance/Rebalance, Removal

#15133 the timeframely tips update
  strings/sillytips.txt
  strings/tips.txt
Labels: Feature, Removal

#15174 probably fixes holoparasites
  code/modules/mob/living/simple_animal/guardian/guardian.dm
Labels: Fix

#15175 meme pr that adds a hallunciation sound
  code/modules/events/mass_hallucination.dm
  code/modules/flufftext/Hallucination.dm
  sound/misc/seth.ogg
Labels: Sound

#15074 PORTS PAI Emag Act
  code/modules/mob/living/silicon/pai/pai.dm
Labels: Feature

#15184 Fixes crawling not overriding new reagent speedups
  code/modules/movespeed/modifiers/mobs.dm
Labels: Fix, Priority: High

#15182 reverts my limb damage changes
  code/modules/surgery/bodyparts/parts.dm
Labels: Revert, Removal

#15190 adds art supplies to the fun vendor
  code/modules/vending/games.dm
Labels: Feature

#15187 blacklists cryogenics from anomaly spawns
  code/modules/events/anomaly.dm
Labels: Code Improvement

#15183 gremlins become shock immune
  code/modules/mob/living/simple_animal/gremlin/gremlin.dm
Labels: Balance/Rebalance

#15192 ports a downstream fix of accordions
  code/modules/instruments/instrument_data/hardcoded.dm
  code/modules/instruments/instrument_data/organ.dm
Labels: Fix

#15200 fixes yet another emeraldsundisk map pr which was not spawning because the Ruin Didn't Actually Exist.
  code/datums/ruins/space.dm
  config/spaceRuinBlacklist.txt
Labels: Fix, Config Update

#15205 fixes code\modules\mob\living\simple_animal\hostile\plaguerat.dm:139:warning: newmouse: variable defined but not used
  code/modules/mob/living/simple_animal/hostile/plaguerat.dm
Labels: Fix

#15210 helter skelter fixes so it doesn't break comms and does not come with a fucking uplink
  _maps/RandomRuins/SpaceRuins/skelter.dmm
Labels: Fix, Map Edit, Balance/Rebalance

#15213 Removes a dead var
  code/game/world.dm
Labels: Removal

#15203 Fixing (cult) slurring and stuttering never going away from non-carbon mobs.
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix, Removal

#15197 Ups minimum lavaland temperature
  code/datums/atmosphere/planetary.dm
Labels: Fix

#15201 fixes monkey shuttle brig
  _maps/shuttles/emergency_nature.dmm
Labels: Fix, Map Edit

#15202 CCS stock safety
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/magic/motivation.dm
Labels: Balance/Rebalance

#15204 shotgun shell clips now have melee click delay (0.8s) with this one weird trick
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Balance/Rebalance

#15206 meta station prison remapping
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/PubbyStation/job_changes.dm
  code/modules/jobs/job_types/prisoner.dm
  tgstation.dme
Labels: Feature, Map Edit

#15191 Puts the ninja status back into the status window and restores the energy charge meter.
  code/modules/mob/living/carbon/human/human.dm
  code/modules/ninja/__ninjaDefines.dm
  code/modules/ninja/suit/ninja_equipment_actions/ninja_status_read.dm
  code/modules/ninja/suit/suit.dm
Labels: Refactor

#15189 a new maintenance ambience
  code/__DEFINES/sound.dm
  sound/ambience/ambimaint10.ogg
Labels: Sound

#15188 ports/adds more edited clothing
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/code/modules/client/loadout/suit.dm
Labels: Feature, Fix, Sprites

#15180 Achivement & Clowncar update
  code/__DEFINES/achievements.dm
  code/__DEFINES/colors.dm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/vehicles.dm
  code/datums/achievements/_achievement_data.dm
  code/datums/achievements/_awards.dm
  code/datums/achievements/boss_achievements.dm
  code/datums/achievements/job_achievements.dm
  code/datums/achievements/job_scores.dm
  code/datums/achievements/misc_achievements.dm
  code/datums/achievements/misc_scores.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/storage/toolbox.dm
  code/modules/antagonists/eldritch_cult/knowledge/flesh_lore.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
  code/modules/antagonists/eldritch_cult/knowledge/void_lore.dm
  code/modules/antagonists/wizard/equipment/soulstone.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/wendigo.dm
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/cars/car.dm
  code/modules/vehicles/cars/clowncar.dm
  code/modules/vehicles/vehicle_actions.dm
  sound/vehicles/carcannon1.ogg
  sound/vehicles/carcannon2.ogg
  sound/vehicles/carcannon3.ogg
  sound/vehicles/clowncar_cannonmode1.ogg
  sound/vehicles/clowncar_cannonmode2.ogg
  tgstation.dme
Labels: Feature, Sound, Code Improvement

#15199 removes motivation player lock; halves the motivation's price; allows motivation to discount.
  code/modules/uplink/uplink_items/uplink_dangerous.dm
Labels: Balance/Rebalance, Removal

#15217 Removes "play on same board" from minesweeper
  code/game/machinery/computer/arcade/minesweeper.dm
Labels: Removal

#15216 da moon outpost nest nerf
  _maps/RandomZLevels/away_mission/moonoutpost19.dmm
Labels: Map Edit, Removal

#15214 [Fix] Grab bag bug fixing
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_medical_and_dinnerware.dm
Labels: Fix
