Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-06, with the labels that each got.

#14764 Touching up boxstation engineering
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#14782 Fixing xenoruins floor
  _maps/RandomRuins/LavaRuins/lavaland_surface_alien_nest.dmm
Labels: Balance/Rebalance, Map Edit

#14723 Delta ce office rearrangement
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Map Edit

#14784 Tiny Pubby Additions
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#14785 Metastation atmos fix
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#14772 Makes sniper zooming work
  code/modules/projectiles/gun.dm
Labels: Fix

#14788 Pubbystation toxins burn chamber fix
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#14786 Fixes float()
  code/game/atoms_movable.dm
Labels: Code Improvement

#14795 Boxstation touchups2
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit

#14793 Pools now get misty at warm insteaed of scalding
  code/modules/pool/pool_controller.dm
Labels: Feature

#14792 More reasonable SUCC for the meta pool drain.
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit

#14160 Adds a new traitor item, Motivation (Part 1)
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/projectiles/ammunition/special/magic.dm
  code/modules/projectiles/guns/magic/motivation.dm
  code/modules/projectiles/projectile/special/judgement_cut.dm
  code/modules/uplink/uplink_items/uplink_dangerous.dm
  icons/effects/effects.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/projectiles.dmi
  sound/weapons/judgementfire.ogg
  sound/weapons/judgementhit.ogg
  tgstation.dme
  tgui/public/tgui-common.bundle.js
Labels: Feature, Needs Review, Sound, Sprites, UI

#14809 Centralizes borg speech and uses some of the icons for the typing indicator
  code/datums/chatmessage.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/mob/typing_indicator.dm
  icons/mob/talk_64x64.dmi
Labels: Code Improvement, Sprites

#14805 Hydroponics slimejelly recipe from tg
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Feature

#14802 Atmos resin buff? fix?
  code/game/objects/effects/effect_system/effects_foam.dm
Labels: Fix

#14787 ORV Uniform Revamp
  code/modules/clothing/under/trek.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
  modular_citadel/code/modules/clothing/trek.dm
Labels: Sprites

#14779 Makes orbit menu show antags if DNR
  code/modules/mob/dead/observer/orbit.dm
  tgui/packages/tgui/interfaces/Orbit.js
Labels: UI

#14810 Clowncar exploit fix
  code/modules/vehicles/cars/car.dm
Labels: Fix

#14808 Fixes soulstones runtiming
  code/modules/antagonists/wizard/equipment/soulstone.dm
Labels: Fix

#14796 Moves medical holodeck to restricted
  code/game/area/areas/holodeck.dm
Labels: Balance/Rebalance

#14771 Lets the Cargo Shuttle use Disposal Pipes again
  code/modules/shuttle/supply.dm
Labels: Balance/Rebalance

#14749 adds goliath calamari (currently untested because Forget™)
  code/modules/food_and_drinks/food.dmi
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
Labels: Feature

#14760 Ports Floor Cluwnes and Cluwnes.
  code/__DEFINES/DNA.dm
  code/__DEFINES/admin.dm
  code/datums/mutations/cluwne.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/clothing/masks/cluwne.dm
  code/modules/clothing/shoes/cluwne.dm
  code/modules/clothing/under/cluwne.dm
  code/modules/events/floorcluwne.dm
  code/modules/mob/living/simple_animal/hostile/floor_cluwne.dm
  code/modules/spells/spell_types/cluwnecurse.dm
  icons/mob/actions/actions_spells.dmi
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/feet_digi.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/mask_muzzled.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/turf/floors.dmi
  sound/effects/bodyscrape-01.ogg
  sound/effects/bodyscrape-02.ogg
  sound/effects/cluwne_feast.ogg
  sound/misc/bikehorn_creepy.ogg
  sound/misc/cluwne_breathing.ogg
  sound/misc/floor_cluwne_emerge.ogg
  sound/misc/honk_echo_distant.ogg
  sound/voice/cluwnelaugh1.ogg
  sound/voice/cluwnelaugh2.ogg
  sound/voice/cluwnelaugh2_reversed.ogg
  sound/voice/cluwnelaugh3.ogg
  tgstation.dme
Labels: Administration, Feature, Sound, Sprites

#14762 adds cat meteors
  code/game/gamemodes/meteor/meteors.dm
  code/modules/events/cat_wave.dm
  code/modules/events/meteor_wave.dm
  icons/obj/meteor.dmi
Labels: Feature, Sprites

#14766 Fix cult area shenanigans, cult can do stuff in maint again.
  code/__DEFINES/_flags/_flags.dm
  code/_globalvars/bitfields.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/holodeck.dm
  code/game/area/areas/shuttles.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_judgement.dm
  code/modules/antagonists/clockcult/clock_structures/stargazer.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/cult/ritual.dm
Labels: Fix

#14776 New Challenger: The Cat Surgeon has appeared! (Ready!)
  code/modules/events/cat_surgeon.dm
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
  code/modules/projectiles/projectile/bullets/dart_syringe.dm
  sound/misc/catscream.ogg
  tgstation.dme
Labels: Sound

#14683 Off Balance Disarms only if shoved into a wall or person.
  code/__DEFINES/combat.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Awaiting further discussion/approval, Balance/Rebalance

#14768 makes xenos immune to stamina damage, with something that might be potentially horrifically abusable but isn't really fixable in a clean way yet
  code/modules/surgery/bodyparts/_bodyparts.dm
Labels: Fix

#14828 fixes the crafting menu, adds an unit test to automatically yell at people who PR untested code that ended up breaking it for me (thanks drpanis)
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/unit_tests/crafting_recipes.dm
Labels: Fix, Priority: CRITICAL

#14825 TG Resprite Compendium Atomization Project | Episode One: Water Coolers
  icons/obj/vending.dmi
Labels: Sprites

#14826 TG Resprite Compendium Atomization Project | Episode Two: Bank Machines
  code/game/machinery/bank_machine.dm
  goon/icons/obj/closet.dmi
  goon/icons/obj/goon_terminals.dmi
  icons/obj/computer.dmi
Labels: Removal, Sprites

#14829 TG Resprite Compendium Atomization Project | Episode Four: Singularity Hammers
  code/game/objects/items/singularityhammer.dm
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Sprites

#14830 TG Resprite Compendium Atomization Project | Episode Five: Dish Drives
  code/game/machinery/dish_drive.dm
  goon/icons/obj/kitchen.dmi
  icons/obj/kitchen.dmi
Labels: Sprites

#14836 adds 7 more round tips
  strings/tips.txt
Labels: Feature

#14820 [FIX] Some cargo related fixes
  .vscode/settings.json
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/modules/cargo/order.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/misc.dm
  code/modules/shuttle/supply.dm
Labels: Fix

#14813 Fixes some small issues with cosmetic syndicate clothing (loadout clothing)
  code/modules/clothing/under/syndicate.dm
Labels: Fix

#14841 Revert "adds cat meteors"
  code/game/gamemodes/meteor/meteors.dm
  code/modules/events/cat_wave.dm
  code/modules/events/meteor_wave.dm
  icons/obj/meteor.dmi
Labels: Balance/Rebalance, Revert, Sprites

#14816 Adds a pen slot for tablet computers
  code/modules/modular_computers/computers/_modular_computer_shared.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/computers/item/tablet.dm
  tgui/packages/tgui/layouts/NtosWindow.js
Labels: Feature, Grammar and Formatting, UI

#14814 Delta Tweaks
  _maps/map_files/Deltastation/DeltaStation2.dmm
  tgui/public/tgui-common.bundle.js
  tgui/yarn.lock
Labels: Feature, Map Edit, Removal, UI

#14824 bees can go in containers and are released upon opening the container
  code/datums/elements/mob_holder.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
Labels: Feature

#14837 (held against my will) adds a onesleeved croptop
  code/modules/clothing/under/accessories.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/accessories.dmi
  icons/obj/clothing/accessories.dmi
Labels: Sprites

#14818 HEY HEY! COME ON OVER, HAVE SOME FUN WITH SNOW TAXI!!!
  _maps/map_files/Snaxi/IcemoonUnderground_Above.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
Labels: Map Edit

#14832 TG Resprite Compendium Atomization Project | Episode Seven: Misc. Resprites & Distinctive Combat Defibs
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/items/defib.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/weaponry.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mining/money_bag.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/head.dmi
  icons/mob/inhands/equipment/custodial_lefthand.dmi
  icons/mob/inhands/equipment/custodial_righthand.dmi
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/mob/inhands/weapons/staves_lefthand.dmi
  icons/mob/inhands/weapons/staves_righthand.dmi
  icons/mob/inhands/weapons/swords_lefthand.dmi
  icons/mob/inhands/weapons/swords_righthand.dmi
  icons/mob/mob.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/defibrillators.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/janitor.dmi
  icons/obj/storage.dmi
Labels: Sprites

#14849 Quick Snaxi fixes.
  _maps/map_files/Snaxi/IcemoonUnderground_Above.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
Labels: Map Edit

#14797 Delete docker_publish.yml
  .github/workflows/docker_publish.yml
Labels: Github

#14854 fixes an oversight causing embed jostling to do 2x as much damage as it should
  code/datums/components/embedded.dm
Labels: Fix

#14851 Extended Armwraps
  code/datums/components/crafting/recipes/recipes_clothing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Feature, Sprites

#14862 BUG FIX: Changeling Bone Gauntlets work again
  code/modules/antagonists/changeling/powers/mutations.dm
Labels: Fix

#14847 21/79 not 20/80 the revenge
  code/modules/atmospherics/machinery/components/unary_devices/tank.dm
Labels: Fix

#14864 Smaller but more important changes to Snaxi.
  _maps/map_files/Snaxi/Snaxi.dmm
Labels: Feature, Map Edit, Removal

#14831 TG Resprite Compendium Atomization Project | Episode Six: Beltslot Sprites & Telebaton Resprite
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/pinpointer.dm
  code/modules/antagonists/nukeop/equipment/pinpointer.dm
  code/modules/antagonists/traitor/equipment/contractor.dm
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/belt_mirror.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Sprites

#14860 Updates our nanite stuff to TG's, mostly
  code/__DEFINES/misc.dm
  code/__DEFINES/nanites.dm
  code/datums/components/nanites.dm
  code/datums/status_effects/buffs.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/nanite_cloud_controller.dm
  code/modules/research/nanites/nanite_program_hub.dm
  code/modules/research/nanites/nanite_programmer.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/research/nanites/nanite_programs/protocols.dm
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/research/nanites/nanite_programs/suppression.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
  icons/effects/blood.dmi
  icons/mob/actions/actions_items.dmi
  icons/obj/machines/research.dmi
  tgui/packages/tgui/interfaces/NaniteCloudControl.js
Labels: Sprites, UI

#14867 wheely heelies finally have that downside people have been telling me about
  code/modules/vehicles/scooter.dm
  html/changelog.html
Labels: Feature

#14863 Various Fixes (freelance)
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit, Removal

#14873 vore href exploit fix
  code/modules/vore/eating/vorepanel.dm
Labels: Fix

#14872 it turns out i accidentally buffed glowshrooms by a factor of 21. this should probably be fixed.
  code/game/objects/effects/glowshroom.dm
Labels: Fix

#14850 the roasted roasted roasted roasted roasted roasted roasted roasted.........
  code/game/objects/items/melee/misc.dm
Labels: Fix

#14870 Metastation xenobiology pen door
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, Map Edit

#14880 Fixes a bunch of things and some related should not sleeps because they make the CI cry
  code/datums/components/nanites.dm
  code/datums/wires/airlock.dm
  code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
Labels: Code Improvement, Fix

#14877 inelastic exports no longer uselessly multiply their price by e^0 every tick
  code/modules/cargo/exports.dm
Labels: Fix

#14876 [Ready] Cat Surgeon Warning
  code/modules/events/cat_surgeon.dm
Labels: Balance/Rebalance, Feature

#14662 Adds syringes, pillbottles, hyposprays to medical protolathe
  code/modules/research/designs/autolathe_desings/autolathe_designs_medical_and_dinnerware.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/_techweb_node.dm
  code/modules/research/techweb/nodes/biotech_nodes.dm
Labels: Feature

#14891 The most important map update for the 5x5 SM.
  _maps/RandomRuins/StationRuins/Box/Engine/engine_sm_5x5.dmm
Labels: Feature, Map Edit

#14887 Swapping some floors on the TEG-map
  _maps/RandomRuins/StationRuins/Box/Engine/engine_teg.dmm
Labels: Map Edit

#14896 Fixes shoddy math & assumptions causing APCs in sufficiently high-power-requiring rooms to work forever
  code/modules/power/apc.dm
Labels: Fix

#14892 [Ready] Googly Eyes! (Hydroponics)
  code/modules/hydroponics/grown/mushrooms.dm
  code/modules/hydroponics/plant_genes.dm
  icons/obj/hydroponics/harvest.dmi
Labels: Feature, Sprites

#14822 Solving inconsistencies regarding QM being command
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/quartermaster.dm
Labels: Map Edit, Removal, UI

#14895 Adds a new survival pod, the penthouse pod.
  _maps/templates/shelter_5.dmm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/shelters.dm
Labels: Feature, Map Edit

#14861 Pubby xenobiology atmospherics update among other things
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#14893 [Ready] The Daily Whiplash (Newspaper Baton)
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/melee/misc.dm
  icons/obj/bureaucracy.dmi
Labels: Feature, Sprites

#14899 Moves tendril KA upgrade disks to blood drunk miner.
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
Labels: Balance/Rebalance

#14883 [Ready] The plushie PR you didn't know we needed (but we kinda did)
  code/game/objects/items/plushes.dm
  icons/obj/plushes.dmi
Labels: Feature, Sprites

#14904 [Hopefully Fixed] Vault Rebalance on Boxstation
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Balance/Rebalance, Map Edit
