Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-05, with the labels that each got.

#14670 General main map fixes + touchups
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit

#14678 Ports #55624 from tgstation
  code/__DEFINES/layers_planes.dm
  code/modules/awaymissions/gateway.dm
  code/modules/lighting/lighting_object.dm
  icons/obj/machines/gateway.dmi
Labels: Sprites

#14673 Soviet Crates, now available!
  code/game/objects/structures/crates_lockers/crates/secure.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/security.dm
  icons/obj/crates.dmi
Labels: Feature, Sprites

#14679 Meta atmos Enhancement
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#14680 Prevents Nightmares from being pulled OUT of jaunt from vendors and engraved messages.
  code/modules/library/soapstone.dm
  code/modules/spells/spell_types/shadow_walk.dm
  code/modules/vending/_vending.dm
Labels: Balance/Rebalance

#14687 Fixes virus bottles being white
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/reagents/reagent_containers.dm
Labels: Fix

#14671 lets humans have digi legs (and avian legs)
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  icons/mob/human_parts_greyscale.dmi
Labels: Feature, Sprites

#14664 The Unrolling Pin! (Ready)
  code/game/objects/items/kitchen.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/food_and_drinks/food/snacks/dough.dm
  code/modules/vending/dinnerware.dm
  icons/mob/inhands/equipment/kitchen_lefthand.dmi
  icons/mob/inhands/equipment/kitchen_righthand.dmi
  icons/obj/kitchen.dmi
Labels: Feature, Sprites

#14688 Makes tooltips good and creates a base for adding more.
  code/_onclick/hud/radial.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/silicon/examine.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defines.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/tooltip/tooltip.dm
  code/modules/tooltip/tooltip.html
Labels: Code Improvement, Feature, Fix

#14696 Adds make priority announcement admin verb
  code/modules/admin/verbs/randomverbs.dm
Labels: Feature

#14637 Derringer Pass 1: No Rest for the Wicked(ly Bad Coder {me})
  code/datums/components/storage/concrete/pockets.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/cargo/packs/armory.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/internal/derringer.dm
  code/modules/projectiles/guns/ballistic/derringer.dm
  code/modules/uplink/uplink_items/uplink_ammo.dm
  code/modules/uplink/uplink_items/uplink_stealth.dm
Labels: Feature, Fix, Needs Review

#14698 Delta station xenobio atmos enhancements.
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Feature, Map Edit

#14703 balances syndie simplemob
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
Labels: Balance/Rebalance

#14707 Delta station Viro atmos 🧂 pr
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Map Edit

#14702 bunny ears but they're not lops (vegas style)
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  modular_citadel/icons/mob/mam_ears.dmi
Labels: Feature

#14708 [Fix] Bugs are BAD!
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#14710 Anthromorphic isnt a word
  code/modules/mob/living/carbon/human/species_types/anthropomorph.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  tgstation.dme
Labels: Grammar and Formatting

#14650 Lavaland Wine: Pinot Mort (Ready)
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#14718 consealed
  code/modules/uplink/uplink_items/uplink_stealth.dm
Labels: Grammar and Formatting

#14715 Removes Voice of God sleep again since an undocumented change readded it.
  code/modules/surgery/organs/vocal_cords.dm
Labels: Balance/Rebalance, Removal

#14627 borg spraycans have a five second delay before being able to knock someone down again
  code/game/objects/items/crayons.dm
Labels: Balance/Rebalance

#14711 removes gateway visuals because byond being in charge of not stack overflowing is too much to ask
  code/modules/awaymissions/gateway.dm
Labels: In Game Exploit, Priority: CRITICAL, Removal

#14721 Meta bots don't get stuck at engi anymore
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, Map Edit

#14724 (not urgent) Deletes a extra nav beacon I left in while fixing the meta bots
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit

#14726 ports Amaretto from TG
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/vending/boozeomat.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#14727 more drink mixture flavortext
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
Labels: Feature

#14731 The E-Fink (Yes, really)
  code/game/objects/items/kitchen.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_medical_and_dinnerware.dm
  code/modules/vending/dinnerware.dm
  icons/mob/inhands/equipment/kitchen_lefthand.dmi
  icons/mob/inhands/equipment/kitchen_righthand.dmi
  icons/obj/kitchen.dmi
  sound/weapons/bladesliceb.ogg
Labels: Feature, Sound, Sprites

#14730 Empty mining capsule pod for all those fun projects which need space.
  _maps/templates/shelter_4.dmm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/shelters.dm
Labels: Feature, Map Edit

#14725 now approaching: Baystation
  code/controllers/subsystem/ticker.dm
  sound/roundend/approachingbaystation.ogg
Labels: Sound

#14653 ports rp's marking system
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories/Citadel_Snowflake.dm
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/synthliz.dm
  code/modules/mob/living/carbon/human/species_types/anthropomorph.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/xeno.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  icons/mob/mutant_bodyparts.dmi
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_citadel/icons/mob/mam_markings.dmi
Labels: Feature, Sprites

#14733 [Fix] Even More bug fixing
  code/game/machinery/computer/communications.dm
  code/modules/antagonists/eldritch_cult/eldritch_items.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
Labels: Fix

#14738 Makes antags actually get activity properly
  code/modules/antagonists/_common/antag_datum.dm
Labels: Fix

#14739 A small ear related PR (Deer ears, Rabbit ears)
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  modular_citadel/icons/mob/mam_ears.dmi
Labels: Sprites

#14742 (READY) Ports Special Hud icons for some simple mobs
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/simple_animal.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/legionnaire.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/pandora.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/hostile/wumborian_fugu.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  icons/mob/screen_gen.dmi
  tgstation.dme
Labels: Sprites

#14743 Lowers pop for Contractors down to 25.
  code/modules/uplink/uplink_items/uplink_bundles.dm
Labels: Balance/Rebalance

#14716 Makes species/antag trait blacklist no longer remove ALL traits
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#14736 big Aerial Rodent hair port because hair moment
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  icons/mob/hair.dmi
  modular_citadel/icons/mob/mam_ears.dmi
Labels: Feature, Sprites

#14737 Traitor's Bizarre Adventure Episode One: Mauler Gauntlets Are Unbreakable
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/uplink/uplink_items/uplink_dangerous.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
  sound/weapons/mauler_punch.ogg
Labels: Feature, Sound, Sprites

#14748 A clean map is a good map
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, Map Edit

#14756 Why Are My Hands Doing Forty Damage Per Punch?: you can no longer stack damage bonuses from scarp + pugilist
  code/__DEFINES/traits.dm
  code/datums/martial/sleeping_carp.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/clothing/gloves/miscellaneous.dm
Labels: Balance/Rebalance

#14750 Ports Swag outfit from /tg/
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/costume.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/feet_digi.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#14755 fix brand intelligence runtime
  code/modules/events/brand_intelligence.dm
Labels: Fix

#14751 Ports the Clown Mob Spawner from /tg/ for admins
  code/game/objects/structures/spawner.dm
Labels: Feature

#14758 Pubby atmos Mixing will no longer auto-suck gasses
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#14757 fixes being able to slam into people while bloodcrawled as slaughter demon
  code/modules/antagonists/slaughter/slaughter.dm
Labels: Fix

#14761 Fixes camera image taking
  code/modules/photography/camera/camera.dm
  code/modules/photography/camera/camera_image_capturing.dm
  icons/effects/camera_image_base.dmi
Labels: Priority: High, Sprites
