Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-04, with the labels that each got.

#14541 You can now pay pirates again
  code/modules/events/pirates.dm
  strings/pirates.json
Labels: Fix

#14542 Added observe logging
  code/modules/mob/dead/observer/observer.dm
Labels: Feature

#14558 Bumbles no longer has a number beside their name
  code/modules/mob/living/simple_animal/friendly/bumbles.dm
Labels: Fix

#14539 Removed "destroy cloning machines" objective
  code/game/gamemodes/objective_sabotage.dm
Labels: Code Improvement, Removal

#14564 kills the 50 towercap crate, closes #14563
  code/modules/cargo/packs/materials.dm
Labels: Balance/Rebalance

#14565 Corrects the wood plank crate's name and description
  code/modules/cargo/packs/materials.dm
Labels: Fix

#14547 Fixing some issues for laptops and lockers/crates.
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/modular_computers/computers/item/laptop.dm
Labels: Fix, Removal

#14567 fixes forced climax causing a climax-with
  code/modules/arousal/arousal.dm
Labels: Fix

#14566 Botany Pass 3: THE CABBAGE PATCH PEOPLE MUST DIE.
  code/modules/hydroponics/grown/misc.dm
Labels: Fix

#14559 Brings back the prayer ding
  code/modules/admin/verbs/pray.dm
Labels: Administration

#14540 Fixes some lizards
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
Labels: Fix

#14535 Adds telescopic baseball bat
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/items/weaponry.dm
  code/modules/uplink/uplink_items/uplink_stealth.dm
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/items_and_weapons.dmi
Labels: Sprites

#14562 Buffs the genetic mutation Autotomy
  code/datums/mutations/actions.dm
  code/datums/status_effects/debuffs.dm
  code/modules/surgery/bodyparts/dismemberment.dm
Labels: Balance/Rebalance

#14551 This was going to just be a fix for slime puddles making mutation and cult visual indicators disappear but it ended up becoming more complicated than I thought
  code/__DEFINES/misc.dm
  code/datums/mutations/_mutations.dm
  code/datums/mutations/radioactive.dm
  code/datums/mutations/space_adaptation.dm
  code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
  code/modules/antagonists/clockcult/clockcult.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/mob/living/carbon/human/innate_abilities/blobform.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/update_icons.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Code Improvement, Fix, Grammar and Formatting

#14570 Sylvan and Mushroom languages now tongueless, EaL learnable
  code/modules/language/machine.dm
  code/modules/language/mushroom.dm
  code/modules/language/sylvan.dm
Labels: Feature

#14574 Container swapping for Pandemic machine
  code/modules/reagents/chemistry/machinery/pandemic.dm
Labels: Feature

#14577 Prevents machines that open from dropping their components
  code/game/machinery/_machinery.dm
Labels: Fix

#14536 removes delta_time from tgui process because it doesn't need it
  code/modules/tgui/tgui.dm
Labels: Removal

#14593 Fixes phantom mob-holder items
  code/datums/elements/mob_holder.dm
Labels: Fix

#14586 Fixed drones nullspacing things they try to place on tables and in closets
  code/modules/mob/living/simple_animal/friendly/drone/inventory.dm
Labels: Fix

#14596 makes a config option off by default
  config/config.txt
Labels: Config Update

#14597 Fixed female slime-subspecies left/right sprites being flipped
  icons/mob/human_parts_greyscale.dmi
Labels: Fix, Sprites

#14267 allows all non queen/empress SIMPLE MOB xenos to spawn from gold cores
  code/modules/mob/living/simple_animal/hostile/alien.dm
Labels: Balance/Rebalance

#14600 viro symptom typo fix
  code/datums/diseases/advance/symptoms/heal.dm
Labels: Fix

#14581 pirate payoff minimum from 20k to 1k
  code/modules/events/pirates.dm
Labels: Balance/Rebalance, Removal

#14545 renders storage objects independently per user
  code/__HELPERS/_lists.dm
  code/_onclick/hud/screen_objects/storage.dm
  code/datums/components/storage/storage.dm
  code/datums/components/storage/ui.dm
  code/datums/numbered_display.dm
  icons/mob/screen_gen.dmi
Labels: Needs Review, Sprites

#14601 Resprites the sushi, tuna can, sea weed and the onigiri icons.
  icons/obj/food/food.dmi
Labels: Good First PR, Sprites

#14609 Antagonists with escape objectives can now podbaby again to greentext
  _maps/map_files/generic/CentCom.dmm
Labels: Fix, Map Edit

#14602 Pirate related fixes and communication console fixes
  code/game/machinery/computer/communications.dm
  code/modules/events/pirates.dm
  icons/obj/machines/dominator.dmi
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
Labels: Fix, Sprites, UI

#14605 Fixes tank dispensers being unusable by borgs
  code/game/objects/structures/tank_dispenser.dm
Labels: Fix

#14611 Color Labels the Operating Computer
  tgui/packages/tgui/interfaces/OperatingComputer.js
Labels: UI

#14616 Fixes an unintentional buff to EMPs when used against mechs (related to the drain amount formula)
  code/game/mecha/mecha_defense.dm
Labels: Fix

#14622 Fixes organic repair surgeries showing for targets without any organic bodyparts
  code/modules/surgery/healing.dm
Labels: Fix

#14599 Revenant changes port from TG - revenants no longer spend their current essence to unlock new abilities; a fix
  code/modules/antagonists/revenant/revenant.dm
  code/modules/antagonists/revenant/revenant_abilities.dm
Labels: Balance/Rebalance, Fix

#14606 TGUIZES the cloning computer
  code/game/machinery/computer/cloning.dm
  code/game/objects/items/implants/implant_misc.dm
  tgui/packages/tgui/interfaces/CloningConsole.js
Labels: Feature, Refactor, Removal, UI

#14626 (i swear this is not due to anyone in particular unironically) fixes heretic not being on jobban panel because every other coder was too busy to for 6 months
  code/modules/admin/DB_ban/functions.dm
  code/modules/admin/topic.dm
Labels: Priority: High

#14584 deletes box ghost burger
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Removal

#14591 ports deathrattle implants but without mob statchange because i am not gonna port that today
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items/implants/implant_deathrattle.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/mob/living/death.dm
  code/modules/uplink/uplink_items/uplink_implants.dm
  sound/items/knell1.ogg
  sound/items/knell2.ogg
  sound/items/knell3.ogg
  sound/items/knell4.ogg
  tgstation.dme
Labels: Feature, Sound

#14603 Activity tracking; traitor class tweaks
  code/__DEFINES/dcs/signals.dm
  code/_onclick/item_attack.dm
  code/datums/components/activity.dm
  code/datums/components/explodable.dm
  code/datums/elements/wuv.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/electrostaff.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/structures/manned_turret.dm
  code/modules/admin/antag_panel.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/traitor/classes/assassin.dm
  code/modules/antagonists/traitor/classes/freeform.dm
  code/modules/antagonists/traitor/classes/human.dm
  code/modules/antagonists/traitor/classes/subterfuge.dm
  code/modules/antagonists/traitor/classes/traitor_class.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/ninja/suit/ninjaDrainAct.dm
  code/modules/uplink/uplink_items/uplink_bundles.dm
  tgstation.dme
Labels: Feature, Fix

#14613 New Bottle Sprites
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Sprites

#14608 The Holdout Update: How I learned to stop whining, and aim a pocket pistol.
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/wallets.dm
  code/modules/cargo/blackmarket/blackmarket_items/weapons.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/goodies.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/boxes_magazines/internal/derringer.dm
  code/modules/projectiles/guns/ballistic/derringer.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/uplink/uplink_items/uplink_stealth.dm
  icons/obj/guns/projectile.dmi
  tgstation.dme
  tgui/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  tgui/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  tgui/.yarn/releases/yarn-2.4.0.cjs
Labels: Feature, Sprites, UI

#14617 CONSITENCY: Matches Dragnet breakout time to Energy Bolas
  code/game/objects/items/handcuffs.dm
Labels: Balance/Rebalance

#14624 adds ash drake meat
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
Labels: Feature

#14625 solars plastitanium glass fix
  code/game/objects/items/stacks/sheets/glass.dm
Labels: Fix

#14543 Cargo bugfixes
  code/__DEFINES/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/modules/cargo/packs.dm
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/misc.dm
  code/modules/shuttle/supply.dm
Labels: Fix

#14546 Ports bluespace pipes from yogs
  code/game/machinery/pipe/construction.dm
  code/game/objects/items/RPD.dm
  code/modules/atmospherics/machinery/pipes/bluespace.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/techweb/nodes/bluespace_nodes.dm
  icons/obj/atmospherics/pipes/bluespace.dmi
  tgstation.dme
Labels: Feature, Sprites

#14582 Slimeperson organs are now unique with a unique name, therefore confusing people
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/stomach.dm
  icons/obj/surgery.dmi
Labels: Feature, Sprites

#14631 Kev please don't kill me for a one number change but this lowers Slaughter Demon Weight
  code/modules/antagonists/slaughter/slaughterevent.dm
Labels: Balance/Rebalance, Priority: High

#14571 Space pirate sleepers can now be crowbared to be destroyed
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Feature

#14443 Another dreaded baton rework pr; batons knockdown and slow on rightclick (with a cooldown), otherwise stagger, plus more
  code/__DEFINES/combat.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/teleprod.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance, Fix

#14633 fixes a slightly important thing
  code/modules/client/verbs/autobunker.dm
Labels: Priority: High

#14656 Rename emergency_airless.dmm to emergency_construction.dmm
  _maps/shuttles/emergency_construction.dmm
Labels: Fix, Map Edit

#14642 TGUI Select Equipment menu
  code/__DEFINES/vv.dm
  code/__HELPERS/icons.dm
  code/datums/dna.dm
  code/datums/outfit.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/outfit_editor.dm
  code/modules/admin/outfit_manager.dm
  code/modules/admin/outfits.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/verbs/selectequipment.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/chameleon.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  tgstation.dme
  tgui/packages/common/collections.js
  tgui/packages/tgui/interfaces/ListInput.js
  tgui/packages/tgui/interfaces/OutfitEditor.js
  tgui/packages/tgui/interfaces/OutfitManager.js
  tgui/packages/tgui/interfaces/SelectEquipment.js
Labels: Administration, UI

#14641 Removes the Reinforcement Chromosome from Genetics.
  code/game/objects/items/chromosome.dm
Labels: Balance/Rebalance, Removal

#14666 Fixes a couple runtimes in SSactivity
  code/controllers/subsystem/activity.dm
Labels: Fix

#14643 Changes the space adaptation sprite to something more subtle.
  code/datums/mutations/space_adaptation.dm
  icons/effects/genetics.dmi
Labels: Sprites

#14636 Inconsistency Fixes, 10MM Rifle tweaks.
  code/modules/cargo/packs/security.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Feature, Fix

#14635 Adds fake blindfolds. For reasons.
  code/modules/clothing/glasses/_glasses.dm
  modular_citadel/code/modules/client/loadout/glasses.dm
Labels: Feature

#14659 Bubblegum HALLUCINATIONS are capitalized
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
Labels: Grammar and Formatting

#14651 The reagent dart gun uplink item needed work.
  code/modules/projectiles/ammunition/special/syringe.dm
  code/modules/projectiles/guns/misc/chem_gun.dm
  code/modules/uplink/uplink_items/uplink_roles.dm
Labels: Balance/Rebalance

#14649 TRADE OFFER: YOU GIVE ME 30000 PLASMA. I GIVE YOU A SINGLE MAGAZINE OF 10MM INCINDIARY AMMO
  code/modules/research/techweb/nodes/syndicate_nodes.dm
  modular_citadel/code/modules/projectiles/boxes_magazines/external/pistol.dm
Labels: Balance/Rebalance

#14647 Ports TGUI limb grower from tg
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/reagents.dm
  code/game/machinery/limbgrower.dm
  tgui/packages/tgui/interfaces/Limbgrower.js
Labels: Code Improvement, Feature, Fix, Refactor, UI

#14648 Decal Painter menu is no longer shit and has visible previews.
  code/game/objects/items/airlock_painter.dm
  code/modules/asset_cache/asset_list_items.dm
  icons/turf/decals.dmi
  tgui/packages/tgui/interfaces/DecalPainter.js
Labels: Feature, Fix, Sprites, UI

#14639 Ports a significant amount of the tg cybernetic organ code + more
  code/__DEFINES/_flags/item_flags.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/cargo/exports/organs_robotics.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/stomach.dm
  icons/obj/surgery.dmi
Labels: Feature, Needs Review, Sprites

#14668 [Fix] Restores the Sprite for the Riot Suit
  code/modules/clothing/suits/armor.dm
Labels: Fix
