Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-11, with the labels that each got.

#15323 Fixes Table Air Alarm on Pubby and Redundant Fire Lock on Box
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#15326 Hey, that's not supposed to be over there (More Pubby Fixes)
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#15334 More lung fixes
  code/modules/surgery/organs/lungs.dm
Labels: Fix

#15337 fixes party pod sprite
  icons/obj/machines/sleeper.dmi
Labels: Fix, Sprites

#15336 fixes red panda head marking
  code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
Labels: Fix

#15345 Fixes power alerts not to work precisely incorrectly
  code/game/area/areas.dm
  code/modules/power/apc.dm
Labels: Fix

#15346 Fixes simultaneous suffocate/overbreathe
  code/modules/surgery/organs/lungs.dm
Labels: Fix

#15342 Adding trash piles to meta and also maybe not everyone should be able to get into xenobio
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#15322 Crayon precision mode
  code/game/objects/items/crayons.dm
  tgui/packages/tgui/interfaces/Crayon.js
Labels: Feature, UI

#15340 Fixes some lambda stuff
  _maps/map_files/LambdaStation/dorms.dmm
  _maps/map_files/LambdaStation/lambda.dmm
Labels: Feature, Fix, Map Edit, Removal

#15351 removes the "REM" macro
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Refactor, Removal

#15300 Fixes racial blood colors.
  icons/effects/blood.dmi
Labels: Fix, Sprites

#15354 Nerf chonker in cuban pete arcade game
  code/game/machinery/computer/arcade/battle.dm
Labels: Balance/Rebalance

#15353 PubbyStation Fixes and Touch-ups aka SALT
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit, Removal

#15330 Dynamic messages admins if it fails to hijack.
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Administration

#15368 Makes ashwalkers not freeze to death on lavaland
  code/datums/atmosphere/planetary.dm
Labels: Fix

#15366 I forgor (Pubby thing)
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#15379 Makes regal rat require not being dead to use abilities
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
Labels: Fix

#15275 Spookystation (Ball Map) and Vector Cars
  _maps/_basemap.dm
  _maps/map_files/SpookyStation/SpookyStation.dmm
  _maps/map_files/SpookyStation/halloweenPersiWork.dm
  _maps/map_files/SpookyStation/job_changes.dm
  _maps/spookystation.dm
  _maps/spookystation.json
  code/game/objects/structures/fireplace.dm
  code/game/objects/structures/flora.dm
  code/game/turfs/closed.dm
  code/modules/holiday/halloween/bartholomew.dm
  code/modules/holiday/halloween/halloween.dm
  code/modules/holiday/halloween/jacqueen.dm
  code/modules/library/lib_items.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/vending/clothesmate.dm
  config/maps.txt
  icons/effects/weather_effects.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/vehicles.dmi
  modular_citadel/code/modules/eventmaps/Spookystation/JTGSZwork.dm
  modular_citadel/code/modules/eventmaps/Spookystation/Tick.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/Tock.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/areas.dmi
  modular_citadel/code/modules/eventmaps/Spookystation/basecaveloop.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/baseinsideloop.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/baseoutsideloop.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/caveloop1.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/caveloop2.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/caveloop3.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/caveloop4.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/clock32x49.dmi
  modular_citadel/code/modules/eventmaps/Spookystation/halloweenPersiWork.dm
  modular_citadel/code/modules/eventmaps/Spookystation/iconfile32.dmi
  modular_citadel/code/modules/eventmaps/Spookystation/iconfile64.dmi
  modular_citadel/code/modules/eventmaps/Spookystation/insideloop1.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/insideloop2.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/insideloop3.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/insideloop4.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/midnightchime.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/outsideloop1.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/outsideloop2.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/talltree128.dmi
  modular_citadel/code/modules/eventmaps/Spookystation/treefall.ogg
  modular_citadel/code/modules/eventmaps/Spookystation/woodchop.ogg
  modular_citadel/code/modules/vectorcrafts/vector_process.dm
  modular_citadel/code/modules/vectorcrafts/vectorcar_heads.dm
  modular_citadel/code/modules/vectorcrafts/vectorcraft.dm
  modular_citadel/code/modules/vectorcrafts/vectorvariants.dm
  sound/vehicles/boost.ogg
  sound/vehicles/boost_ready.ogg
  sound/vehicles/clutch_fail.ogg
  sound/vehicles/clutch_win.ogg
  sound/vehicles/high_eng.ogg
  sound/vehicles/low_eng.ogg
  sound/vehicles/norm_eng.ogg
  sound/vehicles/skid.ogg
  tgstation.dme
Labels: Feature, Map Edit, Sprites, Sound, Config Update

#15360 Emergency tgui fixing measures
  code/modules/client/client_procs.dm
Labels: Feature, Fix

#15320 Improvements to the reagent gun and brand new smart dart repeater. [Ready]
  code/modules/projectiles/ammunition/special/syringe.dm
  code/modules/projectiles/guns/misc/chem_gun.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/nodes/weaponry_nodes.dm
  icons/obj/guns/projectile.dmi
Labels: Feature, Sprites, Balance/Rebalance

#15384 Acid overlay no longer lingers after done
  code/datums/components/_component.dm
  code/datums/components/acid.dm
  code/game/atoms.dm
Labels: Fix, Code Improvement

#15383 Thins up the loot piles
  code/game/objects/structures/loot_pile.dm
Labels: Balance/Rebalance

#15382 Allows Clockwork cultists to create Cogscarabs.
  code/modules/antagonists/clockcult/clock_scriptures/scripture_applications.dm
  code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
Labels: Feature

#15381 Synthetics can now hook up their power cord to cells instead of relying on moth-esque code
  code/modules/power/cell.dm
  code/modules/surgery/organs/augments_arms.dm
Labels: Feature, Removal

#15377 Pubby Surgery + Loot Piles
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#15308 Adds search box on cwc slab
  tgui/packages/tgui/interfaces/ClockworkSlab.js
Labels: Feature, UI

#15389 Pubby Paramedical
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit

#15393 Donator - Adds Space Hoodie
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#14868 buildmode mapgen tool save [ready]
  code/__DEFINES/mapexporting.dm
  code/datums/components/storage/storage.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/buildmode/submodes/save_area.dm
  code/modules/mapexporting/mapexporter.dm
  code/modules/mining/machine_silo.dm
  tgstation.dme
Labels: Feature, Sprites, Sound, UI, Config Update, Github

#15376 Double beds
  code/__DEFINES/dye_keys.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/modules/mining/equipment/survival_pod.dm
  icons/obj/bedsheets.dmi
  icons/obj/lavaland/survival_pod.dmi
  icons/obj/objects.dmi
Labels: Feature, Fix, Sprites, Code Improvement

#15397 Allows toggling of Captain's female formal outfit's legs
  code/modules/clothing/under/jobs/command.dm
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
Labels: Sprites

#15396 Various Main Map Tweaks
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#15386 FestiveMap (Winter Ball 2021)
  _maps/festivestation.dm
  _maps/festivestation.json
  _maps/map_files/FestiveBall/FestiveStation.dmm
  _maps/map_files/FestiveBall/doorButtonOrganizer.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/ice_storm.dm
  code/game/area/areas/edina.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/fluff.dm
  code/modules/clothing/gloves/mittens.dm
  code/modules/holiday/halloween/jacqueen.dm
  code/modules/vehicles/vehicle_key.dm
  config/maps.txt
  icons/mob/radial.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/halloween_items.dmi
  icons/obj/sofaclean.dmi
  icons/turf/areas.dmi
  modular_citadel/code/modules/festive/32x64.dm
  modular_citadel/code/modules/festive/32x64icons.dmi
  modular_citadel/code/modules/festive/alleywaybricks.dmi
  modular_citadel/code/modules/festive/bigtree.dmi
  modular_citadel/code/modules/festive/blue_brick_wall.dmi
  modular_citadel/code/modules/festive/blue_brick_window.dmi
  modular_citadel/code/modules/festive/city_sign.dmi
  modular_citadel/code/modules/festive/cobblestone.dmi
  modular_citadel/code/modules/festive/festive_decals.dm
  modular_citadel/code/modules/festive/festive_notes.dm
  modular_citadel/code/modules/festive/festive_objects.dmi
  modular_citadel/code/modules/festive/grey_brick_wall.dmi
  modular_citadel/code/modules/festive/grey_brick_window.dmi
  modular_citadel/code/modules/festive/grey_panel_wall.dmi
  modular_citadel/code/modules/festive/privacy.dm
  modular_citadel/code/modules/festive/rails.dmi
  modular_citadel/code/modules/festive/red_brick_wall.dmi
  modular_citadel/code/modules/festive/red_brick_window.dmi
  modular_citadel/code/modules/festive/sidewalk.dmi
  modular_citadel/code/modules/festive/stairs.dmi
  modular_citadel/code/modules/festive/streetdecals.dmi
  modular_citadel/code/modules/festive/trainplatform.dmi
  modular_citadel/code/modules/festive/trainplatformedges.dmi
  modular_citadel/code/modules/festive/turfs.dm
  modular_citadel/code/modules/festive/wheelchair.dm
  modular_citadel/code/modules/festive/white_alleywaybricks.dmi
  modular_citadel/code/modules/festive/white_brick_wall.dmi
  modular_citadel/code/modules/festive/white_brick_window.dmi
  modular_citadel/code/modules/festive/wooden.dmi
  modular_citadel/code/modules/vectorcrafts/vectorcraft.dm
  modular_citadel/code/modules/vectorcrafts/vectortruck.dm
  tgstation.dme
Labels: Feature, Map Edit, Sprites, UI, Config Update

#15380 Block & Pellet wound pass
  code/datums/components/pellet_cloud.dm
  code/datums/elements/embed.dm
  code/game/objects/items/shields.dm
  code/modules/projectiles/projectile.dm
Labels: Fix, Balance/Rebalance
