Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-02, with the labels that each got.

#14113 fixes piggybacking initial offsets. Also, adds the ability to carry around pAIs, because this totally won't result in more metaclique drama.
  code/datums/components/riding.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/silicon/pai/pai.dm
  config/game_options.txt
Labels: Config Update, Feature

#13895 Restores speedup to meth and nuka cola
  code/modules/movespeed/modifiers/reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Balance/Rebalance, Test Merge Candidate

#14184 oops/speedmerge pls - fixes green esaber forward facing sprite
  icons/mob/inhands/weapons/swords_righthand.dmi
Labels: Fix, Sprites

#14132 MASSIVE SALT NERF
  code/modules/uplink/uplink_items/uplink_stealth.dm
Labels: Balance/Rebalance

#14155 Port of TG's "Auto Observe"
  code/__HELPERS/unsorted.dm
  code/datums/components/orbiter.dm
  code/game/atoms.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/orbit.dm
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/public/tgui.bundle.js
Labels: Feature, UI

#14170 Fixes KAs being broken by circuits
  code/modules/integrated_electronics/subtypes/weaponized.dm
Labels: Fix

#14172 Cell Charger Buffs
  code/game/machinery/cell_charger.dm
Labels: Balance/Rebalance

#14174 Meathook Adjustments
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Balance/Rebalance

#14183 dwarf facial hair is no longer randomised
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
Labels: Feature

#14188 i forgot a sprite
  icons/obj/clothing/accessories.dmi
Labels: Sprites

#14193 sanitizes id cards
  code/modules/modular_computers/file_system/programs/card.dm
Labels: Priority: CRITICAL

#14159 Fixes Alien Royals being able to ventcrawl
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
  code/modules/mob/living/carbon/alien/humanoid/queen.dm
Labels: Fix

#14182 i hate xenobiology players
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Priority: High, this isn't tested yet

#13890 ablative parry armwraps
  code/__DEFINES/dcs/signals.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mob/living/living_active_parry.dm
  code/modules/mob/living/living_blocking_parrying.dm
  code/modules/uplink/uplink_items/uplink_clothing.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Feature, Sprites

#13966 [Ready] Fixes and tweaks for the chemistry machine suite
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_heater.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  tgui/packages/tgui/interfaces/ChemDispenser.js
  tgui/packages/tgui/interfaces/ChemMaster.js
  tgui/public/tgui.bundle.js
Labels: Needs Review, UI

#14179 Signed language (Requested changes complete)
  code/__DEFINES/traits.dm
  code/datums/traits/good.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/language/signlanguage.dm
  code/modules/mob/living/carbon/say.dm
  code/modules/mob/living/say.dm
  tgstation.dme
Labels: Feature, Good First PR, Sprites

#14189 Diversify weapon sound
  code/game/objects/items/stacks/rods.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/rifles.dm
  sound/weapons/LaserSlugv3.ogg
  sound/weapons/ParticleBlaster.ogg
  sound/weapons/beam_sniper.ogg
  sound/weapons/grenadelaunch.ogg
  sound/weapons/gunshot_smg_alt.ogg
  sound/weapons/gunshotshotgunshot.ogg
  sound/weapons/lmgshot.ogg
  sound/weapons/magpistol.ogg
  sound/weapons/magrifle.ogg
  sound/weapons/noscope.ogg
  sound/weapons/plasma_cutter.ogg
  sound/weapons/revolvershot.ogg
  sound/weapons/rifleshot.ogg
  sound/weapons/rocketlaunch.ogg
Labels: Code Improvement, Removal, Sound, Tweak

#14196 sentient viruses can now infect synths and ipcs (fastest salt in the west)
  code/modules/antagonists/disease/disease_disease.dm
Labels: Balance/Rebalance

#14194 Adds clown waddle to clown shoes.
  code/modules/clothing/shoes/miscellaneous.dm
  html/changelog.html
  tgstation.dme
Labels: Feature

#14199 Boxstation disposals update
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Feature, Map Edit

#14195 Donator Item - NT Choker
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#14214 Clothing PR
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/suits.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature, Sprites

#14215 Added a config to disallow unreadied players from voting on modes
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/vote.dm
Labels: Config Update, Feature

#14216 corrects two persistent blood related issues
  code/game/objects/effects/decals/cleanable/humans.dm
  icons/effects/footprints.dmi
Labels: Fix, Sprites

#14208 sound PR oversights fix
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/items/weaponry.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  sound/weapons/woodbonk.ogg
Labels: Fix, Sound

#14205 Triples Warp Implant's cooldown
  code/game/objects/items/implants/implant_misc.dm
Labels: Balance/Rebalance

#14204 Removes the Power Sink Objective
  code/game/gamemodes/objective_sabotage.dm
Labels: Removal

#14203 makes the a.sterile mask no longer hide your face
  code/modules/clothing/masks/miscellaneous.dm
Labels: Tweak

#14202 Adds nanogel to the robodrobe
  code/modules/vending/wardrobes.dm
Labels: Tweak

#14201 Flechette Rifle/CX Shredder now work with wounds
  modular_citadel/code/modules/projectiles/guns/ballistic/rifles.dm
Labels: Sound

#14211 pickpocketing is now logged outside of hrefs
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Administration

#14218 Gives boxstation vault door actual vault door access
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Tweak

#14206 Nerfs VoG stun, knockdown, vomit. Removes sleep command.
  code/modules/surgery/organs/vocal_cords.dm
Labels: Removal

#14221 Random delta station fix
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Map Edit, Tweak

#14220 what atvs? - replaces the snowcabin ATVs with snowmobiles
  _maps/RandomZLevels/away_mission/SnowCabin.dmm
Labels: Balance/Rebalance, Map Edit

#14228 TGUI recompile
  tgui/public/tgui-common.chunk.js
  tgui/yarn.lock
Labels: Priority: CRITICAL, UI

#14223 changes a migration error to use log_game instead of message_admins
  code/modules/client/preferences_savefile.dm
Labels: Administration

#14166 energy bola nerf - reduced breakout time (6 sec -> 2.5), deletes on remove
  code/game/objects/items/handcuffs.dm
  code/modules/mob/living/carbon/carbon.dm
  icons/obj/items_and_weapons.dmi
Labels: Balance/Rebalance, Sprites

#14225 [hello if someone could fight the maintainers to take a look that'd be great] fixes durathread armor kits
  code/game/objects/items/armor_kits.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/_under.dm
Labels: Fix, Tweak

#14232 Fixes & Improves some antagpanel stuff
  code/modules/antagonists/clockcult/clockcult.dm
  code/modules/antagonists/cult/cult.dm
Labels: Administration, Fix

#14231 sigh
  code/modules/mob/living/carbon/alien/larva/larva.dm
Labels: Fix

#14207 Multilingual fix? (Has since been tested.)
  code/__DEFINES/language.dm
  code/datums/traits/good.dm
Labels: Code Improvement

#14192 Ports *pain emote from CM13
  html/changelog.html
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/sound/voice/human_female_pain_1.ogg
  modular_citadel/sound/voice/human_female_pain_2.ogg
  modular_citadel/sound/voice/human_female_pain_3.ogg
  modular_citadel/sound/voice/human_male_pain_1.ogg
  modular_citadel/sound/voice/human_male_pain_2.ogg
  modular_citadel/sound/voice/human_male_pain_3.ogg
  modular_citadel/sound/voice/human_male_pain_rare.ogg
  modular_citadel/sound/voice/pain emote credits.txt
Labels: Feature, Sound

#14233 About unarmed parrying..
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Balance/Rebalance, Fix

#14227 CLOAK, PARKA, COLORFUL SHOES
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/neck.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/cloaks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/code/modules/client/loadout/neck.dm
  modular_citadel/code/modules/client/loadout/shoes.dm
  modular_citadel/code/modules/client/loadout/suit.dm
Labels: Feature, Fix, Sprites

#14224 Makes clockies yell less
  code/modules/antagonists/clockcult/clock_scriptures/scripture_applications.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_drivers.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_scripts.dm
Labels: Balance/Rebalance

#14241 fixes href logging prefiltering of chat pings, removes extraneous newlines from verbose tgui logging
  code/__HELPERS/_logging.dm
  code/controllers/configuration/entries/logging.dm
  code/modules/client/client_procs.dm
  tgstation.dme
Labels: Config Update, Priority: CRITICAL, Removal

#14243 logging defaults to on instead of off, patches a few holes
  code/controllers/configuration/entries/general.dm
  code/controllers/configuration/entries/logging.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/pool/pool_controller.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/rags.dm
  code/modules/surgery/dental_implant.dm
Labels: Administration, Config Update, Priority: CRITICAL

#14096 makes people on the ground punch less hard. completely removes punch rng miss.
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance, Removal

#14140 fixes chat highlighting not working (literally) half the time
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/public/tgui-panel.bundle.js
Labels: Fix, UI

#14245 adds config entry for sprint removal that works prettier than just setting sprint speed to 0
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/configuration/entries/game_options.dm
  code/modules/mob/living/living_sprint.dm
  code/modules/mob/living/silicon/robot/robot_sprint.dm
  modular_citadel/icons/ui/screen_clockwork.dmi
  modular_citadel/icons/ui/screen_midnight.dmi
  modular_citadel/icons/ui/screen_operative.dmi
  modular_citadel/icons/ui/screen_plasmafire.dmi
  modular_citadel/icons/ui/screen_slimecore.dmi
Labels: Config Update

#14244 streamlining botany logging, adds english_list_assoc
  code/__HELPERS/_lists.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/seeds.dm
Labels: Administration

#14186 [READY][PORT] Codename: Blue Eyes White Jumpsuit, the Citadel TCG. Part 1
  _maps/RandomRuins/AnywhereRuins/golem_ship.dmm
  _maps/RandomRuins/IceRuins/icemoon_surface_hotsprings.dmm
  _maps/RandomRuins/IceRuins/icemoon_surface_lust.dmm
  _maps/RandomRuins/IceRuins/icemoon_surface_mining_site.dmm
  _maps/RandomRuins/IceRuins/icemoon_underground_wendigo_cave.dmm
  _maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_dead_ratvar.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hierophant.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_ufo_crash.dmm
  _maps/RandomRuins/SpaceRuins/abandonedzoo.dmm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomRuins/SpaceRuins/gondolaasteroid.dmm
  _maps/RandomRuins/SpaceRuins/mechtransport.dmm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/persistence/_persistence.dm
  code/datums/components/storage/concrete/tcg.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/cargo/packs/costumes_toys.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/tcg/cards.dm
  code/modules/tcg/pack_1.dm
  code/modules/tcg/pack_nuclear.dm
  code/modules/tcg/pack_star.dm
  code/modules/uplink/uplink_items/uplink_badass.dm
  code/modules/vending/games.dm
  icons/mob/radial.dmi
  icons/obj/tcg/misc.dmi
  icons/obj/tcg/pack_1.dmi
  icons/obj/tcg/pack_nuclear.dmi
  icons/obj/tcg/pack_star.dmi
  tgstation.dme
Labels: Feature, Map Edit, Needs Review, Sprites

#14236 Removes prevent from leaving alive, maroon objective
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/traitor/classes/assassin.dm
  code/modules/antagonists/traitor/classes/human.dm
  code/modules/antagonists/traitor/classes/subterfuge.dm
Labels: Removal

#14254 Messages admins of certain holodeck actions
  code/modules/holodeck/computer.dm
Labels: Administration

#14255 Disallows specific fermichem to deal liver damage
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
Labels: Tweak

#14252 spellchecks priviledge --> privilege
  code/__DEFINES/robots.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/mob_helpers.dm
  code/modules/power/apc.dm
  html/changelogs/.all_changelog.yml
Labels: Grammar and Formatting

#14248 Fix for floorbots not placing a plate before placing a floor.
  code/modules/mob/living/simple_animal/bot/floorbot.dm
Labels: Fix

#14239 well that's what i get for trusting my own code - makes golem GPSes start off, but actually this time
  code/datums/components/gps.dm
  code/game/objects/items/devices/gps.dm
Labels: Fix

#14259 staring into pierced realities is now logged
  code/modules/antagonists/eldritch_cult/eldritch_effects.dm
Labels: Administration

#14249 Set buzz fuzz's addiction threshold to fit the comment
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Fix

#14256 Polychromic Pants & Jacket
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/pants.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature, Sprites, Tweak

#14262 stops people using Message All on PDAs when their cartridge doesn't allow it
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#14251 Massive synthflesh buff
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#14246 Multilingual conditions fix.
  code/modules/mob/living/carbon/say.dm
  code/modules/mob/living/say.dm
Labels: Fix

#14261 [READY] Small QoL changes to TCG
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/persistence/_persistence.dm
  code/game/machinery/cryopod.dm
  code/modules/cargo/packs/costumes_toys.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/tcg/cards.dm
Labels: Needs Review, Tweak

#14273 chaplain vampires won't burn in their own chapel now
  code/modules/mob/living/carbon/human/species_types/vampire.dm
Labels: Fix

#14272 Port of "removes unnecessary %"
  code/modules/hydroponics/seed_extractor.dm
Labels: Removal, Tweak

#14271 Revert "Fix for floorbots not placing a plate before placing a floor."
  code/modules/mob/living/simple_animal/bot/floorbot.dm
Labels: Revert

#14263 the one where i make anomaly announcements and brand intelligence always announce
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/shuttle_loan.dm
Labels: Balance/Rebalance

#14260 fixes the 'undeleted query' message at the start of every shift
  modular_citadel/code/modules/mentor/mentor.dm
Labels: Fix

#14258 Raises Space Vine Population Requirement
  code/modules/events/spacevine.dm
Labels: Balance/Rebalance

#14269 More arousal logging; adds back aphro/nympho
  code/__DEFINES/traits.dm
  code/datums/traits/neutral.dm
  code/modules/arousal/arousal.dm
  code/modules/arousal/genitals.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/vending/kinkmate.dm
  modular_citadel/code/datums/status_effects/chems.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Administration, Feature

#14235 Jungle gateway nerf and touch ups: ape edition
  _maps/RandomZLevels/away_mission/jungleresort.dmm
  code/modules/awaymissions/mission_code/jungleresort.dm
Labels: Balance/Rebalance, Feature, Fix, Map Edit, Tweak

#14264 Pain emote is now added to getting wounded! As well as more pain sounds
  code/datums/wounds/_wounds.dm
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/sound/voice/human_female_scream_2.ogg
  modular_citadel/sound/voice/human_female_scream_3.ogg
  modular_citadel/sound/voice/human_female_scream_4.ogg
  modular_citadel/sound/voice/human_male_scream_1.ogg
  modular_citadel/sound/voice/human_male_scream_2.ogg
  modular_citadel/sound/voice/human_male_scream_3.ogg
  modular_citadel/sound/voice/human_male_scream_4.ogg
Labels: Feature, Sound

#14280 prioritises mobs with clients in the banning panel
  code/modules/admin/topic.dm
Labels: Fix

#14286 Donator Item - Metal Mask
  icons/mob/clothing/custom_w.dmi
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#14282 >put "spawn a new copy of this" in the garbage collection logic of a mob >that seems like it'll cause problems, huh.
  code/modules/holiday/halloween/jacqueen.dm
Labels: Priority: CRITICAL

#14253 Hyperblade restored to uplink
  code/game/objects/items/melee/energy.dm
  code/modules/uplink/uplink_items/uplink_dangerous.dm
Labels: Balance/Rebalance, Feature

#14268 alternatively, replaces the cube sentinel spawn with an actual simplemob sentinel that drops a carbon sentinel body on death so you still get to run this to the ground without being able to be a literal alien queen
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
Labels: Balance/Rebalance

#14299 Fixes all crowbars openning powered airlocks
  code/game/machinery/doors/airlock.dm
  code/game/objects/items.dm
  code/game/objects/items/tools/crowbar.dm
Labels: Fix

#14294 Once again fixes objective generation
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/traitor/classes/subterfuge.dm
Labels: Fix

#14303 Adds state check callbacks to machine frame tool use
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/constructable_frame.dm
Labels: Code Improvement

#14305 sam dennison you exploit hoarding banana i will shove a barrel of ghost peppers down your throat for this crime
  code/game/objects/items/holy_weapons.dm
Labels: Fix

#14314 Fixes misaligned sprite for the strange metal mask donator item
  icons/mob/clothing/custom_w.dmi
Labels: Sprites

#14285 makes tcg cards and binders small and thus easier to store for persistence
  code/modules/tcg/cards.dm
Labels: Tweak

#14283 buhhh lingfist nerf 3am webedit
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance

#14281 parrying nerf/pugilism buff
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/living_active_parry.dm
Labels: Balance/Rebalance

#14300 Allows Sentient Disease to purchase most abilities from the start.
  code/modules/antagonists/disease/disease_abilities.dm
Labels: Balance/Rebalance

#14289 Botany Pass II: How the hell did it take me this long to notice that these things aren't functioning????
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
Labels: Feature

#14316 Makes tablets not permacontam.
  code/modules/modular_computers/computers/item/computer.dm
Labels: Tweak

#14325 Fixes toxin healing for slimes in heretic related stuff
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/eldritch_cult/knowledge/rust_lore.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#14321 Makes polychromic windbreaker's message not be nonsense
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/toggles.dm
Labels: Code Improvement, Fix

#14311 Body rejuvenation automatically repeats until completely healed
  code/modules/surgery/advanced/toxichealing.dm
Labels: Tweak

#14293 [READY] TCG fixes
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/persistence/_persistence.dm
  code/modules/tcg/cards.dm
Labels: Fix, Needs Review

#14340 Jungle Gateway Quickfix
  _maps/RandomZLevels/away_mission/jungleresort.dmm
Labels: Fix, Map Edit
