Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2021-07, with the labels that each got.

#14903 fixes and rewrites sprays
  code/game/objects/effects/decals/misc.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Fix, Test Merge Candidate

#14906 [Very Ready] Axolotl Ear [Fix]
  modular_citadel/icons/mob/mam_ears.dmi
Labels: Fix

#14909 Changes turrets back to check for stamcrit instead of mobility_use
  code/game/machinery/porta_turret/portable_turret.dm
Labels: Fix

#14913 Tweaks to auxmos compile on linux
  dependencies.sh
  tools/build/build.sh
  tools/tgs4_scripts/PreCompile.sh
Labels: Tools

#14914 Optimizes the slowest Life proc in the game to make it not do 81x as much work as it needs to
  code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
Labels: Fix

#14915 [Actually ready] ONE PIXEL AAA (or: I fixed a sprite that was previously not even visible ingame)
  modular_citadel/icons/mob/mam_ears.dmi
Labels: Fix

#14833 TG Resprite Compendium Atomization Project | Episode Eight: The Finale: TG Tools
  _maps/RandomRuins/SpaceRuins/shuttlerelic.dmm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/wirecutters.dm
  code/modules/ruins/spaceruin_code/caravanambush.dm
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/clothing/belt_overlays.dmi
  icons/obj/device.dmi
  icons/obj/nuke_tools.dmi
  icons/obj/tools.dmi
Labels: Fix, Map Edit, Sprites

#14925 funding button
  .github/FUNDING.yml
Labels: Github

#14927 Fixes golem / plasmaman species color
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#14928 AAAAAAAAAH
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit

#14929 Adds another wall to the AM engine
  _maps/RandomRuins/StationRuins/Box/Engine/engine_am.dmm
Labels: Feature, Map Edit

#14932 Makes it so AIs can plasmaflood in pubby
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#14842 [Ready] Wheelchair Sprite Rollback + Motorized Hoverchairs
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/modules/vehicles/motorized_wheelchair.dm
  code/modules/vehicles/wheelchair.dm
  icons/obj/vehicles.dmi
  sound/effects/chairwhoosh.ogg
  tgstation.dme
Labels: Sound, Sprites

#14936 fixes to the new survival pod.
  _maps/templates/shelter_5.dmm
Labels: Balance/Rebalance, Fix, Map Edit

#14922 Removes causes_dirt_buildup_on_floor and replaces it with just making humans do that in their Move
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_movement.dm
Labels: Refactor, Removal

#14918 Pubby mirror for the captains office
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#14935 Meta station toxins
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit

#14921 Componentizes acid
  code/controllers/subsystem/acid.dm
  code/datums/components/acid.dm
  code/game/objects/effects/alien_acid.dm
  code/game/objects/items.dm
  code/game/objects/obj_defense.dm
  code/game/objects/objs.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
  tgstation.dme
Labels: Refactor

#14942 [S] Makes it so that moving your mouse over mobs doesn't lag the server
  code/modules/tooltip/tooltip.dm
Labels: Fix

#14944 Fix tiny oopsies
  tools/tgs4_scripts/PreCompile.sh
Labels: Tools

#14945 fixes photosynthesis stopping nutrition going past well fed from non-photosynthesis means
  code/datums/elements/photosynthesis.dm
Labels: Fix

#14941 Vore additions/update
  code/__DEFINES/voreconstants.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/tgui/states/vorepanel.dm
  code/modules/tgui/tgui_alert.dm
  code/modules/vore/eating/bellymodes.dm
  code/modules/vore/eating/living.dm
  code/modules/vore/eating/vorepanel.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/VorePanel.js
Labels: Code Improvement, Feature, Refactor, UI

#14933 [PORT] Stripping a disconnected player will tell them when they come back (+Lazynull)
  code/__DEFINES/inventory.dm
  code/__HELPERS/_lists.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/login.dm
  code/modules/mob/living/living.dm
Labels: Feature

#14930 Ports Breaking a mirror now gives you a bad omen
  code/game/objects/structures/mirror.dm
Labels: Feature

#14926 Human leather hats
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/clothing/head/misc.dm
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites

#14943 Custom Kegs
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/hydroponics/fermenting_barrel.dm
  icons/obj/objects.dmi
Labels: Feature, Sprites

#14949 Port of "[s] Fixes a major memory leak in shuttle code (KILO IS FREE)"
  code/game/turfs/change_turf.dm
Labels: Fix

#14947 Crafting menu cleaning up
  code/__DEFINES/construction.dm
  code/datums/components/crafting/craft.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
Labels: Code Improvement, Fix

#14946 anthros can now select the cow tail
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
Labels: Fix

#14952 fixes boxstation line endings
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Priority: CRITICAL

#14874 slight baton powercreep tweak (5 --> 3.5 seconds rmb cooldown, 35 --> 40 damage)
  code/game/objects/items/stunbaton.dm
Labels: Balance/Rebalance

#14960 Some hallucination tweaks
  code/modules/flufftext/Hallucination.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Balance/Rebalance, Fix

#14910 Boxstation rooms 'n fixes
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Balance/Rebalance, Feature, Fix, Map Edit

#14966 Quickly removes a transform button that does nothing on the vore panel
  code/modules/vore/eating/vorepanel.dm
Labels: Removal

#14967 Makes HE pipe min temp diff 0.01 instead of 20
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
Labels: Balance/Rebalance

#14964 Round 1 of initial fixes/changes for OmegaStation.
  _maps/map_files/OmegaStation/OmegaStation.dmm
  tgstation.dme
Labels: Map Edit

#14879 [Review/Testmerge] Icemoon Ruins but on Lavaland!
  _maps/RandomRuins/LavaRuins/lavaland_surface_bathhouse.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_engioutpost.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hotsprings.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_library.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_lust.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_mining_site.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_wrath.dmm
  code/datums/ruins/lavaland.dm
Labels: Balance/Rebalance, Feature, Map Edit

#14957 Pubby Deco
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#14972 Random Boxstation Fixes (Space edition)
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit
