Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-06, with the labels that each got.

#15639 Mech movement power use debug pass
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/gygax.dm
  code/modules/vehicles/mecha/combat/medigax.dm
  code/modules/vehicles/mecha/combat/phazon.dm
  code/modules/vehicles/mecha/combat/reticence.dm
  code/modules/vehicles/mecha/medical/odysseus.dm
  code/modules/vehicles/mecha/working/ripley.dm
Labels: Fix, Test Merge Candidate

#15650 optimises quirks
  code/datums/traits/_quirk.dm
  code/datums/traits/good.dm
  code/datums/traits/negative.dm
Labels: Mechanic

#15655 Kitsune masks
  code/modules/clothing/masks/miscellaneous.dm
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/mask_muzzled.dmi
  icons/obj/clothing/masks.dmi
  modular_citadel/code/modules/client/loadout/mask.dm
Labels: Sprites, Content Expansion

#15641 Some gas balancing/rearranging (nitryl nerf)
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/auxgm.dm
  code/modules/cargo/exports/large_objects.dm
  code/modules/surgery/organs/lungs.dm
Labels: Balance/Rebalance, Refactor, Test Merge Candidate

#15648 Pizza rate limiting (prevents a cheesy exploit vector)
  code/modules/food_and_drinks/pizzabox.dm
Labels: Salt

#15647 Boxstation - fixes the incinerator's sensors simply not working
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Fix, Map Edit

#15634 Jukebox refresh - Jukebox queue, working volume knob, emagging, preliminary multiz support, and more!
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/LambdaStation/dorms.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  code/__DEFINES/logging.dm
  code/__HELPERS/_logging.dm
  code/__HELPERS/roundend.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/logging.dm
  code/controllers/subsystem/jukeboxes.dm
  code/game/atoms.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/dance_machine.dm
  code/game/sound.dm
  code/game/world.dm
  code/modules/research/bepis.dm
  code/modules/surgery/organs/ears.dm
  code/modules/vending/_vending.dm
  config/entries/logging.txt
  tgui/packages/tgui/interfaces/Jukebox.js
Labels: Map Edit, UI, Config Update, Mechanic

#15632 Bot refresh - Makes bot output channels configurable, makes the bot capable of pinging the reboot role
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/bot.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/ticker.dm
  code/modules/mob/living/simple_animal/parrot.dm
  config/config.txt
  config/entries/bot.txt
  config/entries/general.txt
  tgstation.dme
Labels: Config Update

#15646 Fixes Omegastation's airmix filter being flipped by default
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit

#15657 Fixes solar panel sprites by removing dirs from the iconstate
  goon/icons/obj/power.dmi
Labels: Fix

#15651 adds paper skin and glass bones quirks
  code/__DEFINES/traits.dm
  code/datums/traits/negative.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
Labels: Mechanic

#15652 Updates the title screen
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/dcs/signals/signals_subsystem.dm
  code/__DEFINES/layers_planes.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/clients.dm
  code/_onclick/hud/new_player.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/title.dm
  code/game/turfs/closed.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/dead/new_player/new_player.dm
  icons/blanks/32x32.dmi
  icons/blanks/96x96.dmi
  icons/blanks/blank_title.png
  icons/default_title.dmi
  icons/hud/lobby/background.dmi
  icons/hud/lobby/bottom_buttons.dmi
  icons/hud/lobby/character_setup.dmi
  icons/hud/lobby/join.dmi
  icons/hud/lobby/observe.dmi
  icons/hud/lobby/poll_overlay.dmi
  icons/hud/lobby/ready.dmi
  icons/runtime/README.md
  icons/runtime/default_title.dmi
  icons/runtime/tcg/default.dmi
  icons/runtime/tcg/xenos.dmi
  tgstation.dme
  tools/deploy.sh
Labels: Map Edit, Sprites, Tools, Refactor

#15658 Fixes a bug in admin vote deobfuscation
  code/controllers/subsystem/vote.dm
Labels: Fix

#15659 polychromic maid outfit + polychromic accessory support
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/accessories.dm
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/neck.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/backpack.dm
  modular_citadel/code/modules/client/loadout/gloves.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/neck.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Sprites, Mechanic

#15640 Updates some pulling and pushing
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_movement.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_living.dm
  code/__DEFINES/movement.dm
  code/modules/mob/living/living.dm
  tgstation.dme
Labels: Refactor

#15662 Fully restores the functionality of audiovisual redirection
  code/datums/components/virtual_reality.dm
  code/game/sound.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
Labels: Fix

#15656 Animation refresh - Fully restores animations broken by BYOND updates, some light animation-related tweaks, and more
  code/__HELPERS/matrices/transform_matrix.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/radial.dm
  code/_onclick/item_attack.dm
  code/datums/chatmessage.dm
  code/datums/components/bouncy.dm
  code/datums/components/storage/storage.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/items/pneumaticCannon.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
  code/modules/mob/living/carbon/alien/larva/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/update_icons.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/guns/misc/syringe_gun.dm
  modular_citadel/code/game/objects/cit_screenshake.dm
  tgstation.dme
Labels: Fix, Code Improvement

#15669 Fix strip_mod and strip_silence
  code/datums/elements/strippable.dm
Labels: Fix

#15674 Rebalancing QCD matter a bit
  code/__DEFINES/reactions.dm
  code/__DEFINES/research.dm
  code/game/machinery/doppler_array.dm
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/research/techweb/_techweb.dm
Labels: Balance/Rebalance

#15679 Fixes Families (thanks Hardsync)
  code/_rendering/atom_huds/atom_hud.dm
  code/modules/antagonists/gang/gang.dm
  code/modules/vehicles/mecha/combat/five_stars.dm
  tgstation.dme
Labels: Fix

#15663 Blockquotes for chat; Prettier examine text and more!
  code/datums/components/embedded.dm
  code/datums/components/mood.dm
  code/datums/wounds/_scars.dm
  code/datums/wounds/burns.dm
  code/game/atoms.dm
  code/game/machinery/iv_drip.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/antagonists/clockcult/clock_mobs.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/login.dm
  code/modules/mob/living/silicon/ai/examine.dm
  code/modules/mob/living/silicon/examine.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/mob.dm
  tgui/packages/tgui-panel/styles/components/Chat.scss
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: UI, Mechanic

#15664 Minimap Refresh - higher detail, JS fixes, pixel-perfect scaling, and more!
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/area/areas/ruins/_ruins.dm
  code/game/objects/objs.dm
  code/modules/mapping/minimaps.dm
  code/modules/power/solar.dm
Labels: Fix, Mechanic

#15673 User-friendly colormates - adds HSV coloration to colormates! (and more)
  code/__HELPERS/matrices/color_matrix.dm
  code/game/machinery/colormate.dm
  tgui/packages/tgui/interfaces/Colormate.js
Labels: UI, Mechanic

#15677 Vocal barks - Fully customizable noises for talking!
  code/__DEFINES/DNA.dm
  code/__DEFINES/preferences.dm
  code/__DEFINES/say.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/bark.dm
  code/datums/dna.dm
  code/game/atoms_movable.dm
  code/game/machinery/_machinery.dm
  code/game/say.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/plushie.dm
  tgstation.dme
Labels: Fix, Mechanic

#15675 Adds a search box and candystripes to Vending machines (all of them)
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: UI, Quality of Life, Mechanic

#15680 Fixes jukebox audio not coming through containers
  code/controllers/subsystem/jukeboxes.dm
Labels: Fix

#15683 shims storage to work properly until we can rewrite to atom storage
  code/datums/components/storage/ui.dm
Labels: Test Merge Candidate

#15693 Fixes some minor bits of code
  code/datums/components/crafting/glassware/glassware.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/modules/admin/admin_verbs.dm
  code/modules/hydroponics/grown/cannabis.dm
Labels: Fix, Grammar and Formatting, Code Improvement

#15695 Changing the range on Dynamic Days
  code/modules/holiday/dynamic.dm
Labels: Removal

#15676 HoS plate carrier
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/suit_digi.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites, Mechanic

#15692 Lingblood tweak - Increases the default value for ling ability loudness to 0.5
  code/modules/antagonists/changeling/changeling_power.dm
Labels: Balance/Rebalance
