Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-04, with the labels that each got.

#15578 Fixes pathfinding not checking diagonal passability properly.
  code/__HELPERS/path.dm
  code/game/machinery/doors/firedoor.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
Labels: Fix

#15576 Fix recycler runtime
  code/game/machinery/recycler.dm
Labels: Fix

#15565 Custom statues and sculpting changes.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
  _maps/shuttles/emergency_discoinferno.dmm
  code/_onclick/hud/radial.dm
  code/controllers/subsystem/materials.dm
  code/datums/components/squeak.dm
  code/datums/elements/art.dm
  code/datums/progressbar.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/structures/statues.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_tools.dm
  code/modules/ruins/lavalandruin_code/elephantgraveyard.dm
  icons/obj/statue.dmi
  sound/items/handling/screwdriver_drop.ogg
  sound/items/handling/screwdriver_pickup.ogg
Labels: Map Edit, Sprites, Sound, Mechanic

#15586 Fixes the changelogs being absolutely deleted only
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/compile_changelogs.yml
  html/changelogs/example.yml
  tgui/packages/tgui/interfaces/Changelog.js
  tools/WebhookProcessor/github_webhook_processor.php
  tools/ci/check_changelogs.sh
  tools/ss13_genchangelog.py
Labels: Fix, Tools, UI, Github

#15582 Fixes bots trying to path through dense corners.
  code/__HELPERS/path.dm
Labels: Fix

#15584 Stasis beds
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FestiveBall/FestiveStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/time.dm
  code/controllers/subsystem/traumas.dm
  code/controllers/subsystem/vis_overlays.dm
  code/datums/status_effects/debuffs.dm
  code/game/machinery/stasis.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  icons/obj/machines/stasis.dmi
  tgstation.dme
Labels: Map Edit, Sprites, Removal, Mechanic

#15589 Quickly fixes medigax before anyone notices
  code/modules/vehicles/mecha/mecha_construction_paths.dm
Labels: Fix

#15591 Fixes mechs (again)
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/mecha_actions.dm
  code/modules/vehicles/mecha/mecha_construction_paths.dm
  code/modules/vehicles/mecha/working/ripley.dm
Labels: Fix

#15053 Adds carcinisoprojection jelly, a limb regrowth chem that is made from slime mutation toxin & blood
  code/datums/diseases/crabcancer.dm
  code/datums/mood_events/generic_negative_events.dm
  code/modules/cargo/bounties/reagent.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/surgery/bodyparts/helpers.dm
  tgstation.dme
Labels: Feature

#15597 Progressbars no longer stay after completing/failing their task.
  code/__HELPERS/do_after.dm
  code/datums/components/storage/concrete/rped.dm
  code/datums/components/storage/storage.dm
  code/datums/status_effects/buffs.dm
  code/game/atoms.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/clockcult/clock_scripture.dm
  code/modules/vehicles/secway.dm
Labels: Fix

#15593 Makes auxmos do fires on Linux
  code/__DEFINES/research.dm
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Fix

#15588 Fixes saving testicle shapes
  code/modules/client/preferences_savefile.dm
Labels: Fix

#15590 Adds sound effects to surgeries
  code/modules/surgery/advanced/brainwashing.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/surgery/advanced/pacification.dm
  code/modules/surgery/advanced/revival.dm
  code/modules/surgery/amputation.dm
  code/modules/surgery/brain_surgery.dm
  code/modules/surgery/burn_dressing.dm
  code/modules/surgery/cavity_implant.dm
  code/modules/surgery/coronary_bypass.dm
  code/modules/surgery/healing.dm
  code/modules/surgery/implant_removal.dm
  code/modules/surgery/lobectomy.dm
  code/modules/surgery/mechanic_steps.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organic_steps.dm
  code/modules/surgery/surgery_step.dm
  sound/items/taperecorder/tape_flip.ogg
  sound/items/taperecorder/taperecorder_close.ogg
  sound/items/taperecorder/taperecorder_hiss_mid.ogg
  sound/items/taperecorder/taperecorder_hiss_start.ogg
  sound/items/taperecorder/taperecorder_open.ogg
  sound/items/taperecorder/taperecorder_play.ogg
  sound/items/taperecorder/taperecorder_print.ogg
  sound/items/taperecorder/taperecorder_stop.ogg
  sound/surgery/cautery1.ogg
  sound/surgery/cautery2.ogg
  sound/surgery/hemostat1.ogg
  sound/surgery/organ1.ogg
  sound/surgery/organ2.ogg
  sound/surgery/retractor1.ogg
  sound/surgery/retractor2.ogg
  sound/surgery/saw.ogg
  sound/surgery/scalpel1.ogg
  sound/surgery/scalpel2.ogg
Labels: Sound, Content Expansion

#15343 Ports Automatic Deadminning from TG
  code/__DEFINES/preferences.dm
  code/controllers/configuration/entries/admin.dm
  code/controllers/subsystem/job.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/living/silicon/login.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/login.dm
  config/entries/admin.txt
Labels: Feature, Config Update

#15604 trashcan quirk now uses correct grammar
  code/datums/elements/trash.dm
Labels: Grammar and Formatting

#15603 Some weird high-temperature reactions (including: absolute hot)
  code/__DEFINES/atmospherics.dm
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Mechanic

#15602 Allow planets to have fuel-based atmospheres
  code/__DEFINES/mobs.dm
  code/datums/atmosphere/planetary.dm
  code/game/objects/effects/effect_system/effects_foam.dm
  code/modules/atmospherics/auxgm/breathing_classes.dm
  code/modules/atmospherics/machinery/airalarm.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/surgery/organs/lungs.dm
Labels: Mechanic

#15594 Makes stasis beds *slightly* less hated
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FestiveBall/FestiveStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
  _maps/map_files/generic/CentCom.dmm
  code/game/machinery/stasis.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/designs/machine_desings/machine_designs_engi.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
Labels: Fix, Map Edit, Balance/Rebalance, Refactor, Mechanic
