Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-02, with the labels that each got.

#15490 Tweenty --> Twenty
  code/game/objects/structures/watercloset.dm
Labels: Grammar and Formatting

#14804 [Ready] pokerchip set donator item
  icons/obj/custom.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
Labels: Sprites

#15488 Get out of the way, you weaboos. The slimes were here first.
  code/modules/language/arachnid.dm
  code/modules/language/dwarven.dm
  code/modules/language/neokanji.dm
  code/modules/surgery/organs/tongue.dm
Labels: Fix

#15466 Ashwalker Update
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/gamemodes/objective.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/ashwalker/ashwalker.dm
  code/modules/awaymissions/corpse.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/ruins/objects_and_mobs/ash_walker_den.dm
  tgstation.dme
Labels: Feature, Fix, Balance/Rebalance

#15494 TGUIzes the Custom Shuttle
  code/modules/shuttle/custom_shuttle.dm
  tgui/packages/tgui/interfaces/CustomShuttleConsole.js
Labels: Feature, UI

#15493 Ports Simplebot TGUI conversion
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/honkbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/bot/secbot.dm
  tgui/packages/tgui/interfaces/SimpleBot.tsx
Labels: Feature, UI, Quality of Life

#15491 Ports TGUI for autolathe
  code/game/machinery/autolathe.dm
  tgui/packages/tgui/interfaces/Autolathe.js
Labels: Feature, UI

#15485 Removes layer from /atom/movable/screen
  code/_onclick/hud/screen_objects.dm
Labels: Fix, Removal

#15480 Allows you to cancel actions
  code/modules/keybindings/keybind/living.dm
Labels: Feature

#15448 literally also just makes it so IPCs can have winges
  code/modules/mob/living/carbon/human/species_types/ipc.dm
Labels: Feature

#15444 Literally just makes it so slimes can have (decorative) wings.
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Feature

#15484 Space Adaptation nulls low-pressure cooling penalties of passive cooling for Synthetics.
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/mutations/space_adaptation.dm
  code/modules/mob/living/carbon/life.dm
Labels: Balance/Rebalance

#15487 Fixes / nerfs stabilized orange extract temp adjustments and tweaks its effects on Synthetics
  code/__DEFINES/atmospherics.dm
  code/modules/mob/living/carbon/human/species_types/anthropomorph.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Balance/Rebalance

#15482 Ports Balloon Alert from TG
  code/__DEFINES/layers_planes.dm
  code/modules/balloon_alert/balloon_alert.dm
  code/modules/reagents/reagent_containers.dm
Labels: Quality of Life

#15499 Snaps "Convert Lineendings"
  .github/workflows/compile_changelogs.yml
Labels: Fix, Github

#15456 silly proof of concept item
  code/game/objects/items/summon.dm
  icons/effects/summon.dmi
  tgstation.dme
Labels: Sprites

#15504 Re-adds the admin button to let them exempt players from job exp requirements.
  code/modules/admin/topic.dm
  code/modules/jobs/job_report.dm
Labels: Administration

#15507 fixes linter errors
  code/__HELPERS/type2type.dm
  code/datums/brain_damage/severe.dm
  code/datums/diseases/dna_spread.dm
  code/game/machinery/requests_console.dm
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
  code/modules/hydroponics/hydroponics_chemreact.dm
  code/modules/mob/mob_helpers.dm
  code/modules/power/singularity/singularity.dm
  code/modules/ruins/lavalandruin_code/elephantgraveyard.dm
  code/modules/surgery/advanced/lobotomy.dm
  code/modules/vending/_vending.dm
  modular_citadel/code/modules/eventmaps/Spookystation/JTGSZwork.dm
Labels: Priority: High

#15359 adds polychromic clown outfit and mask
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/mask.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Feature, Sprites

#15512 Readds content-requiring-prior-approval section in contributing.md (and tweaks it lightly!)
  .github/CONTRIBUTING.md
Labels: Github

#15513 Fixes the linux auto-compile
  tools/tgs4_scripts/PreCompile.sh
Labels: Fix, Priority: High, Tools

#15510 Omega Station Fixes/Tweaks
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit, Removal, Mechanic

#15515 Makes reinforced plasma glass windows buildable
  code/game/objects/structures/window.dm
Labels: Fix

#15414 TG wing ports with some Citadel additions. All species can now use the flight potion and grow (unique) wings.
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/species.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/angel.dm
  code/modules/mob/living/carbon/human/species_types/anthropomorph.dm
  code/modules/mob/living/carbon/human/species_types/arachnid.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/carbon/human/species_types/xeno.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  icons/mob/wings.dmi
  icons/mob/wings_functional.dmi
  tgstation.dme
Labels: Feature, Sprites, Test Merge Candidate

#15516 fixes parallax whitifier applying when parallax is disabled
  code/_rendering/parallax/parallax_holder.dm
Labels: Sprites

#15521 Fixes targets
  code/game/objects/items/shooting_range.dm
  code/game/objects/structures/target_stake.dm
Labels: Fix

#15519 More Omega
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit, Removal, Mechanic

#15514 adds snake coiling
  code/__DEFINES/dcs/signals.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/legs_and_taurs.dm
  code/modules/mob/living/carbon/human/innate_abilities/coiling.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_mobility.dm
  icons/mob/actions/actions_snake.dmi
  modular_citadel/icons/mob/mam_taur.dmi
  tgstation.dme
Labels: Sprites, Mechanic

#15524 Fixes siphoning vents to be labeled right
  tgui/packages/tgui/interfaces/common/AtmosControls.js
Labels: UI

#15527 Omega Solars + two things
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit, Mechanic

#15523 Change BOMB_TARGET_SIZE to match new trit fire
  code/__DEFINES/research.dm
Labels: Balance/Rebalance

#15495 Weekly high-chaos dynamic days
  code/controllers/configuration/entries/dynamic.dm
  code/modules/holiday/dynamic.dm
  tgstation.dme
Labels: Feature, Config Update

#15503 Lets the limbgrower make mobs with only a chest
  code/game/machinery/limbgrower.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/research/designs/limbgrower_designs.dm
  tgui/packages/tgui/interfaces/Limbgrower.js
Labels: UI, Mechanic

#15505 Player Playtime TGUI
  code/__HELPERS/cmp.dm
  code/modules/admin/playtimes.dm
  code/modules/admin/verbs/randomverbs.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PlayerPlaytimes.js
Labels: UI, Mechanic

#15526 adds bartender cartridge for drink recipe searching, updates chemist cartridge to have equivalent functionality for all recipes
  code/_globalvars/lists/objects.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/special.dm
  icons/obj/pda.dmi
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: Sprites, Mechanic

#15522 Insulation works both ways you know.
  code/__DEFINES/atmospherics.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/gloves/mittens.dm
  code/modules/clothing/gloves/tacklers.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/miscellaneous.dm
Labels: Mechanic

#15530 fixes coiling issue
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  code/modules/mob/living/carbon/human/innate_abilities/customization.dm
Labels: Fix, Sprites
