Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-07, with the labels that each got.

#15701 Fix miasma not being colored right
  code/modules/atmospherics/auxgm/gas_types.dm
Labels: Fix

#15696 fixes slimes blood processing (see pr description)
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/innate_abilities/limb_regeneration.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Mechanic

#15684 Bark followup - audio balance pass, bark intercepts, yelling nerf, falloff fix, and more!
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/say.dm
  code/datums/bark.dm
  code/datums/dna.dm
  code/game/atoms_movable.dm
  code/game/machinery/_machinery.dm
  code/game/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/parrot.dm
  sound/voice/barks/chitter.ogg
Labels: Sound, Code Improvement, Mechanic

#15702 Ports Tau Ceti's welding animation!
  code/game/objects/items.dm
  code/game/objects/items/tools/weldingtool.dm
  code/modules/projectiles/guns/energy/special.dm
  icons/effects/welding_effect.dmi
Labels: Sprites, Mechanic

#15705 tweak
  tools/WebhookProcessor/github_webhook_processor.php
Labels: Fix, Tools

#15700 Sprite Rework
  code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_citadel/icons/mob/widerobot.dmi
Labels: Removal, Mechanic

#15690 Nerfs quark matter's value a lot
  code/__DEFINES/reactions.dm
  code/modules/atmospherics/auxgm/gas_types.dm
Labels: Balance/Rebalance

#15707 makes brain trauma event respect canSpawnEvent conditions such as min players
  code/modules/events/brain_trauma.dm
Labels: Fix

#15710 Dark purple slime runtimes
  code/modules/research/xenobiology/crossbreeding/_status_effects.dm
Labels: Fix

#15708 Fixes check knowledge on identification
  code/datums/components/identification.dm
Labels: Fix

#15712 Gateway Power Issues
  _maps/RandomZLevels/away_mission/SnowCabin.dmm
  _maps/RandomZLevels/away_mission/jungleresort.dmm
  _maps/RandomZLevels/away_mission/undergroundoutpost45.dmm
Labels: Fix, Map Edit, Tweak, Balance/Rebalance, Removal

#15711 Fixes a decade-old typo (if you know, you know.)
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/FestiveBall/FestiveStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
  code/controllers/subsystem/persistence/polly_parrot.dm
  code/controllers/subsystem/persistence/poly_parrot.dm
  code/datums/diseases/parrotpossession.dm
  code/modules/admin/chat_commands.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/bloodsucker/powers/mesmerize.dm
  code/modules/awaymissions/super_secret_room.dm
  code/modules/cargo/packs/engineering.dm
  code/modules/events/holiday/halloween.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/wiremod/preset/speech_relay.dm
  config/entries/logging.txt
  strings/cas_white.txt
  strings/phobia.json
  tgstation.dme
Labels: Map Edit, Tweak, Config Update

#15716 Fixes cleanbots being invisible whenever they get turned on or off
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
Labels: Fix

#15714 Puts public library paintings in Omegastation's library instead of generic empty ones
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Map Edit, Mechanic

#15713 Adds two additional certain vendors to Deltastation
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Map Edit, Mechanic

#15721 Fixes hierophant walls letting non-casters pass through them.
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
Labels: Fix

#15715 Tea dispensing fix
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Fix

#15717 Grown inedibles now properly take seed stats into account
  code/modules/hydroponics/growninedible.dm
Labels: Fix

#15718 Player-controlled cleanbots can now clean dirt
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
Labels: Quality of Life

#15719 Using wirecutters on an autolathe will now have appropriate behavior
  code/game/machinery/autolathe.dm
Labels: Fix

#15720 Shocked autolathe will no longer infinitely zap you with the menu open
  code/game/machinery/autolathe.dm
Labels: Fix

#15709 Fixes slime people (i don't know what the ill effect but runtimes is)
  code/__DEFINES/dcs/signals.dm
  code/datums/brain_damage/split_personality.dm
  code/modules/antagonists/blob/blob/blobs/blob_mobs.dm
  code/modules/antagonists/clockcult/clock_mobs/clockwork_guardian.dm
  code/modules/antagonists/clockcult/clock_mobs/clockwork_marauder.dm
  code/modules/antagonists/devil/imp/imp.dm
  code/modules/holiday/halloween/jacqueen.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/punpun.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/simple_animal/eldritch_demons.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/crab.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/plushie.dm
  code/modules/mob/living/simple_animal/guardian/types/charger.dm
  code/modules/mob/living/simple_animal/guardian/types/fire.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/illusion.dm
  code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mega_arachnid.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/pandora.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/ice_demon.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/ice_whelp.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/polarbear.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/wolf.dm
  code/modules/mob/living/simple_animal/hostile/mushroom.dm
  code/modules/mob/living/simple_animal/hostile/netherworld.dm
  code/modules/mob/living/simple_animal/hostile/plaguerat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/statue.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
  code/modules/mob/living/simple_animal/hostile/wumborian_fugu.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/slime/life.dm
Labels: Fix

#15722 fixes slime limb regeneration
  code/modules/mob/living/carbon/human/innate_abilities/limb_regeneration.dm
Labels: Fix

#15731 Untied shoes: a minor event of little consequence
  code/modules/events/untie_shoes.dm
  tgstation.dme
Labels: Mechanic

#15729 ports tg's fix to accessing storage in closed lockers
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#15730 Rebalances some events
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/atmos_speed.dm
  code/modules/events/brain_trauma.dm
  code/modules/events/cat_surgeon.dm
  code/modules/events/disease_outbreak.dm
  code/modules/events/dust.dm
  code/modules/events/heart_attack.dm
  code/modules/events/mass_hallucination.dm
  code/modules/events/supermatter_surge.dm
  code/modules/events/supernova.dm
  code/modules/events/vent_clog.dm
  tgstation.dme
Labels: Tweak, Balance/Rebalance, Mechanic

#15733 Fixes rad collectors to use correct units
  code/modules/power/singularity/collector.dm
Labels: Fix

#15735 Makes stasis beds fine for surgery
  code/modules/surgery/surgery.dm
Labels: Balance/Rebalance
