Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-08, with the labels that each got.

#15739 fixes defib divide by zero
  code/game/objects/items/defib.dm
Labels: Fix

#15737 Refactor bitfields global, improve turret_flags debugging
  code/__DEFINES/bitfields.dm
  code/_globalvars/bitfields.dm
  code/game/machinery/porta_turret/portable_turret.dm
  tgstation.dme
Labels: Administration, Refactor

#15741 Another minor bomb points nerf
  code/__DEFINES/research.dm
Labels: Balance/Rebalance, Code Improvement

#15742 lets AIs control status displays (vtuber mode)
  code/__DEFINES/say.dm
  code/datums/saymode.dm
  code/game/machinery/status_display.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/ai/say.dm
Labels: Mechanic

#15749 removes debug messages from AI screen PR (POV I merged way too quickly)
  code/modules/mob/living/silicon/ai/say.dm
Labels: Priority: High, Removal

#15743 Lotsa more AI screen thingies on box
  _maps/map_files/BoxStation/BoxStation.dmm
Labels: Map Edit, Mechanic

#15736 Fixes Gateway Power (For Realz)
  _maps/RandomZLevels/away_mission/SnowCabin.dmm
  _maps/RandomZLevels/away_mission/jungleresort.dmm
  _maps/RandomZLevels/away_mission/undergroundoutpost45.dmm
Labels: Map Edit, Quality of Life

#15750 fixes airlocks calling diag hud update on electrification timer
  code/game/machinery/doors/airlock.dm
Labels: Fix

#15752 L6 Rechambering (tg parity, not a balance thing, fixes L6 match ammo)
  code/controllers/subsystem/traumas.dm
  code/modules/cargo/exports/weapons.dm
  code/modules/projectiles/ammunition/ballistic/lmg.dm
  code/modules/projectiles/boxes_magazines/external/lmg.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/projectile/bullets/lmg.dm
  code/modules/tcg/pack_nuclear.dm
  code/modules/uplink/uplink_items/uplink_ammo.dm
  code/modules/uplink/uplink_items/uplink_dangerous.dm
Labels: Tweak

#15748 increase midi2piano line limit
  tools/midi2piano/midi2piano.py
Labels: Tools

#15744 Some tweaks to untied shoelaces (+ miner boots minor buff)
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/events/untie_shoes.dm
Labels: Tweak, Balance/Rebalance

#15747 fix catwalk overlays not working properly
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/open/floor/catwalk_plating.dm
  icons/turf/floors/catwalk_plating.dmi
Labels: Fix, Sprites

#15751 /vg/station style recoil - screen pushback
  code/modules/client/preferences.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Tweak

#15753 Fixes lack of eyes
  .vscode/settings.json
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/eyes.dmi
Labels: Fix, Sprites, Quality of Life

#15757 crusher UNIQUE_RENAME + 350 chr limit custom descs
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/paperwork/pen.dm
Labels: Tweak

#15756 Nitric oxide second pass (+ some prettiness stuff in the UI)
  code/modules/atmospherics/auxgm/gas_types.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  tgui/packages/tgui/constants.js
Labels: Tweak, Balance/Rebalance, UI

#15780 Omega Map Tweaks
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Map Edit, Tweak, Removal, Mechanic

#15787 Makes station trait on round start work
  code/controllers/subsystem/ticker.dm
Labels: Fix

#15793 Hey remember #15780
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit, Removal

#15792 Glowing goo no longer has persistence
  code/game/objects/effects/decals/cleanable/misc.dm
Labels: Balance/Rebalance

#15796 Makes linux performance on startup better
  code/__DEFINES/_auxtools.dm
Labels: Fix

#15795 Probably fixes bad stake behavior
  code/modules/antagonists/bloodsucker/items/bloodsucker_stake.dm
Labels: Fix

#15794 cauteries searing tools and energy scalpels now have heat and can be used to light cigarettes
  code/modules/surgery/tools.dm
Labels: Tweak

#15797 sandstorm nerf
  code/modules/events/dust.dm
Labels: Balance/Rebalance

#15788 ports "Reworks the sanitize_ooccolor proc"
  code/__HELPERS/sanitize_values.dm
  code/modules/client/preferences.dm
  code/modules/client/verbs/ooc.dm
Labels: Tweak

#15800 Fix infinite blood trails
  code/modules/mob/living/living.dm
Labels: Tweak

#15799 Makes signal commander work
  code/modules/modular_computers/file_system/programs/signaler.dm
Labels: Fix

#15798 Makes binary translator key not show a wrong description
  code/game/objects/items/devices/radio/encryptionkey.dm
Labels: Fix

#15782 Make sure ChangeTurf updates air ref on all paths
  code/game/turfs/change_turf.dm
  code/game/turfs/open.dm
Labels: Fix

#15781 the great medbay resprite PR: ported from a freshly merged TG PR
  code/game/objects/items/dna_injector.dm
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/surgery/tools.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/nuke_tools.dmi
  icons/obj/storage.dmi
  icons/obj/surgery.dmi
  icons/obj/syringe.dmi
Labels: Sprites

#15779 radial menu surgery
  code/modules/surgery/organ_manipulation.dm
Labels: Mechanic

#15768 ninja sprite refresh + very minor evening/midnight gloves consistency + removes a stray pixel from the mauler gauntlets
  code/modules/ninja/suit/shoes.dm
  code/modules/ninja/suit/suit.dm
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/feet_digi.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/inhands/weapons/bombs_lefthand.dmi
  icons/mob/inhands/weapons/bombs_righthand.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/grenade.dmi
Labels: Sprites, Removal

#15764 Space lube is now a chem gas (also some other stuff too)
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Mechanic

#15760 skill mod shuffle pr + implied complaining about why dont they reflect the actual skill xp levels themselves
  code/datums/skills/modifiers/job.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/scientist.dm
Labels: Tweak

#15761 bloodborne (adds dodgeroll combat RMB to the cleaving saw, confers melee/projectile iframes)
  code/modules/mining/lavaland/necropolis_chests.dm
  sound/effects/body-armor-rolling.ogg
Labels: Sound, Mechanic

#15773 mining drills scanners and crushers getting a TG inspired glow up
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/equipment/mineral_scanner.dm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/projectiles/guns/energy/special.dm
  icons/mob/inhands/equipment/mining_lefthand.dmi
  icons/mob/inhands/equipment/mining_righthand.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
  icons/obj/device.dmi
  icons/obj/mining.dmi
Labels: Sprites

#15786 the sexy workout shorts
  code/modules/clothing/under/pants.dm
  code/modules/clothing/under/shorts.dm
  code/modules/vending/clothesmate.dm
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Sprites, Mechanic

#15801 disabler suicide now actually works
  code/modules/projectiles/gun.dm
Labels: Fix

#15805 Fixes the plate carrier sprite
  icons/mob/clothing/suit.dmi
Labels: Sprites, Tweak

#15813 fixes security levels
  code/controllers/subsystem/security_level.dm
Labels: Fix

#15809 thighjob from a girl wearing a microskirt who can beat the shit out of you at any moment (hyper slutskirt/secukini sprites)
  code/modules/clothing/under/jobs/security.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_digi.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Mechanic

#15814 Add a grep for empty Find() calls
  tools/ci/check_grep.sh
Labels: Tools, Code Improvement

#15812 unbaconifies the recharge cable courtesy of ship test
  icons/obj/power.dmi
Labels: Sprites

#15806 Penthouse pod rework plus new garden pod.
  _maps/templates/shelter_5.dmm
  _maps/templates/shelter_6.dmm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/shelters.dm
Labels: Map Edit, Tweak

#15821 Better climax logging
  code/modules/arousal/arousal.dm
Labels: Administration

#15823 fixes harpy wings and steals the harpy wings from rp so that there is some variety
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  icons/mob/wings.dmi
Labels: Fix, Sprites, Mechanic

#15828 Made some events still show messages with intern
  code/modules/events/alien_infestation.dm
  code/modules/events/anomaly.dm
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  code/modules/events/blob.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/cat_surgeon.dm
  code/modules/events/dust.dm
  code/modules/events/immovable_rod.dm
  code/modules/events/ion_storm.dm
  code/modules/events/major_dust.dm
  code/modules/events/meateor_wave.dm
  code/modules/events/meteor_wave.dm
  code/modules/events/pirates.dm
  code/modules/events/radiation_storm.dm
  code/modules/events/space_dragon.dm
  code/modules/events/stray_cargo.dm
  code/modules/events/supermatter_surge.dm
  code/modules/events/supernova.dm
  code/modules/events/travelling_trader.dm
  code/modules/events/vent_clog.dm
  code/modules/events/wormholes.dm
Labels: Fix

#15825 Unfricks job code (oh well)
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/prisoner.dm
Labels: Fix

#15808 Allows setting antags to "low" (if antag rep is on)
  code/__DEFINES/preferences.dm
  code/__DEFINES/role_preferences.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/game_mode.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Code Improvement, Mechanic
