Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-01, with the labels that each got.

#15450 Adds a config flag for if station renames require admin approval (and enables it)
  code/controllers/configuration/entries/general.dm
  code/game/objects/items/charter.dm
  code/modules/admin/topic.dm
  config/entries/general.txt
Labels: Priority: High, Administration, Config Update

#15437 Fixes bluespace pipes (I think)
  code/game/machinery/pipe/construction.dm
Labels: Fix

#15445 Meta Atmos Layout
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#15452 your jordans are fake - adds a mining boot skin for jumpboots
  code/game/objects/items/melee/energy.dm
  code/modules/clothing/shoes/miscellaneous.dm
  icons/mob/clothing/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites

#15446 Making Omega Playable
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Feature, Fix, Map Edit

#15459 Adding an engineering/atmos airlock on omega
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Feature, Map Edit

#15463 Makes alcohol cause drunkenness properly again
  code/modules/mob/living/carbon/life.dm
Labels: Fix

#15398 Fix few instances of bleeding white blood
  _maps/RandomRuins/LavaRuins/lavaland_surface_mining_site.dmm
  code/datums/wounds/bones.dm
  code/datums/wounds/pierce.dm
  code/game/mecha/equipment/tools/mining_tools.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
Labels: Fix, Map Edit

#15467 Added more logging for climax-in-container
  code/modules/arousal/arousal.dm
Labels: Administration

#15465 Supernova rad storm tweaks
  code/modules/events/supernova.dm
Labels: Balance/Rebalance

#15473 Revert "Bump pillow from 8.3.2 to 9.0.0 in /tools"
  tools/requirements.txt
Labels: Tools, Revert

#15324 Ashen tree!
  code/datums/mapgen/Cavegens/LavalandGenerator.dm
  code/modules/mining/lavaland/ash_tree.dm
  icons/obj/lavaland/ash_tree.dmi
  tgstation.dme
Labels: Feature, Sprites

#15419 Adds an event that speeds up/slows down atmos
  code/modules/events/atmos_speed.dm
Labels: Feature

#15449 Allows pod people to be made using other fluids
  code/game/objects/effects/decals/cleanable/gibs.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/modules/arousal/genitals.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/mob/living/blood.dm
Labels: Balance/Rebalance

#15430 Synth stuff : Balancing Nightmare Edition (aka, coolant)
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/controllers/subsystem/processing/quirks.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/antagonists/abductor/equipment/glands/heal.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/handle_corruption.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/anthropomorph.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/nodes/robotics_nodes.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/stomach.dm
  icons/mob/screen_synth.dmi
Labels: Sprites, Balance/Rebalance

#15478 Various chem tweaks
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/SDGF.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/eigentstasium.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
Labels: Fix, Grammar and Formatting

#15479 The book has 10 pagess remaining.
  code/modules/projectiles/guns/magic/spell_book.dm
Labels: Grammar and Formatting

#15477 Certain reagents are once again invalid for blood dna relaying and therefore podcloning / decal detscanning.
  code/modules/arousal/genitals.dm
Labels: Removal

#15483 Fixes linter errors && PaperSheet not working
  tgui/packages/tgui/interfaces/ClockworkSlab.js
  tgui/packages/tgui/interfaces/PaperSheet.js
Labels: Fix, UI
