Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-03, with the labels that each got.

#15531 Omega Station Again
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit

#15541 Omega Un-Decalening
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Map Edit, Removal

#15538 Fixed a SNAFU due to config entries auto-lower-casing
  code/modules/holiday/dynamic.dm
Labels: Config Update

#15520 Update for Python bootstrap
  dependencies.sh
  tools/bootstrap/python.bat
  tools/bootstrap/python37._pth
  tools/bootstrap/python_.ps1
  tools/mapmerge2/convert.py
  tools/mapmerge2/dmm.py
  tools/mapmerge2/fixup.py
Labels: Tools, Code Improvement

#15540 Adds a LOT more enthalpy to tritium
  code/modules/atmospherics/auxgm/gas_types.dm
Labels: Balance/Rebalance

#15534 Screentips
  code/__DEFINES/_flags/_flags.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screentip.dm
  code/game/atoms.dm
  code/game/turfs/simulated/floor.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  interface/skin.dmf
  tgstation.dme
Labels: Removal, Mechanic

#15535 Statpanel update
  code/modules/client/client_procs.dm
  html/statbrowser.html
Labels: Refactor

#15536 Implements JPS (Jump Point Search) Pathfinding
  code/__HELPERS/AStar.dm
  code/__HELPERS/heap.dm
  code/__HELPERS/path.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/objs.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/blob/blob/theblob.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/integrated_electronics/subtypes/smart.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/parrot.dm
  tgstation.dme
Labels: Refactor

#15543 spraypainting a stack of floor tiles makes the placed tile the same colour!
  code/game/turfs/simulated/floor/plating.dm
Labels: Mechanic

#15548 Omega-ning (Gravgen, Xenobio)
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit, Removal

#15375 Removes being able to access departmental budgets via NTIRN
  code/modules/modular_computers/file_system/programs/budgetordering.dm
Labels: Balance/Rebalance, Removal, Salt

#15195 Weakens chemistry's revival chems
  code/__DEFINES/reagents.dm
  code/game/objects/items/defib.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm
Labels: Balance/Rebalance

#15425 Nerfs* passive organ healing, plus some minor stuff
  code/__DEFINES/DNA.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/stomach.dm
Labels: Fix, Balance/Rebalance

#15476 Buffs regen core healing for robots on lavaland, nerfs regen cores when not on lavaland
  code/datums/status_effects/buffs.dm
Labels: Balance/Rebalance

#15550 Makes should_do_equalization actually work
  code/controllers/subsystem/air.dm
Labels: Fix

#15546 Makes supermatter take damage (and not heal) if too near to spaced turfs
  code/modules/power/supermatter/supermatter.dm
Labels: Balance/Rebalance

#15547 Adds a minimum vote count to continue rounds
  code/__DEFINES/vote.dm
  code/controllers/subsystem/vote.dm
Labels: Mechanic

#15553 Fix implosion compressor impossibility
  code/modules/research/anomaly/explosive_compressor.dm
Labels: Balance/Rebalance

#15554 Metastation Nav Beacon
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit

#15559 Solves some LOG_VICTIM issues
  code/__HELPERS/_logging.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/logging.dm
  code/datums/status_effects/debuffs.dm
  code/game/atoms.dm
  code/game/objects/items/implants/implantchair.dm
  code/game/world.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/surgery/advanced/brainwashing.dm
  config/entries/logging.txt
Labels: Fix, Config Update

#15561 Omega Air Mixer + Turbine Wire
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Map Edit, Mechanic

#15564 Fixes balloon alerts sourced on turfs
  code/__HELPERS/unsorted.dm
  code/datums/chatmessage.dm
  code/modules/balloon_alert/balloon_alert.dm
Labels: Fix

#15566 Meta customs wire
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, Map Edit

#15568 Omega Tcomms and Gravgen Pipes
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Map Edit, Mechanic

#15438 Makes it so alter form can affect eyes.
  code/modules/mob/living/carbon/human/innate_abilities/customization.dm
Labels: Feature

#15497 Advanced mutation toxin nerf; new cure, removes instant subspecies transformation
  code/datums/diseases/transformation.dm
Labels: Balance/Rebalance, Removal

#15571 Fixes self-fueling welder refueling in edge cases
  code/game/objects/items/tools/weldingtool.dm
Labels: Fix

#15570 Climax with partner now counts mouth
  code/modules/arousal/arousal.dm
Labels: Mechanic

#15572 Fixes the compile warnings
  tgui/babel.config.js
  tgui/yarn.lock
Labels: UI, Code Improvement

#15304 Butts, nuts, n' tats. (please testmerge or merge & deploy before Halloween ball)
  code/__DEFINES/DNA.dm
  code/__DEFINES/citadel_defines.dm
  code/__HELPERS/_cit_helpers.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/controllers/configuration/entries/fetish_content.dm
  code/game/machinery/limbgrower.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/arousal/genitals.dm
  code/modules/arousal/genitals_sprite_accessories.dm
  code/modules/arousal/organs/butt.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/innate_abilities/customization.dm
  code/modules/reagents/reagent_containers/hypovial.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/research/designs/limbgrower_designs.dm
  code/modules/vending/kinkmate.dm
  config/entries/fetish_content.txt
  icons/obj/genitals/breasts_onmob.dmi
  icons/obj/genitals/butt.dmi
  icons/obj/genitals/butt_onmob.dmi
  icons/obj/genitals/testicles_onmob.dmi
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
  tgstation.dme
Labels: Feature, Fix, Sprites, UI, Config Update
