Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-05, with the labels that each got.

#15608 Actually fixes dragging storage items into themself.
  code/game/atoms.dm
Labels: Fix

#15609 Fixes the round time thing
  code/controllers/subsystem/statpanel.dm
Labels: Fix

#15606 an actual salt pr (adds sodium sensitivity quirk)
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/traits/neutral.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Salt, Mechanic

#15615 Makes it so synths spark when they *blush or *cry, instead of just IPCs.
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/emote.dm
Labels: Mechanic

#15612 Syncs status displays to tg's version
  code/__DEFINES/mobs.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/status_display.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/emote.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/ai/logout.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_construction.dm
  icons/obj/wallframe.dmi
  tgstation.dme
Labels: Sprites, Refactor, Mechanic

#15611 Alter form for wings.
  code/modules/mob/living/carbon/human/innate_abilities/customization.dm
Labels: Mechanic

#15610 Hub refresh 2022 - Cleans up update_status(), adds more hub-related config options, and more!
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/configuration/entries/server.dm
  code/game/world.dm
  config/entries/server.txt
  strings/server_taglines.txt
Labels: Tweak, Config Update

#15587 Synth Brainwashing AKA Reprogramming
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
  code/modules/surgery/advanced/brainwashing.dm
  code/modules/surgery/advanced/robot_brainwashing.dm
  tgstation.dme
Labels: Fix, Balance/Rebalance, Mechanic

#15616 Moves server_taglines.txt to config dir for better TGS compatibility
  code/_globalvars/lists/flavor_misc.dm
  config/server_taglines.txt
  strings/server_taglines.txt
Labels: Config Update

#15617 poly alt cloak can now be renamed/dedescriptioned in loadout
  modular_citadel/code/modules/client/loadout/neck.dm
Labels: Mechanic

#15624 quirks are now organised into three tabs for positive, neutral and negative
  code/__DEFINES/loadout.dm
  code/modules/client/preferences.dm
Labels: Mechanic

#15630 Makes flavor texts a tiny bit better
  code/__DEFINES/say.dm
  code/datums/elements/flavor_text.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/unit_tests/character_saving.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
Labels: Fix

#15231 Antag roles will now respect your backup role preferences if none of the enabled roles are available
  code/controllers/subsystem/job.dm
Labels: Test Merge Candidate

#15636 Switches transfer vote to approval voting
  code/controllers/subsystem/autotransfer.dm
Labels: Test Merge Candidate
