Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-09, with the labels that each got.

#15829 replaces weight machine sprites with TG's and subsequently wipes a portion of the goon file's existence
  code/modules/mining/lavaland/ruins/gym.dm
  goon/icons/obj/chairs.dmi
  goon/icons/obj/fitness.dmi
  goon/sound/effects/spring.ogg
  icons/obj/fitness.dmi
  sound/machines/creak.ogg
Labels: Fix, Sprites, Sound

#15830 comfier disks take longer to summon lone ops (they still will though)
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
Labels: Tweak

#15827 Field generators now yell on the radio if they fail while there's a singulo/tesla
  code/modules/power/singularity/field_generator.dm
  code/modules/power/singularity/singularity.dm
Labels: Balance/Rebalance

#15839 Destructive analyzer no longer buy one get 49 free
  code/modules/research/destructive_analyzer.dm
Labels: Fix

#15838 lets ghosts click a pAI device to download into it without a master
  code/controllers/subsystem/pai.dm
  code/modules/mob/living/silicon/pai/pai.dm
Labels: Mechanic

#15847 Ports the RBMK reactor from both NSV using Hyper and Splurt code (WIP)
  _maps/RandomRuins/StationRuins/Box/Engine/engine_rbmk.dmm
  _maps/templates/reactor_1.dmm
  code/__DEFINES/sound.dm
  code/__HELPERS/matrices.dm
  code/__HELPERS/radiation.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/datums/ruins/station.dm
  code/game/atoms.dm
  code/game/objects/items/manuals.dm
  code/modules/cargo/exports/engineering.dm
  code/modules/cargo/packs/emergency.dm
  code/modules/cargo/packs/engine.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/shelters.dm
  code/modules/modular_computers/computers/machinery/console_presets.dm
  code/modules/power/reactor/fuel_rods.dm
  code/modules/power/reactor/rbmk.dm
  code/modules/power/reactor/reactor_cargo.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
  config/entries/general.txt
  icons/obj/control_rod.dmi
  icons/obj/inflatable.dmi
  icons/obj/machines/rbmk.dmi
  icons/obj/machines/rbmk_computer.dmi
  icons/obj/machines/reactor_parts.dmi
  icons/obj/rbmk_computer.dmi
  sound/effects/rbmk/alarm.ogg
  sound/effects/rbmk/meltdown.ogg
  sound/effects/rbmk/reactor_hum.ogg
  sound/effects/rbmk/switch.ogg
  sound/effects/rbmk/switch2.ogg
  sound/effects/rbmk/switch3.ogg
  sound/effects/rbmk/turbine_end.ogg
  sound/effects/rbmk/turbine_mid.ogg
  sound/effects/rbmk/turbine_start.ogg
  sound/effects/ship/freespace2/crane_1.wav
  sound/effects/ship/reactor/falloutwind.ogg
  sound/effects/ship/reactor/startup.ogg
  sound/effects/ship/reactor/startup2.ogg
  tgstation.dme
  tgui/packages/tgui/interfaces/NtosRbmkStats.js
  tgui/packages/tgui/interfaces/RbmkControlRods.js
  tgui/packages/tgui/interfaces/RbmkStats.js
Labels: Map Edit, Sprites, Sound, UI, Config Update, Mechanic

#15837 Lets xenohybrids eat junkfood.
  code/modules/mob/living/carbon/human/species_types/xeno.dm
Labels: Balance/Rebalance

#15846 Ports Quantum Spin Inverter from TG.
  code/game/objects/items/devices/swapper.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/techweb/nodes/bluespace_nodes.dm
  icons/obj/device.dmi
  tgstation.dme
Labels: Sprites, Mechanic

#15844 Ports the launchpad targeting icon from TG.
  code/__DEFINES/rendering/atom_hud.dm
  code/_rendering/atom_huds/data_huds.dm
  code/game/machinery/computer/launchpad_control.dm
  code/game/machinery/launch_pad.dm
  icons/effects/effects.dmi
Labels: Sprites, Balance/Rebalance

#15845 Fixes encoded langauge so people can speak it, also redoes xeno tongue.
  code/_globalvars/lists/flavor_misc.dm
  code/modules/surgery/organs/tongue.dm
Labels: Fix

#15834 tgstation 56520 port - combo meter/readout for martial arts
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/martial/_martial.dm
  code/datums/martial/cqc.dm
  code/datums/martial/plasma_fist.dm
  code/datums/martial/rising_bass.dm
  code/datums/martial/sleeping_carp.dm
  icons/mob/screen_gen.dmi
Labels: Sprites, Mechanic

#15850 fixes the worst use of a for loop ever
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Code Improvement

#15852 adds bellows, mumbles, and crackles as speech verbs
  code/_globalvars/lists/flavor_misc.dm
Labels: Mechanic

#15855 Ports borg pdas from hyper. Credit to haha26315 for the orginal PR and BongaTheProto for their port to splurt.
  code/__DEFINES/hud.dm
  code/_onclick/hud/robot.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Mechanic

#15843 HUD desoulification fan fiction
  icons/mob/hud.dmi
Labels: Sprites

#15832 Makes from-ghost midrounds not roll if no ghosts
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Fix

#15853 Port of the Posialert console from hyper. Credit to jjpark-kb for initial work.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CogStation/CogStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/LambdaStation/lambda.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/Snaxi/Snaxi.dmm
  code/game/machinery/posi_alert.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_construction.dm
  icons/obj/machines/terminals.dmi
  tgstation.dme
Labels: Map Edit, Sprites, Mechanic

#15856 Fixes the mining borg point card
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mining/machine_vending.dm
Labels: Fix, Mechanic

#15854 Ports Adding radio access to borgs by default from splurt. Credit to NopemanMcHalt for the splurt port and Ayfa212 for the initial work.
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Mechanic

#15848 Port of a bunch of stuff to update guns at this point because we have a bunch of stuff we are missing.
  code/__DEFINES/combat.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/gun.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/drag_drop.dm
  code/datums/action.dm
  code/datums/components/fullauto.dm
  code/modules/cargo/centcom_podlauncher.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/energy/laser_gatling.dm
  icons/effects/mouse_pointers/weapon_pointer.dmi
  icons/mob/actions/actions_items.dmi
  tgstation.dme
Labels: Sprites, Mechanic
