Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2022-10, with the labels that each got.

#15866 Revert "Allow AI, mime, clown to have the same name as LITERALLY ANY MOB IN THE WORLD(???)"
  code/__HELPERS/unsorted.dm
Labels: Priority: CRITICAL, Revert

#15868 misc clockcult balance changes
  code/modules/antagonists/clockcult/clock_items/clockwork_armor.dm
  code/modules/antagonists/clockcult/clock_items/clockwork_slab.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_applications.dm
  code/modules/antagonists/clockcult/clock_scriptures/scripture_cyborg.dm
  code/modules/vehicles/mecha/combat/neovgre.dm
Labels: Balance/Rebalance

#15857 Readds the premium ka for borgs
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mining/machine_vending.dm
Labels: Balance/Rebalance

#15867 [READY FOR REVIEW] [FRAMEWORK] kinetic brawling - the kinetic gauntlets rework nobody asked for
  code/datums/status_effects/debuffs.dm
  code/modules/mining/equipment/gauntlet_styles.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  tgstation.dme
Labels: Mechanic

#15870 shoving severed bodyparts (e.g. heads) in smartfridges imparts organ freezing
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Labels: Fix

#15840 Hard caps supermatter gas output
  code/modules/power/supermatter/supermatter.dm
Labels: Balance/Rebalance

#15818 Let's just hard cap QCD research output (per burst)
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Balance/Rebalance

#15861 Ports random whiteships from tg
  _maps/RandomRuins/SpaceRuins/whiteshipdock.dmm
  code/modules/shuttle/shuttle.dm
Labels: Map Edit, Mechanic

#15833 drops floor cluwnes (random event max occurrences 0)
  code/modules/events/floorcluwne.dm
Labels: Removal

#15871 Updates DreamAnnotate to v2
  .github/workflows/ci_suite.yml
Labels: Github

#15869 Grant Arachnid Abilities to Driders
  code/__DEFINES/inventory.dm
  code/modules/mob/dead/new_player/sprite_accessories/legs_and_taurs.dm
  code/modules/mob/living/carbon/human/innate_abilities/customization.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/arachnid.dm
Labels: Tweak, Mechanic

#15862 adds multiline /me emotes
  code/modules/mob/say.dm
Labels: Mechanic
