Repository Citadel-Station-13/Citadel-Station-13, pull requests merged in 2023-01, with the labels that each got.

#15577 Adds beauty back
  code/datums/components/mood.dm
Labels: Mechanic

#15930 Update to reskinning
  code/__DEFINES/misc.dm
  code/_onclick/click.dm
  code/datums/elements/object_reskinning.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/melee/energy.dm
  code/game/objects/objs.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/reagents/reagent_containers/hypovial.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
  tgstation.dme
Labels: Refactor, Quality of Life

#15918 [PORT] Non-global heirloom definitions
  code/_globalvars/lists/flavor_misc.dm
  code/datums/traits/negative.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/prisoner.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/bugmen.dm
  code/modules/mob/living/carbon/human/species_types/dwarves.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/synthliz.dm
  icons/obj/storage.dmi
Labels: Refactor

#15941 Prevent using Nutriment Pump implant with 'no process food' trait
  code/modules/surgery/organs/augments_chest.dm
Labels: Fix

#15915 [PORT] /tg/station Drink Sprites
  icons/obj/drinks.dmi
Labels: Sprites
